### ISSUE TITLE
继承 QMUICommonViewController 的VC 的View Y 值怎么不是从64开始算，而是0

### ISSUE THREAD

**Issue by boai** [QMUI/QMUI_iOS#100]
### 运行环境 ###

- [x] iOS 设备：`iPhone` 
- [x] 系统版本：`iOS 10.3`
- [x] Xcode 版本：`8.3`
- [x] QMUI iOS 版本：`1.4`

### 具体问题描述 ###
继承 QMUICommonViewController 的VC 的View Y 值怎么不是从64开始算，而是0，看了demo 也没看懂你们怎么设置的，能不能直接默认从navi 下面开始计算？

**Comment by MoLice** [comment]
自 iOS 7 开始，系统默认表现就是这样。建议可以了解 `UIViewController` 这几个属性：
```Objective-C
@property(nonatomic,assign) UIRectEdge edgesForExtendedLayout;
@property(nonatomic,assign) BOOL extendedLayoutIncludesOpaqueBars;
@property(nonatomic,assign) BOOL automaticallyAdjustsScrollViewInsets;
```
