### ISSUE TITLE
QMUIImageWriteToSavedPhotosAlbumWithAlbumAssetsGroup 保存之后的图片不正确

### ISSUE THREAD

**Issue by wudb** [QMUI/QMUI_iOS#101]
### 运行环境 ###

- [x] iOS 设备：`iPhone`  / `模拟器`
- [x] 系统版本：`iOS 10.2`
- [x] Xcode 版本：`8.3`
- [x] QMUI iOS 版本：`1.4.0`

### 具体问题描述 ###
用QMUIImageWriteToSavedPhotosAlbumWithAlbumAssetsGroup方法保存图片后, 取回调的asset中的图片跟保存的图片不一致，是相册中最早的那张图片

**Comment by wudb** [comment]
我自己回了吧
在类QMUIAssetsManager中的方法
+ (PHAsset *)fetchLatestAssetWithAssetCollection:(PHAssetCollection *)assetCollection {
    PHFetchOptions *fetchOptions = [[PHFetchOptions alloc] init];
    // 按时间对 PHAssetCollection 内的资源进行排序，最新的资源排在数组第一位
    fetchOptions.sortDescriptors = @[[NSSortDescriptor sortDescriptorWithKey:@"creationDate" ascending:YES]];
    PHFetchResult *fetchResult = [PHAsset fetchAssetsInAssetCollection:assetCollection options:fetchOptions];
    // 获取 PHAssetCollection 内第一个资源，即最新的资源
    PHAsset *latestAsset = fetchResult.firstObject;
    return latestAsset;
}
写的是按时间升序，应该改成降序(改为NO)就可以了

**Comment by MoLice** [comment]
嗯，这里有 bug，已经在[这次 commit](https://github.com/QMUI/QMUI_iOS/commit/a7cb1238b3e69ecd9d6df160ce760780572efbc2) 里修复，感谢反馈。
