### ISSUE TITLE
希望QMUI可以做一个渐变色的导航栏

### ISSUE THREAD

**Issue by RabbitDream** [QMUI/QMUI_iOS#102]
### 运行环境 ###

- [x] iOS 设备：`iPhone` 
- [x] 系统版本：`iOS 10.3`
- [x] Xcode 版本：`8.3`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
公司新项目准备用QMUI来做底层UI框架, 首页要实现渐变色导航栏, 现在的做法就是隐藏掉QMUI的, 放一个自定义的View上去, 但这样在展示的会有过渡问题, 希望QMUI可以实现这个功能.

**Comment by MoLice** [comment]
不清楚你说的渐变效果具体是怎样，绝大部分的导航栏效果都可以通过设置一张背景图来实现，不一定要隐藏系统导航栏。
这种属于具体的业务需求，不具备通用型，不适合由 QMUI 来实现。你也可以通过继承QMUI来自定义你想要的效果。
