### ISSUE TITLE
QMUIDialogViewController或者QMUIAlertController怎么添加多个按钮

### ISSUE THREAD

**Issue by lijunW** [QMUI/QMUI_iOS#105]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by MoLice** [comment]
@lijunW `QMUIDialogViewController` 目前仅支持两个按钮，也即头文件里的 addSubmitButton 和 addCancelButton。
`QMUIAlertController` 可以通过 `addAction:` 添加任意多个按钮。
