### ISSUE TITLE
QMUIAlbumViewController进入图片库以后点击报错

### ISSUE THREAD

**Issue by TracyYanghandsome** [QMUI/QMUI_iOS#106]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
在模拟器上面是没有任何问题的，连接手机真机调试时，能正常进去照片库，然后点击进去就报错了，报错信息Trapped uncaught exception 'NSInternalInconsistencyException', reason: 'isViewControllerTransiting = YES, -[QMUINavigationController pushViewController:animated:];

#### 问题截图 ####
![Uploading 4F083941D8D3B3B96A07AFE41B864841.png…]()
![Uploading 5647579B-F7C9-4B70-B754-C28CE2E25937.png…]()
代码执行到1111时跳转的时候报错了
![Uploading 83C5F6A9-D03D-4E40-A1F5-ADB5218A7D8D.png…]()

**Comment by TracyYanghandsome** [comment]
![4f083941d8d3b3b96a07afe41b864841](https://cloud.githubusercontent.com/assets/19200800/25267055/04fc6390-26a6-11e7-8516-7530c6dd7aae.png)
![83c5f6a9-d03d-4e40-a1f5-adb5218a7d8d](https://cloud.githubusercontent.com/assets/19200800/25267068/1051ca28-26a6-11e7-873f-59f7d481b936.png)
代码执行到1111时跳转的时候报错了
![5647579b-f7c9-4b70-b754-c28ce2e25937](https://cloud.githubusercontent.com/assets/19200800/25267076/143462ea-26a6-11e7-96e8-7bac6c53f169.png)

**Comment by MoLice** [comment]
这个是[这里的 assert](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIMainFrame/QMUINavigationController.m#L158) 了，这个 assert 是为了保护那种“上一次界面切换动画尚未结束时就又进行一次界面切换”的场景，这种场景容易导致很多 bug，所以做了保护。

请确认你点击相簿 cell 前做了什么操作？是否界面切换动画尚未结束就很快点击了 cell？

**Comment by TracyYanghandsome** [comment]
没有啊 之前还是好好的 不是为什么突然就不行了 点击cell之前都没什么操作 就是进了相册界面之后全部加载出来了以后 点击的时候就崩溃了

**Comment by MoLice** [comment]
能否贴一下你调起相簿列表的代码，例如 present 的那一段

**Comment by TracyYanghandsome** [comment]
https://cloud.githubusercontent.com/assets/19200800/25267068/1051ca28-26a6-11e7-873f-59f7d481b936.png 就这个啊

**Comment by MoLice** [comment]
`albumViewController.albumViewControllerDelegate = self` 这句，请检查你的 `self` 是否有实现 `[QMUIAlbumViewControllerDelegate imagePickerViewControllerForAlbumViewController:]` 方法并返回一个 `QMUIImagePickerViewController` 对象？

**Comment by TracyYanghandsome** [comment]
![efb42f0a-728e-46d8-ae8a-79b3dfa5221a](https://cloud.githubusercontent.com/assets/19200800/25311619/51d81770-2838-11e7-8583-f6093fd179c0.png)
实现了的

**Comment by MoLice** [comment]
如果有实现的话，我这边按照你的代码，是无法重现这个问题的，或者你看能否把你的代码简化一份发给 qmuiteam@qq.com，我调试一下。

**Comment by TracyYanghandsome** [comment]
已经解决了

**Comment by MoLice** [comment]
@TracyYanghandsome 请问最终是什么原因呢？

**Comment by chenxing890** [comment]
解决了也不说明一下怎么解决的
