### ISSUE TITLE
关于QMUICommonTableViewController在Storyboard中使用

### ISSUE THREAD

**Issue by maxhis** [QMUI/QMUI_iOS#108]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.3`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.5.x`

### 具体问题描述 ###
使用`UITableViewController`可以在Interface Builder中拖拽的方式定义TableView Cell UI，而`QMUICommonTableViewController`因为不是`UITableViewController`的子类，所以在IB中不会显示出来TableView。请问这种情况有什么好的解决办法吗？

**Comment by MoLice** [comment]
这个暂时没有办法，IB 没有这么智能的设置，哈哈
