### ISSUE TITLE
qmui_animationDidStopBlock提前结束

### ISSUE THREAD

**Issue by PageGuo** [QMUI/QMUI_iOS#1084]
**Bug 表现**
import  “CAAnimation+QMUI.h”，使用qmui_animationDidStopBlock结束回调，监听动画完成。
APP先切入后台动画尚未执行完成，qmui_animationDidStopBlock却回调了结束。
使用delegate的方式监听结束不会影响动画执行。

**截图**
```  
    CGPoint startCenter = CGPointMake(CGRectGetMidX(textLayerFrame), textLayer.center.y);
    CGPoint endCenter = CGPointMake(-(CGRectGetWidth(textLayer.bounds) * 0.5), textLayer.center.y);
    CAKeyframeAnimation *animation = [CAKeyframeAnimation animationWithKeyPath:@"position"];
    animation.keyTimes = @[@0, @1];
    animation.duration = 5.0;
    animation.values = @[[NSValue valueWithCGPoint:startCenter], [NSValue valueWithCGPoint:endCenter]];
    animation.repeatCount = 0;
    animation.removedOnCompletion = NO;
    animation.fillMode = kCAFillModeForwards;
    animation.qmui_animationDidStopBlock = ^(__kindof CAAnimation *aAnimation, BOOL finished) {
    };

    [textLayer addAnimation:animation forKey:kBarrageAnimation];
    [self.layer addSublayer:textLayer];
```

**如何重现**
动画执行过程中，进行前后台切换

**预期的表现**
接受`animation.removedOnCompletion`的控制

**其他信息**
 - 设备: [iPhone]
 - iOS 版本: [iOS 9+]
 - Xcode 版本: [Xcode 11.7]
 - QMUI 版本: [4.1.3]

**Comment by MoLice** [comment]
测试过并未发现你说的问题，不管是 `qmui_animationDidStopBlock` 或是 `CAAnimationDelegate`，在5秒的动画过程中把 App 切到后台后，依然会在正确的5秒时执行回调。

同时也不清楚这与你在**预期的表现**里提到的 `removedOnCompletion` 有什么关系？

请确认问题出现的具体条件，补充后再重新 open issue。或者提供一份 Demo。
