### ISSUE TITLE
关于 AutoLayout

### ISSUE THREAD

**Issue by huangboju** [QMUI/QMUI_iOS#109]
考虑到AutoLayout的性能问题，建议是否接入FlexBox这种高性能的布局方式，还可以与[前端布局](http://www.ruanyifeng.com/blog/2015/07/flex-grammar.html)保持统一

**推荐**
https://github.com/facebook/componentkit
这个[FlexBox库](https://github.com/LPD-iOS/FlexBoxLayout)语法有点同[Masonry](https://github.com/SnapKit/Masonry)

**Comment by zhoon** [comment]
多谢建议，我们研究研究
