### ISSUE TITLE
侵入性还是比较强

### ISSUE THREAD

**Issue by wangbiye** [QMUI/QMUI_iOS#11]
### 真机 ###

- [x] iOS 设备： iPhone5
- [x] 系统版本：`iOS 10.2`
- [x] Xcode 版本：`8.2`
- [x] QMUI iOS 版本：`1.x.x`

将项目引入我的工程之后, 首先就出现 NavigationController 的 Crash, 因为我的NavigationController是自定义的, 可能跟UINavigationController+NavigationBarTransition冲突, 导致了 crash

**Comment by zhoon** [comment]
@wangbiye 你好，请问可以提供一下具体crash的原因或者截图吗？
QMUI作为一个比较全局的工具，侵入性是比较强，所以比较适合于新的项目或者比较小的项目，对于比较复杂的大项目可能会产生一些冲突。目前我们也在思考有没有什么方案可以解决这个问题，如果有什么建议欢迎反馈给我们。

**Comment by wangbiye** [comment]
我按照上一次的方式重新引入 QMUI 的工程, 但是在Embedded Binaries 和 Linked Frameworks and Libraries 中引入 QMUIKit.framework 之后, 导入头文件并不会提示, 所以不能复现上次的情况, 然后我使用 pod 导入, 发现 pod 还搜索不到 QMUI, 我也刷新了我的 pod, 是有延迟吗

**Comment by zhoon** [comment]
昨晚我们更新了pod上QMUI的名字，你可以尝试一下刷新pod的索引然后再搜一下“pod search QMUIKit”

![image](https://cloud.githubusercontent.com/assets/2041356/21561720/70b3f9d4-ceab-11e6-8045-840ee6bd0f5b.png)

**Comment by zhoon** [comment]
为了尽量减少侵入性，我们已经在给QMUI的一些分类的方法和属性加前缀了，很快就会更新上去。

**Comment by wangbiye** [comment]
pod 导入暂时没有出现 Crash, 持续观察, 有的话再反馈

**Comment by zhoon** [comment]
好，多谢支持
