### ISSUE TITLE
navigationBar 返回按钮

### ISSUE THREAD

**Issue by wxlpp** [QMUI/QMUI_iOS#110]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
设置navigationBar 返回按钮能给个参数是否强制缩放成系统的(13,21)尺寸~，有事有特殊的需求，自己再在qmui初始化后面写上不甚优雅~

**Comment by MoLice** [comment]
这种建议在配置表里把 `NavBarBackIndicatorImage` 置为 `nil`，从而屏蔽 QMUI 默认的处理，然后在自己业务的代码里去设置 `[UINavigationBar appearance].backIndicatorImage`。

因为 QMUI 配置表里的 `NavBarBackIndicatorImage` 和 `NavBarBarBackButtonTitlePositionAdjustment` 等属性是互相搭配使用的，如果允许非 (13, 21) 尺寸的图片，会导致其他配置项不准确。
