### ISSUE TITLE
UIImage扩展

### ISSUE THREAD

**Issue by huangboju** [QMUI/QMUI_iOS#111]
+ (UIImage *)qmui_imageWithView:(UIView *)view;

+ (UIImage *)qmui_imageWithView:(UIView *)view afterScreenUpdates:(BOOL)afterUpdates;

这两个扩展扔到UIView里面是不是更合理

**Comment by MoLice** [comment]
可以，下午我加一下

**Comment by MoLice** [comment]
已更新，请查看 [UIView (QMUI_Snapshotting)](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIKitExtensions/UIView%2BQMUI.h#L123-L127)。

**Comment by huangboju** [comment]
nice
