### ISSUE TITLE
Swift 枚举兼容性

### ISSUE THREAD

**Issue by xnxin** [QMUI/QMUI_iOS#113]
### 运行环境 ###

- [x] QMUI iOS 版本：`1.5.0`

### 具体问题描述 ###
Swift使用QMUIButton的时候，使用imagePosition无法直接使用 button.imagePosition = .top
必须使用button.imagePosition = QMUIButtonImagePositionTop

StoryBoard中直接设置了继承自QMUICommonViewController与QMUINavigationController之后，在SB中设置了title无效
storyboard中设置了颜色Button颜色，运行时会被template中的QMUICMI.buttonTintColor 覆盖

**Comment by MoLice** [comment]
已发布 [1.6.0](https://github.com/QMUI/QMUI_iOS/releases/tag/1.6.0)，这里提到的所有问题均已修复。

**Comment by xnxin** [comment]
感谢开发人员的努力，谢谢
