### ISSUE TITLE
QMUICommonTableViewController在StoryBoard中的兼容性

### ISSUE THREAD

**Issue by xnxin** [QMUI/QMUI_iOS#116]
QMUICommonTableViewController 中tableView未申明为IBDesignable，无法在StoryBoard中设置

**Comment by MoLice** [comment]
你的意思是否指如果你用 `QMUICommonTableViewController`，你无法像使用 `UITableViewController` 一样在右边去设置 `tableView` 的属性（如下图）？

![image](https://cloud.githubusercontent.com/assets/1190261/25890468/2335e5b2-35a0-11e7-881a-9bfece698a94.png)

**Comment by xnxin** [comment]
在sb中拖拽出一个UITableView无法关联到控制器上，QMUICommonTableViewController 不是IBoutlet 声明的

**Comment by MoLice** [comment]
@xnxin 方便的话可以加 QQ 具体聊：298076318

**Comment by MoLice** [comment]
已在最新的 [1.7.0](https://github.com/QMUI/QMUI_iOS/releases/tag/1.7.0) 里加上了 `IBOutlet` 标记。
