### ISSUE TITLE
如何修改QMUIImagePickerViewController中checkbox的颜色

### ISSUE THREAD

**Issue by maxhis** [QMUI/QMUI_iOS#117]
### 运行环境 ###

- [x] iOS 设备：`iPhone` 
- [x] 系统版本：`iOS 10.3`
- [x] Xcode 版本：`8.3`
- [x] QMUI iOS 版本：`1.5.2`

### 具体问题描述 ###
没找到设置项，试了几个全局配置也不行，请问该如何设置CollectionViewCell的CheckBox颜色？感谢！

#### 问题截图 ####
![image](https://cloud.githubusercontent.com/assets/1464097/25934592/64f2368e-3651-11e7-90ac-f68f22b19dcb.png)

**Comment by MoLice** [comment]
[QMUIImagePickerCollectionViewCell.h](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIComponents/ImagePickerLibrary/QMUIImagePickerCollectionViewCell.h#L24-L27) 已经有开放接口用于修改 checkbox 的图片，你可以把任意的图片赋值给它们。

如果要在 QMUI 原来的图片基础上改颜色，可使用 [UIImage (QMUI) qmui_imageWithTintColor:](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIKitExtensions/UIImage%2BQMUI.h#L75) 方法。

**Comment by maxhis** [comment]
如何才能拿到`QMUIImagePickerCollectionViewCell`对象呢？在`QMUIImagePickerViewControllerDelegate`里吗？

**Comment by MoLice** [comment]
如果你的 checkbox 是全局修改的，那直接用 appearance 去改就行了，不用对实例操作。

如果要操作实例，一般都是继承 `QMUIImagePickerViewController` ，自己在 `collectionView:cellForItemAtIndexPath:` 里获取。

**Comment by maxhis** [comment]
才注意到appearance()方法，感谢！
