### ISSUE TITLE
Carthage 无法使用新版本

### ISSUE THREAD

**Issue by xnxin** [QMUI/QMUI_iOS#118]
### 运行环境 ###

- [x] QMUI iOS 版本：`1.6.0`

### 具体问题描述 ###

Carthage 无法导入最新的1.6.0, 只能导入 1.5.0

**Comment by MoLice** [comment]
![image](https://cloud.githubusercontent.com/assets/1190261/26048846/64c72e16-398b-11e7-83d3-4aeb20c17866.png)

已更新 1.6.1，解决这个问题了。

提 issue 时建议提供详细信息，“无法导入” 的描述过于空泛，没有实际作用。

**Comment by xnxin** [comment]
好的，感谢
