### ISSUE TITLE
是否可以维护一份 RELEASE NOTE

### ISSUE THREAD

**Issue by mattchen** [QMUI/QMUI_iOS#119]
我最初开始使用时还是 1.5.0，现在没多久时间已经 1.6.1 了，其中还有一些比较大的变化，每次更新只能通过 commit logs 甚至源码才能看到有什么不同，不知道官方是否可以维护一份 release note，记录每次的变化情况？谢谢

**Comment by MoLice** [comment]
不知道[这个](https://github.com/QMUI/QMUI_iOS/releases)是否是你说的 Release Note？每次发 Release 我们会重点把相对于旧版本需要业务项目改动的点详细说明，其他点如非太细微否则也会列出来。

**Comment by mattchen** [comment]
sorry my bad, 没有注意到这里
