### ISSUE TITLE
QMUISearchController 配合 MJRefresh 使用时列表会往下掉

### ISSUE THREAD

**Issue by TracyYanghandsome** [QMUI/QMUI_iOS#123]
### 运行环境 ###

- [x] iOS 设备：`iPhone5s`
- [x] 系统版本：`iOS 9.3.5`
- [x] Xcode 版本：`8.1`
- [x] QMUI iOS 版本：`1.6.0`

### 具体问题描述 ###
控制器是QMUICommonTableViewController，在使用QMUISearchController的时候使用了MJRefresh会出现以下Bug，第一次进来是正常的，当点击搜索出现的时候，TableView明显往下偏移了。然后点取消，再点搜索时，TableView继续往下偏移。如果用模拟器的话就没问题

代码：
- (BOOL)shouldShowSearchBarInTableView:(QMUITableView *)tableView {
    return YES;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section{
    if (tableView == self.tableView) {
        return _dataArr.count;
    }
    return _searchResultsKeywords.count;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    
    schemeListModel *model = [self.dataArr objectAtIndexCheck:indexPath.row];
    static NSString *identifier = @"cell";
    schemeListCell *cell = [tableView dequeueReusableCellWithIdentifier:identifier];
    if (!cell) {
        cell = [[schemeListCell alloc] initForTableView:self.tableView withReuseIdentifier:identifier];
        cell.selectionStyle = UITableViewCellSelectionStyleNone;
        cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator;
    }
    
    if (tableView == self.tableView) {
        cell.model = model;//[self.searchResultsKeywords objectAtIndexCheck:indexPath.row];
    } else {
        cell.model = [self.searchResultsKeywords objectAtIndexCheck:indexPath.row];
    }
    
    [cell updateCellAppearanceWithIndexPath:indexPath];
    
    return cell;
    
}
- (void)searchResult:(NSString *)content searchController:(QMUISearchController *)searchController{
    
    [self.searchResultsKeywords removeAllObjects];
}
#### 问题截图 ####
![3fe246fa8c5addec11af276253dc607b](https://cloud.githubusercontent.com/assets/19200800/26194339/a94573a2-3bea-11e7-99ed-00010389a396.png)
![7d0f69b2b9ae16546a32828ea9227b8c](https://cloud.githubusercontent.com/assets/19200800/26194347/b059d304-3bea-11e7-86fc-1f5660df9ab0.png)

**Comment by TracyYanghandsome** [comment]
![3fcec234110472740993469ea8cc53b7](https://cloud.githubusercontent.com/assets/19200800/26194661/a9a92c48-3beb-11e7-8e84-5b1b7843d63f.png)
![053f6e57426c2c157046c63faa8204f9](https://cloud.githubusercontent.com/assets/19200800/26194669/b4338cee-3beb-11e7-8602-e13c6a5d1883.png)

**Comment by TracyYanghandsome** [comment]
之前是用TableView+SeachControl 把seachControl加在self.view上面 这样就不会出现之前的问题

**Comment by MoLice** [comment]
请检查你的self.view.frame.origin.y是从导航栏下方开始还是从0开始？

**Comment by TracyYanghandsome** [comment]
是从0开始的

**Comment by MoLice** [comment]
这个场景我们需要测试一下看能否重现。
在此之前你也可以自己重写QMUITableView的setContentOffset:和setContentInset: 方法，在里面打断点看看按照你所说的操作后，是谁触发了列表的offset/inset的变化，从而能找到问题根源。

**Comment by TracyYanghandsome** [comment]
- (void)willPresentSearchController:(QMUISearchController *)searchController {
    [QMUIHelper renderStatusBarStyleDark];
    //    self.navigationController.navigationBar.translucent = NO;
    
    NSLog(@"1contentOffsetY- %f",self.tableView.contentOffset.y);
    NSLog(@"1contentInsetY- %f",self.tableView.contentInset.top);
}

- (void)willDismissSearchController:(QMUISearchController *)searchController {
    
    NSLog(@"2contentOffsetY- %f",self.tableView.contentOffset.y);
    NSLog(@"2contentInsetY- %f",self.tableView.contentInset.top);
    
    BOOL oldStatusbarLight = NO;
    if ([self respondsToSelector:@selector(shouldSetStatusBarStyleLight)]) {
        oldStatusbarLight = [self shouldSetStatusBarStyleLight];
    }
    if (oldStatusbarLight) {
        [QMUIHelper renderStatusBarStyleLight];
    } else {
        [QMUIHelper renderStatusBarStyleDark];
    }
    
}
这样测试出来的结果是偏移了 第一次：1contentOffsetY- -64.000000 1contentInsetY- 64.000000 2contentOffsetY- -64.000000 2contentInsetY- 64.000000 
第二次：1contentOffsetY- -108.000000 1contentInsetY- 108.000000  2contentOffsetY- -108.000000 [fg; 2contentInsetY- 108.000000

**Comment by TracyYanghandsome** [comment]
- (void)willPresentSearchController:(QMUISearchController *)searchController {
    [QMUIHelper renderStatusBarStyleDark];
   
    NSLog(@"1contentOffsetY- %f",self.tableView.contentOffset.y);
    NSLog(@"1contentInsetY- %f",self.tableView.contentInset.top);
    NSLog(@"1tableViewY- %f",self.tableView.y);
    
    self.tableView.scrollEnabled = NO;
}

- (void)willDismissSearchController:(QMUISearchController *)searchController {
    
    self.tableView.scrollEnabled = YES;
    NSLog(@"2contentOffsetY- %f",self.tableView.contentOffset.y);
    NSLog(@"2contentInsetY- %f",self.tableView.contentInset.top);
    NSLog(@"2tableViewY- %f",self.tableView.y);
    
    BOOL oldStatusbarLight = NO;
    if ([self respondsToSelector:@selector(shouldSetStatusBarStyleLight)]) {
        oldStatusbarLight = [self shouldSetStatusBarStyleLight];
    }
    if (oldStatusbarLight) {
        [QMUIHelper renderStatusBarStyleLight];
    } else {
        [QMUIHelper renderStatusBarStyleDark];
    }
    
}
目前我是这样解决了这个问题 不知道这样解决是否妥当

**Comment by MoLice** [comment]
你是否有在某些地方修改过 `navigationBar.translucent` 或者 `UIViewController.automaticallyAdjustsScrollViewInsets`、`UIViewController.extendLayoutIncludesOpaqueBars` 、`UIViewController.edgesForExtendedLayout`这三个属性？有的话请恢复他们的值为默认值再尝试。

**Comment by TracyYanghandsome** [comment]
之前修改过navigationBar.translucent 现在恢复成默认的还是一样的

**Comment by MoLice** [comment]
那就不清楚了，需要实际测试才知道，你可以先按你那样改，我估计周末才能查。

**Comment by TracyYanghandsome** [comment]
好的 如果发现了是什么原因有什么好的解决方法请告知 麻烦了

**Comment by MoLice** [comment]
@TracyYanghandsome 方便的话加 QQ 细聊，298076318

**Comment by pjocer** [comment]
我比较好奇为什么要在search 界面加一个下拉刷新控件
