### ISSUE TITLE
QMUITableViewController的tableView content offset 与IQKeyboardManager有冲突，会无限增长

### ISSUE THREAD

**Issue by damonful** [QMUI/QMUI_iOS#124]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
QMUITableViewController的tableView content offset 与IQKeyboardManager有冲突
#### 问题截图 ####
操作步骤：
1. podfile引入pod 'IQKeyboardManager','~>4.0.9'和pod 'QMUIKit'
2. 执行QMUIDemo
3. 进入QMUISearchViewController
4. 点击搜索->取消
5. 重复操作4，观察tableview的contentOffset变化

**Comment by MoLice** [comment]
经测试，这个问题与 QMUI 无关，而是 IQKeyboardManager 对于这种 `UIViewController + UITableView` 的使用方式的支持都有问题。如下截图是一个 UIViewController 上自己添加一个 UITableView 和 UISearchController 后的测试效果，项目中没有用到 QMUIKit。

![image](https://cloud.githubusercontent.com/assets/1190261/26615748/e038a5b2-45fb-11e7-95af-747ebcb62c05.png)

有空的话我们会看看如何兼容，或者看 IQKeyboardManager 如何修复这个问题，目前可能不会优先处理。
