### ISSUE TITLE
QMUIPickImage 默认选取图片   预览图片的时候   图片显示位置不对

### ISSUE THREAD

**Issue by xeyuez** [QMUI/QMUI_iOS#125]
### 运行环境 ###

- [x] iOS 设备：`iPhone`
- [x] 系统版本：`iOS 10.3.1`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.6.1`

### 具体问题描述 ###
QMUIPickImage 默认选取图片   预览图片的时候   图片显示位置不对

#### 问题截图 ####

系统相册访问正常的图片
![img_0310](https://cloud.githubusercontent.com/assets/15902056/26393676/1de52f5c-409d-11e7-8ec2-9bd3cdd3ba8c.PNG)

选中后 预览时候的照片
![image](https://cloud.githubusercontent.com/assets/15902056/26391424/4c1f2ae2-4095-11e7-8ec9-e41b54705b39.png)

**Comment by hughkli** [comment]
你好，从截图来看似乎是 QMUIZoomImageView 的 viewportRect 属性设置错误，请尝试删掉设置 viewportRect 的相关代码再看看是否仍会出现这个 bug？

如果仍然出现 bug，请像下图中这样在 QMUIZoomImageView 的 -(void)handleDidEndZooming 的方法体最底部打一个断点，然后将底部的相关变量的数据截个图发给我们看一下？留意把 contentInset 的 top,left,bottom,right 四个值都展示在截图中。如果这个方法被多次调用到，选取最后一次被调用时截图就好。

<img width="1075" alt="e19f53fa-34c2-4529-9df6-1e04037845ea" src="https://cloud.githubusercontent.com/assets/15059475/26442271/5f51c5b2-4166-11e7-915b-a2c0e3249bc1.png">

**Comment by xeyuez** [comment]
注释了那段代码还是没有多大作用,顺序选择图片是好的,乱序选择图片就不行了 
或者左滑是好的右滑位置又错了

下面是取消所有注释代码的时候, 滑动到这张图片的截图....其余正常的图片显示是 top: 251, left: 0, bottom: 251, right: 0 手机是iphone6sP
![qq20170525-175411](https://cloud.githubusercontent.com/assets/15902056/26445598/35990f2a-4173-11e7-940f-c9104dfaa3b4.png)

**Comment by hughkli** [comment]
根据你提供的信息，猜测应该是 `QMUIZoomImageView.m 的 [`revertZooming`](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIComponents/QMUIZoomImageView.m#L214-L218) 方法实现里的一个 bug 导致的，将
 `revertZooming` 方法体里的 `self.imageView` 替换为 `[self currentContentImageView]` 应该就可以修复这个 bug。

我们会在预计本周六发布的一次大版本更新中统一修复这个 bug。

感谢您的反馈！

**Comment by hughkli** [comment]
根据你提供的信息，猜测应该是 `QMUIZoomImageView.m` 的 [`revertZooming`](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIComponents/QMUIZoomImageView.m#L214-L218) 方法实现里的一个 bug 导致的，将 `revertZooming` 方法体里的 `self.imageView` 替换为`[self currentContentImageView]` 应该就可以修复这个 bug。

我们会在预计本周六发布的一次大版本更新中统一修复这个 bug。

感谢您的反馈！

**Comment by xeyuez** [comment]
嗯 我试了一下,位置解决了,但还是有其他问题,如:1.滑动到最后几张图片显示的是黑屏,2.选中了9张图片但是可以滑动查看不止这九张(偶尔出现)       

但还是非常感谢你们的的开源项目,非常好用...

**Comment by hughkli** [comment]
非常非常抱歉现在才有时间回复你！

关于问题 2，滑动查看的本来就是整个相册的照片而非选中的照片，所以这个表现应该是符合预期的吧？

关于问题 1，请问具体什么操作途径能重现这个 bug 呢？如果没有稳定重现的途径的话，你可以按照以下途径给一些线索：
1）在 QMUIZoomImageView 的 setImage: 方法顶部打一个断点，看 image 是否为 nil，如果为 nil 则说明并没有成功拿到图片资源
2）如果成功拿到了图片资源又是黑屏，则可能是布局错误（比如 imageView 的 size 为 0 或位置被布局到了屏幕外），那么请和上次讨论的一样，在 handleDidEndZooming 方法底部打一个断点以提供一下 contentInset, contentViewFrame 等等信息帮助我们判断。

感谢！

**Comment by hughkli** [comment]
非常非常抱歉现在才有时间回复你！

关于问题 2，滑动查看的本来就是整个相册的照片而非选中的照片，所以这个表现应该是符合预期的吧？

关于问题 1，请问具体什么操作途径能重现这个 bug 呢？如果没有稳定重现的途径的话，你可以按照以下途径给一些线索：
1）在 `QMUIZoomImageView` 的 [`setImage:`](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIComponents/QMUIZoomImageView.m#L86) 方法顶部打一个断点，看 `image` 是否为 `nil`，如果为 `nil` 则说明并没有成功拿到图片资源
2）如果成功拿到了图片资源又是黑屏，则可能是布局错误（比如 `imageView.size` / `scrollView.contentSize` 之类的 为 0 或位置被布局到了屏幕外），那么请和上次讨论的一样，在 `handleDidEndZooming`[https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIComponents/QMUIZoomImageView.m#L276] 方法底部打一个断点以提供一下 `contentInset`, `contentViewFrame` 等等信息帮助我们判断。

感谢！

**Comment by hughkli** [comment]
非常非常抱歉现在才有时间回复你！

关于问题 2，滑动查看的本来就是整个相册的照片而非选中的照片，所以这个表现应该是符合预期的吧？

关于问题 1，请问具体什么操作途径能重现这个 bug 呢？如果没有稳定重现的途径的话，你可以按照以下途径给一些线索：
1）在 `QMUIZoomImageView` 的 [`setImage:`](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIComponents/QMUIZoomImageView.m#L86) 方法顶部打一个断点，看 image 是否为 nil，如果为 nil 则说明并没有成功拿到图片资源
2）如果成功拿到了图片资源又是黑屏，则可能是布局错误（比如 `imageView.size` / `scrollView.contentSize` 之类的 为 0 或位置被布局到了屏幕外），那么请和上次讨论的一样，在 [`handleDidEndZooming`](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIComponents/QMUIZoomImageView.m#L276) 方法底部打一个断点以提供一下 `contentInset`, `contentViewFrame` 等等信息帮助我们判断。

感谢！

**Comment by MoLice** [comment]
请更新 [1.7.0](https://github.com/QMUI/QMUI_iOS/releases/tag/1.7.0) 版本并重试。

**Comment by MoLice** [comment]
@xeyuez 请问使用新版后是否能解决上述问题？

**Comment by xeyuez** [comment]
还是感觉不太稳定啊 , 预览还会浏览到不是选中的图片

**Comment by kayo5994** [comment]
@xeyuez 你说的场景是否为：选中了若干张照片，然后预览，在预览的时候左右滑动会看到没有选中的照片？

**Comment by xeyuez** [comment]
是的

**Comment by kayo5994** [comment]
@xeyuez 这里的交互是这样的：

**Comment by MoLice** [comment]
@xeyuez 请问怎么样？确认是交互问题的话，我就 close 掉了
