### ISSUE TITLE
qmui_addSubview

### ISSUE THREAD

**Issue by johnko5057** [QMUI/QMUI_iOS#126]
### 运行环境 ###

- [x] iOS 设备：`iPhone 5S`
- [x] 系统版本：`iOS 8.1.3`
- [x] Xcode 版本：`8.3.1`
- [x] QMUI iOS 版本：`1.6.1`

### 具体问题描述 ###

在 iOS8 点击最后一个tabbar 时 崩溃 在qmui_addSubview

#### 问题截图 ####

![screen shot 2017-05-24 at 9 07 59 pm](https://cloud.githubusercontent.com/assets/13794636/26404656/4007e61a-40c5-11e7-8810-3000bd80ad9b.png)

**Comment by MoLice** [comment]
请贴一下更具体的信息，例如 Xcode 里对异常的描述、当前的堆栈信息、self指向哪个对象。
单纯靠目前的截图是无法定位到任何问题的。

**Comment by johnko5057** [comment]
![screen shot 2017-05-24 at 9 21 58 pm](https://cloud.githubusercontent.com/assets/13794636/26405209/3524d792-40c7-11e7-809b-8d14b337bff8.png)


(
82 "0 libobjc.A.dylib 0x0000000193883bdc objc_msgSend + 28",
83 "1 UIKit 0x0000000187d04f74 0x0000000187910000 + 4149108",
84 "2 UIKit 0x00000001879f9bec 0x0000000187910000 + 957420",
85 "3 UIKit 0x00000001879f9960 0x0000000187910000 + 956768",
86 "4 UIKit 0x0000000187a005e0 0x0000000187910000 + 984544",
87 "5 UIKit 0x000000018791d5f8 0x0000000187910000 + 54776",
88 "6 UIKit 0x000000018793ea34 0x0000000187910000 + 191028",
89 "7 UIKit 0x000000018791d310 0x0000000187910000 + 54032",
90 "8 UIKit 0x000000018791d310 0x0000000187910000 + 54032",
91 "9 UIKit 0x000000018791d310 0x0000000187910000 + 54032",
92 "10 UIKit 0x000000018791d310 0x0000000187910000 + 54032",
93 "11 UIKit 0x000000018791d310 0x0000000187910000 + 54032",
94 "12 UIKit 0x000000018791c9e0 0x0000000187910000 + 51680",
95 "13 UIKit 0x000000018791c8c0 0x0000000187910000 + 51392",
96 "14 UIKit 0x00000001879283a0 0x0000000187910000 + 99232",
97 "15 QMUIKit 0x0000000100f8f0e4 -[UIView(QMUI_Debug) qmui_addSubview:] + 420",
98 "16 UIKit 0x0000000187a140b0 0x0000000187910000 + 1065136",
99 "17 UIKit 0x0000000187a58128 0x0000000187910000 + 1343784",
100 "18 UIKit 0x0000000187a579f0 0x0000000187910000 + 1341936",
101 "19 UIKit 0x0000000187b215c4 0x0000000187910000 + 2168260",
102 "20 UIKit 0x0000000187955418 0x0000000187910000 + 283672",
103 "21 UIKit 0x0000000187b21430 0x0000000187910000 + 2167856",
104 "22 UIKit 0x0000000187955418 0x0000000187910000 + 283672",
105 "23 UIKit 0x000000018793e52c 0x0000000187910000 + 189740",
106 "24 UIKit 0x0000000187b21068 0x0000000187910000 + 2166888",
107 "25 UIKit 0x0000000187955418 0x0000000187910000 + 283672",
108 "26 UIKit 0x000000018793e52c 0x0000000187910000 + 189740",
109 "27 UIKit 0x0000000187954db4 0x0000000187910000 + 282036",
110 "28 QMUIKit 0x0000000100f76318 -[UIControl(QMUI) qmui_touchesEnded:withEvent:] + 444",
111 "29 UIKit 0x0000000187914750 0x0000000187910000 + 18256",
112 "30 CoreFoundation 0x000000018312aa50 0x000000018304c000 + 911952",
113 "31 CoreFoundation 0x00000001831279dc 0x000000018304c000 + 899548",
114 "32 CoreFoundation 0x0000000183127dbc 0x000000018304c000 + 900540",
115 "33 CoreFoundation 0x00000001830550a4 CFRunLoopRunSpecific + 396",
116 "34 GraphicsServices 0x000000018c1f75a4 GSEventRunModal + 168",
117 "35 UIKit 0x0000000187986aa4 UIApplicationMain + 1488",
118 "36 treasure 0x000000010014454c main + 124",
119 "37 libdyld.dylib 0x0000000193edea08 0x0000000193edc000 + 10760"
120 )

**Comment by johnko5057** [comment]
0 libobjc.A.dylib	objc_msgSend + 28
1 UIKit	-[UITableViewRowData _updateNumSections] + 88
2 UIKit	-[UITableViewRowData invalidateAllSections] + 76
3 UIKit	-[UITableView _updateRowData] + 220
4 UIKit	-[UITableView didMoveToWindow] + 68
5 UIKit	-[UIView(Internal) _didMoveFromWindow:toWindow:] + 1464
6 UIKit	-[UIScrollView _didMoveFromWindow:toWindow:] + 68
7 UIKit	-[UIView(Internal) _didMoveFromWindow:toWindow:] + 720
8 UIKit	-[UIView(Internal) _didMoveFromWindow:toWindow:] + 720
9 UIKit	-[UIView(Internal) _didMoveFromWindow:toWindow:] + 720
10 UIKit	-[UIView(Internal) _didMoveFromWindow:toWindow:] + 720
11 UIKit	-[UIView(Internal) _didMoveFromWindow:toWindow:] + 720
12 UIKit	___45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 144
13 UIKit	-[UIView(Hierarchy) _postMovedFromSuperview:] + 484
14 UIKit	-[UIView(Internal) _addSubview:positioned:relativeTo:] + 1764
15 QMUIKit	-[UIView(QMUI_Debug) qmui_addSubview:] + 420
16 UIKit	-[UITransitionView transition:fromView:toView:removeFromView:] + 1228
17 UIKit	-[UITabBarController transitionFromViewController:toViewController:transition:shouldSetSelected:] + 1536
18 UIKit	-[UITabBarController _setSelectedViewController:] + 360
19 UIKit	-[UITabBarController _tabBarItemClicked:] + 312
20 UIKit	-[UIApplication sendAction:to:from:forEvent:] + 96
21 UIKit	-[UITabBar _sendAction:withEvent:] + 468
22 UIKit	-[UIApplication sendAction:to:from:forEvent:] + 96
23 UIKit	-[UIControl _sendActionsForEvents:withEvent:] + 612
24 UIKit	-[UITabBar(Static) _buttonUp:] + 128
25 UIKit	-[UIApplication sendAction:to:from:forEvent:] + 96
26 UIKit	-[UIControl _sendActionsForEvents:withEvent:] + 612
27 UIKit	-[UIControl touchesEnded:withEvent:] + 592
28 QMUIKit	-[UIControl(QMUI) qmui_touchesEnded:withEvent:] + 444
29 UIKit	__UIGestureRecognizerUpdate + 8536
30 CoreFoundation	___CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
31 CoreFoundation	___CFRunLoopDoObservers + 360
32 CoreFoundation	___CFRunLoopRun + 836
33 CoreFoundation	CFRunLoopRunSpecific + 396
34 GraphicsServices	GSEventRunModal + 168
35 UIKit	UIApplicationMain + 1488
36 treasure	main + 124
37 libdyld.dylib	_start + 4
