### ISSUE TITLE
UIFont+QMUI.h 如何设置细体的动态字，只有正常和粗体动态字？

### ISSUE THREAD

**Issue by lijunW** [QMUI/QMUI_iOS#129]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by MoLice** [comment]
最近会更新 1.7.0 版本，动态字体的代码会重新整理，到时会增加 `UIDynamicFontLightMake()` 的宏。

**Comment by MoLice** [comment]
你好，请更新 [1.7.0](https://github.com/QMUI/QMUI_iOS/releases/tag/1.7.0) 版本，即可使用 `UIDynamicFontLightMake()` 宏。
