### ISSUE TITLE
请教一下关于子工程导入头文件

### ISSUE THREAD

**Issue by github410117** [QMUI/QMUI_iOS#130]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
我是将你们这个库作为子工程拖入到我主工程里的，然后我需要修改你们库中的一些文件，但是需要使用到我主工程pods里的第三方库，但是我导入头文件的时候提示无法找到，用import ""和import </>都找不到，设置了Header Search Paths也不行，第一次使用子工程这种，搜索了很久也没有找到解决办法，希望能在这里得到你们的解决办法，谢谢！

**Comment by MoLice** [comment]
>但是我导入头文件的时候提示无法找到，用import ""和import </>都找不到

你的意思是在你的项目里 import QMUI 时找不到，还是在 QMUI 里 import pods 里的第三方库时找不到第三方库？

**Comment by github410117** [comment]
第二种，在qmui里import pods里的第三方库找不到,可能我已经解决这个问题了，我把qumi从子工程删除改为使用pods导入，然后引入第三方库就可以使用，虽然弄好了，我还是想请教一下如果是子工程应该怎么处理这个问题呢？我在网上查询了一些关于profile的写法
例如：
xcodeproj 'Demo.xcodeproj'

platform :ios, "6.0"

def common_pods_for_target
    pod 'AA', '0.0.1'
    pod 'BB', '0.0.1'
    pod 'CC', '0.0.1'
    pod 'DD', '0.0.1'
    pod 'EE', '0.0.1'
    pod 'FF', '0.0.1'
    pod 'GG', '0.0.1'
end

target "Demo" do
    pod 'Demo-A', '3.1.1'
    pod 'Demo-B', '1.0'
    pod 'Demo-C', '~> 1.9.0'
    pod 'Demo-D', '~> 1.1'
    common_pods_for_target
end

target "DemoTests" do
    pod 'DemoTests-X', '3.1.1'
    pod 'DemoTests-Y', '0.4.0'
    pod 'DemoTests-Z', '4.1.1'
    common_pods_for_target
end

target "DemoWidget" do
    pod 'DemoWidget-1', '3.1.1'
    pod 'DemoWidget-2', '0.4.0'
    pod 'DemoWidget-3', '4.1.1'
end
我之前使用这种写法，虽然能够导入了，但是build的时候会报错
报错内容为`linker command failed with exit code 1 (use -vto see invocation)`
以前遇到这种情况一般是我导入了相同的.m文件导致，但是这个是直接clone下来你们的项目，应该不存在重复导入的问题，我查询资料弄了一个小时还是没有弄好！所以就改为pod导入了.
因为想多学习种思路，如果可以的话，希望您能够帮忙解决一下这个小问题！谢谢

**Comment by zhoon** [comment]
@github410117 据我所知子项目是无法import父项目的文件的，而且从使用规范来说也不应该这样做。如果需要做一些子项目依赖父项目的需求，要么你就不要使用子项目这种形式，要么你就在子项目开接口出来给父项目使用（就像QMUI的配置表的使用方式）。
