### ISSUE TITLE
【QMUIImagePickerViewController】一些细节问题

### ISSUE THREAD

**Issue by wanhmr** [QMUI/QMUI_iOS#133]
```
.h
@property(nonatomic, assign) NSInteger maximumSelectImageCount; // 最多可以选择的图片数，默认为无符号整形数的最大值，相当于没有限制
`实际上是 NSInteger `

.m
_alertTitleWhenExceedMaxSelectImageCount = [NSString stringWithFormat:@"你最多只能选择%lu张图片", (unsigned long)_maximumSelectImageCount];
`这里转换类型却用的是 unsigned long,  按照目前实际代码 _maximumSelectImageCount 是 NSInteger 类型， 应该使用 long `
```

**Comment by wanhmr** [comment]
我以前都是使用，%zd。今天临时一查，才发现这样有问题。
参考链接：
1.[stackoverflow](https://stackoverflow.com/questions/18893880/alternatives-to-type-casting-when-formatting-nsuinteger-on-32-and-64-bit-archi)
2.[appledoc](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Strings/Articles/formatSpecifiers.html#//apple_ref/doc/uid/TP40004265-SW1)

**Comment by MoLice** [comment]
今天已 commit 了一些代码，改正了这个类型问题。
