### ISSUE TITLE
NavigationBar现在支持隐藏吗？

### ISSUE THREAD

**Issue by Winter-Yang** [QMUI/QMUI_iOS#135]
比如我有视图控制器A->B->C

A: 导航栏为蓝色
B：导航栏隐藏
C：导航栏黄色

系统的导航栏隐藏需要每个都处理，不知道现在有支持吗

**Comment by zhoon** [comment]
导航栏的颜色QMUI是支持修改的，使用 QMUINavigationControllerDelegate 里面的 navigationBarBackgroundImage 等接口可以方便的控制每个控制器自己的颜色；
至于隐藏的话，如果是整条导航栏隐藏的话，就只能使用系统的接口 setNavigationBarHidden 每个控制器自己控制，如果只需要控制导航栏的背景色透明，而保留navItem，那么可以在 navigationBarBackgroundImage 里面返回一个透明的图片即可。

**Comment by Winter-Yang** [comment]
自己实现setNavigationBarHidden是可以实现我的需求，但是毕竟Navigation框架已经相当于重写了，建议应该加上支持这种需求，这个需求在国内还是毕竟常见的。
现实中可能还会有这种需求,
A页面是一个列表，随着列表滚动导航栏渐变，或者隐藏，目前修改背景图是用代理方法实现，这需求只能开发者自己实现
目前框架应该是不支持的。
我这边有2个建议：
1：支持导航栏的动态修改（颜色或透明随着滚动变化等待）、隐藏
2：全局pop返回，手机是越来越大，单手操作侧边返回并不方便，我觉得全屏幕pop是可以添加的，


这两个建议我在1.0的版本的基础上单独抽离出来做了修改，且实现了功能，但是在隐藏导航栏这块多次push、pop有bug，  希望QMUI后续版本可以添加这两个需求

**Comment by MoLice** [comment]
@Winter-Yang 你提到的有 3 个建议，逐个回复如下：

> 1. 由 QMUI 框架提供控制每个界面是否显示 `navigationBar` 的功能。

这个目前 QMUI 不支持，如果业务项目需要，建议可以这么处理：
1. 创建一个项目自己的 protocol，例如 `XxxNavigationControllerDelegate <QMUINavigationControllerDelegate>`，里面包含方法 `- (BOOL)shouldShowNavigationBar;`，然后让每个 viewController 都实现它。
2.  继承 `QMUINavigationController`，在 `willShowViewController:` 里询问要显示的 viewController 的 `shouldShowNavigationBar` 方法，根据返回值来更改 `navigationBar.hidden` 的值。

这样的解决方案本身较为简单，至于是否应该由 QMUI 来处理，我们后续会讨论这种需求的普适性后再决定。

<hr />

> 2. navigationBar 的样式随着界面上列表的滚动而变化

这种设计我们在微信读书里也大量使用，并且也是由独立的控件去实现，但目前暂未有将其加入到 QMUI 功能里的计划，因为考虑到一个是实现成本不高，另一个是需求不具备较高的普遍性——而这两个原因始终是我们在设计 QMUI 的功能时最优先考虑的点。目前这个阶段的 QMUI 不需要去引领设计/交互的潮流，所以我们会谨慎增加新功能，并且尽量以第三方控件的形式来提供支持。

<hr/>

> 3. 支持全屏幕内的手势返回

与第 2 点相同。

**Comment by wanhmr** [comment]
@MoLice @zhoon
我做了一个DEMO，大致实现了微信读书的效果。
但是遇到了如下问题：
如果设置 UINavigationBar 的 translucent 为 YES， backgroundImage 默认加了透明度，
如果设置为 NO，UINavigationBar 的 backgroundView 又不能透明了。
 [项目地址：https://github.com/wanhmr/TPNavBarParallaxViewController/tree/masterl](https://github.com/wanhmr/TPNavBarParallaxViewController/tree/masterl)

**Comment by zhoon** [comment]
尝试一下 translucent 为 YES 的时候可以把默认的 alpha 记下来作为 alpha 变化的一个最大值？

**Comment by zhoon** [comment]
@wanhmr 
尝试一下 translucent 为 YES 的时候可以把默认的 alpha 记下来作为 alpha 变化的最大值？

**Comment by wanhmr** [comment]
@zhoon 
```
   |    | <UINavigationBar: 0x100511470; frame = (0 20; 375 44); opaque = NO; autoresize = W; tintColor = color = RGBA: (0, 0, 0, 1.00), AARRGGBB: #ff000000; gestureRecognizers = <NSArray: 0x17004b2b0>; layer = <CALayer: 0x170030ca0>>
   |    |    | <_UIBarBackground: 0x100512640; frame = (0 -20; 375 64); userInteractionEnabled = NO; layer = <CALayer: 0x170030a80>>
   |    |    |    | <UIImageView: 0x100512f30; frame = (0 0; 375 64); alpha = 0.909804; opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x170031fe0>>
   |    |    |    | <UIImageView: 0x100513120; frame = (0 64; 375 0.5); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x170032060>>
   |    |    | <QMUINavigationTitleView: 0x100516770; baseClass = UIControl; frame = (173 11.5; 29 21); userInteractionEnabled = NO; tintColor = color = RGBA: (0, 0, 0, 1.00), AARRGGBB: #ff000000; layer = <CALayer: 0x170032e80>>, title = title, subtitle = (null)
   |    |    |    | <UILabel: 0x100508a70; frame = (0 0; 29 21); text = 'title'; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x17008c0d0>>
   |    |    |    | <UILabel: 0x100512860; frame = (0 0; 0 0); userInteractionEnabled = NO; layer = <_UILabelLayer: 0x17008c490>>
   |    |    |    |    | <_UILabelContentLayer: 0x174031c20> (layer)
   |    |    | <_UINavigationBarBackIndicatorView: 0x1005201c0; frame = (8 11.5; 13 21); alpha = 0; opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x1700344c0>>
```
当 UINavigationBar.translucent = YES
可以看到 _UIBarBackground.imageView （用来设置 backgroundImage） 的 alpha = 0.909804，
而且当我在控制器的生命周期 `viewDidAppear:` 方法中强行设置为 1，他也会自动再次设置为 0.909804。
但是奇怪的是我项目中同样的设置（也有可能我忽略了什么）, alpha 是正常的QAQ。

**Comment by wanhmr** [comment]
@zhoon  解决了，当我不用 storyboard，使用代码创建 navgation controller，就正常了。但是还不是知道这是为什么。

**Comment by provswin** [comment]
目前遇到一个问题，情况是这样的：
1、对QMUINavigationController的root ViewController设置导航栏为透明图片；即在navigationBarBackgroundImage中返回一个透明图片。root ViewController记作A
2、此时从root ViewController中Push到下一个ViewController中，这个新的ViewController记作B，B中没有做特殊处理，导航栏是[QMUICMI navBarBackgroundImage]；
3、再从B返回到A时，发现A的导航栏又不透明了。

另外，如果root ViewController中设置的导航栏不为透明图片，比如是一个红色图片，[UIImage qmui_imageWithColor:UIColorMakeWithRGBA(255, 0, 0, 1)];
那么返回从B返回A却是正常的显示为了红色。
这个不知道是什么原因

**Comment by provswin** [comment]
已解决，是由于在B中设置了self.navigationController.navigationBar.translucent = NO

**Comment by leixu2txtek** [comment]
> 目前遇到一个问题，情况是这样的：
> 1、对QMUINavigationController的root ViewController设置导航栏为透明图片；即在navigationBarBackgroundImage中返回一个透明图片。root ViewController记作A
> 2、此时从root ViewController中Push到下一个ViewController中，这个新的ViewController记作B，B中没有做特殊处理，导航栏是[QMUICMI navBarBackgroundImage]；
> 3、再从B返回到A时，发现A的导航栏又不透明了。
> 
> 另外，如果root ViewController中设置的导航栏不为透明图片，比如是一个红色图片，[UIImage qmui_imageWithColor:UIColorMakeWithRGBA(255, 0, 0, 1)];
> 那么返回从B返回A却是正常的显示为了红色。
> 不知道是什么原因，设置A的导航栏为透明时，从B返回时却又不透明了。

我在A viewController 中 设置 透明图片， home 退出，再回来，就又不透明了。 这个问题又遇到过吗？

**Comment by leixu2txtek** [comment]
> > 目前遇到一个问题，情况是这样的：
> > 1、对QMUINavigationController的root ViewController设置导航栏为透明图片；即在navigationBarBackgroundImage中返回一个透明图片。root ViewController记作A
> > 2、此时从root ViewController中Push到下一个ViewController中，这个新的ViewController记作B，B中没有做特殊处理，导航栏是[QMUICMI navBarBackgroundImage]；
> > 3、再从B返回到A时，发现A的导航栏又不透明了。
> > 另外，如果root ViewController中设置的导航栏不为透明图片，比如是一个红色图片，[UIImage qmui_imageWithColor:UIColorMakeWithRGBA(255, 0, 0, 1)];
> > 那么返回从B返回A却是正常的显示为了红色。
> > 不知道是什么原因，设置A的导航栏为透明时，从B返回时却又不透明了。
> 
> 我在A viewController 中 设置 透明图片， home 退出，再回来，就又不透明了。 这个问题又遇到过吗？

- (UIImage *)navigationBarBackgroundImage {
    
    return [UIImage qmui_imageWithColor:UIColorMakeWithRGBA(66, 66, 66, 0)];
}

这样是ok了， 不能使用 [UIImage new]

**Comment by MoLice** [comment]
> > 目前遇到一个问题，情况是这样的：
> > 1、对QMUINavigationController的root ViewController设置导航栏为透明图片；即在navigationBarBackgroundImage中返回一个透明图片。root ViewController记作A
> > 2、此时从root ViewController中Push到下一个ViewController中，这个新的ViewController记作B，B中没有做特殊处理，导航栏是[QMUICMI navBarBackgroundImage]；
> > 3、再从B返回到A时，发现A的导航栏又不透明了。
> > 另外，如果root ViewController中设置的导航栏不为透明图片，比如是一个红色图片，[UIImage qmui_imageWithColor:UIColorMakeWithRGBA(255, 0, 0, 1)];
> > 那么返回从B返回A却是正常的显示为了红色。
> > 不知道是什么原因，设置A的导航栏为透明时，从B返回时却又不透明了。
> 
> 我在A viewController 中 设置 透明图片， home 退出，再回来，就又不透明了。 这个问题又遇到过吗？

项目中是不是用了 QMUITheme？那是 QMUITheme 的问题，在 [这里](https://github.com/Tencent/QMUI_iOS/issues/839#issuecomment-560263339) 有 issue 跟进。

**Comment by leixu2txtek** [comment]
> > > 目前遇到一个问题，情况是这样的：
> > > 1、对QMUINavigationController的root ViewController设置导航栏为透明图片；即在navigationBarBackgroundImage中返回一个透明图片。root ViewController记作A
> > > 2、此时从root ViewController中Push到下一个ViewController中，这个新的ViewController记作B，B中没有做特殊处理，导航栏是[QMUICMI navBarBackgroundImage]；
> > > 3、再从B返回到A时，发现A的导航栏又不透明了。
> > > 另外，如果root ViewController中设置的导航栏不为透明图片，比如是一个红色图片，[UIImage qmui_imageWithColor:UIColorMakeWithRGBA(255, 0, 0, 1)];
> > > 那么返回从B返回A却是正常的显示为了红色。
> > > 不知道是什么原因，设置A的导航栏为透明时，从B返回时却又不透明了。
> > 
> > 
> > 我在A viewController 中 设置 透明图片， home 退出，再回来，就又不透明了。 这个问题又遇到过吗？
> 
> 项目中是不是用了 QMUITheme？那是 QMUITheme 的问题，在 [这里](https://github.com/Tencent/QMUI_iOS/issues/839#issuecomment-560263339) 有 issue 跟进。

ok, 我再看看，目前没太大影响
