### ISSUE TITLE
iOS11导航栏问题

### ISSUE THREAD

**Issue by github410117** [QMUI/QMUI_iOS#136]
### 运行环境 ###

- [x] iOS 设备： `模拟器`
- [x] 系统版本：`iOS 11`
- [x] Xcode 版本：`9`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
在模拟器上push的时候，会出现如下的现象，如图，好像iOS11的NavigationBar结构上有改动，希望能看一下。谢谢
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/15375736/27042187-cea3249a-4fc8-11e7-89b9-5d0504b61f6b.png)
![image](https://user-images.githubusercontent.com/15375736/27042201-d839f43e-4fc8-11e7-811f-8dd797f64e3b.png)

**Comment by zhoon** [comment]
感谢提醒，现在已经在修复中

**Comment by MoLice** [comment]
@github410117 已发布 [1.7.2](https://github.com/QMUI/QMUI_iOS/releases/tag/1.7.2) 版本，这个问题顺便修复了。
