### ISSUE TITLE
QDStaticTableViewController 中的 static cell 是不是 不能响应点击

### ISSUE THREAD

**Issue by lubaoyilang** [QMUI/QMUI_iOS#137]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###

QMUIStaticTableViewCellData staticTableViewCellDataWithIdentifier:0
                                                                                                          image:nil
                                                                                                           text:@"标题1"
                                                                                                     detailText:nil
                                                                                                  accessoryType:QMUIStaticTableViewCellAccessoryTypeDisclosureIndicator
                                                                                                         target:self
                                                                                                         action:@selector(aaaaa)]

通过你封装的方法 创建的 cell model，但是 不执行aaaa方法，代码是在你最新的demo中测试的，请帮忙看一下

**Comment by zhoon** [comment]
@lubaoyilang 是我们demo里面写漏了，应该要在 tableView:didSelectRowAtIndexPath: 里面调用一句 QMUIHelper 的代码

`- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    [tableView deselectRowAtIndexPath:indexPath animated:YES];
    [QMUIHelper staticTableView:tableView didSelectRowAtIndexPath:indexPath withDataSource:self.dataSource];
}`

**Comment by MoLice** [comment]
我们正在整理 static cell 相关的 demo 以及代码注释，这两天会更新一个版本，到时请关注。

**Comment by lubaoyilang** [comment]
@MoLice 
静态列表 能不能 增加一种 accessoryType，很多时候 ，列表右侧显示文字 还挺常用的。
自己也能在 库外边实现，但是 感觉 QMUI 原生支持会好很多

**Comment by lubaoyilang** [comment]
比如个人中心的 个人资料，可以一一查看 每项资料，昵称 性别 个性签名等。所以需要 在列表右侧显示文字。
但是个人资料还需要修改，比如更改昵称这些操作。希望可以 加入进来

**Comment by MoLice** [comment]
@lubaoyilang 你说的其实就是系统自带的 `UITableViewCellStyleValue1`。

至于右侧支持编辑文字，这种需求较复杂，以目前的简单接口是不可能实现的，就算实现操作起来也很麻烦。

其实  staticTableView 系列的代码本质上就是帮你创建一个拥有唯一 identifier 的 cell，它要解决的主要问题是在于“实现简单的功能却要写一堆繁杂的代码”，而不在于“用简单的代码去实现复杂的功能”，显然编辑昵称应该属于后者，所以建议自行实现。

**Comment by lubaoyilang** [comment]
@MoLice 好的，谢谢

**Comment by MoLice** [comment]
@lubaoyilang 已发布 [1.7.2](https://github.com/QMUI/QMUI_iOS/releases/tag/1.7.2) 版本，重构了 `QMUIStaticTableViewCellData` 组件，具体的使用请查看[头文件注释](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIComponents/StaticTableView/QMUIStaticTableViewCellDataSource.h#L16-L23)，或者 [QDStaticTableViewController.m](https://github.com/QMUI/QMUIDemo_iOS/blob/master/qmuidemo/Modules/Demos/Components/QDStaticTableViewController.m)，现在使用起来应该没有以前那么多不确定的东西了。
