### ISSUE TITLE
如何设置屏幕旋转

### ISSUE THREAD

**Issue by ChinaJackSion** [QMUI/QMUI_iOS#138]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
在需要旋转的控制器里添加了self.supportedOrientationMask=UIInterfaceOrientationMaskLandscapeRight;但是没什么效果。继承的是QMUICommonViewController和QMUINavigationController把这两个取消就可以旋转，继承之后就旋转不了了💔

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/27083978-e5769c88-507c-11e7-9246-8dd78f61c9d1.png)
我刚在 QD 里测试了是没问题的。

`supportedOrientationMask` 属性是 `QMUICommonViewController` 自己的属性，最终生效是通过询问 `[QMUICommonViewController supportedInterfaceOrientations]` 的返回值来实现的。请在 [QMUICommonViewController.m:160](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIMainFrame/QMUICommonViewController.m#L160) 打断点看 return 值是否是你想要的 `UIInterfaceOrientationMaskLandscapeRight`。

**Comment by ChinaJackSion** [comment]
@MoLice 你好，我试了再QDUIKitViewController里面添加的没问题。但是我想让控制器都是竖屏，只是到某个控制器时变成强制横屏。在Demo里试的，如果再QDButtonViewController等控制器里设置，没有起作用。

![2017-06-16 9 48 47](https://user-images.githubusercontent.com/15258279/27208682-c0afca92-5279-11e7-985c-60784417c488.png)

**Comment by MoLice** [comment]
@ChinaJackSion 哦你是这个场景，这属于 QMUI 没做好的点，下一个版本我们补充一下。

**Comment by ChinaJackSion** [comment]
@MoLice  好的，谢谢啦😄

**Comment by MoLice** [comment]
@ChinaJackSion 已发布 [1.7.2](https://github.com/QMUI/QMUI_iOS/releases/tag/1.7.2)，新版本里，你只需要通过 `QMUICommonViewController.supportedOrientationMask` 为每个界面设置支持的方向，即可在界面切换时自动帮你旋转屏幕方向。

另外配置表里提供的开关 `SupportedOrientationMask` 可以控制界面默认支持的方向。

**Comment by Eli51** [comment]
@ChinaJackSion  只在某个控制器横屏其他都竖屏在ipad上测试不起作用

**Comment by Eli51** [comment]
新版xcode设置变了已搞定   qmui代码没毛病

**Comment by ws1227** [comment]
> 新版xcode设置变了已搞定 qmui代码没毛病

什么问题
