### ISSUE TITLE
QMUILabel 的contentEdgeInsets 在 AutoLayout 下有问题

### ISSUE THREAD

**Issue by cjskw** [QMUI/QMUI_iOS#14]
### 运行环境 ###

- [x] iOS 设备：`模拟器`
- [x] 系统版本：`iOS 8.1`
- [x] Xcode 版本：`8.1`
- [x] QMUI iOS 版本：`1.1.4`

### 具体问题描述 ###
设置了 label 的 contentEdgeInsets 为 {3,5,3,5} 然后设置AutoLayout 的约束为居中，没有设置宽高，出现无法完整显示的问题。自己写了一个实现重写了 `intrinsicContentSize` 方法就没问题了。
#### 问题截图 ####
![simulator screen shot 2016 12 31 22 35 28](https://cloud.githubusercontent.com/assets/21332141/21577968/76fb49ce-cfa9-11e6-97c8-a07d35da1c40.png)

**Comment by zhoon** [comment]
目前大部分控件都还没有支持AutoLayout，我们会在后面考虑支持，感谢关注。

**Comment by cjskw** [comment]
谢谢回复，我觉得这种情况最好能在文档里说明一下，因为现在 AutoLayout 基本已经普及了。

**Comment by zhoon** [comment]
好的，谢谢提醒，我们先在文档里面说一下。
