### ISSUE TITLE
QMUISearchController隐藏取消按钮隐藏不了

### ISSUE THREAD

**Issue by LanYanQin** [QMUI/QMUI_iOS#140]
### 具体问题描述 ###
如题目标题一样，我在外部调用   
` [self.mySearchController.searchBar setShowsCancelButton:NO animated:NO];
`
还是没用，然后我进到QMUISearchController.m里的QMUICustomSearchController调用
` [self.mySearchController.searchBar setShowsCancelButton:NO animated:NO];
`
之后就会有一个隐藏动画，这让我不知道如何是好了。

**Comment by MoLice** [comment]
这个难题与 QMUI 无关，UIKit 本身就是这样的，我也很无奈。
