### ISSUE TITLE
上架被拒，2.5.1：使用苹果未公开的 APIs

### ISSUE THREAD

**Issue by KevinDengSir** [QMUI/QMUI_iOS#142]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
最近上架 App 但是被拒，是由于违反了2.5.1，发现 QMUIKit 使用了些未公开的 Api,
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/17451988/27490490-060d9ffe-5871-11e7-8a9c-d422679be14f.png)

**Comment by MoLice** [comment]
我们的App（QMUI ，以及使用QMUI 的其他App）目前是正常通过审核的，稍等我现在看看可以怎么解决。

**Comment by KevinDengSir** [comment]
你好，请问有解决方案了么？
其中有私有 api 在 QMUI 中是使用了的，另外两个估计也是。
![image](https://user-images.githubusercontent.com/17451988/27509605-7cbda9e2-5933-11e7-97e3-b46b8c3e9e0a.png)

**Comment by MoLice** [comment]
请把这段改为：
```Objective-C
+ (void)load {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        // 使用 [UIColor colorWithRed:green:blue:alpha:] 或 [UIColor colorWithHue:saturation:brightness:alpha:] 方法创建的颜色是 UIDeviceRGBColor 类型的而不是 UIColor 类型的
        ReplaceMethod([UIColor colorWithRed:1 green:1 blue:1 alpha:1].class, @selector(description), @selector(qmui_description));
    });
}
```

下午我们已经把修改后的 App 提交 AppStore，正常通过了 ipa 扫描阶段（这个阶段苹果也会检查私有 API），目前处于 waiting for review，期望以这个版本的提交来测试是否存在私有 API 的问题。

猜测 `UISearchBarTextField` 与 `UISearchBarBackground` 与 QMUI 无关，你可以先改 UIColor (QMUI) 那段试试看。

**Comment by KevinDengSir** [comment]
谢谢，如果有进展的话，希望您在在反馈下，非常需要你的帮助。

**Comment by MoLice** [comment]
好的

**Comment by MoLice** [comment]
@KevinDengSir 15分钟前过审了，所以 QMUI 的私有API使用是没问题的，建议可以检查项目内的代码。

**Comment by KevinDengSir** [comment]
好的，十分感谢您的帮助！
