### ISSUE TITLE
(BUG)我的TabBar不见了

### ISSUE THREAD

**Issue by Steven-Yung** [QMUI/QMUI_iOS#143]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.3.3`
- [x] QMUI iOS 版本：`1.7.1`

### 具体问题描述 ###
由于QMUI提供的TabBarConroller不够灵活(我需要类似微博的TabBar)，所以我使用了自己自定义的TabBarController,但是viewControllers依然使用QMUICommonViewController的子类，运行后发现在storyboard上预设的背景颜色消失了，好在TabBar还在，但是一旦viewControllers是navigationController(无论是QMUINavigationController还是UINavigationController),当然navigationController的rootViewController依然是QMUICommonViewController，这时候TabBarController就消失不见了(ಥ _ ಥ)，这是bug吗？
#### 问题截图 ####
未嵌入navigationController时：
![default](https://user-images.githubusercontent.com/8358206/27515723-fac49b58-59dc-11e7-9b05-99003a65103b.png)
![navigation](https://user-images.githubusercontent.com/8358206/27515724-039350f8-59dd-11e7-8c4d-3e9e25c44e6c.png)
嵌入navigationController后：
![tabbar](https://user-images.githubusercontent.com/8358206/27515727-128e107a-59dd-11e7-88ea-b2c80fa91cd0.png)
![tabbar](https://user-images.githubusercontent.com/8358206/27515728-190fee5a-59dd-11e7-975a-04196c8da3ce.png)
代码:
![default](https://user-images.githubusercontent.com/8358206/27515730-238d2956-59dd-11e7-9154-8ced144f7782.png)

**Comment by MoLice** [comment]
麻烦搜索微信号“qmui_team”加好友详聊

**Comment by Steven-Yung** [comment]
补充一句，如果ViewController是继承系统UIViewController运行能正常，一旦改成继承QMUICommonViewController就出问题了

**Comment by MoLice** [comment]
>运行后发现在storyboard上预设的背景颜色消失了

这是因为 `QMUICommonViewController` 在 [viewDidLoad](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIMainFrame/QMUICommonViewController.m#L60) 里强制把 `self.view` 的背景色修改为配置表里的值，导致在 storyboard 里设置的背景色失效。下个版本会修复，避免对 storyboard 的设置产生影响。在版本发布前建议在代码里手动修改背景色。

>这时候TabBarController就消失不见了

tabBar 的消失是因为 [QMUICommonViewController.m:42](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIMainFrame/QMUICommonViewController.m#L42) 修改了 `hidesBottomBarWhenPushed` 的值，默认修改为 `YES`，导致在 navigationController 里使用 `QMUICommonViewController` 时会把 tabBar 隐藏。这个也会在下个版本里修复，将默认值改为与系统相同的 `NO`。版本发布前建议重写 tabBarController 首页的那几个 viewController 的 `didInitialized` 方法，在里面将 `hidesBottomBarWhenPushed` 的值改为 `NO`。

**Comment by MoLice** [comment]
@Steven-Yung 已发布 [1.7.2](https://github.com/QMUI/QMUI_iOS/releases/tag/1.7.2) 版本，`QMUICommonViewController` 已经不会强制修改背景色了，而 `hidesBottomBarWhenPushed` 默认值也保持为 `NO`。

请更新 QMUI 版本后再重试。

**Comment by Steven-Yung** [comment]
@MoLice 谢谢
