### ISSUE TITLE
  QMUIAlertAction.button 的文字颜色怎么修改不了？费解。。。

### ISSUE THREAD

**Issue by dushihao** [QMUI/QMUI_iOS#145]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
大大们好，请问 如何修改 QMUIAlertAction.button 的文字颜色？我怎么修改之后，没有效果呢。哪里写错了么
#### 问题截图 ####
![2017-06-26 11 39 29](https://user-images.githubusercontent.com/16110584/27524075-6c52b23c-5a64-11e7-92cd-4d7492b9b0f5.png)
![2017-06-26 11 40 13](https://user-images.githubusercontent.com/16110584/27524078-6fef76e6-5a64-11e7-8570-65fecae84b65.png)

**Comment by MoLice** [comment]
`QMUIAlertController` 里控制按钮的文字样式是通过 `alertButtonAttributes` 属性来实现的，以达到对同一种 style 的 action 展示相同的样式的目的。最终实现上是使用 `button setAttributedTitle:forState:` 的接口，所以用 `setTitleColor:` 去修改是不生效的，只能设置一个新的 attributedTitle。另外由于按钮文字样式的设置是在 `showWithAnimated:` 里做的，所以你的自定义修改也只能在调用了 `showWithAnimated:` 之后才能做。

这样看来目前这个控件对自定义样式的使用不太友好，我们会重构它的接口，在后续的版本里更新。目前你的这种需求可以这么写：

```Objective-C
QMUIAlertAction *action1 = [QMUIAlertAction actionWithTitle:@"立即开启" style:QMUIAlertActionStyleDefault handler:nil];
QMUIAlertAction *action2 = [QMUIAlertAction actionWithTitle:@"暂不开启" style:QMUIAlertActionStyleDefault handler:nil];
QMUIAlertController *alertController = [QMUIAlertController alertControllerWithTitle:@"蓝牙" message:nil preferredStyle:QMUIAlertControllerStyleAlert];
[alertController addAction:action1];
[alertController addAction:action2];
[alertController showWithAnimated:YES];

NSMutableDictionary<NSString *, id> *alertButtonAttributes = [[NSMutableDictionary alloc] initWithDictionary:alertController.alertButtonAttributes];
alertButtonAttributes[NSForegroundColorAttributeName] = UIColorBlack;
[action2.button setAttributedTitle:[[NSAttributedString alloc] initWithString:action2.title attributes:alertButtonAttributes] forState:UIControlStateNormal];
```

![image](https://user-images.githubusercontent.com/1190261/27524616-2f46dd1e-5a69-11e7-83d1-935f57a9df04.png)

**Comment by dushihao** [comment]
老哥 ，稳  谢谢。
