### ISSUE TITLE
提两点建议

### ISSUE THREAD

**Issue by Steven-Yung** [QMUI/QMUI_iOS#146]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.7.2`

### 具体问题描述 ###
问题1：
QMUICommonTableViewController不能像使用系统UITableViewController一样使用，虽然有QMUIStaticTableViewCellData,但是不够灵活，例如不能在Storyboard里使用Static cells,在Cell里直接添加UILabel，UIButton，UITextField等等，直接OutLet到.h或者.m里去，有时候页面比较简单也会相对的花上不少时间，如果能像使用系统UITableViewController的static cells一样使用就好了
问题2：
showEmptyViewWithLoading显示的loading能自定义动画图片就好了，比如传一组帧动画的图片数组，用UIImageView的animationImages实现

**Comment by MoLice** [comment]
对于问题1，需要让 `QMUICommonTableViewController` 继承自 `UITableViewController` 而不是 `QMUICommonViewController`，这个需要再斟酌。

对于问题2，目前的 [loadingView](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIComponents/QMUIEmptyView.h#L25) 
属性已能实现自定义动画，你只要把符合类型的 UIView 传给 `loadingView` 即可。微信读书空界面的翻书 loading 就是这么实现的。
