### ISSUE TITLE
navigationBarBackgroundImage 这个方法，在进入后，再退出然后快速进入的时候，navi 背景失效

### ISSUE THREAD

**Issue by boai** [QMUI/QMUI_iOS#147]
### 运行环境 ###

- [x] iOS 设备：`iPhone 7` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 11`
- [x] Xcode 版本：`8.3`
- [x] QMUI iOS 版本：`1.7`

### 具体问题描述 ###
navigationBarBackgroundImage 这个方法，在进入后，再即将退出的时候然后快速进入，navi 背景失效
#### 问题截图 ####

- (UIImage *)navigationBarBackgroundImage
{
    return [UIImage imageWithColor:[UIColor redColor]];
}

**Comment by MoLice** [comment]
无法重现，请搜索微信号“qmui_team”详聊。

**Comment by boai** [comment]
加你了

**Comment by boai** [comment]
对了，刚更新 pod ，突然出现这个问题：
qmui_visibleViewControllerIfExist:，找不到可见的viewController。self = <UIViewController: 0x7fa9a1f06bb0>
superclass:				UIResponder
title:					(null)
view:					<UIView: 0x7fa9a1d134c0; frame = (0 0; 320 568); autoresize = W+H; layer = <CALayer: 0x60800023e1c0>>, self.view.window = (null)

**Comment by MoLice** [comment]
`qmui_visibleViewControllerIfExist` 的问题建议直接打断点在那个 `NSLog` 的位置，看是哪里调用。

这种一般都是调用时机不对的问题。
