### ISSUE TITLE
QMUIAlertController 在iOS8.3上蒙板没有效果，不能取消，且按钮sheet、alert上的按钮均不能响应点击事件

### ISSUE THREAD

**Issue by songxing10000** [QMUI/QMUI_iOS#148]
### 运行环境 ###

- [x] iOS 设备：`iPhone 5s`
- [x] 系统版本：`iOS 8.3`
- [x] Xcode 版本：`8.3.3`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by MoLice** [comment]
我刚在 iOS 8.3 上运行 QMUI Demo 测试了并没有这个问题。

QMUIAlertController 是通过 UIWindow 的方式显示出来的，猜测是否你当前界面有更高 `windowLevel` 的 UIWindow 实例存在，导致盖在 QMUIAlertController 的 window 上，从而无法点击。

**Comment by songxing10000** [comment]
就一个普通页面，弹窗，弹窗后，后面的可以操作，弹窗上的按钮不能点击奇怪 了

**Comment by MoLice** [comment]
是否可以写个 Demo，搜索微信号“qmui_team”（备注写 issue 编号）发我们看看？

**Comment by songxing10000** [comment]
demo已写好

**Comment by MoLice** [comment]
@songxing10000 是自行抽取 alertController 部分代码使用，并非使用完整的 QMUIKit，所以在 iOS 8 下，alertController 内的 window 的 frame.size 为 0，导致看得到内容却无法接受点击事件。

已解决，建议完整使用 QMUIKit 框架。

**Comment by songxing10000** [comment]
万分感谢

**Comment by lxooxl** [comment]
swift 中有同样的问题， 完整使用qmuiKit的情况下

**Comment by MoLice** [comment]
@lxooxl 请在[这里](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/QMUIComponents/QMUIModalPresentationViewController.m#L434)打断点，看 init 完后的 `self.containerWindow` frame 是否为 zero。

**Comment by lxooxl** [comment]
@MoLice  不为zero， 当controller持有alert的的时候 可以响应， 不持有的时候 就不能响应了

**Comment by lxooxl** [comment]
[qmuialert.zip](https://github.com/QMUI/QMUI_iOS/files/2000057/qmuialert.zip)
@MoLice  测试Demo
