### ISSUE TITLE
StaticCell问题

### ISSUE THREAD

**Issue by github410117** [QMUI/QMUI_iOS#149]
### 运行环境 ###

- [x] iOS 设备：`iPhone`
- [x] 系统版本：`iOS 11`
- [x] Xcode 版本：`9.0`
- [x] QMUI iOS 版本：`1.7.2`

### 具体问题描述 ###
使用`QMUIStaticTableViewCellDataSource`创建cell的时候由于需要有个cell的文字需要居中显示(退出登录),但是没有接口可以设置，还有cell文字颜色等大小好像都没办法设置，而且也获取不到cell，无法在当前控制器里自己修改cell样式，还有如果点击cell是弹出alertViewController，点击取消后，cell的选中颜色无法取消,还有个小问题没找到，就是当TableView的Style为Group时，第一个Section距离顶部的距离怎么那么远呢？

**Comment by MoLice** [comment]
请阅读 [QMUIStaticTableViewCellDataSource](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIComponents/StaticTableView/QMUIStaticTableViewCellDataSource.h#L21) 的注释（第 4 点），以及参考 QMUI Demo 里的[示例代码](https://github.com/QMUI/QMUIDemo_iOS/blob/master/qmuidemo/Modules/Demos/Components/QDStaticTableViewController.m#L175-L195)，你的需求都可以自行重写 UITableViewDelegate、UITableViewDataSource 来实现。

至于 group style 的列表顶部的间距，那些是系统默认行为，可自行修改 tableView.contentInset.top 的方式调整。
