### ISSUE TITLE
swift 3.0 下使用QMUIAlertController会crash

### ISSUE THREAD

**Issue by timelessg** [QMUI/QMUI_iOS#15]
### 运行环境 ###

- [x] iOS 设备：iPhone
- [x] 系统版本：`iOS 10.2`
- [x] Xcode 版本：`8.2`
- [x] QMUI iOS 版本：`1.1.4`

### 具体问题描述 ###
swift 3.0 下使用QMUIAlertController会crash
#### 问题截图 ####
![2017-01-03 11 43 16](https://cloud.githubusercontent.com/assets/8768185/21599583/e7f87df2-d1a9-11e6-990c-3f6ccdef816f.png)

**Comment by MoLice** [comment]
请参照 QMUI Demo，检查一下是否有在 `application:didFinishLaunchingWithOptions:` 调用 `[QMUIConfigurationTemplate setupConfigurationTemplate]` 和 `[QMUIConfigurationManager renderGlobalAppearances]`？

![image](https://cloud.githubusercontent.com/assets/1190261/21599644/ffd99dce-d1aa-11e6-976c-f40510ce7ab4.png)

**Comment by timelessg** [comment]
@MoLice 多谢

**Comment by sgxiang** [comment]
@MoLice 在swift项目里面用Carthage安装之后导入，发现调用不了QMUIConfigurationTemplate这个类，编译成的动态库没发现到.h头文件

**Comment by MoLice** [comment]
@timelessg @sgxiang 刚刚更新了 [1.5.0](https://github.com/QMUI/QMUI_iOS/releases/tag/1.5.0) 版本，对 3 种使用 QMUI iOS 的方式重新整理，其中对配置表 `QMUIConfigurationTemplate` 的使用也有明确的说明，建议重新查看哈。
