### ISSUE TITLE
为什么CocoaPods 用不了 显示找不到这个库 项目还可以就是集成困难 集成头大

### ISSUE THREAD

**Issue by batmanWeng** [QMUI/QMUI_iOS#150]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by MoLice** [comment]
https://github.com/QMUI/QMUI_iOS/issues/21

**Comment by MoLice** [comment]
@batmanWeng 请问解决吗？解决的话我就 close 掉这个 issue 了

**Comment by batmanWeng** [comment]
没有解决啊

**Comment by MoLice** [comment]
请贴具体的报错信息，不然没有任何帮助。

**Comment by batmanWeng** [comment]
Last login: Tue Jul  4 08:52:49 on console
Weng:~ zs$ cd /Users/zs/Desktop/QMUIDemo 
Weng:QMUIDemo zs$ touch Podfile
Weng:QMUIDemo zs$ pod install

[!] Invalid `Podfile` file: syntax error, unexpected ':', expecting end-of-input
platform: ios, '7.0'
         ^.

 #  from /Users/zs/Desktop/QMUIDemo/Podfile:1
 #  -------------------------------------------
 >  platform: ios, '7.0'
 #  pod 'QMUIKit'
 #  -------------------------------------------
Weng:QMUIDemo zs$ pod install
Analyzing dependencies
[!] The dependency `QMUIKit` is not used in any concrete target.
Weng:QMUIDemo zs$

**Comment by zhoon** [comment]
@batmanWeng 看你的信息好像是 Podfile 文件的语法写错了，麻烦确认一下？

[!] Invalid Podfile file: syntax error, unexpected ':', expecting end-of-input
platform: ios, '7.0'
^.

**Comment by batmanWeng** [comment]
看下面 显示搜不到这个框架

**Comment by batmanWeng** [comment]
[!] The dependency QMUIKit is not used in any concrete target.
Weng:QMUIDemo zs$

**Comment by coldmn3** [comment]
尝试 pod repo update 后再试试。

**Comment by batmanWeng** [comment]
问题已经解决了谢谢你
