### ISSUE TITLE
【导航条】显示错误

### ISSUE THREAD

**Issue by wanhmr** [QMUI/QMUI_iOS#151]
### 运行环境 ###

- [x] iOS 设备：`iPhone` 
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.7.2`

### 具体问题描述 ###
A 隐藏导航条，B 显示导航条。如果从 B 使用手势回退到 A 的途中取消手势，会导致 B  的导航条也消失，从代码来看，是因为 willAppear A 的时候设置了隐藏导航条，但是取消手势再次显示 B，并没有再设置回来。

#### 问题截图 ####
```
- (void)willShowViewController:(UIViewController *)viewController {
    // 子类可以重写
    [self renderStyleInNavigationController:self currentViewController:viewController];
}

- (void)didShowViewController:(UIViewController *)viewController {
    // 子类可以重写
}
```

**Comment by wanhmr** [comment]
感觉弄的好复杂啊，并且控制导航条的代码也不在一块（可能是有其他原因）。但是还是想吐槽，弄的好复杂。。。

**Comment by wanhmr** [comment]
我的疑问是，关于导航条的隐藏，为什么会有 `NavigationBarHiddenStateUsable` 这种东西？看注释，为了减少对项目的侵入性？但是就算加上，也并没有看出会比原来多很多？（也可能是我有没注意的地方，欢迎拍砖QAQ）。

**Comment by MoLice** [comment]
我们在 QMUI Demo 里使用 `QMUINavigationControllerDelegate preferredNavigationBarHiddenState` 来控制 bar 的显隐，并按照你说的“A 隐藏、B 显示”的方式来测试，是不会出现你说的问题的。

为什么提供一个 `preferredNavigationBarHiddenState` 的 delegate 方法来控制导航栏的显隐，是因为如果不这么做，那么你只能分别在 A 和 B 的 `viewWillAppear:`、`viewWillDisappear:` 里都写上一句控制导航栏显隐的代码，这样你总共需要写 4 句，而如果用 QMUI 提供的这个方法，你只需要写两句，并且是在统一、具备良好语义的方法里写。

配置表里提供 `NavigationBarHiddenStateUsable` 这个开关来控制 QMUI 是否要使用 `preferredNavigationBarHiddenState` 接口，是因为 QMUI 提供的所有功能的原则都是默认行为保持与系统一致，所以这个开关默认是关闭的，`preferredNavigationBarHiddenState` 也是无效的，只有当你需要用这种风格的代码来控制导航栏显隐时，才去打开它，这就是所谓的“减少对项目的侵入性”。

**Comment by wanhmr** [comment]
@MoLice 
![navigation_bar_test](https://user-images.githubusercontent.com/14258488/27798937-d8e79ae8-6045-11e7-9ea8-a7a93e17c9b6.gif)

**Comment by wanhmr** [comment]
@MoLice 

1. QMUICMI.navigationBarHiddenStateUsable = YES; 
2.`QDChangeNavBarStyleViewController`
```
- (QMUINavigationBarHiddenState)preferredNavigationBarHiddenState {
    if (self.barStyle == QDNavigationBarStyleDark) {
        return QMUINavigationBarHiddenStateHideWithoutAnimated;
    }else {
        return QMUINavigationBarHiddenStateShowWithoutAnimated;
    }
}
```

**Comment by wanhmr** [comment]
并且 `QMUICMI.navigationBarHiddenStateUsable ` 是进行全局控制的，不能够针对指定的控制器。这样子，如果我在新的控制器中想去使用，但我又要不影响旧代码，似乎能不能够做到。

**Comment by wanhmr** [comment]
我所说的代码复杂，是因为 QMUI 中控制转场效果的代码是分散的。只是根据 `NavigationBarHiddenStateUsable ` 来做处理，这样子看起来不是很舒服。

**Comment by MoLice** [comment]
看来是 WithoutAnimated 的有问题，带动画的是没问题的。
我们改一下，感谢反馈。

**Comment by MoLice** [comment]
发布了 [1.7.3](https://github.com/QMUI/QMUI_iOS/releases/tag/1.7.3)，该问题已修复。

**Comment by wanhmr** [comment]
@MoLice 1.7.3还是有问题。我提交了一个PR #152  ，请 review 一下。

**Comment by MoLice** [comment]
@wanhmr 今天测试过没问题。你说的有问题，也是用之前相同的代码测试吗？

**Comment by wanhmr** [comment]
@MoLice 有问题
```
- (QMUINavigationBarHiddenState)preferredNavigationBarHiddenState {
    if (self.barStyle == QDNavigationBarStyleDark) {
        return QMUINavigationBarHiddenStateHideWithAnimated;
    }else {
        return QMUINavigationBarHiddenStateShowWithoutAnimated;
    }
}
```
换成上面代码就有问题了

**Comment by wanhmr** [comment]
发现只要使用 `QMUINavigationBarHiddenStateHideWithAnimated` 就会有问题。

**Comment by wanhmr** [comment]
我觉得还是和 `- (void)setNavigationBarHidden:(BOOL)hidden animated:(BOOL)animated` 的调用时机有关。在 `viewWillAppear:` 之后调用就没有问题。

**Comment by wanhmr** [comment]
```
a push b:

b:viewWillAppear:
navigationController:willShowViewController:(UIViewController *)viewController animated:
b:viewDidAppear:
navigationController:didShowViewController:(UIViewController *)viewController animated:
```

发现 viewController 的生命周期函数会比 navigationCtroller 的代理方法更前一点。

而对于 navigationCtroller 的 `interactivePopGestureRecognizer` 手势回调，会比 viewController 的生命周期函数更前一点。如手势结束回调，然后才会 `viewWillAppear ` 、`viewDidAppear ` 等方法。

**Comment by wanhmr** [comment]
@MoLice 我完善了下这里，目前提交的 PR 所产生的效果和系统一致。并且不要主动控制 `- (void)setNavigationBarHidden:(BOOL)hidden animated:(BOOL)animated;` 方法的 `animated` 参数。

**Comment by wanhmr** [comment]
@MoLice 今天我继续整理了下，感觉已经比较可以了。测试的效果也已经符合预期，你可以测试看一下。并且从实际来看 `NavigationBarHiddenStateUsable ` 是没有必要的，当然可能我考虑的不完善，请斧正。

**Comment by wanhmr** [comment]
@MoLice 抱歉上次提交的有问题提。重新提交了 commit，并且在已在项目中使用没有发现问题。

**Comment by MoLice** [comment]
@wanhmr 你好，感谢反馈 QMUI 这个问题，我们发布了 [1.7.4](https://github.com/QMUI/QMUI_iOS/releases/tag/1.7.4) 版本，重新整理了这一部分的代码，具体可查看 Release 说明，谢谢！

**Comment by wanhmr** [comment]
@MoLice 收到，😓，本来为了解决子控制器影响导航条的问题，我又把代码移到了 `QMUINavigationController` 中。不过看了 1.7.4 的代码，代码还是可以在 `UINavigationController+NavigationBarTransition` 中的哈哈。
