### ISSUE TITLE
Bitcode

### ISSUE THREAD

**Issue by xeyuez** [QMUI/QMUI_iOS#153]
### 运行环境 ###

- [x] iOS 设备：`iPhone6s`
- [x] 系统版本：`iOS 11`
- [x] Xcode 版本：`8.2`
- [x] QMUI iOS 版本：`1.7`

### 具体问题描述 ###
ld: bitcode bundle could not be generated because '/Users/yuez/Desktop/amway2/ECPChat/QMUIKit.framework/QMUIKit' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

#### 问题截图 ####
![image](https://user-images.githubusercontent.com/15902056/27898186-51e47a0c-6257-11e7-91f8-9c3f7debe0ac.png)

打包出现的,   Build Settings 中关闭Bitcode 重新打包就好了 .是QMUIKit 没用Bitcode, 还是我使用的姿势不对?

**Comment by MoLice** [comment]
我们目前多个项目的使用均没遇到 bitcode 的问题，你是在 CocoaPods 里指定 `use_frameworks!` 吗？

建议可以先自行搜索。

**Comment by LH-Liu** [comment]
我今天用cartHage集成碰见了同样的问题。
![image](https://user-images.githubusercontent.com/14884787/59319895-eac6f500-8cfe-11e9-9714-55f8d2da085c.png)
