### ISSUE TITLE
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '如果你看到这条提示，建议到 GitHub 上提 issue，让我们联系你查看项目的配置表使用情况，否则请注释掉这一行。' BUG

### ISSUE THREAD

**Issue by gouhanghang** [QMUI/QMUI_iOS#1570]
**Bug 表现**
允许项目 奔溃

**截图**
![WX20240923-105208](https://github.com/user-attachments/assets/a91caff2-cce0-4976-a623-2bd7634ec70c)

**如何重现**
1. 在OC项目中,添加swift.vc文件, 就会报这个错误信息! 100% 报错. 而且项目运行不下去.
2. 如果隐藏掉 if (numberOfClasses <= 0) {} 是可以运行, 但是后面导航栏哪些就会有问题

**预期的表现**
在未更新Xcode16之前可以运行. 更新以后直接奔溃

**其他信息**
 - 设备: 
 - iOS 版本: [iOS 18.0]
 - Xcode 版本: [Xcode 16.0]
 - QMUI 版本: [4.8.0]
 - OS版本: 15.0

 在以上最新的版本系统中,项目直接跑不起来! 希望引起重视. 谢谢

@MoLice  MoLice

**Comment by gouhanghang** [comment]
我在补充一下,  是在OC项目中添加swift 控制器并且继承UI QM VC 导致的这个问题,..

**Comment by gouhanghang** [comment]
我测试了, 新建OC项目里面在新建SWIFT 项目, 它100% 奔溃

**Comment by gouhanghang** [comment]
@tencent-adm

**Comment by cczufish** [comment]
*** Assertion failure in -[QMUIConfiguration applyInitialTemplate], QMUIConfiguration.m:101
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '如果你看到这条提示，建议到 GitHub 上提 issue，让我们联系你查看项目的配置表使用情况，否则请注释掉这一行。'      ios18

**Comment by MoLice** [comment]
4.8.0 还是有问题？

**Comment by gouhanghang** [comment]
> 4.8.0 还是有问题？

是的, 大佬, 而且是100% 报错, 如何方便的话, 你可以联系我: 1067197037@qq.com  到时候可以远程看看什么问题. 大家一起来解决这个问题

希望大佬能 帮忙解决, 因为我的项目就用的是你的架构, 而且很重要, ZF项目.

**Comment by gouhanghang** [comment]
> 4.8.0 还是有问题？

希望大佬能 帮忙解决,  因为我的项目就用的是你的架构, 而且很重要, ZF项目.

**Comment by MoLice** [comment]
![IMG_6987](https://github.com/user-attachments/assets/ba5dbd2f-5aae-4d6d-9fa7-9fd4140285cf)

**Comment by cikichen** [comment]
~~同样，模拟器运行报错，4.8.0~~,4.8.0不报错了，最低版本要升级到13

**Comment by buginux** [comment]
碰到了同样的问题，请问有解决方案了吗？临时的方案也行，现在项目运行不起来，比较着急。

**Comment by MenaceiOS** [comment]
碰到了同样的问题，请问有解决方案了吗？临时的方案也行，现在项目运行不起来，比较着急。

**Comment by winterwd** [comment]
同样问题，刚更新的 xcode16，就不能用了

**Comment by MoLice** [comment]
已经发了4.8.0就有解决这个问题，自行更新。

**Comment by MyNameIsXiongWen** [comment]
> 已经发了4.8.0就有解决这个问题，自行更新。

有没有最低支持系统低于iOS13的办法啊，有一部分客户还是比较老的iPad，iOS12的，

**Comment by Microhx** [comment]
找到一个简单的方法，找到 QMUIConfiguration.m 文件，直接把那一行注释掉即可：

<img width="1354" alt="Image" src="https://github.com/user-attachments/assets/f5f7c579-c9ab-403a-8d3e-1f680c121273" />
