### ISSUE TITLE
关于QMUIPopupMenuView在4.8.0版本中的改变

### ISSUE THREAD

**Issue by DLsunset** [QMUI/QMUI_iOS#1575]
QMUIPopupMenuView相比之前少了很多灵活的设置，尤其是Item的字体和颜色的设置，之前是使用的字体和颜色的不同来区分item的选中状态，现在新版本完全做不到了，可不可以再加回来对item字体和颜色的设置功能呢？

----------
研究了一下之后找到了设置颜色的方法
目前使用的是这种方式

<img width="1137" alt="image" src="https://github.com/user-attachments/assets/92b6e9ae-cf2c-4201-8fe1-2c5899780caa">

但是这段代码需要在每次show的时候都调用一下。

请问有没有更合适的方法实现这样的功能。也就是不使用自带的勾选选中，而是使item在选中的时候显示不同颜色来区分选中状态。

**Comment by MoLice** [comment]
你截图的写法是一种方式。
另一种是你可以继承一个自己的 QMUIPopupMenuItemView 子类，在里面根据 self.selected、self.highlighlited 去设置不同的颜色，这样业务在 itemViewConfigurationHandler 里只需要修改 itemView.selected 的值即可，具体的色值就被解耦到你的 itemView 子类里。这是我认为比较合理的做法。
