### ISSUE TITLE
升级到xcode16后,运行代码报如图的错误

### ISSUE THREAD

**Issue by weiza-paradise** [QMUI/QMUI_iOS#1577]
使用的是 iPad

![WechatIMG319](https://github.com/user-attachments/assets/145da849-a802-4c3f-9e3c-e4e4d7187682)

 - iOS 版本: [iOS 18.0.1]
 - Xcode 版本: [Xcode 16]
 - QMUI 版本: [4.8.0]

**Comment by weiza-paradise** [comment]
QMUIKit 版本:  4.6.0

**Comment by ngn999** [comment]
升级到4.8.0看看.

**Comment by MoLice** [comment]
https://github.com/Tencent/QMUI_iOS/issues/1570
