### ISSUE TITLE
QMUIPopupMenuButtonItem被移除掉了?是否有其他替代组件

### ISSUE THREAD

**Issue by yz7805325** [QMUI/QMUI_iOS#1578]
![1728461770472](https://github.com/user-attachments/assets/c5ddab6e-57b2-43f4-b8c5-9a5253f27afa)

![2](https://github.com/user-attachments/assets/629dbbde-0922-46bc-b495-f5dbe1d6ba75)

QMUIPopupMenuButtonItem被移除掉了? 引用比较多改动有点大,是否有其他替代组件?

XCode16
iOS18
QMUIKit 4.8.0

**Comment by winterwd** [comment]
QMUIPopupMenuItem
看看这个是不是可以用？

**Comment by yz7805325** [comment]
可用~
