### ISSUE TITLE
UINavigationBar的崩溃问题

### ISSUE THREAD

**Issue by yz7805325** [QMUI/QMUI_iOS#1579]
<img width="1199" alt="image" src="https://github.com/user-attachments/assets/9d3e8fd1-ef4b-4ebc-a4eb-175847188721">

配置项如下:
![image](https://github.com/user-attachments/assets/b93d885f-60c7-400f-9b6c-60977ec2ca7a)

<img width="965" alt="image" src="https://github.com/user-attachments/assets/9c3ce181-3ebc-4d09-ae14-b8c58c21b643">

XCode16
iOS18
QMUIKit 4.8.0

**Comment by mygithub877** [comment]
same as question

**Comment by saySnake** [comment]
same as question

**Comment by MoLice** [comment]
https://github.com/Tencent/QMUI_iOS/issues/1570
