### ISSUE TITLE
QMUIModalPresentationViewController展示自定义view时，能用xib处理吗

### ISSUE THREAD

**Issue by songxing10000** [QMUI/QMUI_iOS#158]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by MoLice** [comment]
已发布 [1.7.4](https://github.com/QMUI/QMUI_iOS/releases/tag/1.7.4)，在 [QMUIModalPresentationViewController.h:111](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIComponents/QMUIModalPresentationViewController.h#L111) 增加 `IBOutlet` 声明。

**Comment by songxing10000** [comment]
好的，改天试一试，之前自定义view，只能是手码frame

**Comment by MoLice** [comment]
frame 确实是需要手写代码哦，因为 modalPresentationController 里有一套管理浮层布局的接口。1.7.4 增加的 `IBOutlet` 只是方便你指定一个自定义的 view 而已（使用自定义 view 的目的应该是为了管理 view 自己内部的 subview，而不是为了处理 view 和 modalPresentationController 的关系）

**Comment by songxing10000** [comment]
原来如此，有时间试试这个新改变

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
