### ISSUE TITLE
iOS 17 升级至 iOS 18 后项目无法启动

### ISSUE THREAD

**Issue by JakeChain** [QMUI/QMUI_iOS#1580]
**Bug 表现**
之前iOS 17 时项目运行是可以正常运行的，升级到iOS 18后出现错误，启动就报错无法运行

**截图**
<img width="1509" alt="image" src="https://github.com/user-attachments/assets/36e58344-81e4-4f05-9885-4e84ee129d10">
<img width="1508" alt="image" src="https://github.com/user-attachments/assets/a0580b50-d877-403e-bffd-f7591a616cfa">

**如何重现**
1. 项目启动就报错

**预期的表现**
项目能够正常启动

**其他信息**
 - 设备: iPhone 13 Pro
 - iOS 版本: iOS 18.0.1
 - Xcode 版本: Xcode 16.0
 - QMUI 版本: static NSString * const QMUI_VERSION = @"4.7.0";

**Comment by luckyczh** [comment]
> **Bug 表现** 之前iOS 17 时项目运行是可以正常运行的，升级到iOS 18后出现错误，启动就报错无法运行
> 
> **截图** <img alt="image" width="1509" src="https://private-user-images.githubusercontent.com/17683311/375176060-36e58344-81e4-4f05-9885-4e84ee129d10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MjU2NTMsIm5iZiI6MTcyODUyNTM1MywicGF0aCI6Ii8xNzY4MzMxMS8zNzUxNzYwNjAtMzZlNTgzNDQtODFlNC00ZjA1LTk4ODUtNGU4NGVlMTI5ZDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDAxNTU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZWIzZmMyMTVmODgyN2FkNTAyNWIzYmY3YzM2ZGE4NzRhNTAzOWE4MjVmMmEzYThiNDk5N2Q0OTgxNmE3ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8Jj1TVp8LcFfFCH5K0B-tK1D1k0xoID9TYtq3vV3fic"> <img alt="image" width="1508" src="https://private-user-images.githubusercontent.com/17683311/375176174-a0580b50-d877-403e-bffd-f7591a616cfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MjU2NTMsIm5iZiI6MTcyODUyNTM1MywicGF0aCI6Ii8xNzY4MzMxMS8zNzUxNzYxNzQtYTA1ODBiNTAtZDg3Ny00MDNlLWJmZmQtZjc1OTFhNjE2Y2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDAxNTU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNjZlYmZmYWYzMzA3OTg3ZGJkNWE0Mjk5ZmM2Yjg5Yjg5ZThmZTU3YTA2Mjg3OGVmMjdkZWY1YWY4ZGEzZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8QU9__nf3kaW1oT6arTFIlB2Xu1BECzXpPjD8slxFpQ">
> 
> **如何重现**
> 
> 1. 项目启动就报错
> 
> **预期的表现** 项目能够正常启动
> 
> **其他信息**
> 
> * 设备: iPhone 13 Pro
> * iOS 版本: iOS 18.0.1
> * Xcode 版本: Xcode 16.0
> * QMUI 版本: static NSString * const QMUI_VERSION = @"4.7.0";

升级到最新版本4.8.0

**Comment by winterwd** [comment]
> > **Bug 表现** 之前iOS 17 时项目运行是可以正常运行的，升级到iOS 18后出现错误，启动就报错无法运行
> > **截图** <img alt="image" width="1509" src="https://private-user-images.githubusercontent.com/17683311/375176060-36e58344-81e4-4f05-9885-4e84ee129d10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MjU2NTMsIm5iZiI6MTcyODUyNTM1MywicGF0aCI6Ii8xNzY4MzMxMS8zNzUxNzYwNjAtMzZlNTgzNDQtODFlNC00ZjA1LTk4ODUtNGU4NGVlMTI5ZDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDAxNTU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZWIzZmMyMTVmODgyN2FkNTAyNWIzYmY3YzM2ZGE4NzRhNTAzOWE4MjVmMmEzYThiNDk5N2Q0OTgxNmE3ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8Jj1TVp8LcFfFCH5K0B-tK1D1k0xoID9TYtq3vV3fic"> <img alt="image" width="1508" src="https://private-user-images.githubusercontent.com/17683311/375176174-a0580b50-d877-403e-bffd-f7591a616cfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MjU2NTMsIm5iZiI6MTcyODUyNTM1MywicGF0aCI6Ii8xNzY4MzMxMS8zNzUxNzYxNzQtYTA1ODBiNTAtZDg3Ny00MDNlLWJmZmQtZjc1OTFhNjE2Y2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDAxNTU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNjZlYmZmYWYzMzA3OTg3ZGJkNWE0Mjk5ZmM2Yjg5Yjg5ZThmZTU3YTA2Mjg3OGVmMjdkZWY1YWY4ZGEzZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8QU9__nf3kaW1oT6arTFIlB2Xu1BECzXpPjD8slxFpQ">
> > **如何重现**
> > 
> > 1. 项目启动就报错
> > 
> > **预期的表现** 项目能够正常启动
> > **其他信息**
> > 
> > * 设备: iPhone 13 Pro
> > * iOS 版本: iOS 18.0.1
> > * Xcode 版本: Xcode 16.0
> > * QMUI 版本: static NSString * const QMUI_VERSION = @"4.7.0";
> 
> 升级到最新版本4.8.0

项目最低支持到 iOS12，使用的是 4.6.0 版本，但是从 4.6.1 以后 QMUI 最低需要 iOS13 了，无解了。。。

**Comment by Jonas-o** [comment]
看最新版的 commit 记录里面有答案 ，附截图
![WX20241010-105126@2x](https://github.com/user-attachments/assets/fbbda3cb-cb4c-4a2a-b930-16cf3e9715c9)

**Comment by Jonas-o** [comment]
> 看最新版的 commit 记录里面有答案 ，附截图 ![WX20241010-105126@2x](https://private-user-images.githubusercontent.com/31504742/375197589-fbbda3cb-cb4c-4a2a-b930-16cf3e9715c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTQ1MTEsIm5iZiI6MTcyODU1NDIxMSwicGF0aCI6Ii8zMTUwNDc0Mi8zNzUxOTc1ODktZmJiZGEzY2ItY2I0Yy00YTJhLWI5MzAtMTZjZjNlOTcxNWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA5NTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYzVhNDI3ZTE3ZjRhYTg1ZmMyZjM1ODc5NGM5YzA2ZTlhNDYyOTA3Yzc0ODA5MmI4Y2U4OTZhYmJhYjg4NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NudbqMIsjYlS-1eKfJYZvt2Kd16MpeO-owe7L9zi6cQ)

@MoLice 老大，这个解决方案还是有点问题，Xcode 16 运行低于 iOS 18 版本设备的时候还是不行的，所以不能用 @available(iOS 18.0, *) 去判定，实测 #ifdef __IPHONE_18_0 可以的

**Comment by Jonas-o** [comment]
> > 看最新版的 commit 记录里面有答案 ，附截图 ![WX20241010-105126@2x](https://private-user-images.githubusercontent.com/31504742/375197589-fbbda3cb-cb4c-4a2a-b930-16cf3e9715c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTQ1MTEsIm5iZiI6MTcyODU1NDIxMSwicGF0aCI6Ii8zMTUwNDc0Mi8zNzUxOTc1ODktZmJiZGEzY2ItY2I0Yy00YTJhLWI5MzAtMTZjZjNlOTcxNWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA5NTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYzVhNDI3ZTE3ZjRhYTg1ZmMyZjM1ODc5NGM5YzA2ZTlhNDYyOTA3Yzc0ODA5MmI4Y2U4OTZhYmJhYjg4NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NudbqMIsjYlS-1eKfJYZvt2Kd16MpeO-owe7L9zi6cQ)
> 
> @MoLice 老大，这个解决方案还是有点问题，Xcode 16 运行低于 iOS 18 版本设备的时候还是不行的，所以不能用 @available(iOS 18.0, *) 去判定，实测 #ifdef __IPHONE_18_0 可以的

@MoLice 打扰了，我又去看了下 commit 「替换判断方式为Xcode16」已经改过来了😜

**Comment by MoLice** [comment]
> > @MoLice 老大，这个解决方案还是有点问题，Xcode 16 运行低于 iOS 18 版本设备的时候还是不行的，所以不能用 @available(iOS 18.0, *) 去判定，实测 #ifdef __IPHONE_18_0 可以的
> 
> @MoLice 打扰了，我又去看了下 commit 「替换判断方式为Xcode16」已经改过来了😜

无懈可击的代码 🫵
