### ISSUE TITLE
请问现在Xcode不显示我们IBInspectable扩展的属性了吗？

### ISSUE THREAD

**Issue by mazhao1609** [QMUI/QMUI_iOS#1581]
如题

**Comment by sunimp** [comment]
> 如题

Xcode 16 Interface Builder Know Issues:
> IBInspectable properties are no longer accessible in Interface Builder. Current values in IB Documents are still compiled into the NIBs and used at runtime. (135140474) (FB15011501)

https://developer.apple.com/documentation/xcode-release-notes/xcode-16_1-release-notes#Interface-Builder
