### ISSUE TITLE
QMUIButton 崩溃

### ISSUE THREAD

**Issue by jaydenin** [QMUI/QMUI_iOS#1589]
**Bug 表现**
使用QMUIButton 显示图标之后，更新图标就崩溃了

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图
<img width="1511" alt="企业微信截图_6cf710d5-e70c-47c7-a4f5-866edd3eae4b" src="https://github.com/user-attachments/assets/39db29c3-9068-455d-b30b-89ecee9efb09">

**如何重现**
1. 通过 pod 'QMUIKit', '4.6.3' 
2. 通过代码把按钮添加到界面之后，可以正常显示
3. 推测是调用了`- (void)setImage:(nullable UIImage *)image forState:(UIControlState)state;`方法更新图片就崩溃了，不过我还没复现，只是看见了这个崩溃的记录

**预期的表现**
不会崩溃

**其他信息**
 - 设备: [iPhone 13]
 - iOS 版本: [iOS 17.5.1]
 - Xcode 版本: [Xcode 15.4]
 - QMUI 版本: [4.6.3]

**Comment by MoLice** [comment]
你在非主线程里去操作 UI？

**Comment by jaydenin** [comment]
是的，都是在非主线程里去刷新 tableview，但是不是每次都崩溃。修改为在主线程刷新就问题了。

**Comment by MoLice** [comment]
那你不挂谁挂...
