### ISSUE TITLE
拦截返回手势错误

### ISSUE THREAD

**Issue by iceDays** [QMUI/QMUI_iOS#159]
### 运行环境 ###

- [x] iOS 设备：iPhone
- [x] 系统版本：iOS 10.3
- [x] Xcode 版本：8.3.2
- [x] QMUI iOS 版本：1.7.3

### 具体问题描述 ###
二级页面拦截返回手势, 当有三级页面时, 手势返回二级页面也会拦截, 点击返回按钮无问题
A -> B
B 添加 canPopViewController
B -> C
C -> B ,错误的显示了弹框

#### 问题截图 ####
![301500017316_ pic](https://user-images.githubusercontent.com/18232351/28202698-295f6e04-68a9-11e7-8736-e98e66de3b01.jpg)

**Comment by iceDays** [comment]
QMUIModalPresentationViewController 状态条颜色为默认 无法修改

**Comment by MoLice** [comment]
状态栏颜色可以自行调用 `[QMUIHelper renderStatusBarStyleDark]` 或 `[QMUIHelper renderStatusBarStyleLight]` 修改。

**Comment by MoLice** [comment]
issue 本身提的问题是 QMUI 的 bug，已发布 [1.7.4](https://github.com/QMUI/QMUI_iOS/releases/tag/1.7.4) 修复这个问题，感谢反馈。
