### ISSUE TITLE
如果你看到这条提示，建议到 GitHub 上提 issue，让我们联系你查看项目的配置表使用情况，否则请注释掉这一行。

### ISSUE THREAD

**Issue by ningzhaochen** [QMUI/QMUI_iOS#1592]
**Bug 表现**
如果你看到这条提示，建议到 GitHub 上提 issue，让我们联系你查看项目的配置表使用情况，否则请注释掉这一行。

**截图**

**如何重现**
1. 启动项目时出现

**预期的表现**
顺利启动

**其他信息**
 - 设备: iPhone
 - iOS 版本: [iOS 18.0.1]
 - Xcode 版本: [Xcode 16.0]
 - QMUI 版本: [4.4.3]

**Comment by MoLice** [comment]
https://github.com/Tencent/QMUI_iOS/issues/1556
