### ISSUE TITLE
Xcode版本16.1 使用最新版的QMUIKit崩溃

### ISSUE THREAD

**Issue by xiangnizhidao** [QMUI/QMUI_iOS#1594]
![1730534104882](https://github.com/user-attachments/assets/747e630d-5e5f-4058-bec1-ffe2842ee97a)

**其他信息**
 - 设备: [例如模拟器、iPhone、iPad]
 - iOS 版本: [iOS 14.x]
 - Xcode 版本: [Xcode 12.x]
 - QMUI 版本: [4.x.x]

**Comment by MoLice** [comment]
提供的信息没有解读的价值，至少像调用堆栈之类的可以提供下。
另外猜测大概率业务问题。
