### ISSUE TITLE
Tabbar 图片不显示，是需要配置什么吗？

### ISSUE THREAD

**Issue by wsr1949** [QMUI/QMUI_iOS#1596]
![Uploading WX20241107-201834@2x.png…]()

**Comment by MoLice** [comment]
你的图裂了

**Comment by wsr1949** [comment]
![WX20241108-224425@2x](https://github.com/user-attachments/assets/a9af63f3-440b-423a-ac21-134615e911e0)

**Comment by MoLice** [comment]
哥，你就贴这个，不提供代码，谁知道你咋写的....

**Comment by wsr1949** [comment]
我按照demo写的啊
