### ISSUE TITLE
一个布局错误和QMUITableViewCellPosition 的作用怎么理解

### ISSUE THREAD

**Issue by SexyIoveing** [QMUI/QMUI_iOS#16]
你好我想知道，QMUITableViewCellPosition 的作用怎么理解，另外咱们有没有技术群

**Comment by MoLice** [comment]
`QMUITableViewCellPosition` 用于标志某个 cell 处于当前 section 里的位置，利用它我们就能方便地做一些位置区分，例如以下代码截图里，我们对最后一个 cell 隐藏掉分隔线。

![image](https://cloud.githubusercontent.com/assets/1190261/21630982/23b93c60-d271-11e6-99e4-506db5ab73bb.png)

**Comment by MoLice** [comment]
至于“一个布局错误”是指什么呢？
