### ISSUE TITLE
想看看这些控是如何实现这些效果的！

### ISSUE THREAD

**Issue by Doraemonyy** [QMUI/QMUI_iOS#160]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by MoLice** [comment]
可自行查看源码，如有问题可提 issue，谢谢。
