### ISSUE TITLE
QMUIFloatLayoutView获取item行数问题

### ISSUE THREAD

**Issue by 15393713650** [QMUI/QMUI_iOS#1602]
有没有获取QMUIFloatLayoutView中的item行数的方法，比如说我现在有多个item，但我最多只要显示两行，应该怎么判断

**Comment by MoLice** [comment]
暂时没有直接的方法，如果你每一个 item 的高度是相同的，那你可以自行在设置 frame 时将高度做个 MIN(两行) 的保护。如果多个 item 高度不一致那就没办法了。

**Comment by 15393713650** [comment]
好的  明白
