### ISSUE TITLE
升级Xcode到16.2之后崩溃

### ISSUE THREAD

**Issue by zhudi12358** [QMUI/QMUI_iOS#1606]
**Bug 表现**
NSAssert(NO, @"如果你看到这条提示，建议到 GitHub 上提 issue，让我们联系你查看项目的配置表使用情况，否则请注释掉这一行。");

**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
1. 升级到xcode16.2，直接崩溃。
2. ...

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: [例如模拟器、iPhone]
 - iOS 版本: [iOS 15.7]
 - Xcode 版本: [Xcode 16.2]
 - QMUI 版本: [4.x.x]

**Comment by zhudi12358** [comment]
QMUI 版本: [4.6.0]

**Comment by codingiran** [comment]
> QMUI 版本: [4.6.0]

https://github.com/Tencent/QMUI_iOS/issues/1556#issuecomment-2365338909
