### ISSUE TITLE
xcode16.1 手机系统iOS18.1.1 运行崩溃

### ISSUE THREAD

**Issue by meiyingda1** [QMUI/QMUI_iOS#1607]
**Bug 表现**
问题的具体描述
运行直接崩溃
**截图**
Bug 现场的界面截图，或者 Xcode 控制台的错误信息截图，有问题的代码截图

**如何重现**
![img_v3_02ho_c1884c7c-b0f0-4d0d-bb6b-4aa99884190h](https://github.com/user-attachments/assets/59a4fd72-37c1-4788-a199-5ac5147c9ed9)

![image](https://github.com/user-attachments/assets/d27c5b68-bb14-4137-aec4-4edfd8dfea96)

**预期的表现**
正常情况下，应该是什么表现

**其他信息**
 - 设备: 、iPhone
 - iOS 版本: [iOS 18.1.1]
 - Xcode 版本: [Xcode 16.1]
 - QMUI 版本: 4.6.0

**Comment by codingiran** [comment]
求求你们看看 Release Note吧，升级到最新版就可以了
@MoLice 这个问题建议置顶🤦‍♂️

**Comment by MoLice** [comment]
> 求求你们看看 Release Note吧，升级到最新版就可以了 @MoLice 这个问题建议置顶🤦‍♂️

@codingiran  置顶也一样不看的哈哈哈哈
