### ISSUE TITLE
QMUIModalPresentationViewController设置了contentViewMargins为UIEdgeInsetsZero,但是左右仍然有20的边距

### ISSUE THREAD

**Issue by Farteen** [QMUI/QMUI_iOS#161]
### 运行环境 ###

- [x] iOS 设备：`模拟器`
- [x] 系统版本：`iOS 10.2`
- [x] Xcode 版本：`8.3.3`
- [x] QMUI iOS 版本：`1.7.3`

### 具体问题描述 ###
QMUIModalPresentationViewController 设置了contentViewMargins为UIEdgeInsetsZero,上下显示没有问题,但是左右还是会有20的边距

#### 问题截图 ####
![simulator screen shot 17 jul 2017 9 38 19 am](https://user-images.githubusercontent.com/5013543/28253210-bcb1989a-6ad3-11e7-86ec-0fe9744c3756.png)

**Comment by MoLice** [comment]
浮层大小会同时受 `maximumContentViewWidth` 和 `contentViewMargins` 属性的影响，这一点在[注释](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIComponents/QMUIModalPresentationViewController.h#L86)里有写，像你这种需求应该是希望浮层占满屏幕，可以把 `maximumContentViewWidth` 设为 `CGFLOAT_MAX` 试试看。

**Comment by Farteen** [comment]
十分感谢,需要多阅读文档!
