### ISSUE TITLE
自己调用QMUIConfigurationTemplate的-applyConfigurationTemplate方法，但无法设置[QMUICMI active]属性为YES

### ISSUE THREAD

**Issue by captain-black** [QMUI/QMUI_iOS#1612]
### 运行环境 ###

- [x] iOS 设备：`iPhone` 
- [x] 系统版本：`iOS 15.x`
- [x] Xcode 版本：`15.x`
- [x] QMUI iOS 版本：`4.6.0`

### 具体问题描述 ###
背景：我业务场景需要自己调用QMUIConfigurationTemplate的-applyConfigurationTemplate方法。

问题：我在外面无法设置QMUIConfiguration的active属性，然而QMUI很多设置都会依赖active=YES才生效，继而导致无法正常使用。

我的暂时处理办法：让QMUIKit默认的QMUIConfigurationTemplate自动生效（仅为了把_active=YES）, 然后再调用我自己新建的QMUIConfigurationTemplateXXX中的-applyConfigurationTemplate方法进行真正的UI样式设置，虽然能解决问题，但是不太优雅。

诉求：大佬们来兼容一下我的使用场景，弄优雅点 ^-^

#### 问题截图 ####
<img width="774" alt="image" src="https://github.com/user-attachments/assets/8112eaf4-6a70-446e-9548-9653a1bd8088" />

**Comment by MoLice** [comment]
想了一下，这种使用方式确实不在预期范围内，所以无法做相关调整。
因为如果要兼顾你说的优雅，势必需要对现有代码做一些“在标准使用方式看来没有理由”的改动，得不偿失。
