### ISSUE TITLE
使用QMUIAlertController 状态栏颜色由白色变为了黑色，

### ISSUE THREAD

**Issue by liuding8909** [QMUI/QMUI_iOS#162]
### 运行环境 ###

- [x] iOS 设备：`iPhone`
- [x] 系统版本：`iOS 10.3.2`
- [x] Xcode 版本：`8.3.3`
- [x] QMUI iOS 版本：`1.7.2`

### 具体问题描述 ###
状态栏颜色开始是白色，当使用 QMUIAlertController 显示弹层时，状态栏就变成了黑色，
使用QMUIModalPresentationViewController 同样也会 

#### 问题截图 ####
![wechatimg44](https://user-images.githubusercontent.com/4556482/28300747-1b184bd2-6bb4-11e7-9f4f-c2d93e8fae17.jpeg)
![wechatimg45](https://user-images.githubusercontent.com/4556482/28300748-1b485d90-6bb4-11e7-8bcf-2a3f0ab4e528.jpeg)
![wechatimg47](https://user-images.githubusercontent.com/4556482/28300749-1b59cdc8-6bb4-11e7-9fcf-888cbd12d0ce.jpeg)
![wechatimg48](https://user-images.githubusercontent.com/4556482/28300750-1b5a982a-6bb4-11e7-943f-2a13b09fd85f.jpeg)

**Comment by zhoon** [comment]
@liuding8909 

这个问题确实是一个Bug，你看看你是不是在项目文件的 info 这个 tab 下面设置了 View controller-based status bar appearance 为 YES 这个选项？因为如果设置为 YES，就默认会使用系统 UIViewController 的 preferredStatusBarStyle 方法，这个方法默认是返回黑色 statusBar 的，而因为 QMUIModalPresentationViewController（QMUIAlertController 实际也是使用
 QMUIModalPresentationViewController的）不是继承QMUICommonViewController，所以导致关于设置 statusBar 的代码都不会被走到，因此走了系统默认的黑色 statusBar。

你可以讲 controller-based status bar appearance 设置为 NO 来临时解决这个问题，我们再看看QMUI怎么来兼容这个问题。

![image](https://user-images.githubusercontent.com/2041356/28305999-4beb8244-6bd0-11e7-889c-85c37dc8335c.png)

**Comment by liuding8909** [comment]
好

**Comment by liuding8909** [comment]
其实我觉得 这个不应该跟据StatusbarStyleLightInitially 来判断显示哪一种样式， 在显示之前是什么状态就应该是什么状态。。因为不同的页面会有不同的样式

**Comment by zhoon** [comment]
@liuding8909 是，一般是显示之前什么状态就应该是什么状态。现在的实现也确实有点不太完美，最好是QMUIModalPresentationViewController可以自己控制，或者QMUIModalPresentationViewController里面的contentViewController来决定要用什么状态，这样是最灵活了，我们会再继续改进一下。
