### ISSUE TITLE
返回按钮变成白色方块儿了

### ISSUE THREAD

**Issue by boai** [QMUI/QMUI_iOS#163]
### 运行环境 ###

- [x] iOS 设备：iPhone
- [x] 系统版本：`iOS 11`
- [x] Xcode 版本：`8.3`
- [x] QMUI iOS 版本：`1.7.4`

### 具体问题描述 ###
返回按钮变成白色方块儿了
#### 问题截图 ####
![1111](https://user-images.githubusercontent.com/13014692/28403882-5c269092-6d59-11e7-8180-1889a102e9fa.png)

**Comment by zhoon** [comment]
请问你这个问题是iOS11才会出现吗？这个返回按钮是你自己定义的还是用了QMUI里面默认的返回按钮图片？

**Comment by boai** [comment]
就是用的QMUI里面默认的返回按钮图

```
    QMUICMI.navBarTitleFont = UIFontBoldMake(17);                               // NavBarTitleFont : UINavigationBar 的标题字体，以及 QMUINavigationTitleView 的默认字体
    QMUICMI.navBarBackButtonTitlePositionAdjustment = UIOffsetZero;             // NavBarBarBackButtonTitlePositionAdjustment : 导航栏返回按钮的文字偏移
//    QMUICMI.navBarBackIndicatorImage = [UIImage qmui_imageWithShape:QMUIImageShapeDetailButtonImage size:CGSizeMake(12, 20) tintColor:NavBarTintColor];                                     // NavBarBackIndicatorImage : 导航栏的返回按钮的图片
    
    QMUICMI.navBarCloseButtonImage = [UIImage qmui_imageWithShape:QMUIImageShapeNavClose size:CGSizeMake(16, 16) tintColor:NavBarTintColor];     // NavBarCloseButtonImage : QMUINavigationButton 用到的 × 的按钮图片
```
    
这些配置我都没变过！

**Comment by MoLice** [comment]
1. 你贴的代码里 `QMUICMI.navBarBackIndicatorImage` 那一行被注释了，所以是有没有用 QMUI 去自定义呢？
2. 假设有使用 QMUI 去自定义的话，看你的代码里，你传了一个 `QMUIImageShapeDetailButtonImage` 形状的 image 给返回按钮，估计是手误？请改为 `QMUIImageShapeNavBack` 再试试？

**Comment by boai** [comment]
我代码上次给你了，给你微信说了，你都不回复，注释那点是我调试的，这都一个多月了！

**Comment by MoLice** [comment]
QMUI 的微信只有在有 issue 需要时才会使用，那不是一个客服，抱歉，有任何问题都请通过 issue 来反馈。

**Comment by boai** [comment]
```
    QMUICMI.navBarBackButtonTitlePositionAdjustment = UIOffsetZero;             // NavBarBarBackButtonTitlePositionAdjustment : 导航栏返回按钮的文字偏移
    QMUICMI.navBarBackIndicatorImage = [UIImage qmui_imageWithShape:QMUIImageShapeNavBack size:CGSizeMake(12, 20) tintColor:NavBarTintColor];                                     // NavBarBackIndicatorImage : 导航栏的返回按钮的图片
```
设置了还是不行，navicontroller 都换成你们demo 的了，这些配置直接复制你们demo的，都没改过

**Comment by zhoon** [comment]
@boai 有没有demo发一份来看看，按照你现在的描述很难知道问题出现在哪里，如果有demo的话麻烦发一份到 qmuiteam@qq.com

**Comment by boai** [comment]
已发送，请查收！

**Comment by boai** [comment]
记得，点击个人中心的那几行，返回按钮都是那样

**Comment by zhoon** [comment]
@boai 看了一下代码，你在很多 base_viewWillAppea r里面去设置了 QMUICMI.navBar 属性 ，这是不符合 QMUI 的使用规范的，QMUICMI 一般只在配置文件里面修改，而如果你要修改业务某个 Controller 里面的样式，可以通过 QMUINavigationControllerDelegate 的方法在自己的 Controller 里面设置。

**Comment by boai** [comment]
那要navi 透明，需要怎么改，就是navi 和地下的颜色一致，感觉demo写的太复杂，有点看不懂！

**Comment by zhoon** [comment]
你看看 QMUINavigationController 里面有个

/// 设置导航栏的背景图，默认为NavBarBackgroundImage
- (nullable UIImage *)navigationBarBackgroundImage;

如果要透明的就在你对应界面的Controller里面实现
- (nullable UIImage *)navigationBarBackgroundImage {
    return [UIImage new];
}

**Comment by boai** [comment]
navi 返回按钮问题解决了，多谢，但是 

```

- (BOOL)shouldSetStatusBarStyleLight
{
    return NO;
}
```
这个设置改变状态栏样式不行，设置了没效果

**Comment by zhoon** [comment]
状态栏的修改需在Info.plist文件内设置字段“View controller-based status bar appearance”的值为“NO”才能生效，你试试看。

**Comment by boai** [comment]
嗯，以后再也不动 QMUICMI 的东西了！多谢啦，已经改好了！
