### ISSUE TITLE
QMUICommonTableViewController中可以更改tableView的高度吗？

### ISSUE THREAD

**Issue by Juice007** [QMUI/QMUI_iOS#164]
### 运行环境 ###

- [x] iOS 设备：`iPhone`
- [x] 系统版本：`iOS 10.3.2`
- [x] Xcode 版本：`8.3`
- [x] QMUI iOS 版本：`1.7.2`

### 具体问题描述 ###
我的一个viewController继承自QMUICommonTableViewController，但需求是底部有一个吸底的Button，所以为了正常显示tableView的高度需要减去这个Button的高度。试过在`initTableView`中修改frame，但是最终不生效。
```
- (void)initTableView {
    [super initTableView];
    self.tableView.frame = CGRectMake(0, 0, SCREEN_WIDTH, SCREEN_HEIGHT - 55);
}
```
所以想请教一下有什么办法可以让QMUICommonTableViewController的子类修改tableView的高度呢？
#### 问题截图 ####
![27c777d5-e2fd-4272-a663-8e20469965b9](https://user-images.githubusercontent.com/16225027/28404466-08aaaff4-6d5c-11e7-861f-648699a06762.png)

**Comment by zhoon** [comment]
修改view的frame都需要在viewDidLayoutSubviews里面修改，不能在initTableView里面修改，否则都会被基类的viewDidLayoutSubviews里面的代码覆盖。

**Comment by Juice007** [comment]
嗯，成功了，谢谢，谢谢！
