### ISSUE TITLE
QMUICommonTableViewController 没有 section title的时候 section颜色不受全局theme控制

### ISSUE THREAD

**Issue by litecy** [QMUI/QMUI_iOS#165]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

#### 问题截图 ####

QMUICommonTableViewController 没有 section title的时候 section颜色不受全局theme控制

是不是在 QMUICommonTableViewController 里默认使用 创建空白的view

**Comment by zhoon** [comment]
QMUI是会默认实现viewForHeaderInSection:，但是前提是你有实现titleForHeaderInSection:并返回一个title，否则并不会创建一个view，所以一般的使用就是只实现titleForHeaderInSection:，如果你需要自定义的SectionHeaderView，那么就在业务实现viewForHeaderInSection:即可。

**Comment by litecy** [comment]
很多时候 section header 并没有内容， 只是用来分隔两个 section， 这个时候就需要单独实现 viewForHeaderInSection 或者  titleForHeaderInSection并返回 空格的 title

这种情况下 也希望theme也能 对 sectionHeader生效， 而不用自行实现上述两个方法

sectionHeader就用了tableview默认的实现了

**Comment by zhoon** [comment]
你说的这种场景还是比较少的吧，如果是要用空白的 header 来分隔两个 section，那建议用 group 类型的 tableView，plain类型的 section header 会靠在界面顶部的。
而且你要显示 section header，就肯定需要实现这两个方法中的一个，系统也是这样，QMUI默认也不显示 header。
