### ISSUE TITLE
搜索状态下进入一下个页面导航栏还在

### ISSUE THREAD

**Issue by liuding8909** [QMUI/QMUI_iOS#166]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.3`
- [x] Xcode 版本：`8.3`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
搜索一个结果，进入一个不显示导航栏的页面，导航栏不会消失，正常进入就不会显示。。。

-(BOOL)shouldCustomNavigationBarTransitionIfBarHiddenable {
    return YES;
}

- (BOOL)prefersStatusBarHidden {
    return YES;
}

**Comment by zhoon** [comment]
@liuding8909 你说的这种搜索状态进入下一个界面这种场景，目前QMUI还没有支持。经过测试，是因为系统 UISearchController在某个时机把 navBar 给显示出来了，我们目前无法干预到这种情况，而这个时机恰好在 QMUI 隐藏了 navBar 之后，所以就覆盖了 QMUI 的操作。
目前还没有好的方法解决这个问题，我们再想想有没有什么其他方法。

**Comment by liuding8909** [comment]
好的
