### ISSUE TITLE
QMButton和SDWebImage的UIButton+WebCache结合使用时出现bug

### ISSUE THREAD

**Issue by coderyin** [QMUI/QMUI_iOS#167]
### 运行环境 ###
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.7.x`

### 具体问题描述 ###
QMButton 使用上文字下图片的风格 结合SDWebImage加载网络图片  并给button setimage 图片会加载原始尺寸 会变得很大..

**Comment by MoLice** [comment]
对，这是 `QMUIButton` 的 bug，稍等我们发个新版本修复。另外为了保证完全解决你的问题，建议可把你对 button 的 init、设置属性等代码贴上来我们看看。
