### ISSUE TITLE
Storyboard

### ISSUE THREAD

**Issue by xnxin** [QMUI/QMUI_iOS#17]
### 运行环境 ###

- [x] iOS 设备：`iPhone`

### 具体问题描述 ###
是否支持storyboard混合使用？

**Comment by MoLice** [comment]
目前暂未测试过与 storyboard 混用的情况，一般的 controller 或 view 在 storyboard 里使用应该没问题，如果遇到什么问题可以提出，我们尽快解决。

**Comment by xnxin** [comment]
@MoLice 非常感谢，有问题我再开issue

**Comment by xnxin** [comment]
未重写awakeFromNib以及initWithCoder 导致默认值未设置，引发多种与预期不符合的bug

**Comment by MoLice** [comment]
已更新 [1.2.0](https://github.com/QMUI/QMUI_iOS/releases/tag/1.2) 版本，支持 storyboard，如在使用过程中遇到什么问题麻烦继续反馈哈。
