### ISSUE TITLE
集成QMUI后上线appstore包大小问题

### ISSUE THREAD

**Issue by lijunW** [QMUI/QMUI_iOS#170]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
qmui框架会给iOSapp最终安装包增加多大

**Comment by zhoon** [comment]
这个目前还没有统计

**Comment by MoLice** [comment]
使用 Bitcode 的情况下，QMUIKit.framework 大概占 1.5MB 的体积。
