### ISSUE TITLE
如何将文字化的QMUIEmotion“[哈哈]”表情变回表情，用QMUILabel显示。

### ISSUE THREAD

**Issue by pptk** [QMUI/QMUI_iOS#171]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by MoLice** [comment]
目前 QMUI 暂不支持把文字转换成表情，需要自行遍历 string 并找到其中表情的占位符，将其替换为图片显示出来。

之前没提供这个功能是因为不同情况下展示图文的方式是不一样的，有些地方是用简单的 `NSTextAttachment` 配合 `NSAttributedString`，有些地方是直接使用 `CoreText` 绘制，QMUI 无法一一兼容，干脆暂不提供这个处理。

后续会视情况考虑。
