### ISSUE TITLE
在使用QQEmotion时，如果QMUITextView设置了maximumTextLength，如果输入到了80时，用表情键盘的删除按钮会造成溢出

### ISSUE THREAD

**Issue by pptk** [QMUI/QMUI_iOS#172]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
![image](https://user-images.githubusercontent.com/5086754/28617335-8ccdb08a-7232-11e7-9071-086901513a6d.png)

**Comment by MoLice** [comment]
这是 QMUI 的 bug，刚刚提交了代码修复了，具体改动可以查看[这里](https://github.com/QMUI/QMUI_iOS/commit/9c86c3f88c42dc937f785e720cd1acd1630ba698)。

但可能不会那么快发 1.7.6 版本，所以如果你是用 Pod 管理的话，可能需要手动先改代码。
