### ISSUE TITLE
QMUIHelper visibleViewController 返回null

### ISSUE THREAD

**Issue by huangboju** [QMUI/QMUI_iOS#173]
### 运行环境 ###

- [x] iOS 设备：`模拟器`
- [x] 系统版本：`iOS 10.3`
- [x] Xcode 版本：`8.3.3`
- [x] QMUI iOS 版本：`1.7.3`

### 具体问题描述 ###
[QMUIHelper visibleViewController] 返回为null，这里就为空了[UIApplication sharedApplication].delegate.window

**Comment by MoLice** [comment]
如果连 `[UIApplication sharedApplication].delegate.window` 都为 nil，说明你整个应用还不可见，那么任何 controller 都是非 "visibile" 的。

建议换个调用时机，你现在的太早。

**Comment by huangboju** [comment]
@MoLice 嗯，找到原因了

**Comment by huangboju** [comment]
@MoLice 我在APPdelegate里面要配置导航栏颜色那些东西，但qmui_visibleViewControllerIfExist里加上了这两个条件self isViewLoaded] && self.view.window

**Comment by MoLice** [comment]
是的，场景不太一样。
