### ISSUE TITLE
Growing IO 框架与 QMUIModalPresentationViewController 冲突导致死循环

### ISSUE THREAD

**Issue by yunyuchen** [QMUI/QMUI_iOS#174]
### 运行环境 ###

- [x] iOS 设备：`iPhone`7s Plus
- [x] 系统版本：`iOS 10.3.2`
- [x] Xcode 版本：`8.3`
- [x] QMUI iOS 版本：`1.7.5

### 具体问题描述 ###
一开始使用QMUIModalPresentationViewController没问题，后来升级了一下
就开始不能用了，一初始化就报错

#### 问题截图 ####
![30d7b53e-dcfe-45da-81a7-da7d603c4429](https://user-images.githubusercontent.com/7653015/28711168-47a556c4-73b9-11e7-8793-ee199b0d8e15.png)
![df004342-88c7-4fe1-9808-e92536fc8a75](https://user-images.githubusercontent.com/7653015/28711177-4d7260ce-73b9-11e7-856c-4bea1d44685e.png)

**Comment by yunyuchen** [comment]
包括一些弹窗，每次都会在initialize这个方法里报错

**Comment by MoLice** [comment]
看看控制台有具体的报错信息吗？截图里好像只是断点而不是异常？试试把断点关闭掉看是否能继续执行下去。
另外，看看是否和你使用的第三方框架有关联？

**Comment by yunyuchen** [comment]
控制台没有报错信息到这里就执行不下去了。。我原来用的1.6版本没问题 后来pod升级了下 一些弹窗的空间都在这里报错

**Comment by yunyuchen** [comment]
找到问题了，我前天刚接入了Growing IO我刚才把Growing IO去掉之后就可以了 好像两个框架起了冲突

**Comment by MoLice** [comment]
好，冲突问题我看看

**Comment by MoLice** [comment]
经测试，这属于 Growing IO 自身问题，与 QMUI 代码无特定联系，已反馈给 Growing IO，待答复。

## 重现条件：
1. 定义一个 UIViewController 的子类。
2. 重写 + (void)initialize 方法，在其中调用当前类的 init 方法。

## 示例代码

```Objective-C
@interface ViewController : UIViewController
@end

@implementation ViewController

+ (void)initialize {
    [[ViewController alloc] init];
}

@end

```

**Comment by yunyuchen** [comment]
Growing IO后来给答复了吗

**Comment by MoLice** [comment]
@yunyuchen 他们还没给回复

**Comment by Jinkeycode** [comment]
@yunyuchen 我也遇到同样的问题，和 GrowingIO 沟通都没回复，建议你切换到腾讯 MTA 进行可视化埋点。

**Comment by bluerainxty** [comment]
@MoLice 我也遇到了这个问题，照着你的重现条件写没有重现crash，最后发现是要在dispatch_once里调用当前类的 init 方法才可以重现。

**Comment by MoLice** [comment]
GrowingIO 的问题可参考这个 [comment](https://github.com/Tencent/QMUI_iOS/issues/712#issuecomment-535423469) 解决，周知。
