### ISSUE TITLE
QMUICommonTableViewController中tableview类型为Group时，底部偏移20像素

### ISSUE THREAD

**Issue by zzw19880707** [QMUI/QMUI_iOS#175]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.7.5`

**Comment by MoLice** [comment]
建议贴个截图表达一下“底部偏移 20 像素”是什么意思？

**Comment by zzw19880707** [comment]
@MoLice 
<img width="1068" alt="wx20170802-104758 2x" src="https://user-images.githubusercontent.com/4556900/28901324-ea719650-7829-11e7-9096-6547f038e7b9.png">

**Comment by zhoon** [comment]
底部的这个空白是group类型的tableview默认自带的，网上有人通过contentInset来去掉这个空间，你可以自行google一下。

**Comment by zzw19880707** [comment]
@zhoon 我替换成系统的tableview时，不会出现这个偏移。只需要设置footer高度为0.01即可。但是并不能解决QMUITableview的问题

**Comment by zhoon** [comment]
@zzw19880707 我查了一下，确实是 QMUI 的锅，因为 qmui_styledAsQMUITableView 方法里面我们设置了 tableFooterView 一个高度为 0 的空白 view。经过测试我们发现，只要第一次给 group 类型的
 tableview 赋值一个高度为 0 的 view，后面再怎么设置一个高度 h 的 view，底部的空间都是 h+20 的高度，所以就去不掉那个空白。
我们会尽快修复，感谢提醒。

**Comment by zzw19880707** [comment]
@zhoon 希望你们团队越来越好

**Comment by MoLice** [comment]
已更新 [1.7.6](https://github.com/QMUI/QMUI_iOS/releases/tag/1.7.6) 版本，重点对这一点做了整理并对齐系统默认表现。

现在对于 `UITableViewStyleGrouped` 类型的 tableView，如果你不使用自定义的 sectionHeader、sectionFooter，只是单纯想控制 section 之间的间距的话，可以使用配置表里的开关 `TableViewGroupedSectionHeaderDefaultHeight` 和 `TableViewGroupedSectionFooterDefaultHeight`。

关于这两个开关的值：
1. 如果想保持间距和系统一致，请赋值为 `UITableViewAutomaticDimension`。
2. 如果想去掉这个间距，请赋值为 `CGFLOAT_MIN`。
3. 如果想指定为某个特定的数值，则直接将数值赋值给它们即可。
4. 不建议赋值为 0，实测赋值为 0 的表现会受 iOS 版本（11 之前和 11 之后）、是否使用了 `estimatedSectionHeaderHeight`和`estimatedSectionFooterHeight` 的影响，很不明确。
