### ISSUE TITLE
想要给QMUICommonTableViewController中的只读属性tableView添加一个方法，可以怎么做呢？

### ISSUE THREAD

**Issue by Juice007** [QMUI/QMUI_iOS#176]
### 运行环境 ###

- [x] 系统版本：`iOS 10.3.3`
- [x] Xcode 版本：`8.3.2`
- [x] QMUI iOS 版本：`1.7.4`
- [x] iOS 设备：`iPhone`

### 具体问题描述 ###
项目中在做一个类似网易云音乐歌手主页的效果。需求是当tableView持续向上滑动时，绿色的那一栏要固定在顶部。外层是QMUITableView，绿色栏下方又包含了UITableView。控制器继承自QMUICommonTableViewController。为了让内外两层tableView都响应滑动手势，需要在外层tableView（也就是QMUITableView）中实现`UIGestureRecognizerDelegate`代理的一个方法：
```
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
    return YES;
}
```
pod导入的项目，所以不能直接修改源码。QMUICommonTableViewController中tableView属性又是只读的，所以覆盖`initTableView`重新初始化也行不通。想请教下有什么办法可以达到这个目的呢？
#### 问题截图 ####
![img_2155](https://user-images.githubusercontent.com/16225027/28903535-fe5f60b2-7837-11e7-92c9-edf379235aa1.PNG)

**Comment by zhoon** [comment]
@Juice007 请问为什么需要用两个tableview？而不是一个tableview，然后绿色那个用sectionHeader来做？这样就只用到一个tableview，绿色那个又可以停靠在顶部。

**Comment by Juice007** [comment]
@zhoon 其实之前项目中用的就是这种方式，但这种方式不支持左右手势滑动，而且当其中一栏数据较少时(cell个数只有几个)，点击切换的时候界面的体验不是很好。所以才想到这种办法的。

**Comment by zhoon** [comment]
如果非要用两个tableview的话，那我建议不要使用QMUICommonTableViewController了，而是使用QMUICommonViewController，然后自己放两个tableview就好了。

**Comment by Juice007** [comment]
@zhoon 好的，谢谢啦。另外，上网查到一种方式是在`QMUICommonViewController `的子类中加上一句话
```
@synthesize tableView = qmuiTableView;
```
然后在子类中重写initTableView方法：
```
- (void)initTableView {
    if (!qmuiTableView) {
        qmuiTableView = [[DIYTableView alloc] initWithFrame:self.view.bounds style:self.style];
        self.tableView.delegate = self;
        self.tableView.dataSource = self;
        [self.view addSubview:self.tableView];
    }  
}
```
亲测这样就可以重新初始化只读属性tableView了（DIYTableView继承自QMUITableView，且实现了`shouldRecognizeSimultaneouslyWithGestureRecognizer `代理方法）
请教下这是什么原理呢，这样用会有什么问题吗？

**Comment by zhoon** [comment]
应该没什么问题，你可以上网自行 google 了解一下 @synthesize 的作用。

**Comment by Juice007** [comment]
@zhoon thanks
