### ISSUE TITLE
QMUILabel's contentEdgeInsets updating issue

### ISSUE THREAD

**Issue by caoer** [QMUI/QMUI_iOS#177]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.7.5`

### 具体问题描述 ###
When update QMUILabel's contentEdgeInsets, it should call layout method to reflect the changes. It seems the setter is not been overwritten. 

Also, maybe we should consider to implement intrinsicContentSize so that the contentEdgeInsets is AutoLayout friendly.

**Comment by MoLice** [comment]
We've just released [1.7.6](https://github.com/QMUI/QMUI_iOS/releases/tag/1.7.6). The `setNeedsDisplay` method will now be called automatically when updating `QMUILabel.contentEdgeInsets`.
As far as support for AutoLayout, please keep an eye on our future releases as we'll be rolling out support not just for `QMUILabel`.

**Comment by caoer** [comment]
@MoLice 
Will keep a close eye on it, you guys rocks!
