### ISSUE TITLE
导航栏目前支持单个页面的隐藏和显示吗

### ISSUE THREAD

**Issue by Winter-Yang** [QMUI/QMUI_iOS#178]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by MoLice** [comment]
请查看 `QMUINavigationControllerDelegate preferredNavigationBarHidden`，[链接](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIMainFrame/QMUINavigationController.h#L48)。
