### ISSUE TITLE
进入一个带搜索的页面点击搜索取消后 进入后台 再回来就会报内存泄漏

### ISSUE THREAD

**Issue by liuding8909** [QMUI/QMUI_iOS#179]
### 运行环境 ###

- [x] iOS 设备：`iPhone`
- [x] 系统版本：`iOS 10.3`
- [x] Xcode 版本：`9.0`
- [x] QMUI iOS 版本：`1.7.5`

### 具体问题描述 ###
在带有搜索框的页面点击搜索再取消，然后切到桌面，再回到应该后 会出现。。

#### 问题截图 ####

![image](https://user-images.githubusercontent.com/4556482/29156217-47a56050-7dd3-11e7-9786-9e0745bb43ca.png)

**Comment by MoLice** [comment]
我看看

**Comment by MoLice** [comment]
2.7.2 已修复这个问题，这真的是个很古老的 issue。
