### ISSUE TITLE
不支持 PHAssetMediaSubtypePhotoLive

### ISSUE THREAD

**Issue by googoodalls** [QMUI/QMUI_iOS#18]
### 运行环境 ###

- [x] iOS 设备：All
- [x] 系统版本：`iOS 10.2`
- [x] Xcode 版本：`8.2`
- [x] QMUI iOS 版本：`1.0`

### 具体问题描述 ###
AlbumViewController 不支持 PHAssetMediaSubtypePhotoLive
#### 问题截图 ####
AlbumViewController 不支持 PHAssetMediaSubtypePhotoLive

**Comment by kayo5994** [comment]
这两天会加入对 PHAssetMediaSubtypePhotoLive 的支持，请持续关注更新，感谢你的支持！

**Comment by kayo5994** [comment]
@googoodalls 刚刚已经加入对 Live Photo 的支持，包括获取 Live Photo 以及 Live Photo 的展示，欢迎更新最新代码。

**Comment by googoodalls** [comment]
👍，Cool！
