### ISSUE TITLE
QMUI 与 GrowingIO 冲突导致死循环

### ISSUE THREAD

**Issue by Jinkeycode** [QMUI/QMUI_iOS#180]
### 运行环境 ###

- [x] iOS 设备：`iPhone`
- [x] 系统版本：`iOS 10.2`
- [x] Xcode 版本：`8.3.3`
- [x] QMUI iOS 版本：`1.7.5`
- [x] Swift 版本：`3.1`
### 具体问题描述 ###
app 启动的时候就会报这个错误，导致 app   @#启动时闪退

#### 问题截图 ####
![image](https://user-images.githubusercontent.com/12148377/29245079-4abdc136-8000-11e7-9b6d-13283c53ac07.png)
![image](https://user-images.githubusercontent.com/12148377/29245127-08697986-8002-11e7-91c9-0010d7b8680d.png)

**Comment by MoLice** [comment]
这个问题与 Swift 无关，请参考 [#174](https://github.com/QMUI/QMUI_iOS/issues/180)
