### ISSUE TITLE
QMUIButton 的图片设置无效

### ISSUE THREAD

**Issue by Jinkeycode** [QMUI/QMUI_iOS#183]
### 运行环境 ###

- [x] iOS 设备：`iPhone`
- [x] 系统版本：`iOS 10.2`
- [x] Xcode 版本：`8.3.3`
- [x] QMUI iOS 版本：`1.7.5`
- [x] Swift 版本：`3.1`
### 具体问题描述 ###
QMUIButton adjustsImageTintColorAutomatically、imageRect的设置无效，无法使图片缩小也无法以 tintColor 重新渲染图片
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/12148377/29346513-66696ef6-8278-11e7-875b-b3182af65b9d.png)
![image](https://user-images.githubusercontent.com/12148377/29346597-dc6dda56-8278-11e7-9706-eec8beb15e99.png)

**Comment by MoLice** [comment]
如果你的按钮只显示 image 而不显示 title 的话，可以这么写：
```Objective-C
titleButton.contentHorizontalAlignment = UIControlContentHorizontalAlignmentFill;
titleButton.contentVerticalAlignment = UIControlContentVerticalAlignmentFill;
titleButton.frame = CGRectMake(0, 0, 100, 200);
[titleButton setImage:[UIImage imageNamed:@"Phone"] forState:UIControlStateNormal];
```

至于 `adjustsImageTintColorAutomatically`，不知道你是想用这个功能还是不想用这个功能？因为看你的示例代码里赋值为 `false` 了。如果想用，这么写就能生效：
```Objective-C
titleButton.adjustsImageTintColorAutomatically = YES;
titleButton.tintColor = [UIColor redColor];// your color
```

**Comment by Jinkeycode** [comment]
@MoLice 

# 我的需求
希望按钮同时显示图片和文字，并且不调整图片颜色
# 遇到的问题
1、图片却大到把按钮的文字都挡住了
2、图片被渲染成蓝色了

另外我是想控制图片的大小而不是按钮的大小，所以应该是设置 titleButton.imageView.frame 而不是 titleButton.frame吧？

求指导

**Comment by MoLice** [comment]
你这里存在几个问题：
1. QMUIButton.imagePosition 默认值就是 Left，不用重新写。
2. QMUIButton. adjustsImageTintColorAutomatically 默认值就是 NO，也不用显式赋值。
3. UIButton.imageView 的 frame 由 UIButton 内部自己管理，外界手动去修改是无效的，也不应该按照这样的思路去做。如果你需要图片显示为特定大小，建议自行把 image 缩放到你想要的大小再通过 setImage: 赋值给 UIButton。
4. 图片被渲染成蓝色这个不确定是什么原因，请查看你的图片的 renderingMode 是否为 `UIImageRenderingModeAlwaysTemplate`，或者你是否在哪些地方修改了 `adjustsImageTintColorAutomatically` 或 `tintColorAdjustsTitleAndImage` 的值。

**Comment by Jinkeycode** [comment]
> UIButton.imageView 的 frame 由 UIButton 内部自己管理，外界手动去修改是无效的，也不应该按照这样的思路去做。如果你需要图片显示为特定大小，建议自行把 image 缩放到你想要的大小再通过 setImage: 赋值给 UIButton。

如果是这么说的话，那么我自己去封装一个 imageView 吧，我以为QMUI 封装了而不是使用系统的 button.imageView。adjustsImageTintColorAutomatically 我看你们的文档也是默认  false 的不知道为什么 图片还是被渲染了。非常感谢你回答。

**Comment by MoLice** [comment]
对，你这种情况建议自己重写 layoutSubviews 去限制 imageView 的 frame。
