### ISSUE TITLE
assetsGroupOfLastestPickerAlbum 闪退

### ISSUE THREAD

**Issue by wxlpp** [QMUI/QMUI_iOS#184]
### 运行环境 ###

- [x] iOS 设备：`iPhone`
- [x] 系统版本：`iOS 10.3.3`
- [x] Xcode 版本：`9-beta5`
- [x] QMUI iOS 版本：`1.7.6`

### 具体问题描述 ###
swift4 下调用`QMUIImagePickerHelper.assetsGroupOfLastestPickerAlbum`导致闪退，1.7.5下无异常

**Comment by wxlpp** [comment]
加上Privacy - Photo Library Usage Description 等权限就好了，但是1.75确实我也没加~

**Comment by MoLice** [comment]
会有闪退最大可能还是因为 Info.plist 里的 key 设置错误。与 1.7.5 无关，因为 1.7.6 和 1.7.5 在这一点上没有改动过。可能刚好你用 1.7.5 的时候使用的 Xcode 版本和用 1.7.6 时的 Xcode 版本不一致？
