### ISSUE TITLE
调用[QMUIAlertController showWithAnimated:NO]方法参数为NO时，Alert无法显示

### ISSUE THREAD

**Issue by Juice007** [QMUI/QMUI_iOS#185]
### 运行环境 ###

- [x] iOS 设备：`iPhone`
- [x] 系统版本：`iOS 10.3`
- [x] Xcode 版本：`8.3`
- [x] QMUI iOS 版本：`1.7.6`

### 具体问题描述 ###
当`QMUIAlertController`的`showWithAnimated:`方法动画参数传NO时，alert无法弹出，并且伴随有循环引用发生
#### 问题截图 ####
在QMUIDemo中`QDAlertController.m`文件的`didSelectCellWithTitle`方法中
```
if ([title isEqualToString:@"显示一个 alert 弹窗"]) {
        QMUIAlertAction *action1 = [QMUIAlertAction actionWithTitle:@"取消" style:QMUIAlertActionStyleCancel handler:^(QMUIAlertAction *action) {
        }];
        QMUIAlertAction *action2 = [QMUIAlertAction actionWithTitle:@"删除" style:QMUIAlertActionStyleDestructive handler:^(QMUIAlertAction *action) {
        }];
        QMUIAlertController *alertController = [QMUIAlertController alertControllerWithTitle:@"确定删除？" message:@"删除后将无法恢复，请慎重考虑" preferredStyle:QMUIAlertControllerStyleAlert];
        [alertController addAction:action1];
        [alertController addAction:action2];
        [alertController showWithAnimated:NO];  //当这里传NO，alert无法显示且有循环引用问题
        return;
    }
```
![74e28cee-464b-4b61-914c-93d34bc9905c](https://user-images.githubusercontent.com/16225027/29443347-12427280-840a-11e7-8fd8-06e37b0fee3a.png)

**Comment by zhoon** [comment]
@Juice007 谢谢提醒，我们尽快修复。

**Comment by MoLice** [comment]
已在 [这次 commit](https://github.com/QMUI/QMUI_iOS/commit/5cb73eac2659693f6f27ae8d82431ff4cb4d8992) 里修复，Release 版本等后续更新，谢谢反馈。
