### ISSUE TITLE
文档问题

### ISSUE THREAD

**Issue by DevilLeven** [QMUI/QMUI_iOS#186]
迫切希望可以写一份API文档，包含各组件的方法、属性、默认值等。现在很多都只能通过看源码，十分感谢

**Comment by MoLice** [comment]
一般情况下你所需的这些信息我们都会在 .h 文件里用注释写明，如果某些地方没写明，说明那个地方的注释不完整，可以的话麻烦跟我们提 issue 指出，谢谢。
API 文档涉及到维护成本，暂时没考虑，我们原本的预期也是通过 .h 里的注释，以及 QMUI Demo 项目的使用示例，就足够了解如何使用了。
