### ISSUE TITLE
QMUITextFeild 崩溃问题

### ISSUE THREAD

**Issue by MineJ** [QMUI/QMUI_iOS#188]
### 请填写运行环境

- [x] 设备： iPhone
- [x] 系统：`iOS 9.x`
- [x] Xcode 版本：`8.3x`
- [x] QMUI iOS 版本：最新版本

### 请描述具体问题
- (BOOL)respondsToSelector:(SEL)aSelector {
    // 修复 iOS 7 下将 UITextField.delegate 指向自身时会死循环的问题
    if (IOS_VERSION < 8.0 && [NSStringFromSelector(aSelector) hasPrefix:@"customOverlayC"]) {
        return NO;
    }
    
    BOOL a = [super respondsToSelector:aSelector];
    BOOL c = [self.originalDelegate respondsToSelector:aSelector];
    BOOL result = a || c;
    return result;
}
#### 相关截图（断点的堆栈、控制台的 log）
http://syworks.image.alimmdn.com/20170825115232.png

**Comment by MoLice** [comment]
与 #98 重复，属于 BlocksKit 与 QMUI 的冲突问题，暂无解决方法。

**Comment by MoLice** [comment]
2.5.0 版本已兼容 BlocksKit。
