### ISSUE TITLE
调用QMUIDialogTextFieldViewController打印错误

### ISSUE THREAD

**Issue by LanYanQin** [QMUI/QMUI_iOS#189]
### 请填写运行环境

- [x] 设备：`模拟器`
- [x] 系统：`iOS 10.0`
- [x] Xcode 版本：`8.3`
- [x] QMUI iOS 版本：`1.x.x`

### 请描述具体问题
调用QMUIDialogTextFieldViewController之后为什么会打印
尝试让一个处于非 keyWindow 上的 QMUITextField becomeFirstResponder，请添加 'QMUISymbolicUIViewBecomeFirstResponderWithoutKeyWindow' 的 Symbolic Breakpoint 以捕捉此类错误
又不会闪退，这个问题会不会影响？

**Comment by MoLice** [comment]
这严格意义上来说是 QMUI 本身的问题，不过不会导致什么问题，我们后续把这一点修复就不会再报这个警告了。

**Comment by MoLice** [comment]
这严格意义上来说是 QMUI 本身的问题，不过不会导致什么问题，我们后续把这一点修复就不会再报这个警告了。

**Comment by LanYanQin** [comment]
好的，谢谢回答

**Comment by MoLice** [comment]
经过考虑，我们暂且只是优化了这一部分的 log 的表述，具体改动请查看 [commit](https://github.com/QMUI/QMUI_iOS/commit/b712a6a0bab8c9dc016a454e1e5b952eb597c142#diff-cc8825900a09a9a379c6659af28af0f0R216)。

这些 log 信息只是一种提醒，并非一定会导致什么问题，具体场景仍需具体分析。
