### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by cjskw** [QMUI/QMUI_iOS#19]
### 运行环境 ###

- [x] iOS 设备：`模拟器`
- [x] 系统版本：`iOS 10.11`
- [x] Xcode 版本：`8.1`
- [x] QMUI iOS 版本：`1.1.4`

### 具体问题描述 ###
有时候会 crash，打断点是断到了这个函数

`- (void)qmui_layoutSubviews 
{

    [self qmui_layoutSubviews];//这一行

    if (self.qmui_shouldShowDebugColor) {
        self.qmui_hasDebugColor = YES;
        self.backgroundColor = [self debugColor];
        [self renderColorWithSubviews:self.subviews];
    }
}`

**Comment by MoLice** [comment]
能否截图看一下 crash 后的 log？

另外请把断点关闭后重试一下看是否还会？有可能不是 crash，只是 debug 时的 breakpoint 而已

**Comment by cjskw** [comment]
抱歉当时没有截取 log，下次如果遇到传一下。应该不是 debug 的断点，我只打了一个全局的异常断点，而且没有修改任何内容再次运行就不会断到这里了，像是个偶现的问题。

**Comment by MoLice** [comment]
debug 断点也会命中系统的一些 breakpoint ，这种一般继续执行就可以了不用理会。下次遇到留意一下就好哈
