### ISSUE TITLE
关于 UIViewController(QMUI).qmui_navigationBarMaxYInViewCoordinator 的使用

### ISSUE THREAD

**Issue by wanhmr** [QMUI/QMUI_iOS#190]
如何适配新版，QMUI 有如下说明：
> 全局搜索使用到 `NavigationContentHeigh`t 和 `NavigationContentOriginY` 的地方，考虑将其更换为新的 `UIViewController(QMUI).qmui_navigationBarMaxYInViewCoordinator`

 目前遇到的问题：
- 如果前一个页面隐藏了导航条，而后一个页面显示导航条的时候，在 `- (void)viewDidLoad` 方法中得到的 `UIViewController(QMUI).qmui_navigationBarMaxYInViewCoordinator` 值是不准确的，因为导航条的显隐是在 `- (void)viewWillAppear:` 中设置。

**Comment by MoLice** [comment]
是，这是 `qmui_navigationBarMaxYInViewCoordinator` 相比以前写死固定值的宏带来的不便，这个问题我们也发现了，可能会重新考虑这个属性和旧的宏的角色问题，在此之前建议自行在项目里定义那两个被 QMUI 废弃的宏，继续用写死值的方式使用。

**Comment by wanhmr** [comment]
然鹅，我一股脑地全替换了，还好不多。不过可以肯定的是，用`qmui_navigationBarMaxYInViewCoordinator` 替代宏是一个很好的尝试，感觉使用宏如同使用 magic number 一样。控制器应该尽量自己管理自己，避免引入过多的外部参数。在 `AutoLayout` 中使用 `topLayoutGuide` 、 `bottomLayoutGuide` 以及在 iOS 11 新增的 `SafeArea` 都是可以比较方便地管理界面布局的方案。

不过希望以后更新，小版本更新做到可以向下兼容，并提醒开发者已废弃但不真正删除接口，大版本更新才真正删除已废弃的接口。

当然这次关于 `qmui_navigationBarMaxYInViewCoordinator ` 的更新，`QMUI` 是保留了原有宏的。
