### ISSUE TITLE
通过iTunes导入的相册，相册列表看不到

### ISSUE THREAD

**Issue by qiuyuliang** [QMUI/QMUI_iOS#191]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by kayo5994** [comment]
@qiuyuliang 谢谢你的反馈，最新代码中已经修复这种问题。

**Comment by qiuyuliang** [comment]
谢谢，看了一下，问题已经修复
