### ISSUE TITLE
导航栏的pop手势驱动动画 总是会左右跳动一下...

### ISSUE THREAD

**Issue by toommiios** [QMUI/QMUI_iOS#194]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by zhoon** [comment]
@toommiios 不太明白你说的左右跳动具体是什么样子的，能传一个动态图给我们看看吗？
