### ISSUE TITLE
QMUIFloatLayoutView 没有自动限制 item 的最大宽度，容易导致 item 溢出

### ISSUE THREAD

**Issue by zzw19880707** [QMUI/QMUI_iOS#195]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 10.x`
- [x] Xcode 版本：`8.0`
- [x] QMUI iOS 版本：`1.7.4`

### 请描述具体问题
1.7.5、1.7.6同样存在类似问题.
#### 相关截图（断点的堆栈、控制台的 log）
<img width="374" alt="wx20170907-080313 2x" src="https://user-images.githubusercontent.com/4556900/30139857-1f06fc4a-93a3-11e7-9226-80f28a01ae6b.png">
![wx20170907-080606](https://user-images.githubusercontent.com/4556900/30140024-1f13d766-93a4-11e7-8325-ce28bba9e89b.png)

**Comment by MoLice** [comment]
2.0 版本已修复。

**Comment by zzw19880707** [comment]
我下载了最新的demo，并未解决此问题。 @MoLice 
<img width="1381" alt="wx20170911-155712 2x" src="https://user-images.githubusercontent.com/4556900/30264081-eea22f9c-9709-11e7-8f1a-44434c60c5ac.png">

**Comment by MoLice** [comment]
不理解你图片标注里说的“按照范围计算长度”是什么意思。我猜测你想表达的是第一种写法能算出换行的size，第二种写法只能算出单行的 size。估计是因为你的 `self.titleLabel.numberOfLines` 没有正确设置为非 1。
另外 item 的 size 怎么算、单行还是多行，这与 `QMUIFloatLayout` 无关，纯粹是 item 自身内部决定的。`QMUIFloatLayout` 只管把一个 item 添加到界面上，并且用 item 的 sizeThatFits: 返回的结果去布局。

**Comment by zzw19880707** [comment]
@MoLice  首先这不是QMUIFloatLayoutView的问题。是QMUIButton的问题。按照范围计算长度理解为:当一段文本，期望他最大显示为（100，30），超过范围将会以...显示。而sizetoFit会计算出文本的真实长度，如果1行的前提下，这段文本长度为1000，那么计算结果就是1000，而非100 。

**Comment by MoLice** [comment]
如果就 QMUIButton 来说的话，目前的实现本身就是符合你需求的，而为什么你写 ` CGSize size =
 [button sizeThatFits:CGSizeMake(100, 30)]` 返回的 `size.width` 会超过 `100`，是因为你的 `button.titleLabel.numberOfLines` 为 1，只要你改为 0，或者别的值，就可以了，这也是我上一个 comment 提醒过的点。

反而系统的 `UIButton` 不管 `titleLabel.numberOfLines` 值为多少，`sizeThatFits:` 返回的 `size.width` 都不会考虑你的 100 的宽度限定。
