### ISSUE TITLE
【讨论】关于 QMUIModalPresentationViewController 中的 contentViewController 类型问题

### ISSUE THREAD

**Issue by wanhmr** [QMUI/QMUI_iOS#196]
在 `QMUIModalPresentationViewController` 中有这样一个属性：
```
/**
 *  要被弹出的浮层，适用于浮层以UIViewController的形式来管理的情况。
 *  @warning 当设置了`contentViewController`时，`contentViewController.view`会被当成`contentView`使用，因此不要再自行设置`contentView`
 *  @warning 注意`contentViewController`是强引用，容易导致循环引用，使用时请注意
 */
@property(nonatomic, strong) IBOutlet UIViewController<QMUIModalPresentationContentViewControllerProtocol> *contentViewController;
```

而 `QMUIModalPresentationContentViewControllerProtocol` 只有一个被声明为 `optional` 的 `- (CGSize)preferredContentSizeInModalPresentationViewController:(QMUIModalPresentationViewController *)controller limitSize:(CGSize)limitSize;` 方法。

实际使用中，如果 `contentViewController ` 不实现 `QMUIModalPresentationContentViewControllerProtocol` 其实也是被允许的。但是如果按照现有方式，为了消除 compiler 的警告则不得不实现这个 `protocol` 。

**Comment by MoLice** [comment]
是的，如果 `contentViewController` 没有实现 `QMUIModalPresentationContentViewControllerProtocol`，则在布局时会直接使用 `self.view sizeThatFits:` 返回的结果，而一般情况下不加控制的话，返回的大小也即撑满 `QMUIModalPresentationViewController`最大内容区域的大小。如果这恰好就是业务想要的话，那么这样使用也是没问题的。

但基于以下两点考虑，我们依然倾向于保持目前的代码设计：
1. 在我们的设计经验里，大部分情况都会需要自行控制浮层大小，只有少部分情况是不需控制的。
2. `QMUIModalPresentationContentViewControllerProtocol` 目前仅有一个方法，且为 `optional`，在目前的阶段看起来这个协议可有可无，但后续可能会继续增加其他方法到这个协议中，为了明确表达出“`contentViewController` 需要以协议的方式受 `modalPresentationController` 限制“，我们依然将 `contentViewController` 指针声明为 `UIViewController< QMUIModalPresentationContentViewControllerProtocol >`。

**Comment by wanhmr** [comment]
关于你所说的第二点，旧代码的改动可能会很多，有以下情况：
1.  `protocol` 中新增 `optional` 方法
2. `protocol` 中新增 `require` 方法
@MoLice 

按照目前实现方式  `contentViewController` 声明为 `UIViewController< QMUIModalPresentationContentViewControllerProtocol > *` ，那么针对上面两种情况会有：
1. 旧代码不需要任何修改
2. 必须实现 `QMUIModalPresentationContentViewControllerProtocol ` 新增的 `require` 方法

如果 `contentViewController` 声明为 `UIViewController *`，针对上面两种会有：
1. 旧代码不需要任何修改
2. 需要将 `contentViewController` 重新声明为 `UIViewController< QMUIModalPresentationContentViewControllerProtocol > *`，并且旧代码需要实现协议 `QMUIModalPresentationContentViewControllerProtocol` 

其实按照成本来说，并没有相差多少。

并且按照目前的使用方式，如果使用 `layoutBlock` 那么可能会覆盖掉 `- preferredContentSizeInModalPresentationViewController:limitSize:` 方法所返回的大小，这样子是否会有歧义？

我认为如果可以实现所需功能， `  - preferredContentSizeInModalPresentationViewController:limitSize:` 可以是 `require` ，去掉 `layoutBlock`。目前 `layoutBlock` 主要是为了实现一些特殊的动画？我对动画了解不多，请多指教。

**Comment by MoLice** [comment]
如果目前 `contentViewController` 声明为 `UIViewController *`，那么当我们将声明改为 `UIViewController <xxx>` 后，旧代码的改动就是每个 `contentViewController` 都要手动再标记实现了 `<QMUIModalPresentationContentViewControllerProtocol>`，这是我指的“改动成本”。

`layoutBlock` 的设计目的是实现完全自定义的布局，这里的“布局”包含 origin 及 size，例如你通过 `preferredContentSizeInModalPresentationViewController:limitSize:` 只能修改 size，但通过 `layoutBlock`，你可以同时修改 origin 和 size。它与动画没有关系，动画对应 `showingAnimation` 属性，如果你没有使用 `layoutBlock`，你也可以通过 `showingAnimation` 来控制浮层的动画。

**Comment by wanhmr** [comment]
@MoLice 可以肯定的是，`layoutBlock` 会影响动画，有些动画如果不在 `layoutBlock` 中做处理，动画效果就会有问题。并且 `conentViewController` 自己可以控制动画，可以不需要 `layoutBlock` 处理 `origin` 和 `size`。

**Comment by wanhmr** [comment]
很感谢你作出回答，这也只是我的一些疑惑或者思考。

**Comment by MoLice** [comment]
嗯嗯，感谢你提出的问题，这些讨论的价值不在于结果如何，而在于思考的过程和引起的审视。`layoutBlock` 影响动画那点我们看看，理论上与预期不符，需要的话再找你拿测试代码。
而在 `contentViewController` 中控制动画并非我们原本的设计意图，因为子 view 只需要管自己有什么内容、内容多大即可，至于自己在父 view 里被怎样布局，应该是父 view 的事情。所以即便可以在 `contentViewController` 里自己控制布局和动画，也不是一个很推荐的做法。

**Comment by wanhmr** [comment]
@MoLice 
我注意到 `QMUIAlertController` 的实现方式，其动画是控制 `contentViewController` 的 `containerView` 来实现的。也就相当于在 `showingAnimation` 调用了 `contentViewController` 中作动画的方法。
```
self.modalPresentationViewController.layoutBlock = ^(CGRect containerBounds, CGFloat keyboardHeight, CGRect contentViewDefaultFrame) {
        weakSelf.view.frame = CGRectMake(0, 0, CGRectGetWidth(containerBounds), CGRectGetHeight(containerBounds));
        weakSelf.keyboardHeight = keyboardHeight;
        [weakSelf.view setNeedsLayout];
    };
    
self.modalPresentationViewController.showingAnimation = ^(UIView *dimmingView, CGRect containerBounds, CGFloat keyboardHeight, CGRect contentViewFrame, void(^completion)(BOOL finished)) {
        if ([weakSelf.delegate respondsToSelector:@selector(willShowAlertController:)]) {
                [weakSelf.delegate willShowAlertController:weakSelf];
            }
            weakSelf.containerView.layer.transform = CATransform3DMakeTranslation(0, CGRectGetHeight(weakSelf.containerView.bounds), 0);
            [UIView animateWithDuration:0.25f delay:0 options:QMUIViewAnimationOptionsCurveOut animations:^{
                weakSelf.maskView.alpha = 1;
                weakSelf.containerView.layer.transform = CATransform3DIdentity;
            } completion:^(BOOL finished) {
                weakSelf.isShowing = YES;
                if ([weakSelf.delegate respondsToSelector:@selector(didShowAlertController:)]) {
                    [weakSelf.delegate didShowAlertController:weakSelf];
                }
                if (completion) {
                    completion(finished);
                }
            }];
    };
```

由 `contentViewMargins` 以及 `preferredContentSizeInModalPresentationViewController:limitSize:` 就已经可以确定 `contentView` 的 origin 以及 size，也就是说 `contentView` 的布局已经可以被确定。

这里的难点其实在于动画，因为动画的时候 `contentView` 的 frme 是改变的，会和静态时的布局冲突。

比较婉约的可以仿照 `QMUIAlertController` 的实现。

我在想，要是有好的方案解决这个问题，那么 `layoutBlock` 其实是没有不要的。

👏拍砖QAQ

**Comment by wanhmr** [comment]
并且我觉得是否可以在 block 中把 `contentView` 给传递出来。

**Comment by MoLice** [comment]
> 可以肯定的是，`layoutBlock` 会影响动画，有些动画如果不在 `layoutBlock` 中做处理，动画效果就会有问题。

@wanhmr 试了没有发现问题，可否贴一下你的测试代码？

**Comment by MoLice** [comment]
> 由 `contentViewMargins` 以及 `preferredContentSizeInModalPresentationViewController:limitSize:` 就已经可以确定 `contentView` 的 `origin` 以及 `size`，也就是说 `contentView` 的布局已经可以被确定。

通过 contentViewMargins” 去间接达到调整浮层 origin 的方式是一个简单场景下的取巧方式，并无法完全替代 `layoutBlock` 的存在。


> 这里的难点其实在于动画，因为动画的时候 `contentView` 的 `frame` 是改变的，会和静态时的布局冲突。

这里牵扯到 `layoutBlock` 和 `showingAnimation` 这两个接口的设计目的。
1. `layoutBlock` 用于自定义浮层**最终**的布局，不管这个布局是否以动画形式展示。
2. `showingAnimation` 用于自定义浮层的打开动画（可能是位移动画也可能不是位移动画），但不决定浮层的最终位置，最终位置要么采用 `QMUIModalPresentationViewController ` 默认的计算结果，要么采用 `layoutBlock` 的计算结果。

所以按场景来划分：
1. “自定义布局位置 +  默认动画”：只实现 `layoutBlock` 即可。
2. “默认布局位置 + 自定义动画”： 只实现 `showingAnimation` 即可。
3. “自定义布局位置 + 自定义动画”： 在 `layoutBlock` 里计算最终状态的布局，然后在 `showingAnimation` 里通过参数 `contentViewFrame` 拿到 `layoutBlock` 的计算结果去做动画。

为什么需要拆分这两个接口，而不让 `showingAnimation` 把布局和动画的责任全都承担了，是因为假设你的浮层已经使用自定义动画展示出来后，此时进行横竖屏旋转，我们需要去刷新浮层的布局，但因为浮层已经处于显示状态，所以不需要重新做“显示动画”（`showingAnimation`），此时如果不把 `layoutBlock` 和 `showingAnimation` 拆开，就很难在 `showingAnimation` 里区分当前被调用的目的（究竟是要我做动画？还是要我刷新布局？）。

**Comment by wanhmr** [comment]
@MoLice 
我写了一份测试代码，主要是使用 `layoutBlock` 的一些问题。
[这里是测试代码](https://github.com/wanhmr/TPQMUI_Demo)

**Comment by MoLice** [comment]
看了一下测试代码，关键在 `QMUIModalViewControllerTest.m:122` 这句代码：
```Objective-C
if (!self.useAbnormalAnimation) {
    rect = CGRectApplyAffineTransform(rect, self.view.transform);
}
```

其实与 `QMUIModalPresentationViewController` 无关，如果你在写一个普通的 `UIView` 的布局+动画代码，并且使用了 transform，那么在 `setFrame` 时也是需要使用 `CGRectApplyAffineTransform` 的，这是 UIKit 设计如此。
