### ISSUE TITLE
pod 无法引入2.0.0

### ISSUE THREAD

**Issue by howardzhush** [QMUI/QMUI_iOS#198]
请问pod是否无法引入2.0.0版本，
pod search的时候只能看到1.7.5

### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by coldmn3** [comment]
pod install --repo-update

**Comment by howardzhush** [comment]
解决了，谢谢
