### ISSUE TITLE
导航控制器侧拉返回

### ISSUE THREAD

**Issue by coderAs7** [QMUI/QMUI_iOS#199]
在 UINavigationController (QMUI) 这个category中
QMUI交换了ViewDidLoad的实现
导致我自定义的导航控制器的侧拉返回功能失效...
而我仅仅是想导入QMUIAlertController这个功能而已,
可否将模块进一步细分?

**Comment by MoLice** [comment]
有没有具体一点的信息提供？或者贴一下相关的代码？主要是想看“为什么 QMUI 交换了 viewDidLoad 的实现，就会影响到你的原有代码”

**Comment by coderAs7** [comment]
我已经解决了,通过阅读 `UINavigationController (QMUI)` 的源码,我发现是你们交换了`UINavigationController`中的`ViewDidLoad`方法,而我在自己`UINavigationController`中的`viewDidLoad`中写了 
` self.interactivePopGestureRecognizer.delegate = self`来保证侧拉手势有效,但是由于你们的交换,导致了这行代码的失效...
但是我同时发现你们在项目中提供了` forceEnableInteractivePopGestureRecognizer` 这个方法,来让控制器选择是否支持强制侧拉,所以,我为控制器创建了一个分类,并且在这个分类中实现这个方法,并且默认返回YES,来保证这个侧拉手势强制生效...

总结
产生这个问题的原因就是,我自己在导航控制器的ViewDidLoad中写了一些代码,但是你们的交换导致了他失效,我仅仅只是单独的想导入一个QMUIAlertController罢了,是否是我使用cocoapods的姿势不对?我在Podfile文件中如下使用QMUIAlertController
pod 'QMUIKit/QMUIComponents/QMUIAlertController'

**Comment by MoLice** [comment]
你使用 CocoaPods 的方式是正确的。
QMUIKit 目前的子模块划分为了在解耦和使用便利性之间取得平衡，将所有的 QMUICore 和 UIKitExtension 都作为最基础的模块，被所有组件依赖，所以就算你只引入了一个 `QMUIAlertController`，也会带上那些 UIKit 的 Category，短期内我们也依然会保持当前的划分方式。如果有遇到类似这个 issue 的场景，麻烦提给我们，谢谢。
