### ISSUE TITLE
什么时候可以投入生产环境使用？

### ISSUE THREAD

**Issue by WildDylan** [QMUI/QMUI_iOS#2]
最近打算重构项目，恰好看到良心之作，所以来问询。
另外有一个建议： 在横屏模式下浏览大图的时候，可否将大图的按比例缩放放到屏幕范围内，现在是超出去的状况。

**Comment by MoLice** [comment]
现在就可以正式使用了，另外本周我们也会支持 CocoaPod。

至于横屏浏览大图的问题，不太清楚你描述的“将大图缩放到屏幕范围内”是什么意思，能否提供更详细的说明，例如截图？

**Comment by WildDylan** [comment]
好的，等待Cocoapods方式支持。

横屏浏览大图的问题：
<img width="552" alt="qq20161226-184759 2x" src="https://cloud.githubusercontent.com/assets/2519544/21480810/d707a310-cb9b-11e6-8a4e-50046755f874.png">

这张图片的具体内容要滑动到下方才可以展示完整。
<img width="552" alt="qq20161226-184832 2x" src="https://cloud.githubusercontent.com/assets/2519544/21480818/ec44d27a-cb9b-11e6-808c-a875084fe2a5.png">

可否按比缩放至屏幕内展示完整。

**Comment by MoLice** [comment]
1、横屏浏览图片，这个稍等，今晚再提交一次代码优化。这一部分是 Demo 的设计问题，一部分是代码实现的问题。
2、已适配 iPad，并没有发现你说的横竖屏旋转时屏幕闪烁，是否先全部变白再重新出现内容？

**Comment by WildDylan** [comment]
是的，先变白。  在使用iPad横竖屏测试的时候，发现TableView的Cell有一点点问题。 打开Toast那个组件列表等可以看到。

<img width="768" alt="qq20161226-191354 2x" src="https://cloud.githubusercontent.com/assets/2519544/21481161/76756484-cb9f-11e6-90e4-9e22c01274b7.png">

**Comment by MoLice** [comment]
iPad 横屏的 cell 左右间距的问题，是系统自行调整的，经过考虑，QMUI 里不对这种行为做特殊调整，业务如果需要，可自行重写 `layoutMargins`，返回 `UIEdgeInsetsZero` 来兼容。

**Comment by WildDylan** [comment]
好的，谢谢回复。 静待cocoapods版本 

@MoLice Pure awesomeness! 👍

**Comment by MoLice** [comment]
@WildDylan 你好，请更新 QMUIDemo 的代码，优化了你提到的横屏查看大图的效果。
其实就是修改了 `QMUIDemo_iOS/qmuidemo/Modules/Demos/Components/QDImagePreviewViewController1.m:73` 的 `contentMode`。

**Comment by WildDylan** [comment]
confirmed.

**Comment by Huang-Libo** [comment]
看了 Demo, 简直太强大了, 等 QMUI 稳定下来后可以考虑用到公司的项目中去.

**Comment by MoLice** [comment]
最新版本已支持 Cocoa Pod，且行且珍惜Category 系列的类方法均已添加`qmui_`前缀避免同名冲突。建议可开始使用，如有问题将及时处理。
