### ISSUE TITLE
UIFont (QMUI) 字体名字返回有问题

### ISSUE THREAD

**Issue by wpo778822** [QMUI/QMUI_iOS#200]
### 请填写运行环境

- [x] 设备：模拟器
- [x] 系统：iOS  9.3
- [x] Xcode 版本：8.3.3
- [x] QMUI iOS 版本：2.0

### 请描述具体问题
+ (UIFont *)qmui_systemFontOfSize:(CGFloat)size weight:(QMUIFontWeight)weight italic:(BOOL)italic {
    BOOL isLight = weight == QMUIFontWeightLight;
    BOOL isBold = weight == QMUIFontWeightBold;
    
    BOOL shouldUsingHardCode = IOS_VERSION < 10.0;// 这 UIFontDescriptor 也是醉人，相同代码只有 iOS 10 能得出正确结果，7-9都无法获取到 Light + Italic 的字体，只能写死。
    if (shouldUsingHardCode) {
        NSString *name = IOS_VERSION < 9.0 ? @"HelveticaNeue" : @".SFUIText";
        NSString *fontSuffix = [NSString stringWithFormat:@"%@%@", isLight ? @"Light" : (isBold ? @"Bold" : @""), italic ? @"Italic" : @""];
        NSString *fontName = [NSString stringWithFormat:@"%@%@%@", name, fontSuffix.length > 0 ? @"-" : @"", fontSuffix];
        UIFont *font = [UIFont fontWithName:fontName size:size];
        return font;
    }

......

@".SFUIText" 这个字体在不选择bold、light的情况下取得有问题，是否是缺少medium应为@".SFUIText-medium"。

**Comment by MoLice** [comment]
不确定你表达的“取得有问题”具体是什么问题？

你的意思是否是你希望增加 `QMUIFontWeightMedium` 这个 enum 值？

**Comment by wpo778822** [comment]
在xcode里并存10 和9的sdk的时候，调试9的时候，字体是取不到那个名字的，然后断开调试，直接在模拟器运行程序是可以的，我之前说把字体名字加medium应该是10之后字体名字变了。
