### ISSUE TITLE
请问ImagePreview 是否考虑支持预览网络图片？

### ISSUE THREAD

**Issue by admintestgithub** [QMUI/QMUI_iOS#201]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by MoLice** [comment]
暂不考虑，因为每个项目基本都有一整套自己的网络请求框架，所以这件事情交给项目自身解决更合适。
