### ISSUE TITLE
用cocoapods管理qmuikit报错，想问下怎么解决？

### ISSUE THREAD

**Issue by LanYanQin** [QMUI/QMUI_iOS#204]
- [x] 设备：模拟器
- [x] 系统：iOS 11
- [x] Xcode 版本：9
- [x] QMUI iOS 版本：2.0

### 请描述具体问题
我用一个.h文件管理一些库的头文件引用，会报错还有几百个警告。
![image](https://user-images.githubusercontent.com/15378253/30681516-553ec3e8-9ed8-11e7-991c-7923183f9e78.png)
以前我直接下载QMUIKit直接拖进项目的话是没有问题的，我想问下这个该怎么解决？

#### 相关截图（断点的堆栈、控制台的 log）
![image](https://user-images.githubusercontent.com/15378253/30681494-3d9405be-9ed8-11e7-8845-ee8a8e7497d7.png)
红色警告：
![image](https://user-images.githubusercontent.com/15378253/30681542-8095ec74-9ed8-11e7-985e-42afe1e3fa4f.png)
黄色的警告：
![image](https://user-images.githubusercontent.com/15378253/30681573-a767f7ca-9ed8-11e7-9935-80777be91f19.png)

**Comment by MoLice** [comment]
方便的话请添加以下微信：
![image](https://user-images.githubusercontent.com/1190261/30682553-a7ff96f8-9edc-11e7-84ec-e78494366cff.png)

**Comment by LanYanQin** [comment]
加了~请通过

**Comment by LanYanQin** [comment]
问题已经解决，因为以前是用动态库的方式把QMUIKit的拖入到项目中。
在一些需要用到的地方这样引用
![image](https://user-images.githubusercontent.com/15378253/30684137-a7bb9524-9ee2-11e7-875f-7be751fe544f.png)
然后我现在改成cocoapods导入后在PrefixHeader这个文件中引用了#import <QMUIKit.h>，造成了冲突。
把其他文件中的头文件删掉就可以了
