### ISSUE TITLE
使用QMUIAlertController 崩溃问题，如果使用系统的AlertController  则会改变titleView.text 的颜色，原来是白色变为蓝色

### ISSUE THREAD

**Issue by LassZhang** [QMUI/QMUI_iOS#206]
### 请填写运行环境

- [x] 设备：`模拟器`
- [x] 系统：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`2.x.x`

**Comment by MoLice** [comment]
> 使用 QMUIAlertController 崩溃问题

请提供具体信息。



> 使用系统 AlertController 则会改变 titleView.text 的颜色

我在 QMUI Demo 的 QMUIAlertController 里测试并没有发现你说的问题，你的 titleView 是 `QMUINavigationTitleView` 吗？如果是的话，请提供相关测试代码辅助定位问题。

**Comment by LassZhang** [comment]
原始邮件
发件人:MoLicenotifications@github.com
收件人:QMUI/QMUI_iOSQMUI_iOS@noreply.github.com
抄送:LassZhang564626704@qq.com; Authorauthor@noreply.github.com
发送时间:2017年9月21日(周四) 17:39
主题:Re: [QMUI/QMUI_iOS] 使用QMUIAlertController 崩溃问题，如果使用系统的AlertController 则会改变titleView.text 的颜色，原来是白色变为蓝色 (#206)


使用 QMUIAlertController 崩溃问题
请提供具体信息。
使用系统 AlertController 则会改变 titleView.text 的颜色
我在 QMUI Demo 的 QMUIAlertController 里测试并没有发现你说的问题，你的 titleView 是 QMUINavigationTitleView 吗？如果是的话，请提供相关测试代码辅助定位问题。




已经在github上回复您了，这是我的qq ,希望大神能帮助解决以下两个问题
- QMUIAlertController 使用崩溃
- 键盘管理
== 说明以下：我用cococaPods 导入的库中没有QMUIKeyboardManager 这个类，我从Demo中拉入的但是不晓得怎么启用和停用。
我的分析：我从cocoapods 直接导入的库是否不够完整，因为在项目中使用的过程中 也发现没有QMUITheme字样的类，希望给出回复！

**Comment by MoLice** [comment]
1. 请检查你本地的 pod 索引是否最新，可以尝试执行 `pod update` 命令。
2. QMUI 里不存在 `QMUITheme`，不确定你说的是什么。
3. 可能你之前是直接回复 GitHub 给你发的邮件？所以一些信息我们是没收到的（例如你的 QQ 那一段...）。

**Comment by LassZhang** [comment]
我给你了一个附件包，里面有详细的崩溃信息，包括代码，控制台信息，我的qq 564626704

原始邮件
发件人:MoLicenotifications@github.com
收件人:QMUI/QMUI_iOSQMUI_iOS@noreply.github.com
抄送:LassZhang564626704@qq.com; Authorauthor@noreply.github.com
发送时间:2017年9月22日(周五) 22:55
主题:Re: [QMUI/QMUI_iOS] 使用QMUIAlertController 崩溃问题，如果使用系统的AlertController 则会改变titleView.text 的颜色，原来是白色变为蓝色 (#206)


请检查你本地的 pod 索引是否最新，可以尝试执行 pod update 命令。 QMUI 里不存在 QMUITheme，不确定你说的是什么。 可能你之前是直接回复 GitHub 给你发的邮件？所以一些信息我们是没收到的（例如你的 QQ 那一段...）。

**Comment by LassZhang** [comment]
我今天CocoaPods更新QMUIKit ，发现其中没有QMUIKeyboardManager 类， 版本是1.3.4 ，如果要用还要单独导入一个Manager类么

**Comment by MoLice** [comment]
请更新你本地的 pod 索引，目前 QMUI 的版本是 2.0
