### ISSUE TITLE
Swift3.2如何像OC一样设置全局样式

### ISSUE THREAD

**Issue by zenghaojim33** [QMUI/QMUI_iOS#207]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.0`
- [x] Xcode 版本：`9`
- [x] QMUI iOS 版本：`2.0.0`

### 请描述具体问题

尝试使用QMUIConfiguration.sharedInstance()中的属性，不能生效。

**Comment by MoLice** [comment]
原来这里也提了一次了，[原 issue ](https://github.com/QMUI/QMUIDemo_iOS/issues/14)在 QMUIDemo 项目。
