### ISSUE TITLE
QMUI_QQEmotion.bundle无法读取到

### ISSUE THREAD

**Issue by gdfyj90** [QMUI/QMUI_iOS#209]
### 请填写运行环境

- [x] 设备：`模拟器`
- [x] 系统：`iOS 11.0`
- [x] Xcode 版本：`9.0`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题
使用pod集成qmui后，将QMUI_QQEmotion.bundle放到自己的工程中，无法读取到里面的表情图片

#### 相关截图（断点的堆栈、控制台的 log）
+ (NSBundle *)resourcesBundleWithName:(NSString *)bundleName {
    NSBundle *bundle = [NSBundle bundleWithPath: [[[NSBundle mainBundle] resourcePath] stringByAppendingPathComponent:bundleName]];
    if (!bundle) {
        // 动态framework的bundle资源是打包在framework里面的，所以无法通过mainBundle拿到资源，只能通过其他方法来获取bundle资源。
        NSBundle *frameworkBundle = [NSBundle bundleForClass:[self class]];
        NSDictionary *bundleData = [self parseBundleName:bundleName];
        if (bundleData) {
            bundle = [NSBundle bundleWithPath:[frameworkBundle pathForResource:[bundleData objectForKey:@"name"] ofType:[bundleData objectForKey:@"type"]]];
        }
    }
    return bundle;
}
经过调试是这个方法里返回nil

**Comment by MoLice** [comment]
请问你是用静态库还是动态库的方式引入 QMUIKit 的呢？

**Comment by gdfyj90** [comment]
静态库，没有user_framework

**Comment by MoLice** [comment]
方便的话可以加一下这个微信，把有问题的工程发一下我们看看。

![image](https://user-images.githubusercontent.com/1190261/30904787-8d851fe6-a3a5-11e7-9e09-af814ec1b8f3.png)

**Comment by MoLice** [comment]
抱歉，是 QMUIKit.podspec 写得有问题，当使用者以子模块的方式引入其中某个子模块（而不是引入整个 QMUIKit）时，resource bundle 是不会被自动加进项目编译的，目前请手动将两个 QMUI Bundle 添加到业务项目里，并且检查在 target → Build Phases → Copy Bundle Resources 里是否存在那两个 QMUI Bundle。

等下一个 Release 版本发布后即可由 pod 自动管理 bundle，谢谢反馈。
