### ISSUE TITLE
CocoaPods引入方式失败

### ISSUE THREAD

**Issue by ShuoHuang** [QMUI/QMUI_iOS#21]
### 具体问题描述 ###

pod install时，提示 [!] Unable to find a specification for `QMUIKit (~> 1.1.4)`

并用pod search QMUIKit时,提示[!] Unable to find a pod with name, author, summary, or description matching `QMUIKit`

**Comment by zhoon** [comment]
请尝试一下更新CocoapPods的索引再试试？

**Comment by zhoon** [comment]
rm -rf ~/.cocoapods
pod setup
pod install
或者
rm ~/Library/Caches/CocoaPods/search_index.json

**Comment by iOSCountry** [comment]
@ShuoHuang 你的问题好了吗

**Comment by iOSCountry** [comment]
@zhoon 
![wx20170111-115506](https://cloud.githubusercontent.com/assets/17453419/21835066/0c5810c6-d7f5-11e6-9b40-f269650e9256.png)

cocoapods 版本是1.0.1,还是搜不到

**Comment by iOSCountry** [comment]
已解决
