### ISSUE TITLE
podspec配置有问题

### ISSUE THREAD

**Issue by jmnice** [QMUI/QMUI_iOS#210]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 7.x`
- [x] Xcode 版本：`8.3.3.x`
- [x] QMUI iOS 版本：`2.0.0`

### 请描述具体问题
我们的App是支持7.0+的，然后用pod更新你们的2.0.0结果不报错(2.0.0支持8.0+)。然后很开心的发了版本，结果这几天收到一堆投诉，说7.x设备一点就崩溃，取出崩溃日志:

Incident Identifier: 017CF34D-051D-49B2-9372-BB3B501066E6
CrashReporter Key:   22dda5f8261471e01052f9b2cb9b86623cb3df3c
Hardware Model:      iPod5,1
Process:             ztjy [197]
Path:                /var/mobile/Applications/036902C4-8CAD-4F02-8EA0-8D41F0352522/ztjy.app/ztjy
Identifier:          com.szy.seebaby
Version:             3 (5.4.3)
Code Type:           ARM (Native)
Parent Process:      launchd [1]

Date/Time:           2017-09-25 11:39:33.028 +0800
OS Version:          iOS 7.1.2 (11D257)
Report Version:      104

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x00000000e7ffdefe
Triggered by Thread:  0

Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/Photos.framework/Photos
  Referenced from: /var/mobile/Applications/036902C4-8CAD-4F02-8EA0-8D41F0352522/ztjy.app/ztjy
  Reason: image not found
  Dyld Version: 324.1
Photos.framework not found  !!!

然后去看了你们的 podspec:
  s.name             = "QMUIKit"
  s.version          = "2.0.0"
  s.summary          = "致力于提高项目 UI 开发效率的解决方案"
  s.description      = <<-DESC
                       QMUI iOS 是一个致力于提高项目 UI 开发效率的解决方案，其设计目的是用于辅助快速搭建一个具备基本设计还原效果的 iOS 项目，同时利用自身提供的丰富控件及兼容处理， 让开发者能专注于业务需求而无需耗费精力在基础代码的设计上。不管是新项目的创建，或是已有项目的维护，均可使开发效率和项目质量得到大幅度提升。
                       DESC
  s.homepage         = "http://qmuiteam.com/ios"
  s.license          = 'MIT'
  s.author           = {"qmuiteam" => "qmuiteam@qq.com"}
  s.source           = {:git => "https://github.com/MoLice/QMUI_iOS.git", :tag => s.version.to_s}
  s.social_media_url = 'https://github.com/MoLice/QMUI_iOS'
  s.requires_arc     = true
  s.documentation_url = 'http://qmuiteam.com/ios/page/document.html'
  s.screenshot       = 'https://cloud.githubusercontent.com/assets/1190261/26751376/63f96538-486a-11e7-81cf-5bc83a945207.png'

  s.platform         = :ios, '7.0'
  s.frameworks       = 'Foundation', 'UIKit', 'CoreGraphics', 'Photos'

我能说什么~~~，你们这么不严谨，我们还敢用吗~~

不过库写的可以，挺方便的~~ 
![121212](https://user-images.githubusercontent.com/8054992/30792542-a78f042e-a1ed-11e7-8dc4-4d53a42d6a4b.png)

**Comment by MoLice** [comment]
非常抱歉，这里疏忽了对 platform 值的更新，已提交新 podspec 文件修复。
