### ISSUE TITLE
如果不是新项目，这个第三方会跟其他库冲突吗，比如IQKeyboardManager

### ISSUE THREAD

**Issue by jianjianhao** [QMUI/QMUI_iOS#211]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

**Comment by zhoon** [comment]
你好，目前仅发现跟BlocksKit有一个冲突，不过挺多人其他的项目也会遇到冲突，猜测是BlocksKit的问题，具体请看这个这个issue：https://github.com/QMUI/QMUI_iOS/issues/98
