### ISSUE TITLE
我的页面隐藏导航栏，怎么在从我的页面push的二级页面里面显示导航栏？需要每个二级页面都实现显示导航栏的方法么？

### ISSUE THREAD

**Issue by AdminTestsGitHub** [QMUI/QMUI_iOS#213]
### 请填写运行环境

- [x] 设备：`iPhone` 模拟器`
- [x] 系统：`iOS 11`
- [x] Xcode 版本：`9`
- [x] QMUI iOS 版本：`2.0.0`

#### 相关截图（断点的堆栈、控制台的 log）
来自QMUI的忠实粉丝。

**Comment by zhoon** [comment]
QMUINavigationControllerDelegate 里面有个方法是 preferredNavigationBarHidden，如果你配置的默认值是 NO，那么你只需要在当前界面实现并且返回 YES，push 到二级界面不需要做任何实现就可以让导航栏显示回来。具体你可以查看相关api。

**Comment by loveuqian** [comment]
@zhoon 
好像单页面隐藏有问题，我当前页面是继承于 commonVC 的，导航隐藏，push 去 commonVC，导航依然隐藏
![image](https://user-images.githubusercontent.com/9745332/44577982-03dcd480-a7c5-11e8-9c88-181c99f98faf.png)

**Comment by openUmbrella** [comment]
@zhoon @loveuqian 我也遇到跟你一样的问题
