### ISSUE TITLE
会考虑对本地gif的支持吗？

### ISSUE THREAD

**Issue by shenzihao** [QMUI/QMUI_iOS#214]

**Comment by kayo5994** [comment]
@shenzihao `QMUIAsset` 中的 [`requestImageData:`](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIComponents/AssetLibrary/QMUIAsset.h#L132) 方法可以获取图片的 `NSData` 对象，以及判断图片是否为 GIF 图片。因此你可以通过 `NSData` 对象以及 `UIWebView` 做 GIF 的展示。

**Comment by MoLice** [comment]
GIF 的展示能力后续的版本会支持

**Comment by MoLice** [comment]
2.1.0 已支持GIF。
