### ISSUE TITLE
iOS 11下QMUICommonTableViewController 的contentInset会出现一个tababr高度的偏差

### ISSUE THREAD

**Issue by codingiran** [QMUI/QMUI_iOS#215]
### 请填写运行环境

- [x] 设备：`iPhone 7` /  `模拟器`
- [x] 系统：`iOS 11.0.1`
- [x] Xcode 版本：`9.0`
- [x] QMUI iOS 版本：`2.0.0`

**Comment by MoLice** [comment]
`QMUICommonTableViewController` 是在属性 `tableViewInitialContentInset` 里会去改到 `automaticallyAdjustsScrollViewInsets`，请问你使用了这个属性了吗？

**Comment by MoLice** [comment]
另外发现 iOS 11 下如果设置了 `tabBar setBackgroundImage:`，也会导致系统自动调整 UIScrollView 的 contentInset.bottom 时无法感知到 `tabBar` 的存在，这个目前正在做兼容。iOS 10 是没问题的。
