### ISSUE TITLE
当通过 UITableViewcell 的 UITableViewRowAction 事件 push 一个 新的 controller时  interactivePopGestureRecognizer 会失效

### ISSUE THREAD

**Issue by frankxzx** [QMUI/QMUI_iOS#216]
代码如下：

-(void)tableView:(UITableView *)tableView commitEditingStyle:(UITableViewCellEditingStyle)editingStyle forRowAtIndexPath:(NSIndexPath *)indexPath {
    
}

-(NSArray<UITableViewRowAction *> *)tableView:(UITableView *)tableView editActionsForRowAtIndexPath:(NSIndexPath *)indexPath {
    UITableViewRowAction *action = [UITableViewRowAction rowActionWithStyle:(UITableViewRowActionStyleDefault) title:@"测试" handler:^(UITableViewRowAction * _Nonnull action, NSIndexPath * _Nonnull indexPath) {
        UIViewController *controller =  [[QDCommonTableViewController alloc]init];
        controller.title = @"当前控制器的左滑回退手势会失效";
        [self.navigationController pushViewController:controller animated:YES];
    }];
    return @[action];
}

**Comment by zhoon** [comment]
@frankxzx 我复制你的代码在 qmuidemo 里面试了，并没有你说的这个问题。
