### ISSUE TITLE
iPhone X 下，UITabBarController 在切换界面时 tabBar 往上跳动

### ISSUE THREAD

**Issue by MoLice** [QMUI/QMUI_iOS#217]
### 请填写运行环境

- [x] 设备：`iPhone X 模拟器`
- [x] 系统：`iOS 11.0`
- [x] Xcode 版本：`9.0`
- [x] QMUI iOS 版本：`2.0.0`

### 请描述具体问题
截图如下：
![image](https://user-images.githubusercontent.com/1190261/30952772-bed3760e-a45b-11e7-84b5-0e6bf129871a.png)

![image](https://user-images.githubusercontent.com/1190261/30952787-cd014dc8-a45b-11e7-9801-a5e83c57e476.png)

重现条件：
1. UITabBarController 内包 UINavigationController，UINavigationController 内包界面 A 和界面 B。
2. 界面 A.hidesBottomBarWhenPushed = NO，界面 B.hidesBottomBarWhenPushed = YES。
3. 从界面 A push 到界面 B，可观察到 tabBar 瞬间往上跳动。

属于 UIKit 自身的 bug。

**Comment by MoLice** [comment]
tabBar 视觉上的跳动可以解决，但因为 safeAreaInset.bottom 错误地变成 0，导致 scrollView 的 contentOffset 会跟着变，这个暂时不好解决。

**Comment by Archer353** [comment]
您好，视觉上的跳动是怎么解决的？

**Comment by Gfengwei** [comment]
@Archer353  我是在继承QMUINavigationController的NavigationController里重写pushViewController:(UIViewController *)viewController然后修改tabBar的frame ；

![snip20171116_1](https://user-images.githubusercontent.com/25836014/32875659-1d2ac646-cad4-11e7-9632-f161afc3f480.png)
`- (void)pushViewController:(UIViewController *)viewController animated:(BOOL)animated{
    [super pushViewController:viewController animated:animated];
    CGRect frame = self.tabBarController.tabBar.frame;
    frame.origin.y = [UIScreen mainScreen].bounds.size.height - frame.size.height;
    self.tabBarController.tabBar.frame = frame;
}`

**Comment by MoLice** [comment]
该 bug 在 iOS 11.2 里已被系统修复，QMUI 仅对 iOS 11.2 以前的版本做修复兼容，在即将发布的新版本里会带上。

**Comment by MoLice** [comment]
请查看配置表开关 `shouldFixTabBarTransitionBugInIPhoneX`。
