### ISSUE TITLE
QMUIImagePickerViewController 进入界面后无法自动滚到底部

### ISSUE THREAD

**Issue by MoLice** [QMUI/QMUI_iOS#219]
### 请填写运行环境

- [x] 设备：`iPhone`
- [x] 系统：`iOS 11.0`
- [x] Xcode 版本：`9.0`
- [x] QMUI iOS 版本：`2.0.0`

### 请描述具体问题

重现方式：
1. 大量图片
2. 以 pushViewController:animated:NO 的方式打开一个 QMUIImagePickerViewController（例如第一次发图后记住上一次选择的相簿，下一次打开相册则直接进入这个相簿）
3. 使用 `QMUIAlbumSortTypePositive` 的排序方式（也即进入界面后自动滚到底部）

**Comment by MoLice** [comment]
某些机器上在走到 `- QMUIImagePickerViewController scrollToInitialPositionIfNeeded`方法内时，会出现 `self.collectionView` 尚未计算好 `contentSize` 的情况，从而虽然正确执行了 `[self.collectionView qmui_scrollToBottom]`，但由于 `self.collectionView.contentSize` 为 0，导致本次滚动请求被忽略，最终表现出来就是列表停留在顶部。

**Comment by zhoon** [comment]
我之前出现这个问题的手机上照片很少

**Comment by MoLice** [comment]
@zhoon 要么图片多，要么手机当时卡，只要这两种，就很容易出现。
