### ISSUE TITLE
QMUIDemo中Components ->QMUIPickingImage操作闪退

### ISSUE THREAD

**Issue by iOS-lancelot** [QMUI/QMUI_iOS#22]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `模拟器`
- [x] 系统版本：`iOS 10.2`
- [x] Xcode 版本：`8.1`
- [x] QMUI iOS 版本：`1.x.x`  QMUIDemo中版本 

### 具体问题描述 ###
操作步骤: 1 : Run Demo > 选择Componments -> QMUIPickingImage 
                2 : 选择任意一个列表 ->进入相册 ->选中一张图片->点击预览->再取消选中图片
控制台j截图 : 

#### 问题截图 ####
控制台截图 : 
![2017-01-06 4 51 24](https://cloud.githubusercontent.com/assets/15032412/21712908/24fbd02a-d432-11e6-95c8-bd262ea8cd41.png)

 操作Gif :
![qmui_imagebug](https://cloud.githubusercontent.com/assets/15032412/21712938/44434512-d432-11e6-91ac-c65e0d8cd309.gif)

**Comment by MoLice** [comment]
谢谢反馈，这个问题昨天也发现了，已经修复，今晚会更新一次版本，到时即可解决。

**Comment by MoLice** [comment]
已修复，请更新代码，谢谢
