### ISSUE TITLE
pod 使用指定分支为 master 后，找不到 QMUICore.h。

### ISSUE THREAD

**Issue by SuperY** [QMUI/QMUI_iOS#220]
### 请填写运行环境

- [x] 设备：`模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`master`

### 请描述具体问题
pod 使用指定分支为 master 后，找不到 QMUICore.h。

**Comment by MoLice** [comment]
目前 master 的文件目录结构经过了重命名整理，Release 2.0.0 没有，而目前的 podspec 文件是针对 2.0.0 写的，所以指定为 master 会因为目录错误而无法使用，建议先指定为 2.0.0，master 的一些改动会待国庆后再跟随 Release 2.1.0 发布。
