### ISSUE TITLE
关于QMUIAlertController的一点建议

### ISSUE THREAD

**Issue by coderAs7** [QMUI/QMUI_iOS#221]
使用了一下 `QMUIAlertController`，感觉有下面地方依旧可以改进....

1. 设置了 `QMUIAlertController` 的代理, 实现 `- (void)didHideAlertController:(QMUIAlertController *)alertController;` 方法后,这个方法会被多次调用,目测是两次(其他方法暂未测试)
2. `QMUIAlertAction` 的 `handler` 回调时机问题,系统 `UIAlertAction` 的 `handler` 默认的是等动画结束后回调，而 `QMUIAlertAction` 点击以后立即回调,这样导致了 `handler` 中写的其他第三方 HUB 可能不会出现(个人测试了 `SVProgressHUB`)
3. `QMUIAlertAction` 不允许设置单独颜色..需要在 `showWithAnimated` 之后设置才有效

**Comment by MoLice** [comment]
好的，这几点我们都检查一下，相应的修改在下一个版本里带上，谢谢提议。

**Comment by zhoon** [comment]
@coderAs7 第3点中，在QMUIAlertAction里面有两个属性可以控制：

> /// `QMUIAlertAction`按钮样式，默认nil。当此值为nil的时候，则使用`QMUIAlertController`的`alertButtonAttributes`或者`sheetButtonAttributes`的值。
@property(nonatomic, strong) NSDictionary<NSString *, id> *buttonAttributes;

> /// 原理同上`buttonAttributes`
@property(nonatomic, strong) NSDictionary<NSString *, id> *buttonDisabledAttributes;

请问这两个可以满足你设置单独颜色的需求吗？
