### ISSUE TITLE
NavigationController手势返回放弃后,提示动画未结束无法push,实际并没有动画进行了

### ISSUE THREAD

**Issue by Joan-m** [QMUI/QMUI_iOS#225]
2017-10-13 17:24:57.611721+0800 ExChanger[533:136360] QMUI - 手势返回放弃了. Called By -[RootNavigationController handleInteractivePopGestureRecognizer:]
2017-10-13 17:24:59.262251+0800 ExChanger[533:136360] QMUI - RootNavigationController, 上一次界面切换的动画尚未结束就试图进行新的 push 操作，为了避免产生 bug，拦截了这次 push。
-[QMUINavigationController pushViewController:animated:], isViewControllerTransiting = YES, viewController = <AddManagementADViewController: 0x100d77cf0>
superclass:				RootViewController
title:					(null)
view:					(null), self.viewControllers = (
    "<AccountViewController: 0x100c1e140>\nsuperclass:\t\t\t\tRootViewController\ntitle:\t\t\t\t\t(null)\nview:\t\t\t\t\t<UIView: 0x100d12460; frame = (0 0; 414 736); autoresize = W+H; gestureRecognizers = <NSArray: 0x174055a20>; layer = <CALayer: 0x170221d60>>",
    "<ManagementADViewController: 0x100d743f0>\nsuperclass:\t\t\t\tRootViewController\ntitle:\t\t\t\t\t(null)\nview:\t\t\t\t\t<UIView: 0x100d8b380; frame = (0 0; 414 736); autoresize = W+H; gestureRecognizers = <NSArray: 0x170249810>; layer = <CALayer: 0x17023c200>>"
). Called By -[QMUINavigationController pushViewController:animated:]

**Comment by Ccmi** [comment]
请问是怎么解决的呢？我也遇到了
