### ISSUE TITLE
QMUIAlertController 的一个问题

### ISSUE THREAD

**Issue by hughkli** [QMUI/QMUI_iOS#226]
### 请填写运行环境

- [x] 设备：模拟器
- [x] 系统：iOS 11.x
- [x] Xcode 版本：9.0
- [x] QMUI iOS 版本：2.0.0

使用 QMUIAlertController 的 showWithAnimated:YES 方法来显示一个弹窗，然后在showAnimation 还没有结束时就调用 hide 方法，这时 alertController 并没有消失。

原因是 hide 方法会先对 isShowing 这个变量进行判断，如果 isShowing 为 NO，则会直接 return 这个 hide 方法，而 isShowing 直到 showAnimation 结束后才会被置为 YES，因此导致了这个 bug。

**Comment by zhoon** [comment]
新提交的代码已经修复这个问题，pod还要过几天才会更新。
