### ISSUE TITLE
QMUIModalPresentationViewController 在ios11大屏适配问题

### ISSUE THREAD

**Issue by 6lihaitao** [QMUI/QMUI_iOS#227]
### 请填写运行环境

- [x] 设备：`iPhone6`
- [x] 系统：`iOS 11.0`
- [x] Xcode 版本：`9.0`
- [x] QMUI iOS 版本：`1.7.6`

### 请描述具体问题
QMUIModalPresentationViewController *qmuiWindow =  [[QMUIModalPresentationViewController alloc] init];
    qmuiWindow.contentView = alertView;
    qmuiWindow.contentViewMargins = UIEdgeInsetsZero;
    qmuiWindow.animationStyle = QMUIModalPresentationAnimationStyleFade;
    [qmuiWindow showWithAnimated:animated completion:completion];

其中alertview的大小是[UIScreen mainScreen].bounds
但是在pod和iphone6上面显示的样式不同，系统都是11的

#### 相关截图（断点的堆栈、控制台的 log）
![Uploading 1.png…]()
![Uploading 2.png…]()

**Comment by MoLice** [comment]
请注意 QMUIModalPresentationViewController.h 第 87 行里的注释，浮层宽度还受最大内容宽度的限制，如果需要撑满整个屏幕，请把 maximumContentWidth 设置为 CGFLOAT_MAX

**Comment by 6lihaitao** [comment]
好的 谢谢
