### ISSUE TITLE
QMUIButton 动画 （UIView animateWithDuration 方式）bug

### ISSUE THREAD

**Issue by AdminTestsGitHub** [QMUI/QMUI_iOS#229]
### 请填写运行环境

- [x] 设备：`iPhone ,模拟器`
- [x] 系统：`iOS 11`
- [x] Xcode 版本：`9`
- [x] QMUI iOS 版本：`2.0`

### 请描述具体问题
想用QMUIButton实现图片文字上下排列，然后对btn做放大，渐隐的组合动画。

[UIView animateWithDuration:time animations:^{
        btn.transform = CGAffineTransformMakeScale(1.5, 1.5);
    }];

btn.alpha = 1;
    [UIView animateWithDuration:time animations:^{
        btn.alpha = 0;
    } completion:^(BOOL finished) {
        [btn removeFromSuperview];
    }];

动画效果没有出来，效果异常。一样的代码 换成系统UIButton则没有问题，我想知道是不是QMUIButton内部设置了什么而导致没有动画效果。

**Comment by zhoon** [comment]
@AdminTestsGitHub 谢谢反馈，我复制你的代码测试了一下，发现动画是可以正常运行的，你可以发一下你有问题的demo给我调试看看吗？如果可以，请发送到邮箱：qmuiteam@qq.com。

**Comment by zhoon** [comment]
@AdminTestsGitHub 我看了你的demo，动画异常的点主要是alpha没有变化，原因是QMUIButton默认在点击的时候回去修改button的alpha，放手的时候再恢复，从而在视觉上有个点击态的效果。这个跟你的alpha动画冲突了，你可以设置QMUIButton： btn.adjustsButtonWhenHighlighted = NO; 来解决这个问题，这个属性设置为 NO，就不会有alpha的点击态了，但是带来的问题就是，如果你要button有点击态，那么就需要自己做。

**Comment by zhoon** [comment]
> 很抱歉我没来得及仔细看QMUIButton的具体细节
>      我以为QMUIButton 在没设置属性的时候不会侵染系统btn 等同于系统btn，我这么想是不是有点简单了？

QMUIButton 虽然继承了 UIButton，但是里面有重写了 layoutSubviews 和 sizeThatFit: 等方法，所以已经不等同于系统的btn了，不过一般在使用上基本可以当成和UIButton等同，是UIButton的加强版
