### ISSUE TITLE
QMUIDialogViewController 多选

### ISSUE THREAD

**Issue by wxlpp** [QMUI/QMUI_iOS#23]
### 具体问题描述 ###
QMUIDialogViewController 中的多选列表希望可以内置一个属性限制多选项目的数量.

**Comment by wxlpp** [comment]
貌似可以通过setCanSelectItemBlock实现,不过比较麻烦

**Comment by MoLice** [comment]
这种属于偏业务细节的需求，不太适合由 `QMUIDialogViewController` 实现，毕竟如果要支持 `maximumSelectionCount` 的话，还需要考虑在达到选中上限后，UI 上要如何表现，要如何提醒用户已经达到上限了，这种不论怎么解决都有点不太通用，所以建议由业务处理即可。
