### ISSUE TITLE
UIView convertRect:fromView: 在 iOS 8 下可能转换错误

### ISSUE THREAD

**Issue by MoLice** [QMUI/QMUI_iOS#230]
### 请填写运行环境

- [x] 设备：`模拟器`
- [x] 系统：`iOS 8.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.0.0`

### 请描述具体问题

iPad 横屏，测试代码如下：
```Objective-C
// 明明 navigationBar.x 是 0，但转换后却得到 1408
CGRect navigationBarFrameInView = [self.view convertRect:self.navigationController.navigationBar.frame fromView:self.navigationController.navigationBar.superview];
```

**Comment by zhoon** [comment]
这个 bug 会导致一些场景下设置某个 view 的 frame 为 NaN，从而导致 crash。

**Comment by wanhmr** [comment]
```
这个方法会在 `viewDidLayoutSubviews:` 调用
- (CGRect)tableViewRectForBounds:(CGRect)bounds {
    return CGRectMake(0, self.qmui_navigationBarMaxYInViewCoordinator, bounds.size.width, bounds.size.height - self.qmui_navigationBarMaxYInViewCoordinator - self.qmui_tabBarSpacingInViewCoordinator);
}
```
@MoLice @zhoon 
 
目前线上由于上面代码导致一大丢闪退

- [x] 设备：`iPhone6`
- [x] 系统：`8.3 (12F70)`
- [x] Xcode 版本：`9.0.3`
- [x] QMUI iOS 版本：`2.x.x`

报如下错误：
```
CALayerInvalidGeometry
CALayer position contains NaN: [187.5 nan]
```

**Comment by wanhmr** [comment]
这里可能是其他问题。请先忽略上面。

**Comment by wanhmr** [comment]
经查，确实是 `QMUI` 问题。
过程如下：
```
- (CGFloat)ql_tabBarSpacingInViewCoordinator {
    if (!self.isViewLoaded) {
        return 0;
    }
    if (!self.tabBarController.tabBar || self.tabBarController.tabBar.hidden) {
        return 0;
    }
    CGRect tabBarFrameOriginal = self.tabBarController.tabBar.frame;
    CGRect tabBarConvertFrame = [self.view convertRect:tabBarFrameOriginal fromView:self.tabBarController.tabBar.superview];
    CGRect viewBounds = self.view.bounds;
    CGRect tabBarFrame = CGRectIntersection(viewBounds, tabBarConvertFrame);
    CGFloat result = CGRectGetHeight(viewBounds) - CGRectGetMinY(tabBarFrame);
    return isnan(result) || isinf(result) ? 0 : result;
}
```

以上代码打印结果：

```
Printing description of tabBarFrameOriginal:
(CGRect) tabBarFrameOriginal = (origin = (x = 0, y = 975), size = (width = 768, height = 49))
Printing description of tabBarConvertFrame:
(CGRect) tabBarConvertFrame = (origin = (x = 0, y = 1300.3333333333335), size = (width = 1024, height = 65.33333333333303))
Printing description of viewBounds:
(CGRect) viewBounds = (origin = (x = 0, y = 0), size = (width = 768, height = 1024))
Printing description of tabBarFrame:
(CGRect) tabBarFrame = (origin = (x = +Inf, y = +Inf), size = (width = 0, height = 0))
```

可以看到，是由于 `CGRectIntersection(a, b)` 方法导致。

**Comment by zhoon** [comment]
@wanhmr QMUI 这个方法确实有问题，归根结底也是这个 ussue 提到的问题，系统的
 convertRect:fromView: 在 iOS 8 下可能转换错误导致的。我们已经提交了临时的修改到git上，你可以先按照修改看看还有没有问题？具体的正确的修改方法，我们研究后后面会发个Pods版本修复。

**Comment by zhoon** [comment]
临时修改请看：https://github.com/QMUI/QMUI_iOS/commit/41f77b38b1635246029a174587a270a70012ac27

**Comment by wanhmr** [comment]
@zhoon 这么修改，你们测试过没有问题？

**Comment by wanhmr** [comment]
@zhoon 现在是有点怕了 = =

**Comment by wanhmr** [comment]
@zhoon 我补充一下，我是用 iOS11 的 iPad 模拟器出发的。

**Comment by zhoon** [comment]
@wanhmr 你的意思是这个不是在 iOS8 上面触发的？

**Comment by MoLice** [comment]
这个问题我们自己的产品也遇到，因此产生一些crash，我们已经在内部版本里修复了，只是因为要等其他更新内容一起发版本，所以没有把那个修复更新到Github 。
不管怎么修改，你更新了代码后最好也请自行测试iOS 8和非iOS 8是否正常。

**Comment by MoLice** [comment]
iOS 11 也会？按照我们实测结果，以及线上用户的crash情况，暂时只能在iOS 8上面重现。

**Comment by wanhmr** [comment]
@zhoon @MoLice 我测试的是在 iOS11 的 iPad 模拟器 ！iOS11 的 iPad 模拟器 ！iOS11 的 iPad 模拟器！

**Comment by wanhmr** [comment]
<img width="522" alt="2017-11-04 10 46 28" src="https://user-images.githubusercontent.com/14258488/32406364-0f6492c4-c1b2-11e7-8066-88a8dfec0b59.png">

**Comment by wanhmr** [comment]
今天刚上线，一大丢 bug。好尴尬，并且正好这次 iPad 没有测试。。。

**Comment by zhoon** [comment]
@wanhmr 是必现的还是偶现？

**Comment by wanhmr** [comment]
@zhoon 必现

**Comment by zhoon** [comment]
@wanhmr 试试刚才那样修改之后还有没有问题？有的话我再加个保护。

**Comment by wanhmr** [comment]
@MoLice @zhoon 其实我有点不理解，我认为没啥比闪退更严重了，为什么 QMUI不更新，或者其他醒目点的提示？

**Comment by wanhmr** [comment]
@zhoon 加上保护目前看来没啥问题。

**Comment by MoLice** [comment]
确实，出现导致crash的问题我们应该第一时间更新，这个是我们没及时处理，后续会避免。

**Comment by MoLice** [comment]
CocoaPods 已更新版本到 2.0.1，修复了这个问题，请更新代码尝试。

**Comment by MoLice** [comment]
经 @wanhmr 提供的测试代码验证，此 bug 与 iOS 版本无关，而是在进行 convert 坐标转换运算时，convert 相关的那两个 view 不存在相同的父 view（例如 `self.view` 尚未被添加到 View 层级树上），导致在横屏下两个 view 的坐标系方向不同，从而导致计算错误。

在本地的 QMUI 版本里已对 convert 方法的调用进行检测，发现两个 view 不存在相同的父 view 时会以 `QMUILog` 的方式提示。同时去掉那些在 `viewDidLoad` 里使用 `self.view convertXxx` 的代码。
