### ISSUE TITLE
QMUI不知道如何设置有透明度的navigationBar

### ISSUE THREAD

**Issue by syk83528** [QMUI/QMUI_iOS#232]
在.h中只能设置navigationbarTintColor
但是这个属性对透明度好像不支持,希望能有结果

**Comment by MoLice** [comment]
配置表 `QMUIConfigurationTemplate.m` 里的 `NavBarTintColor` 对应的是 `navigationBar` 上面的按钮的颜色，而从你的 issue title 里猜测你要改的其实是 navigationBar 的背景色？如果是背景色，则对应配置表里的 `NavBarBarTintColor`，它最终改的是 `navigationBar.barTintColor`。

由于有磨砂效果，所以 `navigationBar.barTintColor` 默认都会被以半透明的形式应用到界面上，所以你看到的最终颜色也并非完全等同于你代码里设置的色值。如果你需要完全按照你代码色值去显示（包括半透明），建议生成一张半透明的图片，通过 `NavBarBackgroundImage` 来设置即可。

生成图片的方式可查看 `UIImage (QMUI)`。

**Comment by syk83528** [comment]
我的需求是在滑动的时候navigationBar的颜色随着滑动透明度渐变  我发现改你们的bartintcolor是改不了颜色透明度的 我自己之前使用的修改透明度的方法是这样的:
![image](https://user-images.githubusercontent.com/15796988/32216045-dcc467c2-bdf1-11e7-9fb0-e2cceb7f873a.png)

**Comment by MoLice** [comment]
建议自行修改 setBackgroundImage:，此 issue 属于具体业务问题，close
