### ISSUE TITLE
修改UISearchBar的高度

### ISSUE THREAD

**Issue by MSurui** [QMUI/QMUI_iOS#238]
UISearchBar的分类中把size给写死了60.28,能不能给放开，类似颜色一样的可配置的。现在这个高度太小的不能自定义高啊

**Comment by MoLice** [comment]
其实你可以自己把那句代码在项目里重新写一遍，使用你自己的 image，这样就能覆盖 QMUI 里的效果。这个方式适用于所有 QMUI 的已有代码。
另外这里的图片最终会被变成 resizable image，理论上最终大小和那个 (60, 28) 无必然联系，也无法通过增大这个 size 来让输入框看起来更大。
