### ISSUE TITLE
QMUIGridView用法问题

### ISSUE THREAD

**Issue by LINAICAI** [QMUI/QMUI_iOS#24]
### 运行环境 ###

- [x] iOS 设备：`iPhone`
- [x] 系统版本：`iOS 10.12.2`
- [x] Xcode 版本：`8.2`
- [x] QMUI iOS 版本：`1.1.4`

### 具体问题描述 ###
QMUIGridView怎么使用的，看了api没看懂，没有回调，没有办法设置item，不清楚怎么使用，也没有demo可看，用layout和设置frame的方式都没看到效果，代码如下：

    QMUIGridView *gridView = [[QMUIGridView alloc]initWithColumn:4 rowHeight:4];
    gridView.frame = self.view.bounds;
    gridView.separatorColor = [UIColor redColor];
    gridView.separatorWidth = 1.0;
    gridView.backgroundColor = [UIColor lightGrayColor];
    [self.view addSubview:gridView];

**Comment by MoLice** [comment]
抱歉，这个是注释及 demo 代码没写清楚，我们补充一下。
`QMUIGridView` 管理的是直接子 View 的布局，所以你只需要以 `addSubview:` 的形式把 item 添加进去即可，demo 在 `QDGridViewController`，可看截图里选中的那几行。
![image](https://cloud.githubusercontent.com/assets/1190261/21742737/5e57ef4a-d52f-11e6-97fe-1aaf318b6d88.png)
