### ISSUE TITLE
QMUIImagePickerViewController 能否支持仅显示图片

### ISSUE THREAD

**Issue by lexiaoyao20** [QMUI/QMUI_iOS#240]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题

当前QMUIImagePickerViewController 支持显示视频和图片，如果我只想让用户选图片（即不显示视频），能否支持一下这个场景？ 

看到你们有对应的枚举 QMUIAlbumContentType， 这个要是能在 QMUIImagePickerViewController 加个属性支持就好了。

**Comment by kayo5994** [comment]
目前相册是支持这个场景的。只要把 `QMUIAlbumViewController` 的 `contentType` 属性设置为 `QMUIAlbumContentTypeOnlyPhoto`，那么包括 `QMUIImagePickerViewController` 在内的相册系列界面都只会显示照片。

**Comment by lexiaoyao20** [comment]
@kayo5994 好的，我已经明白了，多谢你的回复！
