### ISSUE TITLE
QMUILabel约束的问题

### ISSUE THREAD

**Issue by syk83528** [QMUI/QMUI_iOS#241]
1.7.6的QMUI版本 10.3系统上

![image](https://user-images.githubusercontent.com/15796988/32871743-70606776-ca48-11e7-9f5d-97afaa21d828.png)
不知道图片传不传的上去   QMUILabel使用的是masonry写的,没有去设置宽高,使用的是内容填充  然后出现了这种问题  请问有什么办法能够解决吗

**Comment by zhoon** [comment]
QMUILabel 和 QMUIButton 前不久才支持了 AutoLayout，你可以 update 到最新的 github 代码试试看，这个修改目前还没同步到 CocoaPods 上，稍后我们再发个版本。
