### ISSUE TITLE
QMUITextView 粘贴长文，多次后变空白

### ISSUE THREAD

**Issue by SuperY** [QMUI/QMUI_iOS#243]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 10.3`
- [x] Xcode 版本：`9.1`
- [x] QMUI iOS 版本：`2.0.1`

### 请描述具体问题
QMUITextView 中粘贴长文字，多次执行后TextView变空白
且：
ScrollEnable=false;
autoResizable = true;

#### 相关截图
https://t1.picb.cc/uploads/2017/11/16/NhgAW.png
![empty](https://t1.picb.cc/uploads/2017/11/16/NhgAW.png)

**Comment by zhoon** [comment]
感谢反馈，我们查查看

**Comment by MoLice** [comment]
无法重现，方便的话加一下以下微信，发送测试代码我看看。

![image](https://user-images.githubusercontent.com/1190261/33368244-1c8634fc-d52c-11e7-89a4-a3b91eb86869.png)

**Comment by SuperY** [comment]
以后复现再说吧～
