### ISSUE TITLE
2.0.1 编译不通过

### ISSUE THREAD

**Issue by stevendinggang** [QMUI/QMUI_iOS#244]
### 请填写运行环境

- [x] 设备：`iPhone`
- [x] 系统：`iOS 11`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.0.1`

### 请描述具体问题
编译不通过

#import "UINavigationController+NavigationBarTransition.h"

No visible @interface for 'UIViewController' declares the selector 'qmui_respondQMUINavigationControllerDelegate'

**Comment by zhoon** [comment]
请问是通过CocoPods下载的吗？是整个项目下载，还是下载了单独的某些组件？

**Comment by Young-Je** [comment]
same problem.

**Comment by Young-Je** [comment]
Version doesn't match ?

**Comment by MoLice** [comment]
use 2.9.2 instead
