### ISSUE TITLE
qmui_lengthWhenCountingNonASCIICharacterAsTwo 返回字数不正确

### ISSUE THREAD

**Issue by StanOz** [QMUI/QMUI_iOS#245]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.0`
- [x] Xcode 版本：`9.0.1`
- [x] QMUI iOS 版本：`1.5.0`

### 请描述具体问题

诸如“一”、“开”等汉字（UTF16 编码下有一个字节为 0x00）在 qmui_lengthWhenCountingNonASCIICharacterAsTwo 的计算方式下返回 1。

#### 相关截图（断点的堆栈、控制台的 log）

无。

**Comment by MoLice** [comment]
2.1.0 版本已修复。
