### ISSUE TITLE
UITextField 在 在StoryBoard 出现奔溃 iOS9.3.4

### ISSUE THREAD

**Issue by davieds** [QMUI/QMUI_iOS#246]
### 请填写运行环境

- [x] 设备：`iPhone`
- [x] 系统：`iOS 9.3.4`
- [x] Xcode 版本：`9.1`
- [x] QMUI iOS 版本：`2.0`

在StoryBoard拖入UITextField ，Run后，奔溃在这段代码

- (NSMethodSignature *)methodSignatureForSelector:(SEL)aSelector {
    NSMethodSignature *a = [super methodSignatureForSelector:aSelector];
    NSMethodSignature *b = [(id)self.originalDelegate methodSignatureForSelector:aSelector];
    NSMethodSignature *result = a ? a : b;
    return result;
}

**Comment by zhoon** [comment]
@davieds 你项目里面是不是使用了其他库，导致冲突？可以参考这个 issue：https://github.com/QMUI/QMUI_iOS/issues/98
