### ISSUE TITLE
self.qmui_navigationBarMaxYInViewCoordinator

### ISSUE THREAD

**Issue by Gfengwei** [QMUI/QMUI_iOS#247]
### 请填写运行环境

- [x] 设备：`iPhone`
- [x] 系统：`iOS 8.2`
- [x] Xcode 版本：`9.1`
- [x] QMUI iOS 版本：`2.1.0`

### 请描述具体问题

QMUIKit~2.0.1之前  self.qmui_navigationBarMaxYInViewCoordinator 是64 升级之后变成了128，
高版本情况下 self.qmui_navigationBarMaxYInViewCoordinator 这个值也是正常的；对比了下 2.0.1 和 2.1.0 里面少了下面这句代码

`if (IOS_VERSION < 9.0) {
        // iOS 8 用上面的方法转换得到的 x = 1408（iPad 横屏下），不知道为什么，暂时认为是系统的 bug，所以这时候先改为转换到 window 坐标系里
        navigationBarFrameInView = [self.view convertRect:self.navigationController.navigationBar.frame fromView:nil];
    }`

之前使用了宏 NavigationContentStaticTop 后来改成了 self.qmui_navigationBarMaxYInViewCoordinator ，目前使用的话是不是以NavigationContentStaticTop 为主？

**Comment by MoLice** [comment]
> QMUIKit~2.0.1之前是64 升级之后变成了128

这个并无法重现，可否提供 demo 代码？

另外 `qmui_navigationBarMaxYInViewCoordinator` 按字面意思，必须是存在 `navigationBar` 的情况下才有效，所以要求这个属性只能在 `viewDidLayoutSubviews` 或 `viewWillAppear:` 之后才能使用。而 `NavigationContentStaticTop` 宏是一个写死的数值，没有调用时机限制，但不够准确优雅，你可以自行衡量选择，我们建议情况允许的情况下优先使用 `qmui_navigationBarMaxYInViewCoordinator`，以保证最准确的计算。

**Comment by Gfengwei** [comment]
是我这边调用过早的问题。
