### ISSUE TITLE
不是很好的支持xib？都是纯代码控件吗？

### ISSUE THREAD

**Issue by LDXu** [QMUI/QMUI_iOS#25]
### 具体问题描述 ###
使用QMUITextView时，是使用xib class改成QMUITextView；
发现placetext无效。

#### 问题截图 ####
控件初始化都是
- (instancetype)initWithFrame:(CGRect)frame {
}

使用xib时都需要
- (void)awakeFromNib {
}

调用初始化里面的方法

**Comment by MoLice** [comment]
目前不支持以 xib 形式使用，正在兼容中，请关注版本更新。

**Comment by MoLice** [comment]
已更新 [1.2.0](https://github.com/QMUI/QMUI_iOS/releases/tag/1.2) 版本，支持 storyboard。如在使用过程中遇到问题麻烦反馈一下。
