### ISSUE TITLE
pod后 iOS11 tableview出现区头区尾

### ISSUE THREAD

**Issue by Qinzhao** [QMUI/QMUI_iOS#250]
### 请填写运行环境

- [x] 设备：`模拟器`
- [x] 系统：`iOS 11.1`
- [x] Xcode 版本：`9.1`
- [x] QMUI iOS 版本：`2.1.0`

#### 相关截图（断点的堆栈、控制台的 log）
    tableView.estimatedSectionHeaderHeight = 0;
    tableView.estimatedSectionFooterHeight = 0;
失效

**Comment by MoLice** [comment]
不如把标题重新打一次？
