### ISSUE TITLE
当实现了- (BOOL)shouldCustomNavigationBarTransitionIfBarHiddenable {          return YES; }该方法,push出新的控制器 控制器的导航栏由  有->无->有,在执行手势返回的时候 控制器不会走dealloc方法

### ISSUE THREAD

**Issue by jhchenchong** [QMUI/QMUI_iOS#251]
### 请填写运行环境

- [模拟器] 设备：`iPhone` / `iPad` / `模拟器`
- [iOS 11.2] 系统：`iOS 11.x`
- [9.2] Xcode 版本：`9.x`
- [2.1.0] QMUI iOS 版本：`2.x.x`

### 请描述具体问题
在第一次执行手势返回的时候是肯定不会走delloc方法  最新的版本也只有第一次执行手势的时候不会走 其他的时候都是正常的  按钮返回就会正常走销毁方法. 具体情况见gif
#### 相关截图（断点的堆栈、控制台的 log）
![1](https://user-images.githubusercontent.com/19201316/33748929-3900bd92-dc06-11e7-8fad-6092f9078051.gif)

**Comment by MoLice** [comment]
好的我们看看

**Comment by zhoon** [comment]
确实有这个问题，只要从有 Bar 返回没有 Bar 的界面，就不会走 dealloc，我新建了一个空白的项目测试是不会的，所以是 QMUI 的锅，再查查看

**Comment by zhoon** [comment]
已经修复，新版本会带上修改
