### ISSUE TITLE
今天有在Bugly上看到用户调用QMUIDialogTextFieldViewController显示的时候造成崩溃

### ISSUE THREAD

**Issue by pptk** [QMUI/QMUI_iOS#254]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题
具体问题我也di定位不清楚，这个后台Log，用户内存还很充足。希望能够帮忙看一下。
#### 相关截图（断点的堆栈、控制台的 log）
![image](https://user-images.githubusercontent.com/5086754/34023114-0a5cdaf2-e17e-11e7-8bcd-c5c8b92f4ab0.png)

![image](https://user-images.githubusercontent.com/5086754/34023104-faeadace-e17d-11e7-9552-50e1a267c191.png)

**Comment by MoLice** [comment]
请问是否有更详细一点的信息，例如怎么使用 `QMUIDialogTextFieldViewController`，怎么使用 `QMUIPopContainerViewController`？或者是否需要加微信具体聊？

**Comment by pptk** [comment]
目前这种情况没有再发生，我自己先排查一下。谢谢回复。
