### ISSUE TITLE
QMUIPopupMenuView

### ISSUE THREAD

**Issue by wxlpp** [QMUI/QMUI_iOS#255]
### 请描述具体问题
QMUIPopupMenuView 能否封装个代理方法,每次添加一个item时实现block有些不方便.

**Comment by MoLice** [comment]
block 和 delegate 属于两种不同的代码风格，它们各有优劣，也适用于不同的场景。通常情况下我们倾向于选择前者，能让代码更紧凑，所以一般情况下 QMUI 的控件都会使用 block，像 `QMUIPopupMenuView`、`QMUIAlertAction`、`QMUIEmotionView` 等。

如果确实需要 delegate 方式，建议可以继承 `QMUIPopupMenuView` 重写 `setItems:` 或 `setItemSections:`，在里面自己 addTarget:，就能实现你自己的 delegate 了。

QMUI 是开源的，所有控件的实现方式都可以自行查看代码了解，很多个性化的需求其实还是很容易自己实现的，不一定需要，也不一定适合都交给 QMUI 来实现。
