### ISSUE TITLE
QMUICommonViewController继承后初始化title显示<##>

### ISSUE THREAD

**Issue by guyinsheng** [QMUI/QMUI_iOS#256]
### 请填写运行环境

- [x] 设备：`模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.2`
- [x] QMUI iOS 版本：`2.2.1`

### 请描述具体问题
自定义一个类IndexViewController，继承QMUICommonViewController，
初始化，[[IndexViewController alloc] init]，
设置IndexViewController的title
QMUINavigationController的initWithRootViewController传入初始化后的自定义类，
设置tabbar等，tabbar的title，
启动模拟器后，画面显示<##>，
若改用QMUICommonViewController的实例传入initWithRootViewController，
则没有问题

#### 相关截图（断点的堆栈、控制台的 log）
![snip20171222_1](https://user-images.githubusercontent.com/34118670/34290254-500e7c50-e731-11e7-8eb4-2a1bb6cdbabd.png)

**Comment by MoLice** [comment]
我猜你有在用 QMUI_iOS_Templates 这个项目？请查看你的 `setNavigationItemsIsInEditMode: animated:` 里是不是有个 `self.title = xxx`

**Comment by guyinsheng** [comment]
非常感谢，因为自身的原因，不太熟悉，依然还需要学习。

**Comment by guyinsheng** [comment]
非常感谢，因为自身的原因，不太熟悉，依然还需要学习。
