### ISSUE TITLE
新版问题

### ISSUE THREAD

**Issue by MaoxinCao** [QMUI/QMUI_iOS#257]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题

更新QMUI pod新版本有几个问题。

1、缺少QMUITableViewHeaderFooterView文件。
2、用XIB自定义了tableview Header与Footer，每次启动时断点会停在 self.tableViewSectionHeaderFont = UIFontBoldMake(12);
（QMUIConfiguration类里第189行）

**Comment by MoLice** [comment]
第2点，你的项目是否有打包某些字体文件进去？
第1点周一我们检查一下。

**Comment by MoLice** [comment]
第1点并没有发现有问题，可能你需要 clean 一下 project

**Comment by MaoxinCao** [comment]
@MoLice  感谢您的回复。

问题1，我从pod中移除QMUI后再install就好了。之前没有移除的时候，每次install都会报缺失QMUITableViewHeaderFooterView文件，检查QMUI pod工程没有没发现这个文件。

问题2，没有打包过字体进去，XIB中都是使用的系统可选的字体。

**Comment by MoLice** [comment]
问题2我们之前遇到过，是因为业务项目不正确引入外部字体导致创建字体时出错，系统给了个断点。卡在QMUI只是因为QMUI那几句话是最先使用到字体的地方，就算去掉QMUI那些代码，也始终会卡在另外一处。你可以弄一个新项目引入QMUI就会发现并没有问题。

**Comment by MaoxinCao** [comment]
问题2，使用系统字体的确是不会出现这个情况了。

但是我项目中并没有引入外部字体，只是在XIB中选择了自定义字体。这样应该不算不正确引入外部字体吧？

**Comment by MoLice** [comment]
这种不确定，我们没有操作过，你可以自行查阅一下相关资料。

**Comment by MaoxinCao** [comment]
嗯，好的。谢谢。
