### ISSUE TITLE
提示警告信息

### ISSUE THREAD

**Issue by kangyeting** [QMUI/QMUI_iOS#258]
-[UIView(QMUI) alertConvertValueWithView:], 进行坐标系转换运算的 <UINavigationBar: 0x125d2add0; frame = (0 -64; 414 44); hidden = YES; opaque = NO; autoresize = W; layer = <CALayer: 0x1c4038760>> 和 <UIView: 0x125e18b10; frame = (0 0; 414 736); autoresize = W+H; layer = <CALayer: 0x1c0225940>> 不存在共同的父 view，可能导致运算结果不准确（特别是在横屏状态下）
几个页面一直报警告. 不知道什么问题

**Comment by MoLice** [comment]
在 alertConvertValueWithView 打个断点，就能看到是谁调用的。应该是你在太早的时机去运算navigationBar相关的坐标导致的。

**Comment by kangyeting** [comment]
断点走这个alertConvertValueWithView方法了, 好像很多地方,再调用,但具体不知道是哪个方法 ... 其他地方也在调用. 我UINavigationBar 是自定义的 ...

**Comment by MoLice** [comment]
你可以把断点时左边的堆栈截图放上来看

**Comment by kangyeting** [comment]
![c058c785e29f2e14e136bf37e028a817](https://user-images.githubusercontent.com/12097404/34428023-4481ce26-ec83-11e7-95cc-394f8c7c0c76.jpg)

**Comment by kangyeting** [comment]
![222](https://user-images.githubusercontent.com/12097404/34428063-ca724cf4-ec83-11e7-8afe-f57e4e4fdbf3.png)

**Comment by MoLice** [comment]
嗯，调用时机太早，navigationBar相关操作建议放到viewDidLayoutSubviews 或者viewWillAppear 里面或者之后。
