### ISSUE TITLE
与GPUImage不兼容，pod方式集成这两个库

### ISSUE THREAD

**Issue by lubaoyilang** [QMUI/QMUI_iOS#26]

**Comment by MoLice** [comment]
请问具体不兼容的点是？

**Comment by lubaoyilang** [comment]
运行不起来，编译错误

**Comment by MoLice** [comment]
对，我的意思是，你能否贴个截图或者报错信息上来？不然你目前提供的信息是无法判断问题所在的。

**Comment by lubaoyilang** [comment]
![error](https://cloud.githubusercontent.com/assets/10125942/22160557/0f91fd72-df81-11e6-836f-50c0058f80ae.jpeg)
截图晚了。。不好意思。

**Comment by lubaoyilang** [comment]
@MoLice

**Comment by MoLice** [comment]
没关系，看这信息，是有一些重复定义的类或方法，我去看看 GPUImage。或者你可以看一下前面的报错信息，应该有明确地写出某个重复定义的符号。

**Comment by MoLice** [comment]
请更新最新代码，已去掉重复的 `dataProviderReleaseCallback` 定义。
