### ISSUE TITLE
如何自定义titleView呢

### ISSUE THREAD

**Issue by CoderMHSun** [QMUI/QMUI_iOS#260]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

**Comment by CoderMHSun** [comment]
QMUINavigationTitleView的，因为我继承了这个QMUINavigationController

**Comment by CoderMHSun** [comment]
我直接写self.navigationItem.titleView = [...]，这样的话，这个系统的titleView是不显示的，如果我[self.titleView addSubview:[...]];这么写的话，我这个view是接受不了点击事件的，不知道原因。

**Comment by MoLice** [comment]
不可点击请查看QMUINavigationTitleView头文件注释，有写，手机打字不方便，你自己看看。

**Comment by MoLice** [comment]
直接写self.navigationItem.titleView = [...]是没问题的，但你要注意不要被QMUI自己的setTitleView代码覆盖。

**Comment by CoderMHSun** [comment]
我的viewDidLoad中就写了这么一个方法，但是这个View还是不显示的。
- (void)configNav {
    IndexTitleView *titleView = [[IndexTitleView alloc] initWithTitles:@[@"推荐",@"控吧",@"动态",@"话题"]];
    titleView.delegate = self;
    
    self.navigationItem.titleView = titleView;
    
}

另外，我使用[self.titleView addSubview: titleView];

**Comment by CoderMHSun** [comment]
我的viewDidLoad中就写了这么一个方法，但是这个View还是不显示的。

- (void)configNav {
IndexTitleView *titleView = [[IndexTitleView alloc] initWithTitles:@[@"推荐",@"控吧",@"动态",@"话题"]];
titleView.delegate = self;

self.navigationItem.titleView = titleView;
}

另外，我使用[self.titleView addSubview: titleView];
self.titleView.userInteractionEnabled = YES;
这样的话，我自定义的titleView还是不可点击的。

**Comment by CoderMHSun** [comment]
但是我继承UIViewController 就是正常的

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/34433184-82e86d84-ecb8-11e7-8252-e6719deaf7ac.png)

![image](https://user-images.githubusercontent.com/1190261/34433201-b7f43b84-ecb8-11e7-9008-39fe8b72b999.png)

你搜索一下就能知道 QMUI 里是在 `viewWillAppear:` 去设置 titleView 的，这就是为什么你看不到效果，因为被 QMUI 覆盖了。

**Comment by CoderMHSun** [comment]
那针对这个问题，我应该如何解决呢
