### ISSUE TITLE
QMUINavigationController 在 present 的同时 push，那么 dismiss 后，原本的 push 界面看不到，以后的 push 也无法响应了

### ISSUE THREAD

**Issue by MoLice** [QMUI/QMUI_iOS#261]
### 请填写运行环境

- [x] 设备：`模拟器`
- [x] 系统：`iOS 11.2`
- [x] Xcode 版本：`9.2`
- [x] QMUI iOS 版本：`2.2.2`

### 请描述具体问题
```Objective-C
// 1. 先 present 一个 vc
UIViewController *vc = [[UIViewController alloc] init];
[self presentViewController:vc animated:YES completion:NULL];

// 2. 同时 push 一个 vc
UIViewController *vc2 = [[UIViewController alloc] init];
[self.navigationController pushViewController:vc2 animated:YES];

// 过了 n 久...

// 3. 将 1 里 present 的那个 vc dismiss 下来
vc dismissXxx

// 4. 再次 push，会发现无法 push
UIViewController *vc3 = [[UIViewController alloc] init];
[self.navigationController pushViewController:vc3 animated:YES];
```

### 原因分析
在 `QMUINavigationController` 里为了保护“上一次 push 动画尚未结束就开始下一次 push 操作”容易导致的 crash，增加了属性 `isViewControllerTransiting` 保护，在 push 时会置为 `YES`，在 push 结束后（也即 `navigationController:didShowViewController:`）恢复为 `NO`，只要 `isViewControllerTransiting` 为 `YES` 的情况下就不响应任何的 push、pop 操作。

而在上述的场景下，由于 `QMUINavigationController` 被 `presentedViewController` 盖住，导致 push 后并不会走到 `navigationController:didShowViewController:`，从而 `isViewControllerTransiting` 属性没有被正确重置，从而影响了后续的 push 操作。

**Comment by zhoon** [comment]
疑难杂症

**Comment by MoLice** [comment]
#1180 根据这个 issue，不只是 prenset 要考虑，还有其他的（例如切 tab），因此判断条件应该改为用 `if (nav.view.window)` 更合理。

**Comment by MoLice** [comment]
> #1180 根据这个 issue，不只是 prenset 要考虑，还有其他的（例如切 tab），因此判断条件应该改为用 `if (nav.view.window)` 更合理。

已发布 [4.2.3](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.3) 优化该处理方式。
