### ISSUE TITLE
QMUIButton 用 swift 4 便利初始化问题

### ISSUE THREAD

**Issue by Ccmi** [QMUI/QMUI_iOS#262]
### 请填写运行环境

- [x] 设备：`iPhone`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.2.2`

### 请描述具体问题
在最新版QMUIKit 2.2.2中， Swift 4 中无法使用QMUIButton 便利初始化方法,因为2.1版本修改了QMUIButton的初始化命名，请支持一下Swift版本的快捷初始化。

**Comment by MoLice** [comment]
`QMUIButton` 一直以来的 designated initializer 就是系统的 `initWithFrame:`，并没有改过。请贴一下你的相关代码？例如 convenience initializer 的写法。

**Comment by Ccmi** [comment]
现在是2.0的版本中，QMUIButton 会有从 OC 桥接过来的初始化方法，由于2.1 版本将这个方法名改变了前缀，导致无法桥接初始化方法到Swift；
![image](https://user-images.githubusercontent.com/17047142/34572703-020f7104-f1ad-11e7-8d29-c1e345613dfa.png)
![image](https://user-images.githubusercontent.com/17047142/34572715-0c018b8e-f1ad-11e7-90a1-1edd98d125c0.png)

**Comment by MoLice** [comment]
这个是 UIButton 分类的方法，不是 QMUIButton 的。由于根据代码规范，QMUI 拓展系统 UIKit 的方法，都必须加 `qmui_` 前缀以避免同名冲突，所以我们才有了这个修改，以前没前缀的方法命名是不规范的。

如果你依然想使用无前缀的方法，建议可以自行在业务项目里添加。
