### ISSUE TITLE
QMUIConfigurationTemplate 没有保证执行时机

### ISSUE THREAD

**Issue by MoLice** [QMUI/QMUI_iOS#264]
### 请填写运行环境

- [x] 设备：`模拟器`
- [x] 系统：`iOS 11.2`
- [x] Xcode 版本：`9.2`
- [x] QMUI iOS 版本：`2.2.2`

### 请描述具体问题

某些 QMUI 控件在用到配置表的值时配置表尚未初始化完成，导致控件的 UI 错误。

按照文档，目前 QMUI 的配置表使用时机是在项目的 `application:didFinishLaunchingWithOptions:` 里，但很多 QMUI 控件的 appearance 是在 `+ initialize` 里就使用配置表的值了，此时配置表尚未设置好，导致这时候的值错误。

**Comment by MoLice** [comment]
### 原因分析

之前配置表其实有一个隐性的要求，就是配置表的应用时机必须必任何使用配置表的时机都要早，但在代码设计层面我们并没有措施保证这一点，仅仅只是在文档里要求配置表在 `application:didFinishLaunchingWithOptions:` 里运行（我们认为这个时机已经足够早）。但其实很多 QMUI 控件会在自己的 `+initialize` 里使用配置表的值去设置 appearance，而这个时机不确定，可能比 `application:didFinishLaunchingWithOptions:` 要早，就会导致 appearance 的值错误。

### 解决方法

1. 配置表里的值的使用是从宏 `QMUICMI` 开始的，因此只要在 `QMUICMI` 被使用之前保证配置表的应用就行，于是我们把宏定义改为：
```Objective-C
#define QMUICMI ({[[QMUIConfiguration sharedInstance] applyInitialTemplate];[QMUIConfiguration sharedInstance];})
```
2. 由于 QMUI 自己保证配置表的执行时机，因此不需要使用者手动去调用了，因此将配置表改为自动运行。为此我们增加了 `QMUIConfigurationTemplateProtocol` 用于规定一份配置表应该具备的接口，并依靠“某个 class 是否有实现这个 protocol”来自动找到配置表的 class。

**Comment by AFlamen** [comment]
我使用的cocoPods安装但是导入QMUIConfigurationTemplate.h和.m文件后，@interface QMUIConfigurationTemplate : NSObject <QMUIConfigurationTemplateProtocol>报错No type or protocol named 'QMUIConfigurationTemplateProtocol'

**Comment by AFlamen** [comment]
我使用的cocoPods安装但是导入QMUIConfigurationTemplate.h和.m文件后，@interface QMUIConfigurationTemplate : NSObject <QMUIConfigurationTemplateProtocol>报错No type or protocol named 'QMUIConfigurationTemplateProtocol'

**Comment by MoLice** [comment]
你的 QMUIKit 并没有默认 import？没有的话请尝试在 `QMUIConfigurationTemplate.h` 顶部写上：
`#import <QMUIKit/QMUIKit.h>`

**Comment by AFlamen** [comment]
我的PrefixHeader.pch已经导入头文件了，奇怪的是我不把QMUIConfigurationTemplate.h和.m两个文件拖到我项目 Xcode 的 Project navigator 里，就能运行

**Comment by MoLice** [comment]
@AFlamen 你这样的操作是没问题的，方便的话请将示例项目打包 zip 发给 qmuiteam@qq.com 我们看看？

**Comment by MoLice** [comment]
@tbfungeek 以我们的项目为例，总 Class 数量为 27808 个，遍历到第 888 个文件即找到配置表，整个过程耗时 0.06秒，基本忽略不计。

以上测试结果基于 iPhone 7，iOS 11.4。

另外有个小技巧，如果担心极限情况下遍历到 27807 个文件时才找到配置表，那么你可以在你项目的 `Build Phases->Compile Sources` 里找到你自己的 `QMUIConfigurationTemplate.m`，把它拖到列表的最底部，即可让它优先被遍历到，不过这步优化带来的收益更多可能是心理层面的。

**Comment by tbfungeek** [comment]
@MoLice 谢谢

**Comment by JianRuHong** [comment]
有一个疑惑，我仅仅把QMUIKit框架拖入到项目中，运行App后，就会自动调用QMUIConfiguration的sharedInstance单例方法。我打断点进行测试，发现该方法执行是在main函数之后，又在didFinishLaunchingWithOptions方法之前。这个实现原理是什么呀？我没做过任何引入头文件，或者使用框架的任何代码，仅仅就是拖入项目中，看源码也没看明白。。。

**Comment by jiasongs** [comment]
> 有一个疑惑，我仅仅把QMUIKit框架拖入到项目中，运行App后，就会自动调用QMUIConfiguration的sharedInstance单例方法。我打断点进行测试，发现该方法执行是在main函数之后，又在didFinishLaunchingWithOptions方法之前。这个实现原理是什么呀？我没做过任何引入头文件，或者使用框架的任何代码，仅仅就是拖入项目中，看源码也没看明白。。。

可以找一下 +(void)load 方法的资料看看

**Comment by MoLice** [comment]
> 您好 QMUIConfiguration applyInitialTemplate 这个方法会便利整个项目的所有类 如果整个项目类文件很多的时候这个遍历会不会很耗时会不会影响性能？
> 
> Protocol *protocol = @protocol(QMUIConfigurationTemplateProtocol);
> int numberOfClasses = objc_getClassList(NULL, 0);
> if (numberOfClasses > 0) {
> Class *classes = (__unsafe_unretained Class *)malloc(sizeof(Class) * numberOfClasses);
> numberOfClasses = objc_getClassList(classes, numberOfClasses);
> for (int i = 0; i < numberOfClasses; i++) {
> Class class = classes[i];
> // 这里用 containsString 是考虑到 Swift 里 className 由“项目前缀+class 名”组成，如果用 hasPrefix 就无法判断了
> if ([NSStringFromClass(class) containsString:@"QMUIConfigurationTemplate"] && [class conformsToProtocol:protocol]) {
> if ([class instancesRespondToSelector:@selector(shouldApplyTemplateAutomatically)]) {
> id template = [[class alloc] init];
> if ([template shouldApplyTemplateAutomatically]) {
> QMUI_hasAppliedInitialTemplate = YES;
> [template applyConfigurationTemplate];
> // 只应用第一个 shouldApplyTemplateAutomatically 的主题
> break;
> }
> }
> }
> }
> free(classes);
> }

@tbfungeek  关于这里的性能问题，可以查看这个评论 https://github.com/Tencent/QMUI_iOS/issues/685#issuecomment-564577633，我们做了优化。

**Comment by boztrail** [comment]
模板自动查找是不是可以支持下动态库，目前看模块的定义放在动态库里的话是查找不到的，因为class的遍历只遍历了main bundle。 @MoLice

**Comment by darvintang** [comment]
新建的swift项目，导入之后导航栏自定义代码无效
配置项太多，根本没有一个可参考的说明
正准备解耦删除QMUIKit

**Comment by MoLice** [comment]
> 新建的swift项目，导入之后导航栏自定义代码无效 配置项太多，根本没有一个可参考的说明 正准备解耦删除QMUIKit

@darvintang 每个配置项都带一句注释，同时提供 QMUI Demo 作为实际示范项目，都做到这样了，还被你认为“没有一个可参考的说明”嘛？或者你也可以展示一下符合你预期的参考说明是什么样的，互相学习😁

**Comment by darvintang** [comment]
@MoLice  swift项目里怎么配置都不生效，代码hook太多，功能太多，配置项太多

**Comment by MoLice** [comment]
> @MoLice swift项目里怎么配置都不生效，代码hook太多，功能太多，配置项太多

@darvintang 如果不 hook 那么多，你用起来就会说太麻烦，每个小功能都要写一堆代码才能用上。
如果功能不多，你就会说这个库没啥用，我自己实现也一样。
如果配置项不多，你就会说一点都不灵活，什么都改不了。

好难，你来写一个功能强大的同时使用起来语句又很少的库借鉴一下吧。

**Comment by XMSECODE** [comment]
请填写运行环境
 设备：真机
 系统：iOS 18.2
 Xcode 版本：16.2
 QMUI iOS 版本：4.4.0
请描述具体问题
        NSAssert(NO, @"如果你看到这条提示，建议到 GitHub 上提 issue，让我们联系你查看项目的配置表使用情况，否则请注释掉这一行。");
在这一行崩溃

**Comment by MoLice** [comment]
> 请填写运行环境 设备：真机 系统：iOS 18.2 Xcode 版本：16.2 QMUI iOS 版本：4.4.0 请描述具体问题 NSAssert(NO, @"如果你看到这条提示，建议到 GitHub 上提 issue，让我们联系你查看项目的配置表使用情况，否则请注释掉这一行。"); 在这一行崩溃

<img width="1131" alt="image" src="https://github.com/user-attachments/assets/4444fdcd-13f9-49f6-b211-29cbb65a68a6" />
@XMSECODE
