### ISSUE TITLE
QMUINavigationController 的代理怎么重新指定?

### ISSUE THREAD

**Issue by Baichenghui** [QMUI/QMUI_iOS#265]
在控制器设置self.navigationController.delegate = self;没用

**Comment by zhoon** [comment]
@Baichenghui 没用的表现是怎样的？你预期是要用来做什么？

**Comment by Baichenghui** [comment]
我设置代理做转场动画，代理方法不走：
- (id<UIViewControllerAnimatedTransitioning>)navigationController:(UINavigationController *)navigationController animationControllerForOperation:(UINavigationControllerOperation)operation fromViewController:(UIViewController *)fromVC toViewController:(UIViewController *)toVC

**Comment by zhoon** [comment]
现在确实有点问题，我看看怎么改。

**Comment by Baichenghui** [comment]
谢谢，麻烦了 baichenghui88888 邮箱：baichenghui88888@gmail.com 签名由 网易邮箱大师 定制 在2018年01月09日 10:40，__粽子 写道： 现在确实有点问题，我看看怎么改。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by MoLice** [comment]
已在 [2.6.0](https://github.com/QMUI/QMUI_iOS/releases/tag/2.6.0) 版本修复。
