### ISSUE TITLE
QMUITextField使用直接崩溃

### ISSUE THREAD

**Issue by zhouxiao87315** [QMUI/QMUI_iOS#266]
### 请填写运行环境

- [x] 设备：模拟器、真机 均测试
- [x] 系统：`iOS 11.x` iOS 10.0 都测试
- [x] Xcode 版本：`9.2`
- [x] QMUI iOS 版本：`2.2.2`

使用QMUIDemo没有问题。在项目中使用直接崩溃。

![1515123723047](https://user-images.githubusercontent.com/7037928/34594676-795e8b5e-f20d-11e7-8c80-f3c954012cad.jpg)
![1515123822827](https://user-images.githubusercontent.com/7037928/34594712-b4ee9470-f20d-11e7-9c9e-e1365f173a14.jpg)

**Comment by zhoon** [comment]
请参考 https://github.com/QMUI/QMUI_iOS/issues/235 和 https://github.com/QMUI/QMUI_iOS/issues/235

**Comment by MoLice** [comment]
2.5.0 版本已兼容 BlocksKit。
