### ISSUE TITLE
QMUIHelper文件会报错

### ISSUE THREAD

**Issue by yangweiguang** [QMUI/QMUI_iOS#267]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.2.2`

### 请描述具体问题
QMUIHelper文件会报错
改Bundle为QBundle之后，错误就会好了

#### 相关截图（断点的堆栈、控制台的 log）
![image](https://user-images.githubusercontent.com/8114763/34636441-7081c3e6-f2dc-11e7-95bb-eb8e0e44960e.png)

**Comment by MoLice** [comment]
QMUI 代码是可以正常编译的。

请尝试 clean project，或者提供更多详细信息辅助定位问题。
