### ISSUE TITLE
QMUITextField无法输入

### ISSUE THREAD

**Issue by CoderDwang** [QMUI/QMUI_iOS#269]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`任何环境
`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题
QMUITextfield无法输入除数字之外的任何内容，

#### 相关截图（断点的堆栈、控制台的 log）
![default](https://user-images.githubusercontent.com/15830996/34657161-91763e28-f45e-11e7-97e1-510bbb1d1eb4.gif)

**Comment by MoLice** [comment]
能否贴一下这个 textField 的 init 相关代码？

**Comment by CoderDwang** [comment]
![snip20180108_98](https://user-images.githubusercontent.com/15830996/34657481-606507e4-f461-11e7-8936-908fc57e44c1.png)

**Comment by MoLice** [comment]
业务代码的问题
