### ISSUE TITLE
qmui_layoutSublayersOfLayer 错误

### ISSUE THREAD

**Issue by heyz-lzj** [QMUI/QMUI_iOS#27]
### 运行环境 ###

- [x] iOS 设备：`iPhone6s` and `模拟器`
- [x] 系统版本：`iOS 10.1`
- [x] Xcode 版本：`8.2`
- [x] QMUI iOS 版本：`1.1.4`

### 具体问题描述 ###
在搞tableview 的时候
- (void)qmui_layoutSublayersOfLayer:(CALayer *)layer {
    
    [self qmui_layoutSublayersOfLayer:layer];
    
    if (self.qmui_borderPosition == QMUIBorderViewPositionNone) {
        return;
    }
#### 问题截图 ####
[self qmui_layoutSublayersOfLayer:layer];这里出现了莫名的错误
BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3599.6.1/UITableView.m:8035

重新继承UITableView 也会出现相同错误

**Comment by MoLice** [comment]
这个方法是私有的，不应该继承重写。你是需要做什么需求？

**Comment by zhoon** [comment]
是不是只是breakpoint而已？

**Comment by hstdt** [comment]
我遇到了一种情况.

比如你创建了XXXViewController.swift以及XXXViewController.xib,同时xib中有Outlet发生了错误的连接,实际上你并没有使用nibname方法.

但是,就算你把xib文件放在那里不管都不行,比如在下图,你把XXXViewController中的tableView属性删除了.

![image](https://cloud.githubusercontent.com/assets/10215098/23859979/806be782-0840-11e7-8581-aab1de22587e.png)

就会崩.(打开断点之后就挂了)

![image](https://cloud.githubusercontent.com/assets/10215098/23860303/863a7a6a-0841-11e7-9bae-50ceceaa97bd.png)

**Comment by Sky0372Lsk** [comment]
这个问题怎么解决？为什么关闭了？
