### ISSUE TITLE
QMUIDialogTextFieldViewController创建的界面,取消和确认按钮均不可见,

### ISSUE THREAD

**Issue by m13026178198** [QMUI/QMUI_iOS#270]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.2`
- [x] QMUI iOS 版本：`2.2.2`

### 请描述具体问题
使用QMUIDialogTextFieldViewController,创建的界面,取消和确认按钮均不可见,
`- (void)showQMUIDialogTextFieldView {
    QMUIDialogTextFieldViewController *dialogViewController = [[QMUIDialogTextFieldViewController alloc] init];
    dialogViewController.title = @"请输入昵称";
    dialogViewController.textField.delegate = self;
![simulator screen shot - iphone x - 2018-01-08 at 20 33 34](https://user-images.githubusercontent.com/11539098/34671169-709a8230-f4b4-11e7-94eb-0cff2cfd6333.png)

    dialogViewController.textField.placeholder = @"昵称";
    dialogViewController.textField.maximumTextLength = 16;
    [dialogViewController addCancelButtonWithText:@"取消" block:nil];
    self.currentTextFieldDialogViewController = dialogViewController;
    [dialogViewController addSubmitButtonWithText:@"确定" block:^(QMUIDialogViewController *dialogViewController) {
        [dialogViewController hide];
    }];
    [dialogViewController show];
}`
#### 相关截图（断点的堆栈、控制台的 log）
见截图

**Comment by MoLice** [comment]
QMUI 2.2.2 版本里 `QMUIDialogViewController` 新增的 `buttonBackgroundColor` 属性默认值被错误地设置为与文字颜色相同的 `UIColorBlue`，所以看不到按钮文字了。我们刚好正在发 `2.3.0`版本，稍后即可更新版本重试，在此之前你可以手动将 `buttonBackgroundColor` 改为 `nil` 或者 `UIColorClear` 避免这个问题。

**Comment by DogTwoChen** [comment]
请问取消按钮cancleButton的字体颜色如何单独修改
