### ISSUE TITLE
cocopod版本更新

### ISSUE THREAD

**Issue by m13026178198** [QMUI/QMUI_iOS#271]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题
我们的项目中普遍使用cocopod集成QMUI,能否辛苦你们更新一下cocopod版本呢?

#### 相关截图（断点的堆栈、控制台的 log）
![2018-01-09 9 03 26](https://user-images.githubusercontent.com/11539098/34700084-fcd0bf3c-f51b-11e7-92f2-487ba0b0cd42.png)

**Comment by zhoon** [comment]
请问你说的更新cocopod版本是否指更新cocopod这个工具的版本？还是QMUI的版本？

**Comment by m13026178198** [comment]
现在的cocospod能搜索到的QMUI的版本还是2.2.2的版本,为了使用最新的版本,我已经采用了其他的方式集成了.

**Comment by MoLice** [comment]
昨晚本来要更新，内网网络有问题所以早上才更新了，你现在应该可以搜到2.3.0了，哈哈
