### ISSUE TITLE
关于 拆分多个库的建议

### ISSUE THREAD

**Issue by MineJ** [QMUI/QMUI_iOS#273]
QMUIKit 相对来说,还是比较好用的,但是 有些不需要的功能,或者不想使用到的 runtime 交换,会影响到一些方法的使用, SO 能否 拆分为多个 Cocoapods 库?这样也很方便使用

**Comment by zhoon** [comment]
QMUI支持子模块，能尽量避免不引用没有使用的功能代码，例如：
`pod 'QMUIKit/QMUIComponents/QMUIModalPresentationViewController'`
至于拆分为多个 Cocoapods 库，目前暂时没有考虑。

**Comment by MineJ** [comment]
OK
