### ISSUE TITLE
设置边框问题

### ISSUE THREAD

**Issue by LWHai** [QMUI/QMUI_iOS#274]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.2.2`

### 请描述具体问题
最近接手个老项目中接入了QMUI开发新的模块，但是发现用了Masonry 的页面每次进入都很卡，没用Masonry相对好些，还有就是只要设置border 属性就很卡。CPU老高...这是冲突吗？
_
![3e6310b1-805f-4764-bae8-f6b96affdb72](https://user-images.githubusercontent.com/9824642/35035786-55a01c9c-fbad-11e7-82f0-73a8f5a2e509.png)
_
//    self.qmui_borderWidth = PixelOne;
//    self.qmui_borderColor = UIColorSeparator;

#### 相关截图（断点的堆栈、控制台的 log）

**Comment by LWHai** [comment]
升级新版本没出现问题，不是冲突。

**Comment by MoLice** [comment]
也就是现在是没问题的吗？
