### ISSUE TITLE
FDFullscreenPopGesture 冲突

### ISSUE THREAD

**Issue by lubaoyilang** [QMUI/QMUI_iOS#275]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题
我们项目中 使用了 FDFullscreenPopGesture，当 滑动返回 上一个 controller时，如果滑动一半，取消滑动，此时，当前controller 中，不能push到 下一个controller了。提示 上一次界面切换的动画尚未结束就试图进行新的 push 操作。外部也没有 设置 isViewControllerTransiting标志位的地方

**Comment by MoLice** [comment]
isViewControllerTransiting 是内部使用的一个标志位，不提供外部修改。稍等，我们用 FDFullscreenPopGesture 测试一下看看。

**Comment by lubaoyilang** [comment]
@MoLice 肿么样？下个版本可以 改动下吗？

**Comment by MoLice** [comment]
这个问题是由于 `FDFullscreenPopGesture` 的界面切换策略与系统原生的不一致导致的。系统原生的手势返回在手势进行到一半又取消时，会重新触发当前界面的 `viewWillAppear:`，而 QMUI 也是在这个时机里把 `isViewControllerTransiting` 标志位重置，从而不会影响后续的界面切换操作，但 `FDFullscreenPopGesture` 在这种场景下并不会触发当前界面的 `viewWillAppear:`，所以标志位没有得到重置。

以下截图是使用系统原生手势返回时触发 `viewWillAppear:` 的堆栈信息。
![image](https://user-images.githubusercontent.com/1190261/35217975-ff9466b0-ffa7-11e7-978b-8f332a08b099.png)

下个版本我们可以把 `isViewControllerTransiting` 的保护做一个开关，业务自行决定是否要使用，至于其利弊衡量也是由业务自行决定。

下个版本预计在月底发布。

**Comment by MoLice** [comment]
https://github.com/QMUI/QMUI_iOS/releases/tag/2.4.0
