### ISSUE TITLE
iOS10环境下UITableVIew设置UITableViewAutomaticDimension无法自适应高度

### ISSUE THREAD

**Issue by Qph1059** [QMUI/QMUI_iOS#278]
### 请填写运行环境

- [x] 设备：`iPhone 6 真机`
- [x] 系统：`iOS 10.3.3`
- [x] Xcode 版本：`9.2`
- [x] QMUI iOS 版本：`2.3.0`

### 请描述具体问题
iOS11环境下自定义cell自适应高度显示正常，iOS10环境下自适应高度没有用，把QMUIKit删除后都显示正常

**Comment by MoLice** [comment]
能否给出更具体一点的信息，例如设置代码。

**Comment by Qph1059** [comment]
TableView的设置代码
self.tableView = [[UITableView alloc] initWithFrame:CGRectZero style:UITableViewStyleGrouped];
self.tableView.backgroundColor = [UIColor clearColor];
self.tableView.delegate = self;
self.tableView.dataSource = self;
self.tableView.tableFooterView = [[UIView alloc] init];
self.tableView.estimatedRowHeight = 80.0f;
self.tableView.rowHeight = UITableViewAutomaticDimension;
self.tableView.separatorStyle = UITableViewCellSeparatorStyleNone;
self.tableView.sectionFooterHeight = 10;
self.tableView.sectionHeaderHeight = 0;

自定义Cell中的布局代码：
-(void)setLayout {
    NSDictionary * views = NSDictionaryOfVariableBindings(_titleLabel, _contentLabel, _timeLabel, _iconImgView, _shareBtn, _likeBtn, _shareNumLabel, _likeNumLabel);
    NSDictionary * metrics = @{
                               @"space1" : @15,
                               @"space2" : @12,
                               @"space3" : @13,
                               @"space4" : @17,
                               @"space5" : @5,
                               @"space6" : @37,
                               @"space7" : @10,
                               @"space8" : @35.3
                               };
    [self.iconImgView autoSetSize:IconImgSize];
    [self.shareBtn autoSetSize:BtnSize];
    [self.likeBtn autoSetSize:BtnSize];
    
    [@[self.titleLabel, self.contentLabel, self.timeLabel] autoAlignWithType:LSAutoLayoutAlignLeft relatedView:self.titleLabel constant:0];
    [@[self.titleLabel, self.contentLabel, self.timeLabel] autoAlignWithType:LSAutoLayoutAlignRight relatedView:self.titleLabel constant:0];
    [@[self.iconImgView, self.likeNumLabel] autoAlignWithType:LSAutoLayoutAlignRight relatedView:self.iconImgView constant:0];
    [@[self.timeLabel, self.shareBtn, self.shareNumLabel, self.likeBtn, self.likeNumLabel] autoAlignWithType:LSAutoLayoutAlignCenterY relatedView:self.timeLabel constant:0];
    
    NSString * H01 = @"H:|-(space3)-[_titleLabel]-(space5)-[_iconImgView]-(space3)-|";
    NSString * H02 = @"H:[_shareBtn]-[_shareNumLabel]-(space1)-[_likeBtn]-[_likeNumLabel]";
    
    NSString * V01 = @"V:|-(space1)-[_titleLabel]-(space2)-[_contentLabel]";
    NSString * V02 = @"V:[_timeLabel]-(space4)-|";
    NSString * V03 = @"V:|-(space7)-[_iconImgView]-(space8)-|";
    [self.contentView autoAddConstraintsWithVisualFormatArray:@[H01, H02, V01, V02, V03] options:0 metrics:metrics views:views];
}

**Comment by wxlpp** [comment]
如果你用的是 CommonTableView  你需要在代理方法中返回 UITableViewAutomaticDimension
而不是 `self.tableView.rowHeight = UITableViewAutomaticDimension;`直接赋值.貌似是这样

**Comment by MoLice** [comment]
@wxlpp 应该是对的，因为 QMUICommonTableViewController 默认实现了 `tableView:heightForRowAtIndexPath:`，可能在 iOS 10 下它的优先级比 `tableView.rowHeight` 要高，导致你的那句 `self.tableView.rowHeight = UITableViewAutomaticDimension;` 并不生效。

**Comment by hanzhe94** [comment]
请问你解决了吗？

**Comment by Qph1059** [comment]
解决了 我把要用的功能单独拿了出来

发自我的 iPhone

在 2018年12月29日，04:00，hanzhe94 <notifications@github.com<mailto:notifications@github.com>> 写道：


请问你解决了吗？
