### ISSUE TITLE
请问iOS8 以上怎么使用cocoapods导入?

### ISSUE THREAD

**Issue by iOSCountry** [QMUI/QMUI_iOS#28]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by zhoon** [comment]
所有iOS版本都是一样的使用方法，cocoapods的具体使用方法请自行google搜索，网上很多资料

**Comment by iOSCountry** [comment]
@zhoon 
![wx20170111-093355](https://cloud.githubusercontent.com/assets/17453419/21831760/39294610-d7e1-11e6-9ba8-d6bd20b5e6e8.png)
我们的项目是iOS 8以上的,该怎么操作?

**Comment by zhoon** [comment]
因为iOS8是可以使用动态库的，你截图里面两个用法的区别就在于 use_frameworks! ，增加这个可以让pod生成一个动态的.framework，否则pod是不会生成动态.frameword的，那么你只能用默认的静态库.a文件，因为你是支持iOS8版本，所以两种方式都可以用，具体看你是选择用静态库还是动态库。

**Comment by iOSCountry** [comment]
@zhoon 具体看你是选择用静态库还是动态库,那弱弱的问一句,动态库和静态库那个更好?

**Comment by zhoon** [comment]
@iOSCountry 动态库使用上回更方便一些，可以省去一些配置操作，比如不需要吧QMUI的bundle文件拖到项目里面，也不用设置.h文件的查询路径等等，因为所有的资源文件都打包在.frameword里面了

**Comment by iOSCountry** [comment]
@zhoon 嗯嗯,查阅了一些资料,谢谢回复
