### ISSUE TITLE
pod 出来 还是2.1.0版本的 ，不是 2.3.0

### ISSUE THREAD

**Issue by datafu** [QMUI/QMUI_iOS#280]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

**Comment by MoLice** [comment]
update 一下你本地的 pod，不然它感知不到外界的更新。

**Comment by datafu** [comment]
确实如此
