### ISSUE TITLE
请问下可以添加  系统 UITabBarController 的基础上实现安卓版微信 TabBar 的滑动切换功能吗？

### ISSUE THREAD

**Issue by datafu** [QMUI/QMUI_iOS#281]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

**Comment by MoLice** [comment]
这种偏业务，不太通用，应该不会考虑。
