### ISSUE TITLE
使用过扫描二维码界面后，停留时间过长返回时就会闪退

### ISSUE THREAD

**Issue by YyItRoad** [QMUI/QMUI_iOS#282]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
Iphone 6s
- [x] 系统：`iOS 11.x`
IOS 10.3.3
- [x] Xcode 版本：`9.x`
9.2
- [x] QMUI iOS 版本：`2.x.x`
2.3.0

### 请描述具体问题
扫描二维码多次失败后，停留时间过长后（>1分钟）就会闪退

#### 相关截图（断点的堆栈、控制台的 log）
*** Assertion failure in void UIViewReportBrokenSuperviewChain(UIView *__strong, UIView *__strong, BOOL)(), /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3600.9.1/UIView.m:189
2018-02-08 10:08:14.116682+0800 CallBox[3333:1353056] [Bugly]  Trapped uncaught exception 'NSInternalInconsistencyException', reason: 'View has lost track of its superview, most likely through unsupported use of CALayer API on the view's layer. If this isn't a crash yet, it will be in the near future. 
	Problem view: <UIImageView: 0x10138f420; frame = (28.125 245.08; 318.75 12); opaque = NO; userInteractionEnabled = NO; animations = { position=<CABasicAnimation: 0x17023ddc0>; }; layer = <CALayer: 0x17003cfc0>>
	Expected parent: <UIView: 0x101478b60; frame = (0 0; 375 667); autoresize = W+H; tintColor = UIExtendedSRGBColorSpace -0.249182 0.521112 0.88113 1, RGBA(-63, 132, 224, 1.00), #ff-3-1584e0; gestureRecognizers = <NSArray: 0x17444f8d0>; layer = <CALayer: 0x174038660>>
Break on UIViewReportBrokenSuperviewChain to debug.' 
(
	0   CoreFoundation                      0x000000018a0baff8 <redacted> + 148
	1   libobjc.A.dylib                     0x0000000188b1c538 objc_exception_throw + 56
	2   CoreFoundation                      0x000000018a0baeb4 <redacted> + 0
	3   Foundation                          0x000000018ab537cc <redacted> + 88
	4   UIKit                               0x00000001904c91c8 UIViewReportBrokenSuperviewChain + 468
	5   UIKit                               0x00000001904c9844 _UIViewTopDownSubtreeTraversal + 1416
	6   UIKit                               0x0000000190b4ed28 <redacted> + 140
	7   UIKit                               0x0000000190b4eeec <redacted> + 48
	8   UIKit                               0x00000001901e8564 <redacted> + 200
	9   UIKit                               0x00000001901e8394 <redacted> + 788
	10  UIKit                               0x00000001901f42ac <redacted> + 1740
	11  UIKit                               0x00000001901f3bc8 <redacted> + 828
	12  QMUIKit                             0x0000000100e795cc -[UIView(QMUI_Debug) qmui_debug_addSubview:] + 420
	13  UIKit                               0x00000001903ccdf0 <redacted> + 180
	14  UIKit                               0x00000001901e92b8 <redacted> + 1288
	15  UIKit                               0x00000001901e906c <redacted> + 700
	16  UIKit                               0x00000001901e8538 <redacted> + 156
	17  UIKit                               0x00000001901e8394 <redacted> + 788
	18  UIKit                               0x00000001901f42ac <redacted> + 1740
	19  UIKit                               0x00000001901f3bc8 <redacted> + 828
	20  QMUIKit                             0x0000000100e795cc -[UIView(QMUI_Debug) qmui_debug_addSubview:] + 420
	21  UIKit                               0x000000019045f054 <redacted> + 1640
	22  UIKit                               0x00000001901fa964 <redacted> + 104
	23  UIKit                               0x00000001903cc950 <redacted> + 260
	24  UIKit                               0x00000001904e9388 <redacted> + 220
	25  UIKit                               0x00000001903cc450 <redacted> + 1060
	26  UIKit                               0x0000000190389818 <redacted> + 3704
	27  UIKit                               0x00000001902a37bc <redacted> + 676
	28  UIKit                               0x00000001902a3424 <redacted> + 64
	29  UIKit                               0x00000001902a3388 <redacted> + 188
	30  UIKit                               0x00000001901e9cc0 <redacted> + 1200
	31  QMUIKit                             0x0000000100e79bec -[UIView(QMUI_Border) qmui_layoutSublayersOfLayer:] + 84
	32  QuartzCore                          0x000000018d3da274 <redacted> + 148
	33  QuartzCore                          0x000000018d3cede8 <redacted> + 292
	34  QuartzCore                          0x000000018d3ceca8 <redacted> + 32
	35  QuartzCore                          0x000000018d34a34c <redacted> + 252
	36  QuartzCore                          0x000000018d3713ac <redacted> + 504
	37  QuartzCore                          0x000000018d371e78 <redacted> + 120
	38  CoreFoundation                      0x000000018a0689a8 <redacted> + 32
	39  CoreFoundation                      0x000000018a066630 <redacted> + 372
	40  CoreFoundation                      0x000000018a066a7c <redacted> + 956
	41  CoreFoundation                      0x0000000189f96da4 CFRunLoopRunSpecific + 424
	42  GraphicsServices                    0x000000018ba01074 GSEventRunModal + 100
	43  UIKit                               0x0000000190251c9c UIApplicationMain + 208
	44  CallBox                             0x00000001000aab30 main + 124
	45  libdyld.dylib                       0x0000000188fa559c <redacted> + 4
)
[3333:1353056] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'View has lost track of its superview, most likely through unsupported use of CALayer API on the view's layer. If this isn't a crash yet, it will be in the near future. 
	Problem view: <UIImageView: 0x10138f420; frame = (28.125 245.08; 318.75 12); opaque = NO; userInteractionEnabled = NO; animations = { position=<CABasicAnimation: 0x17023ddc0>; }; layer = <CALayer: 0x17003cfc0>>
	Expected parent: <UIView: 0x101478b60; frame = (0 0; 375 667); autoresize = W+H; tintColor = UIExtendedSRGBColorSpace -0.249182 0.521112 0.88113 1, RGBA(-63, 132, 224, 1.00), #ff-3-1584e0; gestureRecognizers = <NSArray: 0x17444f8d0>; layer = <CALayer: 0x174038660>>
Break on UIViewReportBrokenSuperviewChain to debug.'
*** First throw call stack:
(0x18a0bafe0 0x188b1c538 0x18a0baeb4 0x18ab537cc 0x1904c91c8 0x1904c9844 0x190b4ed28 0x190b4eeec 0x1901e8564 0x1901e8394 0x1901f42ac 0x1901f3bc8 0x100e795cc 0x1903ccdf0 0x1901e92b8 0x1901e906c 0x1901e8538 0x1901e8394 0x1901f42ac 0x1901f3bc8 0x100e795cc 0x19045f054 0x1901fa964 0x1903cc950 0x1904e9388 0x1903cc450 0x190389818 0x1902a37bc 0x1902a3424 0x1902a3388 0x1901e9cc0 0x100e79bec 0x18d3da274 0x18d3cede8 0x18d3ceca8 0x18d34a34c 0x18d3713ac 0x18d371e78 0x18a0689a8 0x18a066630 0x18a066a7c 0x189f96da4 0x18ba01074 0x190251c9c 0x1000aab30 0x188fa559c)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by MoLice** [comment]
这个好像跟 QMUI 没关系？
