### ISSUE TITLE
swift中如何使用QMUIConfigurationTemplate

### ISSUE THREAD

**Issue by limuyang2** [QMUI/QMUI_iOS#283]
### 请填写运行环境

- [x] 设备：`iPhone`
- [x] 系统：`iOS 11.2`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.4.0`

### 请描述具体问题
请问在swift中如何使用？需要桥接文件么？
能给个范例么？

**Comment by 1284115201** [comment]
我也想问，你解决了吗

**Comment by wxlpp** [comment]
@limuyang2 两种解决方法，一种把QMUIConfigurationTemplate的 OC  文件拖过来做桥接。另外一种用Swift 自己写。用 Swift自己写的话，由于 Swift 的命名空间问题，目前不支持自动搜索配置文件，这个问题我已经提了，也已改了。估计在下个版本发布内。我现在是用 Swift 自己写一遍，然后在didFinishLaunchingWithOptions 中手动应用。下个版本预计可以将手动应用代码去掉

**Comment by MoLice** [comment]
感谢@wxlpp 解答
