### ISSUE TITLE
自定义 TitleVIew 无法正确的设置 self.titleView 的大小；

### ISSUE THREAD

**Issue by Ccmi** [QMUI/QMUI_iOS#284]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题
自定义 TitleVIew 无法正确的设置 self.titleView 的大小，导致自定义视图位置偏移,希望可以解答一下如何在使用 QMUINavigationController 作为基类的情况下设置自定义 titleVIew 方式

**Comment by MoLice** [comment]
猜测你指的“自定义 titleView 的大小”是类似 `self.titleView.frame = xxx` 的做法？按 `QMUINavigationTitleView` 目前的实现，大小是由内容决定的，所以手动修改 frame 是无效的。
如果要限制最大宽度，可以使用 `maximumWidth` 属性。

**Comment by Ccmi** [comment]
请问如果我有一个自定义大小的视图，需要加到 titleVIew 上，并且视图可以交互，正确的方式是什么呢？

**Comment by MoLice** [comment]
如果你这个要额外加上的 view 需要与 titleView 原有的其他 subview 一起并存使用的话，通常是用继承子类的方式来实现，不过 `QMUINavigationTitleView` 的代码设计存在一些问题，导致继承子类时可能不太方便，有些运算结果没有开放出来，继承子类时无法复用那部分的代码。这个问题我们已经在优化，在完成优化之前可能继承起来比较麻烦。

如果不需要和其他 subview 一起并存，那么直接创建一个新的 titleView，以 `vc.navigationItem.titleView = xxx` 的方式将你的 view 当成 titleView 使用即可。这就与 QMUI 无关了，是 UIKit 自身的功能。
