### ISSUE TITLE
麻烦发下二维码，项目基于QMUI框架开发，有些细节希望及时沟通 744520665@qq.com,3Q

### ISSUE THREAD

**Issue by GoodLuckBobe** [QMUI/QMUI_iOS#286]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

**Comment by MoLice** [comment]
已发
