### ISSUE TITLE
快速点击俩次按钮，闪退

### ISSUE THREAD

**Issue by random496** [QMUI/QMUI_iOS#288]
### 请填写运行环境
自己的项目里集成了qmui，当快速点击俩次按钮要push或者pop的时候，会闪退。必现。。
- [x] 设备：`iPhone``
- [x] 系统：`测试了11.0的系统，9.2.1的系统`
- [x] Xcode 版本：`9。2`
- [x] QMUI iOS 版本：`最新版`

### 请描述具体问题

[#### 相关截图（断点的堆栈、控制台的 log）
![1520852774739](https://user-images.githubusercontent.com/18606030/37280590-2d826822-2629-11e8-9a32-2980084d0a76.jpg)

**Comment by MoLice** [comment]
看目前提供的信息和截图，无法得出什么结论。能否有更进一步的补充？例如 crash 后控制台输出的 log 内容，或者发一下测试 demo 看看。
