### ISSUE TITLE
继承QMUICommonViewController后，没法添加titleView

### ISSUE THREAD

**Issue by halfrisk** [QMUI/QMUI_iOS#289]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题
继承
下面的代码将无效，导航栏中没法显示搜索栏
- (void)viewDidLoad {
    [super viewDidLoad];
//    self.view.backgroundColor = [UIColor whiteColor];
    //给导航添加搜索框
    UISearchBar *searchBar = [[UISearchBar alloc] init];
    self.navigationItem.titleView = searchBar;
    searchBar.placeholder = @"搜索";
    searchBar.delegate = self;    
}

**Comment by MoLice** [comment]
QMUICommonViewController 对 navigationItem 的操作都在 setNavigationItemInEditMode 里，而这个方法的调用时机在 viewWillAppear，所以覆盖了你的 viewDidLoad 里的操作。建议按照规范，把你这段代码放到 setNavigationItemInEditMode 里即可。
