### ISSUE TITLE
QMUIOrderedDictionary可否提供使用字典初始化，现在只有一种初始化方式，很不方便。我从网络获取了配置信息，没法塞到QMUIOrderedDictionary中，它只能键值初始化。

### ISSUE THREAD

**Issue by dudongdaoqi** [QMUI/QMUI_iOS#290]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

**Comment by MoLice** [comment]
字典初始化是指？意思是传入一个 `NSDictionary`，输出为一个 `QMUIOrderedDictionary`？

**Comment by MoLice** [comment]
如果希望“传入一个 NSDictionary，输出为一个 QMUIOrderedDictionary”的话，由于 dictionary 本身已经无序了，所以无法保证输出的 QMUIOrderedDictionary 的顺序，所以做不到。

如果是希望直接用类似 @{} 格式的字面量来初始化一个 QMUIOrderedDictionary，目前做不到，语言本身的限制。但我们确实希望能做得到，哈哈。
