### ISSUE TITLE
QMUIMultipleDelegates 替换方法会导致父类及父类的所有子类都被替换

### ISSUE THREAD

**Issue by MoLice** [QMUI/QMUI_iOS#292]
### 请填写运行环境

- [x] 设备：`模拟器`
- [x] 系统：`iOS 11.2`
- [x] Xcode 版本：`9.2`
- [x] QMUI iOS 版本：`2.5.0`

### 请描述具体问题

在 [NSObject+QMUIMultipleDelegates.m:54-103](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/QMUIComponents/QMUIMultipleDelegates/NSObject%2BQMUIMultipleDelegates.m#L54-L103) 里对当前的 class 进行了方法替换，而由于类继承的设定，这里获取到的要被替换的方法有可能是父类的，所以后面继续进行的替换方法的操作会把父类以及父类的所有子类也替换了，导致出现预期外的行为。

例如，你原本想替换的是 `[UITextView setDelegate:]` 方法，但实际上替换的是 `[UIScrollView setDelegate:]`，于是 `[UITableView setDelegate:]` 和 `[UICollectionView setDelegate:]` 也会被替换，因为它们都是 UIScrollView 的子类。

**Comment by MoLice** [comment]
解决方式：
在最终被替换成的方法被调用时，要自己加一下 class 的判断保护，保证只有 self.class 及 self.superclass 才执行。

以上面的例子为例，也即，保证只有 `UITextView` 及 `UITextView` 的子类才执行，其他的都使用原方法的实现。

**Comment by MoLice** [comment]
发了 2.5.1 小版本修复这个问题。

**Comment by MoLice** [comment]
2.6.1 发现另一个问题：
`QMUINavigationController` 默认打开了 `qmui_multipleDelegatesEnabled`，而如果你创建一个子类 `@interface QMUINavigationController2 : QMUINavigationController`，再创建一个 2 的子类 `@interface QMUINavigationController3 : QMUINavigationController2`，在这两个子类里什么都不用做，就会发现 `QMUINavigationController3` 的 delegate 丢失了，然后界面也无法 push。

这个问题是因为虽然 2 和 3 没有做什么，但在 `NSObject (QMUIMultipleDelegates)` 里依然会给 2 和 3 分别创建单独的 setDelegate block，于是在 3 的 setDelegate 里，设置真正 block 之前先置为 nil 的那一步会走到 2 的 setDelegate block，导致把 delegates 容器清空。

**Comment by MoLice** [comment]
2.6.2 版本已修复此问题。

**Comment by wanhmr** [comment]
总觉得这不是个大众需求，每个类单独写也可以。

**Comment by MoLice** [comment]
你是指 QMUI 那些 class 可以默认不开启 `qmui_multipleDelegatesEnabled` 吗？
