### ISSUE TITLE
push后出现两个返回箭头

### ISSUE THREAD

**Issue by halfrisk** [QMUI/QMUI_iOS#293]
### 请填写运行环境

- [x] 设备：`iPhone 6s`
- [x] 系统：`iOS 11.3`
- [x] Xcode 版本：`9.3`
- [x] QMUI iOS 版本：`2.5.1`

### 请描述具体问题
push后出现两个返回箭头，目前在ios 11上出现，有什么方案解决？而ios 10，ios 9都是正常
#### 相关截图（断点的堆栈、控制台的 log）

![image](https://user-images.githubusercontent.com/19650796/38164644-0043b5c6-353a-11e8-8b6d-caac6c1787b4.png)

**Comment by halfrisk** [comment]
1、没有使用自定义返回按钮图片。
2、所有页面都是这个现象。
说明：有一个页面引入GitHub一个组件后出现这个现象
[https://github.com/wangmchn/WMPageController](url)
#import <UIKit/UIKit.h>
#import <WMPageController/WMPageController.h>

@interface MessageViewController : WMPageController

@end

**Comment by MoLice** [comment]
按目前提供的信息暂时无法判断是怎么回事，另外url 404了。

QMUI 大量使用的过程中尚未发现有这种问题，建议最好能先自行界定问题的根源，例如确实与某个第三方框架冲突？是第三方框架代码的问题还是QMUI的问题？或者是业务某些代码的问题？如果是 QMUI 的问题我们继续跟进。

**Comment by halfrisk** [comment]
找到问题的地方了，是由于引入别人的框架，自定义了导航引入这个问题的。
