### ISSUE TITLE
QMUISearchController -searchBar 下移

### ISSUE THREAD

**Issue by liuweixingGitHub** [QMUI/QMUI_iOS#295]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 10.3.`
- [x] Xcode 版本：`9.3`
- [x] QMUI iOS 版本：`2.5.1

### 请描述具体问题

1. 集成 `QMUISearchController`，可通过属性 `shouldShowSearchBar` 来快速为列表生成一个 searchBar 及 searchController，具体请查看 QMUICommonTableViewController (Search)。

搜索输入文字后,再取消搜索, searchBar 会无限制往下移动,
这个需要自己控制吗?

#### 相关截图（断点的堆栈、控制台的 log）
![img_0406](https://user-images.githubusercontent.com/18339649/38317393-91db0d72-385f-11e8-8492-adbedaaad83a.PNG)

**Comment by MoLice** [comment]
是不是与 #124 重复？

**Comment by liuweixingGitHub** [comment]
确实是重复问题
