### ISSUE TITLE
如何结合QDPopupContainerViewController中案例实现QQ中popover的效果？

### ISSUE THREAD

**Issue by halfrisk** [QMUI/QMUI_iOS#296]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题
点击self.navigationItem.rightBarButtonItem，出现如图效果，看demo有点迷糊
#### 相关截图（断点的堆栈、控制台的 log）
![image](https://user-images.githubusercontent.com/19650796/38344443-32c7f806-38bc-11e8-9c94-9405cca3ef32.png)

**Comment by MoLice** [comment]
`QMUIPopupContainerView` 需要参照某个 UIView 或者某个 CGRect 去布局，所以你这个需求的本质就是：
1. 先获取 `rightBarButtonItem` 的 view。
2. 初始化一个 `QMUIPopupMenuView` 然后基于步骤 1 里的 view 布局。
3. show 出来。

获取 `UIBarButtonItem` 的 view，简单搜搜就能知道，可以通过 `[barButtonItem valueForKey:@"view"]` 的方式获取。

**Comment by MoLice** [comment]
另外，Demo第三个tab最后一个cell，Log Manager里就有这种场景，可以参考。

**Comment by shuiliang** [comment]
请问QMUIPopupMenuView 选中后 选中项文字高亮状态怎么设置？
![image](https://user-images.githubusercontent.com/17922774/59014151-760f3900-886e-11e9-806c-bb764119cc1d.png)

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/59179836-d87d7780-8b95-11e9-8868-f2cec26516d6.png)

按照普通 UIButton 的方式去处理即可。
