### ISSUE TITLE
UINavigationController+QMUI 反馈

### ISSUE THREAD

**Issue by liuweixingGitHub** [QMUI/QMUI_iOS#297]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 10.3`
- [x] Xcode 版本：`9.3`
- [x] QMUI iOS 版本：`2.5.1`

### 请描述具体问题
 - (IBAction)buttonAction:(id)sender {
    
     NSLog(@"buttonAction");
    AAViewController *vc = [[AAViewController alloc]init];
    [self.navigationController pushViewController:vc animated:YES];
}

1.push时,就会奔溃,显示如下代码位置 (测试出与我项目的工具类代码冲突)

2.与GitHub中 UINavigationController+TZPopGesture 这个第三方有点冲突,会影响侧滑返回失效,按钮返回正常,或者QMUI有该功能的方法吗?

#### 相关截图（断点的堆栈、控制台的 log）
![default](https://user-images.githubusercontent.com/18339649/38347579-e357a6be-38ce-11e8-873b-74fff97bfe29.png)

**Comment by MoLice** [comment]
估计是有其他第三方项目冲突了，由目前的信息，无法得到更有效的解决方式。
