### ISSUE TITLE
用bugly统计线上崩溃，崩溃到[UIView(QMUI_Border) qmui_layoutSublayersOfLayer:]这里

### ISSUE THREAD

**Issue by guojuzheng** [QMUI/QMUI_iOS#299]
### 请填写运行环境

- [x] 设备：iPhone6，iPhone6s
- [x] 系统：`iOS 9.x`
- [x] Xcode 版本：`9.1`
- [x] QMUI iOS 版本：`2.1.0`

**Comment by MoLice** [comment]
请贴具体的堆栈，不然根据目前给到的信息，无法得出任何结论。
另外，建议再仔细查看一下堆栈，猜测仅仅只是因为 QMUI 重写了 layoutSublayersOfLayer 所以出现在堆栈里而已，真正的崩溃原因和这个无关。

**Comment by guojuzheng** [comment]
SEGV_ACCERR
libobjc.A.dylib | objc_msgSend + 28
-- | --
1 CoreFoundation | CFEqual + 340
2 CoreFoundation | ___NSCacheKeyEqual + 12
3 libcache.dylib | __entry_get_optionally_checking_collisions + 164
4 libcache.dylib | cache_get_and_retain + 132
5 CoreFoundation | -[NSCache objectForKey:] + 68
6 CoreUI | -[CUIStructuredThemeStore _canGetRenditionWithKey:isFPO:lookForSubstitutions:]+ 360
7 CoreUI | +[CUICatalog _resolvedRenditionKeyFromThemeRef:withBaseKey:scaleFactor:deviceIdiom:deviceSubtype:sizeClassHorizontal:sizeClassVertical:memoryClass:graphicsClass:graphicsFallBackOrder:] + 1204
8 CoreUI | -[CUICatalog namedLookupWithName:scaleFactor:deviceIdiom:deviceSubtype:sizeClassHorizontal:sizeClassVertical:] + 148
9 UIKit | ___98-[_UIAssetManager imageNamed:scale:idiom:subtype:cachingOptions:sizeClassPair:attachCatalogImage:]_block_invoke + 424
10 UIKit | -[_UIAssetManager imageNamed:scale:idiom:subtype:cachingOptions:sizeClassPair:attachCatalogImage:] + 212
11 UIKit | -[_UIAssetManager imageNamed:withTrait:] + 528
12 UIKit | __UIImageWithNameAndTraitCollection + 96
13 UIKit | _UIImageWithName + 48
14 UIKit | __GetTextFieldClearButtonWithCustomColor + 244
15 UIKit | -[UITextField _clearButtonImageForState:] + 156
16 UIKit | -[UITextField clearButton] + 176
17 UIKit | -[UITextField _updateButtons] + 116
18 UIKit | -[UITextField _layoutContent] + 92
19 UIKit | -[UITextField layoutSubviews] + 68
20 UIKit | -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 644
21 JupuCircle | -[UIView(QMUI_Border) qmui_layoutSublayersOfLayer:] (UIView+QMUI.m:319)
22 QuartzCore | -[CALayer layoutSublayers] + 148
23 QuartzCore | CA::Layer::layout_if_needed(CA::Transaction*) + 292
24 QuartzCore | CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 32
25 QuartzCore | CA::Context::commit_transaction(CA::Transaction*) + 252
26 QuartzCore | CA::Transaction::commit() + 516
27 UIKit | __afterCACommitHandler + 180
28 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
29 CoreFoundation | ___CFRunLoopDoObservers + 372
30 CoreFoundation | ___CFRunLoopRun + 928
31 CoreFoundation | CFRunLoopRunSpecific + 384
32 GraphicsServices | GSEventRunModal + 180
33 UIKit | UIApplicationMain + 204
34 JupuCircle | main (main.m:14)
35 libdyld.dylib | _start + 4

请问是这种堆栈信息吗

**Comment by MoLice** [comment]
这个问题与 QMUI 无关，只是 QMUI 重写了Layout 所以出现在堆栈里而已，请自行排查业务的问题。
