### ISSUE TITLE
确实很牛逼，赞一个

### ISSUE THREAD

**Issue by gdfyj90** [QMUI/QMUI_iOS#3]
有点美中不足的是在选择相册图片那里，虽然可以预览但是没有显示原图的按钮。

**Comment by kayo5994** [comment]
考虑到相册界面可以有各种不同的表现，而显示原图不是一个必须的功能，因此框架预览中并没有预先增加显示原图的功能，但资源类 `QMUIAsset` 是具有获取原图的方法，如果需要的话可以自行实现该功能。最近 Demo 中也准备加入显示原图的调用示例，可以持续关注 Demo 的更新

**Comment by kayo5994** [comment]
@gdfyj90 目前选择图片展示的示例中已经加上了发送原图的功能，采用了与微信相同的交互，有需要的可以查看最新的 Demo 代码。
