### ISSUE TITLE
[!] Unable to find a specification for `QMUIKit`

### ISSUE THREAD

**Issue by 2zuckerberg** [QMUI/QMUI_iOS#30]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
为什么cocoapods找不到呢？

**Comment by zhoon** [comment]
https://github.com/QMUI/QMUI_iOS/issues/21
请参考这个issue

**Comment by 2zuckerberg** [comment]
谢谢，更新一下就好了。
