### ISSUE TITLE
QMUI_IOS与masonry有冲突吗？

### ISSUE THREAD

**Issue by halfrisk** [QMUI/QMUI_iOS#301]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.3`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题
目前在使用masonry老是出现如下错误，我通过新建一个工程，然后测试masonry没有问题，之后把同一份代码移植到含有QMUI_IOS框架的项目中，就是报错，也不知道如何定位，masonry不是很熟悉。
#### 相关截图（断点的堆栈、控制台的 log）
2018-04-11 07:00:25.215525+0800 TaoMaoDuoBao[7334:3203849] *** Assertion failure in -[MASViewConstraint setSecondViewAttribute:], /Users/hongxing/github/Masonry/Masonry/MASViewConstraint.m:135
2018-04-11 07:00:50.366221+0800 TaoMaoDuoBao[7334:3203849] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempting to add unsupported attribute: (null)'

对应出错的代码段：
- (void)setSecondViewAttribute:(id)secondViewAttribute {
    if ([secondViewAttribute isKindOfClass:NSValue.class]) {
        [self setLayoutConstantWithValue:secondViewAttribute];
    } else if ([secondViewAttribute isKindOfClass:MAS_VIEW.class]) {
        _secondViewAttribute = [[MASViewAttribute alloc] initWithView:secondViewAttribute layoutAttribute:self.firstViewAttribute.layoutAttribute];
    } else if ([secondViewAttribute isKindOfClass:MASViewAttribute.class]) {
        MASViewAttribute *attr = secondViewAttribute;
        if (attr.layoutAttribute == NSLayoutAttributeNotAnAttribute) {
            _secondViewAttribute = [[MASViewAttribute alloc] initWithView:attr.view item:attr.item layoutAttribute:self.firstViewAttribute.layoutAttribute];;
        } else {
            _secondViewAttribute = secondViewAttribute;
        }
    } else {
        NSAssert(NO, @"attempting to add unsupported attribute: %@", secondViewAttribute);
    }
}

**Comment by halfrisk** [comment]
初步发现问题是以下定没有生效
//define this constant if you want to use Masonry without the 'mas_' prefix
#define MAS_SHORTHAND

//define this constant if you want to enable auto-boxing for default syntax
#define MAS_SHORTHAND_GLOBALS
#import "Masonry.h"

如果带有make的约束带有 mas_ 前缀，没有问题了。

**Comment by halfrisk** [comment]
此问题与QMUI有关系吗？

**Comment by MoLice** [comment]
暂时不能确定，有没有一些 crash 时的断点、堆栈截图可以看看？有很多同时使用这两个框架的同学，但尚未有人反馈过这种问题。
