### ISSUE TITLE
rightBarButton如何让与系统模式一致，靠右

### ISSUE THREAD

**Issue by halfrisk** [QMUI/QMUI_iOS#304]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题
如何做到像这样的效果
![image](https://user-images.githubusercontent.com/19650796/38787252-790a15b4-415f-11e8-95ff-f1c7cc452f93.png)
下面位置错误的原因是什么？

#### 相关截图（断点的堆栈、控制台的 log）
![image](https://user-images.githubusercontent.com/19650796/38787169-fb3b28b2-415e-11e8-8e26-0df725ad24ae.png)

![image](https://user-images.githubusercontent.com/19650796/38787215-4193f514-415f-11e8-9b70-f4cbdc84ee60.png)

**Comment by MoLice** [comment]
可能是因为，你的图片本来就那么大...
