### ISSUE TITLE
QMUIImagePickerPreviewViewController的checkboxButton选中状态错误

### ISSUE THREAD

**Issue by fanyuecheng** [QMUI/QMUI_iOS#306]
### 请填写运行环境

- [x] 设备：`iPhone `模拟器`
- [x] 系统：`iOS 11.3`
- [x] Xcode 版本：`9.3`
- [x] QMUI iOS 版本：`2.5.1`

### 请描述具体问题
在相册里面选中图片后，返回相簿列表，再重新进入之前退出的相簿，触发refreshWithAssetsGroup:assetsGroup方法，进而将imagesAssetArray重新赋值，然而selectedImageAssetArray还是旧数据，导致进入QMUIImagePickerPreviewViewController后，图片的选中状态是错误的。

**Comment by MoLice** [comment]
确实，我们改一下

**Comment by MoLice** [comment]
已在 [2.6.0](https://github.com/QMUI/QMUI_iOS/releases/tag/2.6.0) 版本修复。
