### ISSUE TITLE
QMUIImagePickerPreviewViewController 闪退

### ISSUE THREAD

**Issue by bluesky335** [QMUI/QMUI_iOS#31]
### Xcode8 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
在多选模式下，选中多张图片后，点击“预览”，然后在预览里取消所有选择，回到图片列表，点击任意一张indexpath.row大于之前选中的图片的总数的图片，程序就会崩溃，官方提供的demo程序也是如此。

具体的说：
打开官方demo应用“QMUI”->选择"Components" ->选择“QMUIPickingImage” -> 选择“默认” -> 选中任意两张图片 -> 点击左下角“预览” -> 点击右上角取消选中 -> 右滑取消另一张图片的选中 -> 返回 -> 点击第三张或之后的任意一张图片 -> 闪退。

#### 原因 ####
QMUIImagePreviewView.m中第96行
```
[self.collectionView scrollToItemAtIndexPath:[NSIndexPath indexPathForItem:currentImageIndex inSection:0] atScrollPosition:UICollectionViewScrollPositionCenteredHorizontally animated:animated];
```
在这里self.collectionView 的item还是之前预览时的数据，没有刷新。currentImageIndex 越界了。

#### 我的解决方法 ####
我在QMUIImagePickerPreviewViewController.m 第202行和203行之间插入以下代码：
```
    [self.imagePreviewView.collectionView reloadData];
```
解决了问题。

望早日修复。

**Comment by MoLice** [comment]
这个之前已经修复了，请检查代码是否是最新版本？
