### ISSUE TITLE
tableviewController中搜索框不对称

### ISSUE THREAD

**Issue by halfrisk** [QMUI/QMUI_iOS#310]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题
搜索框在tableHeaderView不对称，如何解决？
#### 相关截图（断点的堆栈、控制台的 log）
![image](https://user-images.githubusercontent.com/19650796/39173465-5ea4d118-47d7-11e8-97d2-2c585d1e468d.png)

**Comment by MoLice** [comment]
因为你显示了右边的索引条，这是系统行为

**Comment by halfrisk** [comment]
有办法解决吗？不对称，感觉不美观。

**Comment by MoLice** [comment]
这属于系统行为，如果你要改变系统行为，只能自行想法办解决了。
