### ISSUE TITLE
通过UINavigationController+QMUI.h, 侧滑屏幕边缘的时候,判断是否允许返回,有问题

### ISSUE THREAD

**Issue by popor** [QMUI/QMUI_iOS#314]
设备：iPhone 6 plus
系统：iOS 11.3
Xcode 版本：9.3
QMUI iOS 版本：2.5.1

需求: 通过UINavigationController+QMUI.h, 侧滑屏幕边缘的时候,判断是否允许返回.
症状: 无论滑动任何地方都会触发- (BOOL)forceEnableInteractivePopGestureRecognizer,使得功能无法开发.

建议:
不能通过 函数1(*)来判断，需要通过函数2(*)来判断,另外判断的语句也有问题,不能使用
if (gestureRecognizer == self.interactivePopGestureRecognizer) {}
应该使用
if ([otherGestureRecognizer isKindOfClass:[UIScreenEdgePanGestureRecognizer class]]){}

请求支援.

------ 注释 -----
函数1:
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch;
函数2:
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer;

**Comment by MoLice** [comment]
> 无论滑动任何地方都会触发- (BOOL)forceEnableInteractivePopGestureRecognizer,使得功能无法开发.
请描述具体一点，例如，为什么这样就“无法开发功能”？你原本想要做的事情是什么？这个方法的调用是怎么影响到你原本要做的事情的？

> 不能使用 `if (gestureRecognizer == self.interactivePopGestureRecognizer)` 应该使用 `if ([otherGestureRecognizer isKindOfClass:[UIScreenEdgePanGestureRecognizer class]])`
这个是为什么呢？

**Comment by popor** [comment]
@MoLice 我能给你发个demo吗?请给个邮箱

**Comment by MoLice** [comment]
可以，请发到 qmuiteam@qq.com

**Comment by popor** [comment]
@MoLice  已发送,请查阅.

**Comment by MoLice** [comment]
> 为什么这样就“无法开发功能”？你原本想要做的事情是什么？这个方法的调用是怎么影响到你原本要做的事情的？

由于在第一次追问中的问题并没有得到直接回答，收到的 Demo 里也没有相关说明，所以时隔半年，我才猜到你希望的效果是不是：

希望 `forceEnableInteractivePopGestureRecognizer` 方法仅在屏幕边缘向右滑动时，才被调用？

**Comment by popor** [comment]
后来我不用这种方式了,因为修改系统navigationBar:shouldPopItem:方法,会在iOS8、9和12发生很多异常,停用后崩溃率下降了90%.

**Comment by MoLice** [comment]
好的
