### ISSUE TITLE
使用QMUI在pch导入#import <QMUIKit/QMUIKit.h>后与视频库冲突

### ISSUE THREAD

**Issue by DogTwoChen** [QMUI/QMUI_iOS#318]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题
<img width="1145" alt="2018-04-28 9 56 43" src="https://user-images.githubusercontent.com/18676761/39390856-8c5301cc-4acd-11e8-9cf1-825e0c2439f7.png">
从pch注释掉之后就没问题

**Comment by MoLice** [comment]
是否有用 `#ifdef __OBJC__` 将 QMUIKit 的 import 包起来？

**Comment by DogTwoChen** [comment]
尝试过用 #ifdef __OBJC__包QMUIKit 的 import,但还是报错
![Uploading 屏幕快照 2018-05-09 上午9.27.08.png…]()
