### ISSUE TITLE
基于第三方库开发的一个需求实现请教

### ISSUE THREAD

**Issue by halfrisk** [QMUI/QMUI_iOS#319]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题
需求：基于第三方库进行开发，只开放了头文件，已知库中一个控制器头文件中，假设为 ThirdController：UIViewController，现在需要自己写一个控制器为：MyController：ThirdController，现在的问题是，怎么在使用QMUINavigationController的QMUINavigationBar上设置leftBarButton或者rightBarButton？

**Comment by MoLice** [comment]
你的需求跟使用哪个第三方库无关，因为，这是 UIKit 自带的功能。
