### ISSUE TITLE
看了下源码和demo，反馈一下

### ISSUE THREAD

**Issue by songxing10000** [QMUI/QMUI_iOS#32]
### 运行环境 ###

- [ ] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
有些代码的确写得很好，很规范，但是感觉框架太大型了，想抽取一个组件出来会涉及到很多

**Comment by MoLice** [comment]
感谢反馈。目前整个 QMUIKit 自成一体，除了 Category 部分，其他的都是强依赖关系，如果要单独拿其中某个控件来使用确实不太方便。不过当初 QMUIKit 设计的目的就不是以控件库为目标，目前也不会以控件库为发展目标（如果真有一些复杂控件，也是单独分享出来，不会成为 QMUIKit 的一部分，QMUIKit 里只包含常用且通用的控件），所以这种场景只能暂时承担抽离成本了。

**Comment by songxing10000** [comment]
如果这样的话希望能越做越好，一直坚持下去，现在iOS市场还是鱼龙混杂，有一些好的写法也挺好，持续关注中


Sent from Mail Master
在2017年01月13日 16:13，MoLice 写道:

感谢反馈。目前整个 QMUIKit 自成一体，除了 Category 部分，其他的都是强依赖关系，如果要单独拿其中某个控件来使用确实不太方便。不过当初 QMUIKit 设计的目的就不是以控件库为目标，目前也不会以控件库为发展目标（如果真有一些复杂控件，也是单独分享出来，不会成为 QMUIKit 的一部分，QMUIKit 里只包含常用且通用的控件），所以这种场景只能暂时承担抽离成本了。

**Comment by MoLice** [comment]
感谢支持，也欢迎贡献代码哈
