### ISSUE TITLE
控制器无法释放

### ISSUE THREAD

**Issue by OpenFeyn** [QMUI/QMUI_iOS#322]
### 请填写运行环境

- [x] 设备：`iPhone6 真机`
- [x] 系统：`iOS 10.3.2`
- [x] Xcode 版本：`9.3`
- [x] QMUI iOS 版本：`2.6.1`

### 请描述具体问题
1、直接在当前导航控制器推出一个QMUIAlbumViewController；
2、任选择一个相册簿进入；
3、无需任何操作，点击回退到相册簿页面
4、MLeaksFinder检测发生内存泄漏

#### 相关截图（断点的堆栈、控制台的 log）
stack: (
    QMUIImagePickerViewController
)

**Comment by OpenFeyn** [comment]
补充：
无需引入项目，在Demo集成MLeaksFinder，操作图片选择，就会出现控制器不释放问题

**Comment by fanyuecheng** [comment]
QMUIAlbumViewController会持有QMUIAlbumViewControllerDelegate传入的QMUIImagePickerViewController，即使返回相簿页面，imagePickerViewController也不会释放，不是酱紫的吗

**Comment by OpenFeyn** [comment]
那应该解决掉这个问题

**Comment by MoLice** [comment]
这是设计如此，`imagePickerViewController` 只创建一个，每次进入不同的相簿都会通过 `refreshWithAssetsGroup:` 去更新九宫格里的图片，所以不属于内存泄露。

MLeaksFinder 本身支持主动屏蔽某些场景的误报，具体可查看 MLeaksFinder 的说明。
