### ISSUE TITLE
导航栏的title的字体颜色怎么修改

### ISSUE THREAD

**Issue by DogTwoChen** [QMUI/QMUI_iOS#323]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题
我在继承QMUINavigationController的导航栏基类里面设置titleTextAttributes,不能对全局的导航栏都生效.

**Comment by listenzz** [comment]
`[UINavigationBar appearance] setTitleTextAttributes:`

**Comment by MoLice** [comment]
如果你的 viewController 是 `QMUICommonViewController`，那么导航栏标题是自定义控件，所以无法响应 `titleTextAttributes` 的修改，建议：
1. 如果你使用了配置表，则直接修改配置表里的 `QMUICMI.navBarTitleColor = xxx` 为你想要的颜色。
2. 如果你不使用配置表，那么也可以在 viewController 里通过 `self.titleView.tintColor = xxx` 修改标题为你想要的颜色。
