### ISSUE TITLE
请问有考虑过提供对导航栏的更多操作功能吗？

### ISSUE THREAD

**Issue by YaoJuan** [QMUI/QMUI_iOS#324]
很抱歉，这不是一个bug.更像一个需求。
目前感觉很好用，但是很多项目中都有例如列表滚动改动nav的alpha&&statusBar Style。然后最近实现这个功能也找了对应的处理的第三方,发现大部分都有冲突，所有请问是否有考虑过添加类似的功能

**Comment by MoLice** [comment]
谢谢建议，会考虑。
