### ISSUE TITLE
自定义pop手饰冲突

### ISSUE THREAD

**Issue by YaoJuan** [QMUI/QMUI_iOS#325]
请填写运行环境
  设备：iPhone7 真机
  系统：iOS 11.3.
  Xcode 版本：9.3
  QMUI iOS 版本：2.6.1
请描述具体问题
由于原生的pop手饰只能在屏幕左侧才能有效，项目需求是需要全屏都有这个左滑返回的手饰，而且QMUINavigationController有些功能很好用，于是我就创建一个navigationController继承自QMUINavigationController，然后自定义了一个手饰，让他触发原生的手饰方法，并且扩大的作用范围，于是有这个效果了。但是就会出现下面截图的crash了。

相关截图（断点的堆栈、控制台的 log）
reason: '-[STBaseNavigationController handleNavigationTransition:]: unrecognized selector sent to instance 0x122044800'
原生的手饰就是触发的这个handleNavigationTransition方法。

我查看了qmui的代码是y因为qmui把之前的delegate换成了自定义的，但是由于自定的代理没有这个方法了。所以导致crash
//    self.interactivePopGestureRecognizer.delegate = (id<UIGestureRecognizerDelegate>)self;

**Comment by MoLice** [comment]
问题描述似乎有点过于精简，建议贴出关键代码或者截图，注意不要缩写，我猜不出来...

**Comment by YaoJuan** [comment]
@MoLice 好的，对不起，重新编辑过了

**Comment by YaoJuan** [comment]
@MoLice 不好意思，刚才提交一个提交错了。本来是想自己fork本地改给自己项目用的，刚玩，不太会。sorry

**Comment by likeSo** [comment]
你好，我也遇到这个问题了，这个问题具体表现为，我们使用下面这段代码来实现全屏幕手势返回（将系统的屏幕边缘手势替换为普通的滑动手势）：
```swift
let target = self.interactivePopGestureRecognizer?.delegate
        // create a pan gesture and execute system screen-edge gesure's method
        let panGesture = UIPanGestureRecognizer(target: target, action: Selector(("handleNavigationTransition:")))
        // handle pan gesture and process gestures's priority
        panGesture.delegate = self
        self.view.addGestureRecognizer(panGesture)
        self.interactivePopGestureRecognizer?.isEnabled = false

```
但是pod引入了QMUIKit之后，滑动返回时报错：`-[UINavigationController handleNavigationTransition:]: unrecognized selector sent to instance`，原因应该就是 @YaoJuan 描述的那样，他已经在他的fork内修改了。
请问官方能提供相关修复吗？ @MoLice
