### ISSUE TITLE
側滑返回手勢無效

### ISSUE THREAD

**Issue by iURWang** [QMUI/QMUI_iOS#326]
### 请填写运行环境

- [x] 设备：iPhone
- [x] 系统：iOS 11.3
- [x] Xcode 版本：9.3
- [x] QMUI iOS 版本：2.6.1

### 请描述具体问题
我需要自定義push/pop轉場動畫，自定義導航控制器繼承自<QMUINavigationController>去實現<UINavigationControllerDelegate>代理，實現以下兩個方法：
`- (id<UIViewControllerAnimatedTransitioning>)navigationController:(UINavigationController *)navigationController animationControllerForOperation:(UINavigationControllerOperation)operation fromViewController:(UIViewController *)fromVC toViewController:(UIViewController *)toVC`

`- (id<UIViewControllerInteractiveTransitioning>)navigationController:(UINavigationController *)navigationController interactionControllerForAnimationController:(id<UIViewControllerAnimatedTransitioning>)animationController`

這個時候控制器的側滑返回無效了，消息轉發裡找不到方法 `_shouldApplyExclusiveTouch `

#### 相关截图（断点的堆栈、控制台的 log）
![bug](https://i.imgur.com/DJ1xPI4.png)

**Comment by MoLice** [comment]
通常遇到问题时，请先确定是否是 QMUI 的问题。

例如 issue 中提到的“实现了 xxx delegate 方法后，手势返回无效”，这是系统设定如此：只要你实现了 `navigationController:animationControllerForOperation:fromViewController:toViewController:`，系统就会自动屏蔽默认的手势返回，这与 QMUI 无关。相反，QMUI 通过 `UINavigationControllerBackButtonHandlerProtocol` 提供了方法 `forceEnableInteractivePopGestureRecognizer` 让你可以重新开启系统默认的手势返回，注意这个方法是要在 `UIViewController` 里实现，而不是在 `UINavigationController` 里实现。

至于第二个问题，找不到方法 `_shouldApplyExclusiveTouch`，用你提供的代码截图，并无法重现你说的问题。
