### ISSUE TITLE
2.6.2的QMUITextView为什么去掉了autoResizable

### ISSUE THREAD

**Issue by peterios2016** [QMUI/QMUI_iOS#328]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.3`
- [x] QMUI iOS 版本：`2.62`

**Comment by MoLice** [comment]
因为原本自增高的功能的使用需要这么操作：
1. 将 `autoResizable` 置为 `YES`。
2. delegate 实现 `textView:newHeightAfterTextChanged:` 方法。

当初将响应和开关分开的考虑是可能同一个输入框在不同状态下会有自增高和固定高度两种状态，所以可以通过 `autoResizable` 直接控制自增高功能的开启/关闭。

但实际使用中我们发现这种场景特别少（目前尚未遇到过），反而令自增高的功能使用起来更麻烦（需要两步操作），所以新版本里我们干脆废弃 `autoResizable` 开关，直接根据是否有实现 delegate 方法来决定是否需要启用自增高功能，期望这是一个提高效率的改进。
