### ISSUE TITLE
QMUIPickingImage组件加载图片模糊的问题

### ISSUE THREAD

**Issue by Luis-X** [QMUI/QMUI_iOS#329]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS`
- [x] Xcode 版本：`9.3`
- [x] QMUI iOS 版本：`2.5.1`

### 请描述具体问题
单选、多选、相机胶卷中缩略图，预览图很模糊。

**Comment by MoLice** [comment]
请更新 QMUI 版本，该问题已修复。
