### ISSUE TITLE
iPhoneX上QMUIPopupMenuView可能会被刘海遮挡

### ISSUE THREAD

**Issue by Loongwoo** [QMUI/QMUI_iOS#331]
### 请填写运行环境

- [x] 设备：`iPhone X`
- [x] 系统：`iOS 11.3.1`
- [x] Xcode 版本：`9.3`
- [x] QMUI iOS 版本：`2.6.2`

### 请描述具体问题
当QMUIPopupMenuItem只有一项的时候会从上面弹出来，其实会部分被iPhoneX的刘海挡住

#### 相关截图（断点的堆栈、控制台的 log）
![wechatimg52](https://user-images.githubusercontent.com/10918135/40160274-6eb280fe-59df-11e8-96f7-96563dc3d08c.jpeg)

**Comment by MoLice** [comment]
`QMUIPopupMenuView` 并不会自动保证不显示到 safeAreaInsets 区域，因为很多时候业务反而是需要显示到 safeAreaInsets 区域的。

如果你要保证浮层不显示到刘海区域，有两种方式：
1. 请将 `preferLayoutDirection` 改为 `QMUIPopupContainerViewLayoutDirectionBelow`，默认是 `QMUIPopupContainerViewLayoutDirectionAbove`。
2. 请将 `safetyMarginsOfSuperview` 的 `top` 加大，从而让浮层认为顶部的刘海区域是不安全的区域，就不会布局到那一块去。

**Comment by Loongwoo** [comment]
发现一个小问题，如果我单单设置Appearance是不会起作用的，如下：
`[QMUIPopupMenuView appearance].preferLayoutDirection = QMUIPopupContainerViewLayoutDirectionBelow;`

只有在实例中设置才起作用：
`QMUIPopupMenuView *popupView = [[QMUIPopupMenuView alloc] init];
    popupView.preferLayoutDirection = QMUIPopupContainerViewLayoutDirectionBelow;`

**Comment by Loongwoo** [comment]
明白了，得设置QMUIPopupContainerView的Appearance：
`[QMUIPopupContainerView appearance].preferLayoutDirection = QMUIPopupContainerViewLayoutDirectionBelow;`
