### ISSUE TITLE
QMUICommonViewController，是代码重复嘛？

### ISSUE THREAD

**Issue by cqz930110** [QMUI/QMUI_iOS#332]
### 请填写运行环境

- [x] 设备：所有
- [x] 系统：所有
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题

QMUICommonViewController下的
- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    [self setupNavigationItems];
    [self setupNavigationItems];
}
是不是修改为
- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    [self setupNavigationItems];
    [self setupToolbarItems];
}

**Comment by MoLice** [comment]
这里写错了，你的修改是对的，准备发个小版本修复这个问题，抱歉！

**Comment by MoLice** [comment]
@cqz930110 2.7.0 版本已发布，修复这个问题。
