### ISSUE TITLE
[UIView(QMUI_Border) qmui_layoutSublayersOfLayer:] iOS9会在这个地方crash怎么回事

### ISSUE THREAD

**Issue by gongshouhui** [QMUI/QMUI_iOS#334]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 9.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

**Comment by zhoon** [comment]
能提供一下具体的控制台log和堆栈吗？
之前也有人反馈类似的问题，最后都确认这个crash应该跟QMUI无关，你可以注释掉看看。

**Comment by MoLice** [comment]
与 #299 #122 重复
