### ISSUE TITLE
QMUIModalPresentationViewController以showWithAnimated方式弹出后，再弹出UIAlertController，UIAlertController会被盖住

### ISSUE THREAD

**Issue by LinDing** [QMUI/QMUI_iOS#337]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

**Comment by MoLice** [comment]
这个属于实现原理导致的问题，因为 `QMUIModalPresentationViewController` 以 `showWithAnimated` 方式显示时，实际上是创建了一个 `windowLevel = UIWindowLevelAlert - 4.0` 的 `UIWindow` 盖在原来的 window 上，而 `UIAlertController` 是以 present 的方式显示，所以 alertController 显示在哪个 window  上取决于你用哪个 viewController 去 present 它。

建议你用 modalPrensentationViewController 去 present alertController，从而让 alertController 能显示在 modal 上。

![image](https://user-images.githubusercontent.com/1190261/40443433-e498c1e8-5ef8-11e8-89c1-250e3051958a.png)
