### ISSUE TITLE
系统的navtileView被劫持了，能否根据具体的业务来选择用qmui的还是系统的

### ISSUE THREAD

**Issue by Gavin123** [QMUI/QMUI_iOS#338]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题
目前的需求是要自定义view是做相关的业务，qmui提供的不能满足我们的需求，能否支持下 ，谢谢

**Comment by MoLice** [comment]
QMUI 通过系统的接口来将 titleView 改为 `QMUINavigationTitleView`，所以搜一下就能知道修改的地方在哪里：
![image](https://user-images.githubusercontent.com/1190261/40476282-3ad373be-5f76-11e8-8120-575dc395f838.png)

所以，你只需要在你的 viewController 的 `setupNavigationItems` 方法里把 `self.navigationItem.titleView` 赋值为你自己想要的 view 即可。
