### ISSUE TITLE
关于屏幕比例适配的问题？

### ISSUE THREAD

**Issue by Gavin123** [QMUI/QMUI_iOS#339]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题

请教一个适配比例的问题，目前我看了下qmui对适配用的是flat()这个函数，但我看了其他的都是基于某个机型的比例来计算的，能否提供下一个可行的解决方案呢？感谢

**Comment by MoLice** [comment]
按你的问题描述，并不清楚你需要的是什么。

flat函数是用于将一个浮点数进行像素取整，保证在当前设备上不会出现0.x个像素点。

不清楚你需要做的是什么事情。
