### ISSUE TITLE
QMUICommonTableViewController第一次选中问题。

### ISSUE THREAD

**Issue by cqz930110** [QMUI/QMUI_iOS#340]
### 请填写运行环境

- [x] 设备：所有
- [x] 系统：iOS
- [x] Xcode 版本：9.3
- [x] QMUI iOS 版本：`2.6.2`

### 请描述具体问题
在ViewController上添加一个继承QMUICommonTableViewController的子试图。第一次点击选中一个cell时候，屏幕上所有的cell都被选中了

**Comment by MoLice** [comment]
你确定这跟 QMUI 有关？
