### ISSUE TITLE
qmui_seperatorDashLayerInHorizontal没有效果

### ISSUE THREAD

**Issue by peterios2016** [QMUI/QMUI_iOS#341]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.6.1`

### 请描述具体问题
在系统默认的cell中使用[cell.contentView.layer addSublayer:[CALayer qmui_seperatorDashLayerInHorizontal]];
并没有产生虚线

#### 相关截图（断点的堆栈、控制台的 log）
全部代码如下
`if (!cell) {
        cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:winnerInsideID];
        //添加虚线
        [cell.contentView.layer addSublayer:[CALayer qmui_seperatorDashLayerInHorizontal]];
    }`

**Comment by MoLice** [comment]
你得为你的layer布局…

**Comment by peterios2016** [comment]
可以说下要怎么设置吗，我设置了layer.bounds和position也没有效果
