### ISSUE TITLE
QMUITextView初始化问题

### ISSUE THREAD

**Issue by HouWan** [QMUI/QMUI_iOS#342]
### 请填写运行环境

- [x] 设备：`iPhone 8 Plus` / `模拟器ALL`
- [x] 系统：`iOS 11.3.1`
- [x] Xcode 版本：`9.3`
- [x] QMUI iOS 版本：`2.6.2`

### 请描述具体问题

`QMUITextView`如果使用`initWithFrame`初始化，页面将不显示，打印高度为0。
必须使用`.frame`方式才可以。

不显示UI的初始化：
```
QMUITextView *textView = [[QMUITextView alloc] initWithFrame:CGRectMake(10, 100, 200, 300)];
textView.placeholder = @"测试";
textView.placeholderColor = [UIColor redColor];
[self.view addSubview:textView];
```

必须这样才可以
```
QMUITextView *textView = [[QMUITextView alloc] init];
textView.frame = CGRectMake(10, 100, 200, 300);
textView.placeholder = @"测试";
textView.placeholderColor = [UIColor redColor];
[self.view addSubview:textView];
```

个人觉得这算是bug，如果不想让用`initWithFrame`初始化，应该使用`UNAVAILABLE_ATTRIBUTE`方法禁掉。我看代码造成这样的原因是属性`maximumHeight`的逻辑问题。

**Comment by MoLice** [comment]
这是 `maximumHeight` 的 bug，在即将发布的版本里将会修复它。

**Comment by MoLice** [comment]
2.7.0 版本已发布，修复了这个问题。
