### ISSUE TITLE
在Swift下使用QMUI不能使用instrument调试问题

### ISSUE THREAD

**Issue by niekang** [QMUI/QMUI_iOS#343]
### 请填写运行环境

- [x] 设备：`iPhone所有设备` 
- [x] 系统：`iOS 9 以上， iOS 9以下未测试过`
- [x] Xcode 版本：`9.3.1`
- [x] QMUI iOS 版本：`2.3.0`

使用instrument (Leaks, Allocation) 点击录制时 APP启动后闪退

**Comment by MoLice** [comment]
有没有更详细的信息？

**Comment by niekang** [comment]
Swift工程pod QMUIKit进来，使用instrument工具, 使用Leaks，点击录制，真机上程序启动，进入启动界面，然后闪退，instrument  Leaks断开， 使用instrument其他工具也会这样，我的611.3, 6splus 11.3，7plus11.3，iPhoneX有这个问题
