### ISSUE TITLE
setupToolbarItems 不被调用

### ISSUE THREAD

**Issue by iURWang** [QMUI/QMUI_iOS#344]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题
setupToolbarItems 在 QMUICommonViewController 并未被调用

`- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    [self setupNavigationItems];
    [self setupNavigationItems];
}`
`- (void)viewControllerKeepingAppearWhenSetViewControllersWithAnimated:(BOOL)animated {
    // 通常和 viewWillAppear: 里做的事情保持一致
    [self setupNavigationItems];
    [self setupNavigationItems];
}`

**Comment by MoLice** [comment]
这是 bug，即将发布新版解决。

**Comment by MoLice** [comment]
2.7.0 版本已发布，修复了这个问题。
