### ISSUE TITLE
QMUIMultipleDelegates在self.delegate = self时，陷入死循环

### ISSUE THREAD

**Issue by ColinHwang** [QMUI/QMUI_iOS#346]
### 请填写运行环境

- [x] 设备：`模拟器`
- [x] 系统：`iOS 11.0.1`
- [x] Xcode 版本：`9.0.1`
- [x] QMUI iOS 版本：`2.6.2`

### 请描述具体问题

实验了下，self.delegate = self会死循环：
```
@interface TestTextView : UITextView

@end

@interface TestTextView ()<UITextViewDelegate>

@end

@implementation TestTextView

- (instancetype)initWithFrame:(CGRect)frame {
    self = [super initWithFrame:frame];
    if (self) {
        self.qmui_multipleDelegatesEnabled = YES;
        self.delegate = self;
    }
    return self;
}

@end
```

之后QMUIMultipleDelegates不断执行forwardInvocation...

**Comment by MoLice** [comment]
确实会死循环，我们看看怎么改。在此之前可以先避免 `textView.delegate = self` 的写法，例如创建一个内部的 object 去当 textView 的 delegate。

**Comment by ColinHwang** [comment]
好速度，可以的👍
