### ISSUE TITLE
UINavigationController (NavigationBarTransition) 添加对 setViewControllers 的处理

### ISSUE THREAD

**Issue by ziecho** [QMUI/QMUI_iOS#351]
除了常见的 push，pop 方法外，UINavigationController 还有 - (void)setViewControllers:(NSArray<UIViewController *> *)viewControllers animated:(BOOL)animated 这一转场方法，当前版本没有对上一个 VC 添加一个假 Bar 导致转场时会出现透明 Bar，修复方法：添加对这种情况的处理：

`
+ (void)load {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        Class cls = [self class];
        ReplaceMethod(cls, @selector(pushViewController:animated:), @selector(NavigationBarTransition_pushViewController:animated:));
        ReplaceMethod(cls, @selector(popViewControllerAnimated:), @selector(NavigationBarTransition_popViewControllerAnimated:));
        ReplaceMethod(cls, @selector(popToViewController:animated:), @selector(NavigationBarTransition_popToViewController:animated:));
        ReplaceMethod(cls, @selector(popToRootViewControllerAnimated:), @selector(NavigationBarTransition_popToRootViewControllerAnimated:));
        // 添加此句
        ReplaceMethod(cls, @selector(setViewControllers:animated:), @selector(NavigationBarTransition_setViewControllers:animated:));
    });
}

- (void)NavigationBarTransition_setViewControllers:(NSArray<UIViewController *> *)viewControllers animated:(BOOL)animated {
    UIViewController *disappearingViewController = self.viewControllers.lastObject;
    UIViewController *appearingViewController = viewControllers.lastObject;
    if (!disappearingViewController) {
        return [self NavigationBarTransition_setViewControllers:viewControllers animated:animated];
    }
    [self handlePopViewControllerNavigationBarTransitionWithDisappearViewController:disappearingViewController appearViewController:appearingViewController];
    
    return [self NavigationBarTransition_setViewControllers:viewControllers animated:animated];
}`

**Comment by zhoon** [comment]
感谢反馈，新版本会做处理

**Comment by MoLice** [comment]
2.7.2 已修复这个问题。
