### ISSUE TITLE
QMUIImagePickerViewController能添加一个选中之前拦截的代理吗，或者添加取消选中接口（预览的也要添加相应的）

### ISSUE THREAD

**Issue by fanxiangyang** [QMUI/QMUI_iOS#352]
新功能建议：感觉取消选中或者选中之前拦截判断，很重要
1.比如我想实现，判断选中5张图片，或者一个视频，应该开放一个代理，来拦截选中的资源，如果是选完图片就不能选择视频，我现在只能选择完视频后才能知道提示但是，视频已经被选中了

麻烦有微信群吗  fanxiangyang_heda@163.com

**Comment by MoLice** [comment]
目前确实缺少一个类似 `shouldCheck` 的方法来控制是否应该被选中，这个后续会加上。
另外按目前的代码，你可以尝试在 `imagePickerViewController:didCheckImageAtIndex:` 里把 `cell.checked = NO`，以及 `selectedImageAssetArray removeObject:xxx`。

**Comment by MoLice** [comment]
2.7.2 已发布，新增 `imagePickerViewController:shouldCheckImageAtIndex:` 方法，具体请查看 Release  Note。
