### ISSUE TITLE
在iPhone5s加载Storyboard崩溃的问题

### ISSUE THREAD

**Issue by ZeroDelegate** [QMUI/QMUI_iOS#353]
### 请填写运行环境

- [x] 设备：iPhone5s
- [x] 系统：`iOS 11.3.2`
- [x] Xcode 版本：`9.3`
- [x] QMUI iOS 版本：`2.0`

#### 相关截图（断点的堆栈、控制台的 log）
![image](https://user-images.githubusercontent.com/24216621/41325763-a1401bc0-6eee-11e8-89d8-ed148376fda1.png)

**Comment by ZeroDelegate** [comment]
在iPhoneX和6S等机型没有此问题

**Comment by MoLice** [comment]
这个与 QMUI 无关，请检查你自身的代码。
这里只是因为我们 swillize 了 layoutSublayersOfLayers 这个系统方法，所以如果才会出现在调用堆栈里。

**Comment by ZeroDelegate** [comment]
我同一个storyboard文件，拖到自己的demo中，在5s可以正常显示，在这个项目中就会崩溃，iphoneX和6s就不会崩溃，因为这个项目之前不是我开发的，就一直crash在上面那个方法中，也没有日志，所以找不到原因

**Comment by MoLice** [comment]
你自己的 demo 里有用 QMUI 吗？
