### ISSUE TITLE
QMUITextView在iOS10上的显示bug

### ISSUE THREAD

**Issue by HouWan** [QMUI/QMUI_iOS#354]
### 运行环境

- [x] 设备：`iPhone 6S` 
- [x] 系统：`iOS 10.2.1`
- [x] Xcode 版本：`9.4`
- [x] QMUI iOS 版本：`2.7.1`

### 请描述具体问题
在真机iPhone 6S上，`QMUITextView`显示异常，如截图所示。白色区域是`QMUITextView`，但是显示的文本，却是从底部开始的。
代码

```
CGRect f = CGRectMake(0, Nav_Height, Screen_Width, 100);
QMUITextView *textView = [[QMUITextView alloc] initWithFrame:f];
textView.backgroundColor = [UIColor whiteColor];
textView.font = HWFont(15);
textView.placeholder = @"留言(最多50个字)";
textView.placeholderColor = App_grey;
textView.maximumTextLength = 50;
[self.view addSubview:textView];
```

#### 相关截图（断点的堆栈、控制台的 log）

![fullsizerender](https://user-images.githubusercontent.com/13991710/41389823-7a6da2e2-6fc5-11e8-9a79-c25527754581.jpg)
![fullsizerender2](https://user-images.githubusercontent.com/13991710/41389824-7a9dda3e-6fc5-11e8-9ff6-a8cf84852ed2.jpg)

**Comment by MoLice** [comment]
与 #327 重复
