### ISSUE TITLE
isAnyAlertControllerVisible 返回不正确

### ISSUE THREAD

**Issue by lxooxl** [QMUI/QMUI_iOS#355]
### 请填写运行环境

- [x] 设备：`模拟器`
- [x] 系统：`iOS 11.3`
- [x] Xcode 版本：`9.3`
- [x] QMUI iOS 版本：`2.7.0`

### 请描述具体问题
第一次alertControllerCount = nil
显示alert 后为 1
alert消失后 再次弹出alert alertControllerCount不正确
当前页面没有alert显示
alertControllerCount 控制台输出为 18446744073709551615
alertControllerCount-- 后 alertControllerCount 控制台输出nil
#### 相关截图（断点的堆栈、控制台的 log）
<img width="718" alt="2018-06-18 4 57 33" src="https://user-images.githubusercontent.com/20851077/41527134-c939ff0a-7318-11e8-8aa7-c760516a8484.png">
<img width="268" alt="2018-06-18 4 57 47" src="https://user-images.githubusercontent.com/20851077/41527142-cdbc8dd6-7318-11e8-9da8-29607145133c.png">

**Comment by MoLice** [comment]
请贴一下你使用 alert 的代码

**Comment by lxooxl** [comment]
`
    fileprivate static func toastMsg(_ title:String,_ msg:String? = nil) {
        if QMUIAlertController.isAnyAlertControllerVisible(){
            return
        }
        var alert:QMUIAlertController!
        if let message = msg {
            alert = QMUIAlertController(title: title, message: message, preferredStyle: .alert)
        } else {
            alert = QMUIAlertController(title: "", message: title, preferredStyle: .alert)
        }
        
        let action = QMUIAlertAction(title: "确定", style: .cancel) { (controller, action)  in
            
        }
        alert.addAction(action)
        alert.showWith(animated: true)
    }
`

**Comment by MoLice** [comment]
action 点击后都会自动隐藏弹窗，不应该在 handler 里手动再去 hide 一次，否则会导致两次 hide 的调用，count 计数就出错了。

这里我们会再对这种错误的使用情况做保护，目前的版本，请不要在 handler 里调用 hide。
