### ISSUE TITLE
originImage获取图片后，获取图片大小不准确

### ISSUE THREAD

**Issue by chanshiguan** [QMUI/QMUI_iOS#356]
### 请填写运行环境

- [x] 设备：`iPhone` / `模拟器`
- [x] 系统：`iOS 11`
- [x] Xcode 版本：`9.4.1`
- [x] QMUI iOS 版本：`2.7.1`

### 请描述具体问题
通过originImage方法获取图片后，获取图片size。最大为5000。而不是图片实际宽度。不过通过requestImageData方法获取图片后，获取图片size，是可以获取到实际图片大小的。请问是系统问题还是bug？谢谢。

**Comment by kayo5994** [comment]
这是一个系统问题，`QMUIAsset` 的  `originImage`  内部实现是调用了系统 `PHCachingImageManager` 的 `requestImageForAsset` 系列方法，并且请求的目标大小已经设置为 `PHImageManagerMaximumSize`，其他的选项也已经尝试过各种组合，最后输出的 `UIImage` 最多也只能是 5000 * 5000 的大小，猜测是系统在 `PHCachingImageManager` 中作了一些限制，而 `requestImageData` 是直接获取原始数据，则不受限制，如果确实需要获取全尺寸图片，可以使用 `requestImageData` 在业务封装一个获取图片的方法，这也是 `requestImageData` 这个接口的作用 —— 灵活地获取图片。
