### ISSUE TITLE
QMUIToastContentView，appearance设置textLabelAttributes 、detailTextLabelAttributes失效

### ISSUE THREAD

**Issue by dreamCC** [QMUI/QMUI_iOS#358]
### 请填写运行环境

- [x] 设备：iPhone /模拟器
- [x] 系统：iOS 11.4
- [x] Xcode 版本：9.4.1
- [x] QMUI iOS 版本：2.7.1

QMUIToastContentView，通过appearance来设置textLabelAttributes和detailTextLabelAttributes属性失效。其主要原因是：-tintColorDidChange方法中，对这两个属性进行了重新赋值，理论上逻辑没有问题。但是在QMUIToastView的- commonInit方法中，调用self.tintColor = UIColorWhite; 导致子控件-tintColorDidChange方法的调用，最后导致appearance来设置这两个属性不起作用。

**Comment by zhoon** [comment]
我们改改

**Comment by MoLice** [comment]
2.7.2 已修复这个问题。
