### ISSUE TITLE
进入项目就崩溃

### ISSUE THREAD

**Issue by Sugarjunfeng** [QMUI/QMUI_iOS#359]
### 请填写运行环境

- [x] 设备：`模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.4.1`
- [x] QMUI iOS 版本：`2.7`

### 请描述具体问题
一进项目就崩溃在这里
![2018-06-26 11 48 30](https://user-images.githubusercontent.com/13251700/41888215-e2a47ea6-7936-11e8-8e36-0ddf394bc49c.png)

**Comment by Sugarjunfeng** [comment]
我自己找到了原因,使用这个QMUIKit框架,里面自带了这个的配置类QMUIConfiguration,这个单例对象,所以你的项目中必须要有某个类继承自QMUICommonTableViewController,并且实现其协议方法,不然就会报错

**Comment by MoLice** [comment]
猜测可能不是你说的那样，可能是与第三方框架有些兼容问题，迟点再看看。

**Comment by Sugarjunfeng** [comment]
这个问题又出现了,能不能帮忙看看啊?

**Comment by MoLice** [comment]
我将最新版的 QMUI 和最新版的 IQKeyboardManager 在同一个项目里使用并没有发现问题。

如果方便，请将有问题的 demo 代码发送到 qmuiteam@qq 的邮箱。

**Comment by Sugarjunfeng** [comment]
我在cocoapod中移除了IQKeyboardManager,还是出现图中的错误,所以这个问题应该不是这个原因导致的

**Comment by MoLice** [comment]
这需要看具体场景才能查出来，只能提供一些代码了。
