### ISSUE TITLE
QMUITips is calling self..

### ISSUE THREAD

**Issue by caoer** [QMUI/QMUI_iOS#36]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

#### 问题截图 ####

should be easy to see the problem. 
https://github.com/QMUI/QMUI_iOS/blob/0d1f8ff1596f01ba04a0c096d342a2b2b1acf05b/QMUIKit/UIComponents/QMUITips.m#L213

**Comment by zhoon** [comment]
Thank you, we have fixed it.

**Comment by caoer** [comment]
👍
