### ISSUE TITLE
NSString+QMUI 里有两个方法和注释的预期结果不一致

### ISSUE THREAD

**Issue by SuperZico** [QMUI/QMUI_iOS#360]
### 请填写运行环境

- [x] 设备： `模拟器`
- [x] 系统：`iOS 11.4`
- [x] Xcode 版本：`9.1`
- [x] QMUI iOS 版本：`2.7.1`

NSString+QMUI 里的
qmui_substringAvoidBreakingUpCharacterSequencesToIndex方法
以及
qmui_substringAvoidBreakingUpCharacterSequencesFromIndex方法
和注释描述的并不一样

#### 相关截图（断点的堆栈、控制台的 log）

![2hlricr7u](https://user-images.githubusercontent.com/13212385/41898858-953e868a-795d-11e8-8601-f9a9962b014a.png)
![2hn1ecawm16_26_18__06_26_2018](https://user-images.githubusercontent.com/13212385/41898916-b86d6626-795d-11e8-9821-2b10bbb8d665.jpg)

**Comment by MoLice** [comment]
注释写错，原文是：
> 例如对于字符串“😊😞”，它的长度为4，若调用 [string qmui_substringAvoidBreakingUpCharacterSequencesToIndex:1]，将返回“😊”。

现改为：
> 例如对于字符串“😊😞”，它的长度为4，若调用 [string qmui_substringAvoidBreakingUpCharacterSequencesToIndex:1 lessValue:NO countingNonASCIICharacterAsTwo:NO]，将返回“😊”。

注意其中 `lessValue` 的值。

至于 `substringToIndex:1` 为什么是 `@""` 而不是 `@"?"`，只是 Xcode 帮你过滤掉了那个错误符号的展示，你可以获取 `c.lenght` 会发现值为 1。

**Comment by SuperZico** [comment]
好的，改了lessValue的值的确正确了
