### ISSUE TITLE
UITableView 添加 tableFooterView 崩溃

### ISSUE THREAD

**Issue by zpnotes** [QMUI/QMUI_iOS#361]
### 请填写运行环境

- [x] 设备：`iPhone`
- [x] 系统：`iOS 11.4`
- [x] Xcode 版本：`9.4.1`
- [x] QMUI iOS 版本：`2.7.1`

### 请描述具体问题
使用懒加载定义UITableView时，如果设置tableFooterView会发生崩溃，不设置不会崩溃，崩溃代码定位 `UITableView+QMUI.m`中 26行 [self qmui_initWithFrame:frame style:style]; 堆栈信息见附件，单独写个Demo没有复现。使用QMUITableView也不会出现问题

#### 相关截图（断点的堆栈、控制台的 log）
<img width="1682" alt="2018-06-30 11 32 02" src="https://user-images.githubusercontent.com/17735379/42121082-a99c1e04-7c59-11e8-9c6f-b0b06ac9bf76.png">
<img width="399" alt="2018-06-30 11 32 25" src="https://user-images.githubusercontent.com/17735379/42121083-abcdabac-7c59-11e8-9eeb-65e8a8e2ebda.png">

**Comment by MoLice** [comment]
你可以尝试把 `UITableView+QMUI.m:30-40` 注释掉，看是否还有问题？

**Comment by zpnotes** [comment]
回滚代码试了一下，注释试了一下，还是一样。

**Comment by MoLice** [comment]
那应该就跟 QMUI 这个代码没关系，以及你说你单独写个 Demo 也没有复现，所以猜测问题还是出在业务代码上。单纯从第一个截图左边的调用堆栈来看，`setTableFooterView:` 触发了 `numberOfRowsInSection`，而后者内部又访问了 tableView 的 getter，导致重新初始化 tableView，然后 tableView 的初始化又触发了 `setTableFooterView:`，于是死循环了。你可以从这一点入手看看。

**Comment by zpnotes** [comment]
好的，感觉应该跟懒加载有关，懒加载去掉后运行正常。Thanks

**Comment by zpnotes** [comment]
可不可以拉我进QQ群
