### ISSUE TITLE
 如果nav的vc栈中有多个vc时，Hook返回时有点问题，请指教

### ISSUE THREAD

**Issue by Gavin123** [QMUI/QMUI_iOS#363]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题
假如 最后添加到栈中的A 和B ,这两个控制器我都hook了返回事件，在A中Hook之后我返回的时候我的逻辑是要跳到B ，然后B中我也hook了，B返回我需要返回到栈顶。 但是我点B的返回时，触发了A的Hook时的逻辑。   

在断点跟进的时候，发现跳转是正常的，但是非断点情况发生上述情况

**Comment by MoLice** [comment]
你指的 hook，具体是怎么实现的？贴一下相关代码？因为目前这个问题描述看起来不知道哪一处是与 QMUI 相关的。

**Comment by Gavin123** [comment]
[
![image](https://user-images.githubusercontent.com/5095402/42204349-045112e2-7ed4-11e8-9f3c-df8757a2710c.png)
](url)

这是支付界面，返回时需要跳到订单列表。

[
![image](https://user-images.githubusercontent.com/5095402/42204397-2d01894c-7ed4-11e8-8c42-e38e0d880c4c.png)
](url)

这是订单列表的返回事件。

目前遇到的情况是：在支付页面点返回时，会通过弹框点击事件进入到订单列表，点订单列表返回时会通过flag值判断是否返回到上一个页面还是栈顶的页面。 现在是订单列表返回时触发支付页面的返回事件。手势返回没问题，但点返回按钮会发生这个情况

**Comment by MoLice** [comment]
> 订单列表返回时触发支付页面的返回事件

你这里的“返回事件”是指 `canPopViewController`？`canPopViewController` 是一个状态询问方法，它可能被任意多次地调用（只要任意地方需要询问某个 viewController 的这个状态），所以当你在其中写一些业务逻辑的时候，也应该有这样的意识，就像你在 `viewWillAppear:` 里写业务逻辑，你也要清楚地意识到 `viewWillAppear:` 可能会被多次调用。

至于你这里为什么在这种操作下会触发 `canPopViewController`，是因为在 `UINavigationController` 试图 pop 一个 viewController 的时候，就会去询问这个 viewController 是否希望被 pop，所以就会调用到这个方法。

建议你自行区分不同场景下调用到这些方法时执行不同的业务逻辑。

**Comment by Gavin123** [comment]
hook返回事件不就是为了做一些业务的处理吗？    以上我主要想说明的是UINavigationController试图 pop 一个 viewController 的时候，会去询问当前这个 viewController 是否希望被 pop。 但不应该去询问上一个 viewController 是否希望被 pop吧。 现在出现的问题是这个

**Comment by MoLice** [comment]
如果你调用的是 popViewController，确实不会去询问前一个界面的 canPop。但你这里调用的是 popToRootViewController，它是会去试图 pop 掉当前所有的界面，所以每一个都询问 canPop 是符合预期的。
