### ISSUE TITLE
QMUINavigationController 返回按钮 的一个问题

### ISSUE THREAD

**Issue by bluesky335** [QMUI/QMUI_iOS#366]
### 请填写运行环境

- [x] 设备：`iPhone6 and iPhone 5`
- [x] 系统：`iOS 9.0 iOS 10.3.3`
- [x] Xcode 版本：`9.4.1`
- [x] QMUI iOS 版本：`2.6.2`

### 请描述具体问题

当我实现了
`- (nullable NSString *)backBarButtonItemTitleWithPreviousViewController:(nullable UIViewController *)viewController;`
方法的时候, 如果在ViewDidLoad中设置`self.navigationItem.hidesBackButton`为隐藏
并且启用了滑动手势返回

刚push进来时返回按钮正常的被隐藏掉了
但是当我在滑动边缘返回的时候取消返回的话,返回按钮会又显示出来
而且位置不定,有时候在中间有时候在最左边,它的frame大小也有问题,经常因为太小而显示为"..."

或者是我的使用姿势不对?   (╯°□°）╯︵┻━┻

顺便解释一下:

Q:为啥隐藏了返回按钮又把它画回来?
A:因为下面那条黄线

Q:为啥那条黄线不用ShadowImage?要自己画?
A:因为UI没给图,又懒得找他要╮(╯_╰)╭

#### 相关截图（断点的堆栈、控制台的 log）
![snipaste_2018-07-16_10-58-52](https://user-images.githubusercontent.com/13523898/42741726-644327ae-88e7-11e8-983c-0429ff42fb32.png)
![snipaste_2018-07-16_10-57-56](https://user-images.githubusercontent.com/13523898/42741729-65e1bb48-88e7-11e8-8e3c-1907ac8269ba.png)

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/47608406-8c931d80-da5f-11e8-8995-f544da286571.png)

经测试无法重现。
