### ISSUE TITLE
QMUIAlbumViewController点击相册出现死循环的情况

### ISSUE THREAD

**Issue by fanyuecheng** [QMUI/QMUI_iOS#369]
### 请填写运行环境

- [x] 设备：`iPhone 6s` / `模拟器`
- [x] 系统：`iOS 11.4`
- [x] Xcode 版本：`9.3`
- [x] QMUI iOS 版本：`2.7.3`

### 请描述具体问题
若某控制器持有QMUIAlbumViewController对象，并且present由该对象初始化的QMUINavigationController。
此时，点击任意相册，然后返回，点击“取消”，dismissViewController后，再次present由该对象初始化的QMUINavigationController，点击任意相册，将会断点进入UIViewController (QMUINavigationControllerTransition)的qmuiNav_viewWillAppear:方法，进入死循环。

另外，preview相片返回时，QMUIImagePickerPreviewViewController的topToolBarView隐藏的动画非常突兀，非iPhone X的机型，QMUIImagePickerViewController的view也会因为statusBar的显示突然整体向下位移20，感觉很不好。

#### 相关截图（断点的堆栈、控制台的 log）
![2018-07-24 4 35 37](https://user-images.githubusercontent.com/34535969/43126575-a3b5aaa0-8f5f-11e8-924e-73cef474c6ba.png)

**Comment by fanyuecheng** [comment]
解决方法只有让控制器不持有QMUIAlbumViewController,每次都初始化新的对象是吗？

**Comment by MoLice** [comment]
这两个问题确实存在，我们查一下。

第一个问题，暂时请先每次初始化新的 viewController。如果你是出于性能考虑的话，这里意义不是很大。

**Comment by MoLice** [comment]
2.7.4 已修复这两个问题。
