### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by zhoupIT** [QMUI/QMUI_iOS#37]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
写的好厉害.但是里面封装的控件耦合性太强了,以后会拆开吗,设计师稍微和我过不去,改点东西,很麻烦.

**Comment by MoLice** [comment]
感谢支持。
先回答前半句，目前暂时没有这个计划。因为 QMUI 的设计目的并非一个控件库，而是一个整体解决方案，以目前的设计方式，强耦合是不可避免的。不过大部分组件有耦合应该也只是与 MainFrame 里的那几个class 有耦合，可以把里面的代码复制出来加到你想要的控件里即可。
至于后半句，和强耦合关系不大，这或许是控件本身设计得不够灵活，才导致你做自定义时不方便。能否把实际例子描述一下（最好有截图），我们看看是否能通过改进控件的设计来满足你的需求。
