### ISSUE TITLE
TableViewCellBackgroundColor  配置未起作用

### ISSUE THREAD

**Issue by wxlpp** [QMUI/QMUI_iOS#370]
### 请填写运行环境

- [x] 设备：`iPhone`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`10.0`
- [x] QMUI iOS 版本：`2.7.3`

### 请描述具体问题
TableViewCellBackgroundColor  配置未起作用

**Comment by Sugarjunfeng** [comment]
设置配置表的其他属性,都是好着的吗?

**Comment by MoLice** [comment]
2.7.4 已修复此问题。
