### ISSUE TITLE
QMUIImagePickerCollectionViewCell的checked状态显示错误

### ISSUE THREAD

**Issue by fanyuecheng** [QMUI/QMUI_iOS#372]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.4`
- [x] Xcode 版本：`9.4.1`
- [x] QMUI iOS 版本：`2.7.3`

### 请描述具体问题
点击进入任意相册，点击任意相片查看预览，在QMUIImagePickerPreviewViewController中选中该相片，退回到QMUIImagePickerViewController，此时QMUIImagePickerCollectionViewCell的checked状态错误（非选中）。

如果将QMUIImagePickerViewController里collectionView:didSelectItemAtIndexPath:方法中，[self.imagePickerPreviewViewController startPreviewFromRectInScreenCoordinate:frame]改为原先的[self.navigationController pushViewController:self.imagePickerPreviewViewController animated:YES]，就没有这个错误。
因为前者不触发QMUIImagePickerViewController的viewWillAppear:方法，self.collectionView没有reloadData。

**Comment by MoLice** [comment]
2.7.4 已修复此问题。
