### ISSUE TITLE
QMUIImagePickerViewController选择照片的bug

### ISSUE THREAD

**Issue by make1a** [QMUI/QMUI_iOS#379]
- [x] QMUI iOS 版本：v2.7.4

### 请描述具体问题
1.进入进入相册选择
2.预览照片
3.点击右上角选中按钮
4.返回 （发现界面UI没有更新（数量不对、选中按钮状态也不对））

#### 相关截图（断点的堆栈、控制台的 log）
![image](https://user-images.githubusercontent.com/17469549/43695516-bbdfad18-996b-11e8-8038-88bb9de79267.png)

**Comment by MoLice** [comment]
从 Demo 的哪个界面进去？并没有重现你说的问题

**Comment by make1a** [comment]
点击 “默认” 进去的

**Comment by MoLice** [comment]
1. 点击进“默认”
2. 点击某张图进入大图预览
3. 选中右上角的 checkbox
4. 返回到九宫格界面
5. 右下角的按钮 enabled、数字，都是正确的。

我按照以上的操作并没有复现问题。如果操作步骤与你的不相同，请详细列出你的操作步骤，如果相同，请确认你的 QMUI 代码版本，如果 QMUI 代码版本也是最新的，可以的话麻烦录屏后把操作视频发送到 qmuiteam@qq.com。

**Comment by MoLice** [comment]
或者还有一个可能，就是之前 GitHub 上的 QMUI Demo 代码并非最新的，我用来复现的版本并没有这个问题。刚好下午发布了 2.7.5 版本，可以用最新的版本再验证一次？

**Comment by mail2chensh** [comment]
这个问题在2.7.3也存在。 
重现步骤为：
1.进入进入相册选择
2.预览照片
3.点击右上角选中按钮
4.返回 
发现选中的数量没有+1，也就是预览图的操作没有同步到外部的数量和状态。

**Comment by MoLice** [comment]
这个问题是中间版本的问题，请用最新版本的 2.7.5。
