### ISSUE TITLE
使用SearchViewController : QMUICommonTableViewController 导航栏pop隐藏不了

### ISSUE THREAD

**Issue by heyz-lzj** [QMUI/QMUI_iOS#38]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / 模拟器
- [x] 系统版本：`iOS 10.`
- [x] Xcode 版本：`8.2`

### 具体问题描述 ###
点击mySearchController 搜索结果cell didselect 执行 pop ,会显示一条灰色的导航栏
如何去除??

上个push的 是默认显示系统navigationbar 的,自定义了一个view的
#### 问题截图 ####
![2017-01-21 5 53 43](https://cloud.githubusercontent.com/assets/15118695/22173563/9b3bf130-e002-11e6-8e1f-3946706cf1ce.png)
![2017-01-21 5 53 50](https://cloud.githubusercontent.com/assets/15118695/22173564/9dd9cac0-e002-11e6-9a1d-39e5709eaa0f.png)

希望获得相关帮助 谢谢

**Comment by MoLice** [comment]
目测是因为第二个截图的 `viewController.view.frame.origin.y` 是 64，`navigationBar` 背后其实是黑色，所以导致磨砂出来的颜色与第一个截图不一样。你可以检查一下看看是否如此。

**Comment by heyz-lzj** [comment]
是的，第二个截图是有个自定义view 作为导航栏，viewController.view.frame.origin.y确实是64，如果点击非搜索结果的cell pop回去没有这个导航栏问题，而点击mySearchController 搜索结果cell 就有

**Comment by heyz-lzj** [comment]
增加了`if ([self respondsToSelector:@selector(edgesForExtendedLayout)]) {
        self.edgesForExtendedLayout = UIRectEdgeTop;
    }
`
会这样子,然而还是存在这个导航栏,
![2017-01-22 11 16 48](https://cloud.githubusercontent.com/assets/15118695/22179623/4e01bc6e-e094-11e6-96a7-5b574c318f2b.png)

- (void)viewDidAppear:(BOOL)animated{
    [self.navigationController setNavigationBarHidden:YES];
}
只有这样才行,不过会闪一下整体移动..

**Comment by MoLice** [comment]
哦，明白了，原来你是要去掉 `navigationBar`，我以为你是在说 `navigationBar` 的背景色错误。

如果要去掉 `navigationBar`，确实得自己手动用 `[self.navigationController setNavigationBarHidden:YES]` 隐藏才行，这个应该和 QMUI 没有关系，也不需要处理 `edgesForExtendedLayout`。

如果要解决闪一下的问题，可以尝试用 `[self.navigationController setNavigationBarHidden:YES animated:YES]`，另外试一下在其他时机调用，包括 didSelect 时、`viewWillDisappear:` 时。

另外 QMUI 下一个新版本可能也会加上对这种“两个界面切换时前后的 bar 的显隐状态不一致”的优化，到时可以留意一下。

**Comment by heyz-lzj** [comment]
嗯 谢谢!
