### ISSUE TITLE
QMUIImagePreviewViewController的bug

### ISSUE THREAD

**Issue by hydreamit** [QMUI/QMUI_iOS#380]
### 请描述具体问题

使用渐隐的动画退出图片预览方法【 - (void)exitPreviewByFadeOut 】时 ，当再次点击图片预览时，预览图层的黑色半透明背景没了，使用另外方法【- (void)exitPreviewToRectInScreenCoordinate:(CGRect)rect】才行，从指定 rect 的位置以动画的形式进入预览 方法【- (void)startPreviewFromRectInScreenCoordinate:(CGRect)rect】位置不对

#### 相关截图（断点的堆栈、控制台的 log）

![simulator screen shot - iphone x - 2018-08-08 at 12 14 22](https://user-images.githubusercontent.com/14271494/43815905-9d38bf40-9b04-11e8-94f3-f963e94b1cd0.png)

**Comment by MoLice** [comment]
2.7.6 已修复
