### ISSUE TITLE
emptyView

### ISSUE THREAD

**Issue by BINUIKit** [QMUI/QMUI_iOS#381]
emptyView默认全屏幕frame，没有数据列表下View还有其他按钮等需要点击被挡住 ，怎么修改frame？
是否可以考虑使用TableView 的tableHeaderView或者tableFooterView 做这个emptyView？

**Comment by MoLice** [comment]
`QMUICommonViewController.h` 里已经有 `layoutEmptyView` 可以用了，而 `QMUICommonTableViewController` 继承自 `QMUICommonViewController`，所以自行重写即可。
