### ISSUE TITLE
UINavigationController+QMUI.m类 --- 方法 gestureRecognizerShouldBegin  

### ISSUE THREAD

**Issue by LJW008** [QMUI/QMUI_iOS#382]
### 请填写运行环境

- [x] 设备：`iPhone`
- [x] 系统：`iOS 9.3.3`
- [x] Xcode 版本：`9.3.1`
- [x] QMUI iOS 版本：`2.7.3`

### 请描述具体问题
你好，请求下这个类拦截返回拦截和手势的一些操作，我在rootVC 左滑为什么没调用 gestureRecognizerShouldBegin方法呢，正常不作处理是会调用的，请求下你们这个没调用是在哪处理的呢，谢谢

**Comment by MoLice** [comment]
> 正常不作处理是会调用的

请问你是如何确定不作处理是会调用的？

**Comment by LJW008** [comment]
你好，我在nav里写的这个方法，滑动返回是会调用的，滑倒第一个也会调用，但是我看咱们的demo没调用，不知道怎么处理了，所以请教下

**Comment by MoLice** [comment]
我指的是你的具体代码，你现在的补充说明，其实和你原来的文字描述，是一样的，没有带来更多信息。我只能做如下猜测：

你继承 `UINavigationController` 写了自己的子类，在里面将 `self.interactivePopGestureRecognizer.delegate = self`，然后只实现 `gestureRecognizerShouldBegin:`，然后发现在 rootViewController 里手势返回时没有走进去？

如果我猜测的没错的话，那么原因是：

1. UINavigationController.interactivePopGestureRecognizer.delegate 原本就非空，你这样直接将其改为 `self`，会丢失原有的 delegate 的实现。
2. 系统在这种情况下其实是不会调用 `gestureRecognizerShouldBegin:` 的，正因为你错误地重置了 delegate，导致原来的 delegate 里的 `gestureRecognizer:shouldReceiveTouch:` 系列的方法都不会被调用，而系统正是通过在 `gestureRecognizer:shouldReceiveTouch:` 里返回 NO，来阻止 rootViewController 手势返回时触发 `gestureRecognizerShouldBegin:`。

所以，QMUI 的表现并没有问题。
