### ISSUE TITLE
非主线程调用问题

### ISSUE THREAD

**Issue by dqb101140127** [QMUI/QMUI_iOS#383]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

#### 相关截图（断点的堆栈、控制台的 log）
![08b68b57-acac-49a8-a026-f4a50d8189cb](https://user-images.githubusercontent.com/13044675/44134056-9b902a34-a095-11e8-89aa-be24e5bb8230.png)

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/44190608-23875380-a15a-11e8-861a-2e305513952a.png)

请将 UIView+QMUI.m 里这几行注释掉再测试看是否会出现这个警告。

目测这个问题与 QMUI 无关，因为看你的截图，最开始是 PLCropOverlay 先在非主线程调用了 `[UIView convertRect:fromView:]`，换句话说，就算 QMUI 不修改 `convertRect:fromView:` 的代码，也依然会有这个报错。
