### ISSUE TITLE
 qmui_borderColor qmui_borderWidth  方法不管用

### ISSUE THREAD

**Issue by lyc59621** [QMUI/QMUI_iOS#385]
### 请填写运行环境

- [x] 设备： `模拟器`
- [x] 系统：`iOS 11.4`
- [x] Xcode 版本：`9.4.1`
- [x] QMUI iOS 版本：`2.7.5`

### 请描述具体问题
 QMUIButton  *btn = [QMUIButton  buttonWithType:UIButtonTypeSystem];
    btn.frame = CGRectMake(30, 300, 200, 40);
    [btn setTitle:@"dwadwada" forState:UIControlStateNormal];
    [btn setBackgroundColor:[UIColor redColor]];
    btn.qmui_borderColor = [UIColor orangeColor];
    btn.qmui_borderWidth = 4;
   [self.view  addSubview:btn];

设置完不管用

而且用xib 设置 相关属性也是不管用
#### 相关截图（断点的堆栈、控制台的 log）

<img width="789" alt="2018-08-17 5 32 30" src="https://user-images.githubusercontent.com/8717225/44259240-8ef92000-a243-11e8-99cf-e5c1979ffcc2.png">
<img width="306" alt="2018-08-17 5 32 10" src="https://user-images.githubusercontent.com/8717225/44259244-91f41080-a243-11e8-9fc2-2d60adfd665a.png">

**Comment by lyc59621** [comment]
我对比了下使用SUIUtils 这个库设置相关属性完全没问题，而使用QMUIKit 设置就无作用！
请看我demo的相关代码和截图 和使用SUIUtils 方法做的对比
<img width="562" alt="2018-08-17 5 51 52" src="https://user-images.githubusercontent.com/8717225/44260647-a76b3980-a247-11e8-893e-f80f7845c4d2.png">
<img width="448" alt="2018-08-17 5 51 45" src="https://user-images.githubusercontent.com/8717225/44260654-aafec080-a247-11e8-8710-afb095e7cdd4.png">
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8717225/44260659-adf9b100-a247-11e8-9856-26750e43e9bd.gif)

**Comment by MoLice** [comment]
因为你没有设置 `qmui_borderPosition`。看你的需求你是要给按钮的上下左右全加边框，这种需求，用系统自带的接口去实现已经足够方便，无需借助第三方框架。QMUI 提供的边框功能也不是为了满足这种需求，请自行阅读注释。

![image](https://user-images.githubusercontent.com/1190261/44319607-81c07900-a46f-11e8-820d-5f4c88026f10.png)

**Comment by lyc59621** [comment]
多谢啦，我没理解清楚

**Comment by MoLice** [comment]
文档、注释已相对齐全，请先仔细阅读。

**Comment by shuiliang** [comment]
QMUI里，UIView的背景色能直接加两种颜色让它成渐变色吗？

**Comment by MoLice** [comment]
非常见需求，暂不支持。请使用 CAGradientLayer。
