### ISSUE TITLE
关于 QMUIButton 中 setEnabled 的一个疑问

### ISSUE THREAD

**Issue by ziecho** [QMUI/QMUI_iOS#387]
### 请填写运行环境

- [x] 设备：` All`
- [x] 系统：`iOS 12`
- [x] Xcode 版本：`9.3`
- [x] QMUI iOS 版本：`2.7.5`

### 请描述具体问题

QMUIButton 中的 setEnabled 方法如下

``` objc

- (void)setEnabled:(BOOL)enabled {
    [super setEnabled:enabled];
    if (!enabled && self.adjustsButtonWhenDisabled) {
        self.alpha = ButtonDisabledAlpha;
    } else {
        [UIView animateWithDuration:0.25f animations:^{
            self.alpha = 1;
        }];
    }
}

```

这里有个疑问 为什么 在 enable == YES 的时候，将 alpha 改成 1 的时候会执行一个 0.25 秒的动画？
这样做导致我有一个 collectionView 在重用的时候，当 Button 从 disable 变成 enable 的时候会有这个透明度变化的动画看起来非常奇怪。

我只能在代码里这么写 - -! 

``` objc
[UIView performWithoutAnimation:^{
    self.button.enabled = buttonEnable;
 }];
```

**Comment by MoLice** [comment]
这里的设计思路比较陈旧，应该区分无动画的 `setEnabled:` 和有动画的 `setEnabled:animated:`，感谢提出，后续优化。

**Comment by MoLice** [comment]
2.7.6 已去掉这个动画
