### ISSUE TITLE
UINavigationController分类导致UISplitViewController里的返回动画不正确

### ISSUE THREAD

**Issue by SuperZico** [QMUI/QMUI_iOS#388]
### 请填写运行环境

- [x] 设备： `iPad` 
- [x] 系统：`iOS 11.4`
- [x] Xcode 版本：`9.2`
- [x] QMUI iOS 版本：`2.7.5`

### 请描述具体问题
UISplitViewController 的detailController里push出AController之后，点击返回，返回动画会从偏左侧开始，造成动画闪动，删除QMUIKit用原生的UINavigationController之后这个情况消失

如下图，点击back之后，返回动画从测试title那里开始
#### 相关截图（断点的堆栈、控制台的 log）
![img_0015](https://user-images.githubusercontent.com/13212385/44445288-f1229e00-a612-11e8-842b-d653da6ce56d.PNG)

**Comment by MoLice** [comment]
经测试并没有发现这个问题，请自行排查是否有其他代码影响，或者提供有问题的 Demo 到 qmuiteam@qq.com。

**Comment by SuperZico** [comment]
测试了下是因为勾选了Device Orientation里的Portrait但是Controller强制横屏导致的问题，不是QM的问题，在Controller里把自动旋屏关闭即可
