### ISSUE TITLE
Xcode playground下的报错

### ISSUE THREAD

**Issue by frankxzx** [QMUI/QMUI_iOS#39]
### 运行环境 ###

-  iOS 设备：Xcode playground
-  系统版本：iOS 10.0
-  Xcode 版本：8.2

=== 报错如下 ===
- objc[75558]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x116055998) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x115dd4880). One of the two will be used. Which one is undefined.

=============

stackoverflow:(http://stackoverflow.com/questions/39520499/class-plbuildversion-is-implemented-in-both-frameworks)

在oc中有类名冲突, 我想在playground中使用,有什么好的解决方法吗？

**Comment by zhoon** [comment]
在Playground下面使用第三方库我们还没有怎么实践，查了一下好像这方面也存在不少坑，所以目前我们没有什么好的解决方法，建议还是新建一个项目使用，感谢支持。
