### ISSUE TITLE
pod 目录结构不是真实的目录结构

### ISSUE THREAD

**Issue by LJW008** [QMUI/QMUI_iOS#392]
### 请填写运行环境

- [x] 设备：`iPhone``
- [x] 系统：`iOS 11.4`
- [x] Xcode 版本：`9.3`
- [x] QMUI iOS 版本：`2.7.6`

### 请描述具体问题
你好，为什么我pod下来的库的目录跟文件夹里的真实目录结构不是一致的呢？
#### 相关截图（断点的堆栈、控制台的 log）

![1512f8a6-1e92-441e-9f8c-8a3888152e72](https://user-images.githubusercontent.com/11679563/44896581-48cda300-acbe-11e8-9cae-2565e4ad0611.png)
![be42e7c2-2e27-4451-ab47-89d1fb14b486](https://user-images.githubusercontent.com/11679563/44896582-48cda300-acbe-11e8-814e-8dbdbe46266c.png)

**Comment by MoLice** [comment]
请自行了解 Xcode Group 概念、CocoaPods 知识，此问题与 QMUI 无关。
