### ISSUE TITLE
设置BarButtonItem = nil 的崩溃问题

### ISSUE THREAD

**Issue by fanyuecheng** [QMUI/QMUI_iOS#398]
### 请填写运行环境

- [x] 设备：`模拟器`
- [x] 系统：`iOS 11.3`
- [x] Xcode 版本：`9.4.1`
- [x] QMUI iOS 版本：`2.7.6`

### 请描述具体问题
QMUINavigationButton.m 文件 UINavigationItem (QMUINavigationButton)中

系统 < iOS 11 下，在setupNavigationItems设置
self.navigationItem.leftBarButtonItem = nil;  (或者 rightBarButtonItem)
在滑动返回时会崩溃
因为直接使用了 @[item]

将QDUIKitViewController的rightBarButtonItem设置为nil，点击任意Controller，滑动返回即可复现。

**Comment by MoLice** [comment]
确实，我们会尽快发布新版本修复这个bug。

**Comment by MoLice** [comment]
2.8.0 已修复
