### ISSUE TITLE
`QMUIModalPresentationViewController`内调用了iOS 9之后才有的`loadViewIfNeeded`

### ISSUE THREAD

**Issue by xilin** [QMUI/QMUI_iOS#4]
没有继承`QMUICommonViewController `，在iOS 8上crash了
这个类是设计成只能在iOS 9之后使用吗？

**Comment by MoLice** [comment]
这个问题已修复，请更新重试。
另，以前只在`QMUICommonViewController` 里对 `loadViewIfNeeded` 做了 iOS 版本的兼容，这次更新把范围扩大到所有的 `UIViewController` 了，具体可查看 `UIViewController+QMUI.m` 文件。
