### ISSUE TITLE
QMUIFloatLayoutView 如何右对齐?

### ISSUE THREAD

**Issue by heyz-lzj** [QMUI/QMUI_iOS#40]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
现在的QMUIFloatLayoutView 默认都是左对齐,希望可以增加右对齐的方法

**Comment by MoLice** [comment]
你好，刚刚增加了这个功能，请更新代码，查看 `QMUIFloatLayoutView.h` 的注释，使用 `contentMode = UIViewContentModeRight` 即可实现你的需求。
