### ISSUE TITLE
使用UITableView (QMUICellHeightKeyCache)配合Masonry 动态cell高度不正确

### ISSUE THREAD

**Issue by LH-Liu** [QMUI/QMUI_iOS#401]
### 请填写运行环境

- [1] 设备：`iPhone` / `iPad` / `模拟器`
- [2] 系统：`iOS 11.4`
- [3] Xcode 版本：`9.4.1`
- [4] QMUI iOS 版本：`2.7.2`

### 使用UITableView (QMUICellHeightKeyCache)配合Masonry 自定义cell，cell高度有问题。经断点查看是在sizeThatFits方法中无法正确获取label高度。
![image](https://user-images.githubusercontent.com/14884787/45620653-31f5c180-bab0-11e8-9eaf-abc1b79cdc26.png)
###使用过程：
```
1. self.tableView.estimatedRowHeight = 120;
    self.tableView.qmui_cacheCellHeightByKeyAutomatically = YES;
自定义cell，设置masonry布局，实现sizeThatFits方法。
//经断点发现，cell中一个label动态变换高度，在sizeThatFits方法中高度不正确，如：label显示三行，高度返回36。或label显示两行，高度返回18.
2.实现 - (id<NSCopying>)qmui_tableView:(UITableView *)tableView cacheKeyForRowAtIndexPath:(NSIndexPath *)indexPath方法
```
***
问：经反复检查代码，未发现自身问题，因首次采用QMUI，不知是否是UITableView (QMUICellHeightKeyCache)问题？

**Comment by MoLice** [comment]
你已经界定出问题是处在 label 了，所以与 cell、cache height 这些是没关系的。

至于为什么 label 的 sizeThatFits 计算出来错误，猜测是，你的 label 最终布局时，width 是 A，但你在截图里红色线划出来的地方传进去的 size 的 width 并不是 A，而是另一个值 B。只要 A 和 B 不相等，你这样计算出来的 size 肯定就是不准确的。

如果猜测无误，那么解决方式就是你自己想办法保证 sizeThatFits 时传给 label 的 width 和你最终布局 label 时 label 的 width 一致即可。

**Comment by LH-Liu** [comment]
解决了。感谢！是我自己问题。另外，QMUIKit在新项目使用中，非常赞！👍感谢开源！
