### ISSUE TITLE
根据targetSize获取高清图

### ISSUE THREAD

**Issue by lcddhr** [QMUI/QMUI_iOS#403]
### 请描述具体问题
`QMUIAsset`类中`requestOriginImageWithCompletion`接口，如果想在请求图片的时候根据targetSize返回相应的大小, 应该如何设置呢？

#### 测试
1. 测试过 size 为8688 × 5792 图片，取出来的图片结果与原图 size 不符
2. size 为 4032 x 2068 的图片，相同的机型，有些iPhone 8 Plus可以获取到4032 x 2068的图片，有些只能获取到2304*1536图片

contenModel ：PHImageContentModeAspectFit

targetSize ： 4032*2068

PHImageRequestOptions *request = [PHImageRequestOptions new];
 request.deliveryMode = PHImageRequestOptionsDeliveryModeHighQualityFormat;
request.resizeMode = PHImageRequestOptionsResizeModeExact;
 request.version = PHImageRequestOptionsVersionCurrent;
 request.networkAccessAllowed = NO;
request.synchronous = YES;

你们有遇到类似的情况吗？

**Comment by kayo5994** [comment]
关于“请求图片的时候根据targetSize返回相应的大小”，可以直接使用系统  `PHCachingImageManager` 的 `requestImageForAsset` 系列方法，支持传入指定的 targetSize。

关于测试的两点内容：
1. “测试过 size 为8688 × 5792 图片，取出来的图片结果与原图 size 不符”，不知道是不是指取出来的图片宽高小于 5000，如果是的话，这是系统 `PHCachingImageManager ` 的限制，导致最后输出的 `UIImage` 最多也只能是 5000 * 5000 的大小，可以参考#356。**但最近测试过，在 iOS 12 中已经没有这个问题。**
2. 第二点的问题这边没能重现，建议使用 iOS 12 进行测试。
