### ISSUE TITLE
QMUIImagePickerPreviewViewController在改变设备方向时，topToolBarView和backButton的布局问题

### ISSUE THREAD

**Issue by fanyuecheng** [QMUI/QMUI_iOS#404]
### 请填写运行环境

- [x] 设备：`模拟器 iPhone XR`
- [x] 系统：`iOS 12.0`
- [x] Xcode 版本：`10.0`
- [x] QMUI iOS 版本：`2.8.0`

### 请描述具体问题
项目支持所有方向时，在浏览相册图片时改变设备方向，QMUIImagePickerPreviewViewController的backButton frame错乱，退出控制器后再次进入，topToolBarView不再显示，消失了

**Comment by MoLice** [comment]
确实，我们发个小版本修复。

**Comment by MoLice** [comment]
2.8.1 已修复该问题
