### ISSUE TITLE
更新到 2.8.1 版本报错

### ISSUE THREAD

**Issue by wyt666** [QMUI/QMUI_iOS#405]
### 请填写运行环境

- [x] 设备：`iPhone`
- [x] 系统：`iOS 12.1`
- [x] Xcode 版本：`10.1 beta`
- [x] QMUI iOS 版本：`2.8.1`

#### 相关截图（断点的堆栈、控制台的 log）
<img width="1207" alt="qq20180927-112344 2x" src="https://user-images.githubusercontent.com/15173846/46122000-16757e00-c249-11e8-84ba-639f2cf89290.png">

**Comment by MoLice** [comment]
你是用 CocoaPods 引入？请贴一下你的 Podfile 写法

**Comment by wyt666** [comment]
@MoLice   是用 CocoaPods 引入的，  2.7.6版本的就不会报错，2.8.0和2.8.1都会报这个错
<img width="696" alt="qq20180929-083833 2x" src="https://user-images.githubusercontent.com/15173846/46238844-329d2a80-c3c3-11e8-9229-fb94d649a905.png">

**Comment by MoLice** [comment]
建议 clean 试试，QMUIKit 本身是没问题的

**Comment by wyt666** [comment]
好的，已经不报错了
