### ISSUE TITLE
QMUIModalPresentationViewController以present形式弹出，不能旋转

### ISSUE THREAD

**Issue by xmalt** [QMUI/QMUI_iOS#407]
### 请填写运行环境

- [x] 设备：iPhone
- [x] 系统：iOS 12
- [x] Xcode 版本：10.0
- [x] QMUI iOS 版本：2.8.0

### 请描述具体问题

App Store上的demo支持旋转，最新demo以及库都不支持旋转

**Comment by xmalt** [comment]
而且一调用就会显示【qmui_visibleViewControllerIfExist:，找不到可见的viewController】

**Comment by MoLice** [comment]
我们查一下看看

**Comment by MoLice** [comment]
[2.9.0](https://github.com/QMUI/QMUI_iOS/releases/tag/2.9.0) 已修复这个问题。
