### ISSUE TITLE
QMUITips 可否提供一个一个类方法hide all QMUITips?

### ISSUE THREAD

**Issue by heyz-lzj** [QMUI/QMUI_iOS#41]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
需求是通过类方法创建一个showLoading view,但是存在隐藏的条件有很多,不希望在当前控制器创建一个全局变量来控制隐藏这个Loading view

#### 问题截图 ####
可否提供一个类似 hide hud 的全局类方法呢?

**Comment by MoLice** [comment]
`QMUITips` 继承自 `QMUIToastView`，你可以查看[QMUIToastView.h:163-171](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIComponents/QMUIToastView.h#L163-L171)，这里提供了一个方法：
```Objective-C
/**
 * 工具方法。隐藏`view`里面的所有ToastView。
 *
 * @param view 即将隐藏的ToastView的superView。
 * @param animated 是否需要通过动画隐藏。
 *
 * @return 如果成功隐藏一个ToastView则返回YES，失败则NO。
 */
+ (BOOL)hideAllToastInView:(UIView *)view animated:(BOOL)animated;
```

是否就是你想要的功能？

**Comment by heyz-lzj** [comment]
感谢回复！正是这个方法希望可以完善下接口文档哈发自网易邮箱大师
            在2017年02月06日 11:36，MoLice 写道:QMUITips 继承自 QMUIToastView，你可以查看QMUIToastView.h:163-171，这里提供了一个方法：
/**
 * 工具方法。隐藏`view`里面的所有ToastView。
 *
 * @param view 即将隐藏的ToastView的superView。
 * @param animated 是否需要通过动画隐藏。
 *
 * @return 如果成功隐藏一个ToastView则返回YES，失败则NO。
 */
+ (BOOL)hideAllToastInView:(UIView *)view animated:(BOOL)animated;
是否就是你想要的功能？

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/QMUI/QMUI_iOS","title":"QMUI/QMUI_iOS","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/QMUI/QMUI_iOS"}},"updates":{"snippets":[{"icon":"PERSON","message":"@MoLice in #41: `QMUITips` 继承自 `QMUIToastView`，你可以查看[QMUIToastView.h:163-171](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIComponents/QMUIToastView.h#L163-L171)，这里提供了一个方法：\r\n```Objective-C\r\n/**\r\n * 工具方法。隐藏`view`里面的所有ToastView。\r\n *\r\n * @param view 即将隐藏的ToastView的superView。\r\n * @param animated 是否需要通过动画隐藏。\r\n *\r\n * @return 如果成功隐藏一个ToastView则返回YES，失败则NO。\r\n */\r\n+ (BOOL)hideAllToastInView:(UIView *)view animated:(BOOL)animated;\r\n```\r\n\r\n是否就是你想要的功能？"}],"action":{"name":"View Issue","url":"https://github.com/QMUI/QMUI_iOS/issues/41#issuecomment-277579633"}}}
