### ISSUE TITLE
UITabBar layout is broken on iOS 12.1

### ISSUE THREAD

**Issue by ziecho** [QMUI/QMUI_iOS#410]
### 请填写运行环境

- [x] 设备：` iPhone X、 iPhone 7 puls `
- [x] 系统：`iOS 12.1`
- [x] Xcode 版本：`10.0`
- [x] QMUI iOS 版本：`2.8.1`

### 请描述具体问题

QMUI Demo 注释掉配置 tabBarBackgroundImage 后可复现：

```objc
//    QMUICMI.tabBarBackgroundImage = [[UIImage qmui_imageWithColor:UIColorMake(249, 249, 249)] resizableImageWithCapInsets:UIEdgeInsetsMake(1, 1, 1, 1)];                     // TabBarBackgroundImage : UITabBar 的背景图
```

#### 相关截图（断点的堆栈、控制台的 log）

![image](https://user-images.githubusercontent.com/16473618/46779433-5dd03400-cd4a-11e8-818e-42728b0f963f.png)

**Comment by MoLice** [comment]
待 12.1 正式版发布后再看这个问题是否还存在

**Comment by MoLice** [comment]
实测这个问题是 iOS 12.1 Beta 3 的问题，只要 UITabBar 是磨砂的，并且 push viewController 时 `hidesBottomBarWhenPushed = YES` 则手势返回的时候就会触发。

出现这个现象的直接原因是 tabBar 内的按钮 `UITabBarButton` 被设置了错误的 frame，`frame.size` 变为 `(0, 0)` 导致的。

如果需要，可以使用以下临时修补代码，待发布的 QMUI 新版里也会带上这部分代码，等到 iOS 12.1 正式版发布后如果这个问题被修复，我们也会把这段代码移除。

```
+ (void)load {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        if (@available(iOS 12.1, *)) {
            OverrideImplementation(NSClassFromString(@"UITabBarButton"), @selector(setFrame:), ^id(__unsafe_unretained Class originClass, SEL originCMD, IMP originIMP) {
                return ^(UIView *selfObject, CGRect firstArgv) {
                    
                    if ([selfObject isKindOfClass:originClass]) {
                        if (!CGRectIsEmpty(selfObject.frame) && CGRectIsEmpty(firstArgv)) {
                            return;
                        }
                    }
                    
                    // call super
                    void (*originSelectorIMP)(id, SEL, CGRect);
                    originSelectorIMP = (void (*)(id, SEL, CGRect))originIMP;
                    originSelectorIMP(selfObject, originCMD, firstArgv);
                };
            });
        }
    });
}
```

**Comment by wyt666** [comment]
如果这个问题没有被修复的话，在UITabBar 的- (void)layoutSubviews 方法中重新给UITabBarButton设置frame也可以解决这个问题

**Comment by MoLice** [comment]
> 如果这个问题没有被修复的话，在UITabBar 的- (void)layoutSubviews 方法中重新给UITabBarButton设置frame也可以解决这个问题

@wyt666 那就需要自己去计算 button 的 frame，那样不是很合理。

**Comment by xiaoxiongke** [comment]
赞一下~~:)

**Comment by ziecho** [comment]
实测 iOS 12.1 正式版还未修复此 BUG

**Comment by zhaoquntao** [comment]
iOS 12正式版并没有修复 这个bug

**Comment by 814349837** [comment]
iOS 12.1 正式版 bug依然存在

**Comment by bawn** [comment]
@ziecho @zhaoquntao @814349837 重写 Tabbar 的解决方式可行

https://gist.github.com/bawn/68e9c20caf785ba3ce20efd3d38a18a2

**Comment by MoLice** [comment]
[2.9.0](https://github.com/QMUI/QMUI_iOS/releases/tag/2.9.0) 已带上这个修复。

**Comment by dingchuandong** [comment]
用上面的方法 
iPhone X tabbar还是会出现一定的下移的呢
其他设备可以

**Comment by MoLice** [comment]
@dingchusndong 你说的是#422 吧？那是另一个问题，与这个无关。

**Comment by dingchuandong** [comment]
嗯 是滴 我在特殊处理下 感谢

**Comment by dingchuandong** [comment]
iOS 12.1 列表加载更多会自动回滚到顶部你们有遇到吗

**Comment by fujianjin6471** [comment]
> 实测这个问题是 iOS 12.1 Beta 2 的问题，只要 UITabBar 是磨砂的，并且 push viewController 时 `hidesBottomBarWhenPushed = YES` 则手势返回的时候就会触发。
> 
> 出现这个现象的直接原因是 tabBar 内的按钮 `UITabBarButton` 被设置了错误的 frame，`frame.size` 变为 `(0, 0)` 导致的。
> 
> 如果需要，可以使用以下临时修补代码，待发布的 QMUI 新版里也会带上这部分代码，等到 iOS 12.1 正式版发布后如果这个问题被修复，我们也会把这段代码移除。
> 
> ```
> + (void)load {
>     static dispatch_once_t onceToken;
>     dispatch_once(&onceToken, ^{
>         if (@available(iOS 12.1, *)) {
>             OverrideImplementation(NSClassFromString(@"UITabBarButton"), @selector(setFrame:), ^id(__unsafe_unretained Class originClass, SEL originCMD, IMP originIMP) {
>                 return ^(UIView *selfObject, CGRect firstArgv) {
>                     
>                     if ([selfObject isKindOfClass:originClass]) {
>                         // 如果发现即将要设置一个 size 为空的 frame，则屏蔽掉本次设置
>                         if (!CGRectIsEmpty(selfObject.frame) && CGRectIsEmpty(firstArgv)) {
>                             return;
>                         }
>                     }
>                     
>                     // call super
>                     void (*originSelectorIMP)(id, SEL, CGRect);
>                     originSelectorIMP = (void (*)(id, SEL, CGRect))originIMP;
>                     originSelectorIMP(selfObject, originCMD, firstArgv);
>                 };
>             });
>         }
>     });
> }
> ```

那如果UITabBar不是磨砂的呢？好像这个问题仍然存在，修改isTranslucent不起作用

**Comment by fujianjin6471** [comment]
iOS 12.1.1 Beta 3仍未修复

**Comment by MoLice** [comment]
> > 实测这个问题是 iOS 12.1 Beta 2 的问题，只要 UITabBar 是磨砂的，并且 push viewController 时 `hidesBottomBarWhenPushed = YES` 则手势返回的时候就会触发。
> > 出现这个现象的直接原因是 tabBar 内的按钮 `UITabBarButton` 被设置了错误的 frame，`frame.size` 变为 `(0, 0)` 导致的。
> > 如果需要，可以使用以下临时修补代码，待发布的 QMUI 新版里也会带上这部分代码，等到 iOS 12.1 正式版发布后如果这个问题被修复，我们也会把这段代码移除。
> > ```
> > + (void)load {
> >     static dispatch_once_t onceToken;
> >     dispatch_once(&onceToken, ^{
> >         if (@available(iOS 12.1, *)) {
> >             OverrideImplementation(NSClassFromString(@"UITabBarButton"), @selector(setFrame:), ^id(__unsafe_unretained Class originClass, SEL originCMD, IMP originIMP) {
> >                 return ^(UIView *selfObject, CGRect firstArgv) {
> >                     
> >                     if ([selfObject isKindOfClass:originClass]) {
> >                         // 如果发现即将要设置一个 size 为空的 frame，则屏蔽掉本次设置
> >                         if (!CGRectIsEmpty(selfObject.frame) && CGRectIsEmpty(firstArgv)) {
> >                             return;
> >                         }
> >                     }
> >                     
> >                     // call super
> >                     void (*originSelectorIMP)(id, SEL, CGRect);
> >                     originSelectorIMP = (void (*)(id, SEL, CGRect))originIMP;
> >                     originSelectorIMP(selfObject, originCMD, firstArgv);
> >                 };
> >             });
> >         }
> >     });
> > }
> > ```
> 
> 那如果UITabBar不是磨砂的呢？好像这个问题仍然存在，修改isTranslucent不起作用

实测用 backgroundImage 的 tabBar 并不存在这个问题。

**Comment by codingiran** [comment]
12.1.1正式版已经修复此问题

**Comment by MoLice** [comment]
[2.9.3](https://github.com/Tencent/QMUI_iOS/releases/tag/2.9.3) 版本里已加上 < 12.1.1 的判断。

**Comment by MoLice** [comment]
[4.2.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.2) 版本已去除该修复代码关联的配置表开关，现改为默认修复。
