### ISSUE TITLE
是否能够屏蔽QMUIDialogTextFieldViewController里对键盘的适配功能？

### ISSUE THREAD

**Issue by xiaoyaoyouzi163com** [QMUI/QMUI_iOS#411]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

**Comment by MoLice** [comment]
请表达清楚，“对键盘的适配功能”具体是指什么？

**Comment by xiaoyaoyouzi163com** [comment]
就是目前在项目用到了IQkeyBoardManager和QMui。然后在某个页面上使用QMUIDialogTextFieldViewController弹出视图时。可以明显地看到程序对于键盘的适配会导致该视图跳一下（先上后下）。据分析，是先是QMui对键盘的适配。让QMUIDialogTextFieldViewController.view整个滚动上升了一个键盘的高度。然后IQkeyBoardManager对textfield适配。导致QMUIDialogTextFieldViewController.view有滚动到textfield刚好到键盘高度的位置。

**Comment by xiaoyaoyouzi163com** [comment]
![图片](https://xiaoyaoyouzi-1256826974.cos.ap-chengdu.myqcloud.com/22222.gif)
大概是图片里的样子。只是图片里看起来不是那么明显。实际中有时候出现一个很夸张的闪跳。目前我是把这个contoller里的IQKeyboardManager给关闭了。我就是先问一下，咱们这个里面有没有类似于IQKeyboardManager的关闭适配的功能。我自己在代码里没有找到。。

**Comment by MoLice** [comment]
`QMUIDialogTextFieldViewController` 里对键盘高度的响应，是在 `QMUIModalPresentationViewController` 里统一实现的，具体可看 [contentViewFrameForShowing](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/QMUIComponents/QMUIModalPresentationViewController.m#L534-L547)。

目前没有专门设计屏蔽键盘响应的接口，如果需要，可通过为 `dialogViewController.modalPresentationViewController.layoutBlock`赋值，重写自己的 dialogViewController 的布局，block 参数已经有把键盘高度传进来。

不过，从你的 GIF 效果来看，这个场景下显然你应该禁用 `IQKeyboardManager` 才对？否则键盘会盖住你的 dialog 操作按钮。

**Comment by xiaoyaoyouzi163com** [comment]
好的，我晚点仔细看一下。谢谢~！~！~！
