### ISSUE TITLE
Plain类型的   heightForHeaderInSection 

### ISSUE THREAD

**Issue by LJW008** [QMUI/QMUI_iOS#413]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.3`
- [x] Xcode 版本：`9.3`
- [x] QMUI iOS 版本：`2.8.1`

### 请描述具体问题
工程引入QMUIKit之后，之前plain类型的tableview 的header 和footer默认都有高度了，自己的代码手动设置位0后可以了，但是这导致我们之前引用的别的SDK里的界面都出现了这个问题，请问下怎么解决？

**Comment by MoLice** [comment]
重复 issue
