### ISSUE TITLE
Plain类型tableview的 heightForHeaderInSection问题

### ISSUE THREAD

**Issue by LJW008** [QMUI/QMUI_iOS#415]
请填写运行环境

  设备：iPhone / iPad / 模拟器
  系统：iOS 11.3
  Xcode 版本：9.3
  QMUI iOS 版本：2.8.1
请描述具体问题

工程引入QMUIKit之后，之前plain类型的tableview 的header 和footer默认都有高度了，自己的代码手动设置位0后可以了，但是这导致我们之前引用的别的SDK里的界面都出现了这个问题，请问下怎么解决？

**Comment by MoLice** [comment]
需要你重新说明你的表达：

> 之前plain类型的tableview 的header 和footer默认都有高度了

这里的“之前”是在表达“QMUIKit 里 header 和 footer 都有默认的高度”，还是在表达“项目在引入 QMUIKit 之前，header 和 footer 已经有默认高度了”？

> 自己的代码手动设置位0后可以了

你是指你改了谁的代码，让谁的高度为 0 ？以及，如何定义“可以了”？意思是“代码里高度改为0后，实际表现的高度就能变成0了”还是指“代码里高度改为0后，实际表现出来的高度就能够不为0了”？

> 别的SDK里的界面都出现了这个问题

“这个问题”是指什么问题？“别的 SDK”又是？

**Comment by LJW008** [comment]
是这种情况，我新建了个工程，写了一个  plain类型的tableview，没有实现heightForFooterInSection和heightForHeaderInSection方法，tableview的显示出来就是header 和 footer 的高度都是0，然后我引入了QMUIKit，之前的的tableviewheader 和 footer 的高度就不是0了，必须要实现那两个方法才是0

**Comment by LJW008** [comment]
1,项目在引入 QMUIKit 之前，header 和 footer 有默认高度了，没引入之前没有高度
2.就是自己写的tabview 设置了高度，代码里高度改为0后，实际表现的高度就能变成0了

**Comment by LJW008** [comment]
找到问题了，QMUICMI.tableViewEstimatedHeightEnabled = YES;                              // TableViewEstimatedHeightEnabled : 是否要开启全局 QMUITableView 和 UITableView 的 estimatedRow(Section/Footer)Height   的影响，之前创建的并不是QMUITableView，而是系统的tableview啊，为什么也会出现这个问题 ～

**Comment by MoLice** [comment]
QMUICMI.tableViewEstimatedHeightEnabled 的注释已经有写明了，该属性对 UITableView 也会生效

**Comment by LJW008** [comment]
![111](https://user-images.githubusercontent.com/11679563/47628784-4a241c00-db05-11e8-842c-c095278158cc.png)
为什么只是引入

#import <QMUIKit/QMUIKit.h>/#import "QDCommonUI.h"
#import "QDUIHelper.h"
#import "QDThemeManager.h"  
之前的界面tableview就变成这样了

**Comment by MoLice** [comment]
长时间无进一步说明，issue 关闭。
