### ISSUE TITLE
导航栏的返回手势问题

### ISSUE THREAD

**Issue by gonglei277** [QMUI/QMUI_iOS#416]
### 请填写运行环境

- [x] 设备：`iPhone`
- [x] 系统：`iOS 12.0`
- [x] Xcode 版本：`9.4`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题
从带有导航栏的界面跳转到没有导航栏的界面之后,使用返回手势的时候,会马上出现一个白色的导航栏还带有一个返回键的图标.如下图:
![3f69c92d-5635-41e5-ae84-53bec597e027](https://user-images.githubusercontent.com/19592626/47306701-c4652400-d65f-11e8-966b-3dc0915c9f22.png)

  处理:我在界面2中使用了这两个方法(在viewWillAppear里显示,隐藏navigationgBar我试过,还是会有带返回键的导航栏出现)
-(BOOL)shouldCustomizeNavigationBarTransitionIfHideable{
    return YES;
}
-(BOOL)preferredNavigationBarHidden{
    return YES;
}
使用了这个方法之后,返回手势就不能使用了(因为接管了系统的控制)

并自定义了手势,  遵守了协议<UIGestureRecognizerDelegate>
- (void)viewDidLoad {
    [super viewDidLoad];
    self.navigationController.interactivePopGestureRecognizer.delegate = self;
}
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer *)gestureRecognizer {
    return [self gestureRecognizerShouldBegin];;
}

- (BOOL)gestureRecognizerShouldBegin {
    return YES;
}

首页也只能调这两个方法来控制导航栏显示
-(BOOL)shouldCustomizeNavigationBarTransitionIfHideable{
    return YES;
}
-(BOOL)preferredNavigationBarHidden{
    return NO;
}

此时,可以完美实现返回手势
![b322b896-88dd-4859-b410-442431889716](https://user-images.githubusercontent.com/19592626/47307413-87019600-d661-11e8-95fb-c0c9a93d5100.png)

我的目的: 完美实现手势返回,并且在没有导航栏的界面(手势返回的时候)不出现导航栏.
我的问题是:进入界面2,返回首页后,再从首页进其他界面就没办法使用返回手势了,应该是接管了系统的控制,可是我并不知道,该怎么在进入其他界面的时候,放开系统的控制!  或者说首页就不能使用那两个方法,可是不这么干,该怎么做呢?  在此求教大神

首页:带导航栏的界面   界面2:不带导航栏

**Comment by MoLice** [comment]
1. 某个界面的 `UINavigationBar` 如果被隐藏，或者因为设置了 `leftBarButtonItem` 而导致系统返回按钮被隐藏，这些情况均会导致手势返回失效，这是系统设定如此，与 QMUI 无关。如果你在这种情况下依然需要开启手势返回，请查看 `UINavigationControllerBackButtonHandlerProtocol - forceEnableInteractivePopGestureRecognizer` 的使用。
2. 如果你有两个界面需要切换导航栏的显隐，有两种方法，一是直接使用系统的方式，在各自界面的 `viewWillAppear:` 里通过 `self.navigationController setNavigationBarHidden:` 去修改导航栏的显隐，另一种是使用 QMUI 的接口，也即你提到的 `shouldCustomizeNavigationBarTransitionIfHideable` 和 `preferredNavigationBarHidden`，具体使用请阅读注释。
