### ISSUE TITLE
是否兼容swift

### ISSUE THREAD

**Issue by huaidan2015** [QMUI/QMUI_iOS#417]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

**Comment by QSBchange** [comment]
设备：iPhone 
  系统：iOS 12.x
  Xcode 版本：10.0
  QMUI iOS 版本：2.8
请问初始化的时候是这样的.为什么只能tabbar 的双击出发只能触发第一个 item 不能触发后面的.
![6d911876-1c69-4487-b844-14462fe75bbe](https://user-images.githubusercontent.com/20322678/47539263-fd242800-d901-11e8-91ab-37680c0714a5.png)

**Comment by MoLice** [comment]
请先阅读 README。

若是遇到具体的兼容问题，请描述你的问题。
