### ISSUE TITLE
swift tabbar 双击触发问题

### ISSUE THREAD

**Issue by QSBchange** [QMUI/QMUI_iOS#418]
### 请填写运行环境

- [x] 设备：`iPhone'
- [x] 系统：`iOS 12.0`
- [x] Xcode 版本：`10.0`
- [x] QMUI iOS 版本：`2.8`
初始化是这样的.但是为什么双击只能触发第一个 Item,不能出其他的呢
![6d911876-1c69-4487-b844-14462fe75bbe](https://user-images.githubusercontent.com/20322678/47539323-57bd8400-d902-11e8-92ae-c8f96ece1ca8.png)

**Comment by QSBchange** [comment]
准确的说是没有触发这个事件
![image](https://user-images.githubusercontent.com/20322678/47539468-2beece00-d903-11e8-9192-6255d481d8db.png)

**Comment by MoLice** [comment]
代码并没有问题，我猜你是直接双击一个不处于 selected 状态的 item，那样不视为双击。

先 selected，再双击，才能触发，设计如此。
