### ISSUE TITLE
侧滑和导航返回按钮怎么调用popToRootViewController和popToViewController跳到指定VC

### ISSUE THREAD

**Issue by iyuanxucheng** [QMUI/QMUI_iOS#419]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`

### 请描述具体问题
请问下，侧滑和导航返回按钮怎么调用popToRootViewController和popToViewController跳到指定VC？
有什么方法可以拦截这个手势？
烦请解答

**Comment by MoLice** [comment]
建议在手势返回之前找个时机直接修改 navigationController.viewControllers 数组，将你希望跳到的界面放到当前界面背后即可。
