### ISSUE TITLE
Cocoapods 用不了,报错:[!] Unable to find a specification for `QMUIKit`

### ISSUE THREAD

**Issue by cellgit** [QMUI/QMUI_iOS#42]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by MoLice** [comment]
请参考这个 [issue](https://github.com/QMUI/QMUI_iOS/issues/21)
