### ISSUE TITLE
UIImage (QMUI) 内对 resizableImage 使用了错误的 capInsets 值进行提醒时，使用 NSAssert 不太恰当

### ISSUE THREAD

**Issue by Zhaoxinak** [QMUI/QMUI_iOS#421]
UIImage (QMUI) resizableImageWithCapInsets 传进来的 capInsets 的水平/垂直方向的和应该小于图片本身的大小，否则会导致 render 时出现 invalid context 0x0 的错误

### 请填写运行环境

- [x] 设备： `iPhone SE`
- [x] 系统：`iOS 12.1`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`2.9.0`

### 请描述具体问题
更新后：
UIImage (QMUI) resizableImageWithCapInsets 传进来的 capInsets 的水平/垂直方向的和应该小于图片本身的大小，否则会导致 render 时出现 invalid context 0x0 的错误

**Comment by MoLice** [comment]
你想说什么？

**Comment by Zhaoxinak** [comment]
更新后直接崩溃。 2.8.1 无此问题。

**Comment by MoLice** [comment]
这是命中了不安全代码的 assert，检查你的图片的 capInsets 值是否如提示里所说的，如果是，改为合理的值即可。

**Comment by Zhaoxinak** [comment]
我没有设置这个值， 图片只在QMUIButton 使用了， 上图下文字的展示方式， 更新后直接报错了。

**Comment by MoLice** [comment]
我测试了并没有重现。你是否在项目里有修改过 UISearchBar 的样式？例如通过 QMUI 配置表的方式，或者通过系统的 appearance，如果有，请贴出你修改的代码。

**Comment by ZhangTonghai** [comment]
我也遇到的同样的问题，最终查找问题是在UITabbarController的子类中有以下代码
[self.tabBar setBackgroundImage:[UIImage new]];
希望对其他人有帮助

**Comment by DarrenKong** [comment]
> 我测试了并没有重现。你是否在项目里有修改过 UISearchBar 的样式？例如通过 QMUI 配置表的方式，或者通过系统的 appearance，如果有，请贴出你修改的代码。

@selector(resizableImageWithCapInsets:resizingMode:)

**Comment by DarrenKong** [comment]
> 我测试了并没有重现。你是否在项目里有修改过 UISearchBar 的样式？例如通过 QMUI 配置表的方式，或者通过系统的 appearance，如果有，请贴出你修改的代码。

@selector(resizableImageWithCapInsets:resizingMode:)

在UIImage+QMUI中的这个方法会引起crash。QMUIDemo_iOS项目，用真机测试“保存视频到指定相册”功能，必现

**Comment by ZhangTonghai** [comment]
### 请填写运行环境

* [x] 设备：iPhone7 Plus
* [x] 系统：iOS 12.1
* [x] xCode: 10.1
* [x] QMUI iOS 版本：2.9.0

### 请描述具体问题
又遇到了，这次是调用imageNamed:方法的时候。
截图部分分别是我是图片的信息，崩溃的堆栈、和控制台log，希望帮忙解答。

### 相关截图（断点的堆栈、控制台的 log）
<img width="849" alt="qq20181108-152311 2x" src="https://user-images.githubusercontent.com/6335614/48183931-6298ff80-e36b-11e8-8f71-48c369303fff.png">
<img width="1391" alt="qq20181108-152929 2x" src="https://user-images.githubusercontent.com/6335614/48183932-6298ff80-e36b-11e8-8871-260122ad48ae.png">
<img width="1393" alt="qq20181108-153251 2x" src="https://user-images.githubusercontent.com/6335614/48183995-983de880-e36b-11e8-8a5d-b4789a6c3d43.png">

**Comment by MoLice** [comment]
@ZhangTonghai 看你的最后一张截图里，当前的 top/left 分别为 291、292，请问这两个值是你显式写了 291、292 吗？

**Comment by MoLice** [comment]
> 我也遇到的同样的问题，最终查找问题是在UITabbarController的子类中有以下代码
> [self.tabBar setBackgroundImage:[UIImage new]];
> 希望对其他人有帮助

对于 `[UIImage new]` 这种特殊情况，新版本已做了保护，请等待发布。

**Comment by ZhangTonghai** [comment]
> 请问



> @ZhangTonghai 看你的最后一张截图里，当前的 top/left 分别为 291、292，请问这两个值是你显式写了 291、292 吗？

并没有，我显式写的是UIEdgeInsets insets = UIEdgeInsetsMake(20, 30, 20, 10)，而且291、292分别对应了我使用的图的宽高。

**Comment by ZhangTonghai** [comment]
> > 我测试了并没有重现。你是否在项目里有修改过 UISearchBar 的样式？例如通过 QMUI 配置表的方式，或者通过系统的 appearance，如果有，请贴出你修改的代码。
> 
> @selector(resizableImageWithCapInsets:resizingMode:)
> 
> 在UIImage+QMUI中的这个方法会引起crash。QMUIDemo_iOS项目，用真机测试“保存视频到指定相册”功能，必现

我在真机上运行demo也出现了复现了这个bug。

**Comment by MoLice** [comment]
> > > 我测试了并没有重现。你是否在项目里有修改过 UISearchBar 的样式？例如通过 QMUI 配置表的方式，或者通过系统的 appearance，如果有，请贴出你修改的代码。
> > 
> > 
> > @selector(resizableImageWithCapInsets:resizingMode:)
> > 在UIImage+QMUI中的这个方法会引起crash。QMUIDemo_iOS项目，用真机测试“保存视频到指定相册”功能，必现
> 
> 我在真机上运行demo也出现了复现了这个bug。

你引用的那段文字里有两个问题，一个是 UISearchBar 的，另一个是系统视频框架的，系统的视频是会命中，我们再考虑怎么处理。UISearchBar 那个无法重现。

**Comment by MoLice** [comment]
已发布 [2.9.1](https://github.com/QMUI/QMUI_iOS/releases/tag/2.9.1)，增加配置表开关 `ShouldAssertResizableImageCapInsetsError` 用于控制遇到这种情况下用 assert 还是用 log 提醒，默认用 log 提醒，可更新版本后使用。

**Comment by MoLice** [comment]
从 [3.1.0](https://github.com/Tencent/QMUI_iOS/releases/tag/3.1.0) 开始，配置表开关 `ShouldAssertResizableImageCapInsetsError` 被废弃，这种类型的错误以后会使用 `QMUILogWarn()` 搭配 `QMUIConsole` 提示。
