### ISSUE TITLE
在不使用配置表的情况下，UIViewController (NavigationBarTransition) 在界面切换时会错误地把导航栏样式设置为系统默认样式

### ISSUE THREAD

**Issue by dustylove** [QMUI/QMUI_iOS#423]
- [x] 设备：`iPhone`  `模拟器`
- [x] 系统：`iOS 12.1`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`2.9.0`

QMUICommonViewController 会把navgationbar的参数设为默认的，上一级设置的self.navigationController.navigationBar.barTintColor = UIColor.redColor；
push到下一个控制器后（QMUICommonViewController），barTintColor变为默认的白色，tintcolor这些参数也是如此。

**Comment by MoLice** [comment]
请问你有使用配置表吗？

**Comment by dustylove** [comment]
没有

**Comment by dustylove** [comment]
好的，谢谢您这么详细的讲解

**Comment by MoLice** [comment]
已发布 [2.9.1](https://github.com/QMUI/QMUI_iOS/releases/tag/2.9.1) 并修复该问题，请更新版本后尝试。
