### ISSUE TITLE
QMUIImagePreviewViewController在列表的九宫格预览图片 会频率很高地出现半透明的情况

### ISSUE THREAD

**Issue by jeryfer** [QMUI/QMUI_iOS#424]
### 请填写运行环境

- [x] 设备：`iPhone`
- [x] 系统：`iOS 12.1`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`2.9.0`

### 请描述具体问题

我是一个iOS新手，在做类似朋友圈的列表时候，用QMUIImagePreviewViewController预览图片，会发现第一个cell的图片预览背景纯黑正常，之后的cell预览图片背景会极大频率出现半透明

之前在QMUI iOS 2.8.0的时候也碰到过

半透明的情况下，往下稍微拖动一下啊就变成纯黑正常的了  怀疑是哪里计算错误了

#### 相关截图（断点的堆栈、控制台的 log）

![01262f7f863dbe3da2aaf7cac6d7b0ae](https://user-images.githubusercontent.com/10444088/47952361-2e0ef780-dfa9-11e8-9a6a-3a5aa421e931.JPG)

**Comment by MoLice** [comment]
请贴出相关代码

**Comment by jeryfer** [comment]
`import UIKit
import Kingfisher

class JCDiscoverViewController: QMUICommonTableViewController {

    private var news = [NewsModel]()
    private var maxBehotTime: TimeInterval = 0.0
    private var indexCell:Int=0
    private var indexImage:Int=0
    private lazy var imagePreviewViewController:QMUIImagePreviewViewController = {
        var imagePreviewViewController=QMUIImagePreviewViewController()
        imagePreviewViewController.imagePreviewView.delegate=self as? QMUIImagePreviewViewDelegate
        return imagePreviewViewController
    }()
    
    override func setupNavigationItems() {
        super.setupNavigationItems()
        self.title="我"
    }
    
    override func didInitialize(with style: UITableView.Style){
        super.didInitialize(with:style)
        tableView.ym_registerCell(cell: WeitoutiaoCell.self)
        _getNewsList()
    }
    
    private func _getNewsList() {
        NetworkTool.loadApiNewsFeeds(category: .weitoutiao, ttFrom: .pull, {
            self.maxBehotTime = $0
            self.news = $1
            self.tableView.reloadData()
        })
    }
    
    override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        let aNews = news[indexPath.row]
        return aNews.weitoutiaoHeight
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return news.count
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.ym_dequeueReusableCell(indexPath: indexPath) as WeitoutiaoCell

        cell.aNews = news[indexPath.row]
        // 点击了那张图片
        cell.didSelectCell = { [weak self] (selectedIndex) in
            self?.indexCell=indexPath.row
            self?.indexImage=selectedIndex
            self?.imagePreviewViewController.imagePreviewView.currentImageIndex = UInt(self!.indexImage)
            self?.imagePreviewViewController.startPreviewByFadeIn()
        }
        return cell
    }
}

extension JCDiscoverViewController: QMUIImagePreviewViewDelegate {
    func numberOfImages(in imagePreviewView: QMUIImagePreviewView!) -> UInt {
        return UInt(self.news[indexCell].large_image_list.count)
    }
    
    func imagePreviewView(_ imagePreviewView: QMUIImagePreviewView!, renderZoomImageView zoomImageView: QMUIZoomImageView!, at index: UInt) {
        var cellNews=self.news[indexCell]
       
        let url = URL(string:cellNews.large_image_list[indexImage].urlString)!
        let resource = ImageResource(downloadURL: url)
        KingfisherManager.shared.retrieveImage(with: resource as! Resource, options: nil, progressBlock: nil, completionHandler: { image, error, cacheType, imageURL in
            zoomImageView.image=image
        })
    }
}`

**Comment by jeryfer** [comment]
```
import UIKit
import Kingfisher

class JCDiscoverViewController: QMUICommonTableViewController {

    private var news = [NewsModel]()
    private var maxBehotTime: TimeInterval = 0.0
    private var indexCell:Int=0
    private var indexImage:Int=0
    private lazy var imagePreviewViewController:QMUIImagePreviewViewController = {
        var imagePreviewViewController=QMUIImagePreviewViewController()
        imagePreviewViewController.imagePreviewView.delegate=self as? QMUIImagePreviewViewDelegate
        return imagePreviewViewController
    }()
    
    override func setupNavigationItems() {
        super.setupNavigationItems()
        self.title="我"
    }
    
    override func didInitialize(with style: UITableView.Style){
        super.didInitialize(with:style)
        tableView.ym_registerCell(cell: WeitoutiaoCell.self)
        _getNewsList()
    }
    
    private func _getNewsList() {
        NetworkTool.loadApiNewsFeeds(category: .weitoutiao, ttFrom: .pull, {
            self.maxBehotTime = $0
            self.news = $1
            self.tableView.reloadData()
        })
    }
    
    override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        let aNews = news[indexPath.row]
        return aNews.weitoutiaoHeight
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return news.count
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.ym_dequeueReusableCell(indexPath: indexPath) as WeitoutiaoCell

        cell.aNews = news[indexPath.row]
        // 点击了那张图片
        cell.didSelectCell = { [weak self] (selectedIndex) in
            self?.indexCell=indexPath.row
            self?.indexImage=selectedIndex
            self?.imagePreviewViewController.imagePreviewView.currentImageIndex = UInt(self!.indexImage)
            self?.imagePreviewViewController.startPreviewByFadeIn()
        }
        return cell
    }
}

extension JCDiscoverViewController: QMUIImagePreviewViewDelegate {
    func numberOfImages(in imagePreviewView: QMUIImagePreviewView!) -> UInt {
        return UInt(self.news[indexCell].large_image_list.count)
    }
    
    func imagePreviewView(_ imagePreviewView: QMUIImagePreviewView!, renderZoomImageView zoomImageView: QMUIZoomImageView!, at index: UInt) {
        var cellNews=self.news[indexCell]
       
        let url = URL(string:cellNews.large_image_list[indexImage].urlString)!
        let resource = ImageResource(downloadURL: url)
        KingfisherManager.shared.retrieveImage(with: resource as! Resource, options: nil, progressBlock: nil, completionHandler: { image, error, cacheType, imageURL in
            zoomImageView.image=image
        })
    }
}
```

**Comment by jeryfer** [comment]
```
import UIKit
import Kingfisher

class JCDiscoverViewController: QMUICommonTableViewController {

    private var news = [NewsModel]()
    private var maxBehotTime: TimeInterval = 0.0
    private var indexCell:Int=0
    private lazy var imagePreviewViewController:QMUIImagePreviewViewController = {
        var imagePreviewViewController=QMUIImagePreviewViewController()
        imagePreviewViewController.imagePreviewView.delegate=self as? QMUIImagePreviewViewDelegate
        return imagePreviewViewController
    }()
    
    override func setupNavigationItems() {
        super.setupNavigationItems()
        self.title="我"
    }
    
    override func didInitialize(with style: UITableView.Style){
        super.didInitialize(with:style)
        tableView.ym_registerCell(cell: WeitoutiaoCell.self)
        _getNewsList()
    }
    
    private func _getNewsList() {
        NetworkTool.loadApiNewsFeeds(category: .weitoutiao, ttFrom: .pull, {
            self.maxBehotTime = $0
            self.news = $1
            self.tableView.reloadData()
        })
    }
    
    override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        let aNews = news[indexPath.row]
        return aNews.weitoutiaoHeight
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return news.count
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.ym_dequeueReusableCell(indexPath: indexPath) as WeitoutiaoCell

        cell.aNews = news[indexPath.row]
        // 点击了那张图片
        cell.didSelectCell = { [weak self] (selectedIndex) in
            self?.indexCell=indexPath.row
            self?.imagePreviewViewController.imagePreviewView.currentImageIndex = UInt(selectedIndex)
            self?.imagePreviewViewController.startPreviewByFadeIn()
        }
        return cell
    }
}

extension JCDiscoverViewController: QMUIImagePreviewViewDelegate {
    func numberOfImages(in imagePreviewView: QMUIImagePreviewView!) -> UInt {
        return UInt(self.news[indexCell].large_image_list.count)
    }
    
    func imagePreviewView(_ imagePreviewView: QMUIImagePreviewView!, renderZoomImageView zoomImageView: QMUIZoomImageView!, at index: UInt) {
        var cellNews=self.news[indexCell]
        let url = URL(string:cellNews.large_image_list[Int(index)].urlString)!
        let resource = ImageResource(downloadURL: url)
        KingfisherManager.shared.retrieveImage(with: resource as! Resource, options: nil, progressBlock: nil, completionHandler: { image, error, cacheType, imageURL in
            zoomImageView.image=image
        })
    }
}
```

**Comment by MoLice** [comment]
代码看起来没什么问题。是否能将你的操作录制为视频发上来看看？

**Comment by jeryfer** [comment]
另外，还发现一个bug，预览图在loading的时候就滑动关闭掉，缩略图变成空白，可以在demo上复现

**Comment by MoLice** [comment]
> 另外，还发现一个bug，预览图在loading的时候就滑动关闭掉，缩略图变成空白，可以在demo上复现

这属于业务使用的问题，不属于 QMUI 控件的问题。Demo 里我们也将对这种场景做兼容，感谢指出。

![image](https://user-images.githubusercontent.com/1190261/47981780-24e86c80-e108-11e8-8d9a-518562a72741.png)

至于前一个问题，按照你的操作视频进行操作也无法重现这个问题，目前的方法要么把一份能出问题的测试项目发邮件到 qmuiteam@qq.com 我们查一下，要么可以自行在 `QMUIImagePreviewViewController` 里搜索 `self.view.backgroundColor = `，检查哪个地方的背景色设置有问题才导致显示了半透明的背景。

**Comment by jeryfer** [comment]
邮件已发，请查收

**Comment by MoLice** [comment]
较长时间无详情信息补充，issue 关闭

**Comment by jeryfer** [comment]
为啥呢？已经把测试项目发送到指定邮箱了，也没有回应，就关闭了？

**Comment by MoLice** [comment]
请查看11月5日22:11的邮件回复，在那之后没再收到你的邮件。
