### ISSUE TITLE
UIViewController (NavigationBarTransition) 会强制修改界面的 view.clipsToBounds，可能与业务代码产生冲突

### ISSUE THREAD

**Issue by bluesky335** [QMUI/QMUI_iOS#425]
### 请填写运行环境

- [x] 设备：`iPhone`&&`iPad` && `模拟器`
- [x] 系统：`iOS 10.0 + `
- [x] QMUI iOS 版本：`2.9.0`
- [x] Xcode 版本：`10.x`

### 请描述具体问题
我使用了QMUINavigationController
在自定义Push的转场动画的时候发现, 我给toView 或 fromView设置的圆角 不能裁剪其子视图了, 最终在QMUI的"UINavigationController+NavigationBarTransition.m"文件中的第146和147行找到如下代码:
```
 fromViewController.view.clipsToBounds = NO;
 toViewController.view.clipsToBounds = NO;
```
我猜应该是它们影响了我的转场动画

**Comment by zhoon** [comment]
自定义push转场动画可以通过以下四个 delegate 屏蔽掉 UINavigationController+NavigationBarTransition  里面的逻辑，也就是不使用QMUI的自定义 NavigationBarTransition。我们再看看怎么在 QMUI 这一层当自定义push转场动画的时候屏蔽掉这些逻辑。

- (BOOL)shouldCustomNavigationBarTransitionWhenPushAppearing;
- (BOOL)shouldCustomNavigationBarTransitionWhenPushDisappearing;
- (BOOL)shouldCustomNavigationBarTransitionWhenPopAppearing;
- (BOOL)shouldCustomNavigationBarTransitionWhenPopDisappearing;

**Comment by zhoon** [comment]
QMUI 已经尝试做了保护，请留意新版本

**Comment by MoLice** [comment]
[2.9.1](https://github.com/QMUI/QMUI_iOS/releases/tag/2.9.1) 已发布，请阅读更新说明。
