### ISSUE TITLE
 在 present 一个 QMUINavigationController 的过程中 push，可能导致 push 被拦截

### ISSUE THREAD

**Issue by ziecho** [QMUI/QMUI_iOS#426]
### 请填写运行环境

- [x] 设备：`All`
- [x] 系统：`iOS 12.1`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`2.9.0`

### 请描述具体问题
在 QMUI Demo 里创建一个 TestViewController
```objc
@interface TestViewController : QDCommonViewController
@end

@implementation TestViewController

- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];

    [self.navigationController pushViewController:[QDCommonViewController new] animated:YES];
}

- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
    [super touchesBegan:touches withEvent:event];
    
    [self.navigationController pushViewController:[QDCommonViewController new] animated:YES];
}

@end
```

触发此问题代码：

```objc

- (void)test {
    
    TestViewController *vc = [TestViewController new];
    
    QMUINavigationController *nav = [[QMUINavigationController alloc] initWithRootViewController:vc];
    
    [self presentViewController:nav animated:YES completion:nil];
    
}

```

此时，TestViewController 的 push 操作被拦截，且后续的 push 操作无响应 (可通过触发 touchesBegan 测试)。
如果稍微延时就没问题：

```objc
- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.3 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [self.navigationController pushViewController:[QDCommonViewController new] animated:YES];
    });
}

```
### 原因分析

如果 present 一个 NavigationController，在转场未结束的时候去 push 一个新的页面，系统会暂时拦截这次 push 存起来，待 present 结束再次 push，而第二次 push 被 QMUI 拦截掉了。

![image](https://user-images.githubusercontent.com/16473618/48176853-0921d800-e34d-11e8-94ad-7c10f830e0fa.png)

![image](https://user-images.githubusercontent.com/16473618/48176885-26ef3d00-e34d-11e8-997a-df2e26aa53e4.png)

### 解决方案

可以考虑增加一个判断条件来解决此问题：

`!self.isBeingPresented`

```objc
    if (!self.presentedViewController && animated && !self.isBeingPresented) {
        self.isViewControllerTransiting = YES;
    }
```

**Comment by MoLice** [comment]
该问题的关键在于某些场景下，系统的 `UINavigationController pushViewController:animated:` 并不会导致一次真正的 push 操作，然而 `QMUINavigationController` 对这种情况没有保护，依然认为该 push 操作已成功进行（所以将 `isViewControllerTransiting` 置为 YES），但由于 push 操作实际上没有正确进行，所以无法在 `UINavigationControllerDelegate - navigationController:didShowViewController:` 内正确将 `isViewControllerTransiting` 置为 NO。

而你描述的场景是其中一种，对该场景也尚未找到任何相关的官方说明，`pushViewController:animated:` 的文档也并没有提到该方法可能失效，因此在不明确的情况下，我们选择直接在调用 `[super pushViewController:animated:] 之后再次检查一次当前的 push 操作是否正确执行，若发现 push 操作失败，则恢复 QMUI 自己的标志位，相关代码如下：

```Objective-C
[super pushViewController:viewController animated:animated];

if (![self.viewControllers containsObject:viewController]) {
    self.isViewControllerTransiting = NO;
}
```

你建议的修改方式对你描述的场景是有效的，但不确定是否还存在其他场景，因此我们选择上述的解决方法，代码将会在下周的新版本中带上，谢谢你的提醒。

**Comment by ziecho** [comment]
这种判断方式更妥当，赞一个

**Comment by MoLice** [comment]
[2.9.1](https://github.com/QMUI/QMUI_iOS/releases/tag/2.9.1) 已发布并修复该问题。
