### ISSUE TITLE
(建议)QMUIAlertController(StyleActionSheet)添加的CustomView size无法动态变化

### ISSUE THREAD

**Issue by codingiran** [QMUI/QMUI_iOS#428]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

### 请描述具体问题
```
self.containerView.frame = CGRectMake(0, 0, SCREEN_WIDTH - 20, 200);

self.containerView.backgroundColor = UIColorRed;//红色

[self.alertController addCustomView:self.containerView];
```

如上述常规操作后，如下图所示
![image](https://user-images.githubusercontent.com/11780294/48300474-3ae79a00-e519-11e8-9823-579115e3c3cf.png)

试图调试为：
![image](https://user-images.githubusercontent.com/11780294/48300418-ff000500-e517-11e8-8947-071098c932cc.png)

由于业务需求我需要改变self.containerView(红色的那块view)的高度，当我修改成50后如下：
![image](https://user-images.githubusercontent.com/11780294/48300443-c14fac00-e518-11e8-858b-af795479869e.png)
试图调试为：
![image](https://user-images.githubusercontent.com/11780294/48300445-d0cef500-e518-11e8-9ef9-dddb30b33d1c.png)

CustomView size发生变化时，内部的headerScrollView没有跟随发生变化

目前我的解决方法是用如下方法强制触发alertController的```viewDidLayoutSubviews```，这样内部的所有控件都会重新布局成正确的size
```self.alertController.view.qmui_height -= 0.5;```

**建议：能不能customView frame发生变化时，alertController自动重新布局一下**

Mark: 我在QMUI群里，如果我表述的不清楚可以@CodingIran

**Comment by MoLice** [comment]
刷新布局请使用 `[alertController.modalPresentationViewController updateLayout]`。

**Comment by MoLice** [comment]
这里的布局思维是，superview 只负责管理 subviews 的 `frame.origin`，不管理 subviews 的 `frame.size`，因为一个 UIView 控件（也即 superview）代表一种布局方式的管理，所以只关心 `frame.origin`，这种思维也是 UIKit 里较为通用的思维。因此经过考虑，当你的 `customView` 大小发生变化时，请主动告知你的 superview，在这个场景里，也即上一条 comment 贴出来的那句代码。

**Comment by codingiran** [comment]
> 这里的布局思维是，superview 只负责管理 subviews 的 `frame.origin`，不管理 subviews 的 `frame.size`，因为一个 UIView 控件（也即 superview）代表一种布局方式的管理，所以只关心 `frame.origin`，这种思维也是 UIKit 里较为通用的思维。因此经过考虑，当你的 `customView` 大小发生变化时，请主动告知你的 superview，在这个场景里，也即上一条 comment 贴出来的那句代码。

OK！了解！
