### ISSUE TITLE
UIView(QMUI_Border) qmui_initWithFrame 内存泄露

### ISSUE THREAD

**Issue by AlanJN** [QMUI/QMUI_iOS#429]
### 请填写运行环境

- [x] 设备：iPad mini4 
- [x] 系统：iOS 11.2
- [x] Xcode 版本：10.0

- [x] QMUI iOS 版本：2.7.6

#### 相关截图（断点的堆栈、控制台的 log）
![1542008968907](https://user-images.githubusercontent.com/7259009/48333509-a86b0600-e692-11e8-8b1b-46599cd4f440.jpg)

**Comment by MoLice** [comment]
这只是方法替换，执行的还是系统原生方法，建议查看调用堆栈，看是哪个业务的 View 存在泄露。
