### ISSUE TITLE
使用QDTabBarViewController Tabbar点击后隐藏

### ISSUE THREAD

**Issue by TracyYanghandsome** [QMUI/QMUI_iOS#43]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 8.2`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.2.0`

### 具体问题描述 ###

**QDTabBarViewController *tabBarViewController = [[QDTabBarViewController alloc] init];
    
    //首页
    HomeViewController *homeVC = [HomeViewController new];
    QDNavigationController *homeNavController = [[QDNavigationController alloc] initWithRootViewController:homeVC];
    homeNavController.hidesBottomBarWhenPushed = NO;
    homeNavController.tabBarItem = [QDUIHelper tabBarItemWithTitle:@"首页" image:[UIImageMake(@"wdsy") imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal] selectedImage:UIImageMake(@"sysyl") tag:0];
    
    //咨询
    ConsultViewController *consultVC = [ConsultViewController new];
    QDNavigationController *consultNavController = [[QDNavigationController alloc] initWithRootViewController:consultVC];
    consultNavController.hidesBottomBarWhenPushed = NO;
    consultNavController.tabBarItem = [QDUIHelper tabBarItemWithTitle:@"咨询" image:[UIImageMake(@"syzx") imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal] selectedImage:UIImageMake(@"syzxs") tag:0];
    
    //客户
    ClientViewController *clientVC = [ClientViewController new];
    QDNavigationController *clientNavController = [[QDNavigationController alloc] initWithRootViewController:clientVC];
    clientNavController.hidesBottomBarWhenPushed = NO;
    clientNavController.tabBarItem = [QDUIHelper tabBarItemWithTitle:@"客户" image:[UIImageMake(@"sykf") imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal] selectedImage:UIImageMake(@"sykfs") tag:0];
    
    //我的
    SettingViewController *myVC = [SettingViewController new];
    QDNavigationController *myNavController = [[QDNavigationController alloc] initWithRootViewController:myVC];
    myNavController.hidesBottomBarWhenPushed = NO;
    myNavController.tabBarItem = [QDUIHelper tabBarItemWithTitle:@"我的" image:[UIImageMake(@"sysz") imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal] selectedImage:UIImageMake(@"wdsz1") tag:0];
    
    tabBarViewController.viewControllers = @[homeNavController, consultNavController, clientNavController, myNavController];
    self.window.rootViewController = tabBarViewController;** 

SettingViewController、ClientViewController、HomeViewController、ConsultViewController控制器都继承与QMUICommonViewController，在点击tabbar的时候tabbar就消失了，就出不来了。如下图
#### 问题截图 ####
![d127f46b-abcb-462c-b05b-bf601a367569](https://cloud.githubusercontent.com/assets/19200800/22816535/9cb9dbf8-ef9d-11e6-8aa6-ba60d9031ed8.png)

**Comment by TracyYanghandsome** [comment]
![86246448-5697-4eb3-a556-f663bc07d8f1](https://cloud.githubusercontent.com/assets/19200800/22816631/1f31cb68-ef9e-11e6-9bb4-6458f962bd4a.png)
第一次能加载出来，点击tabbar后就隐藏了

**Comment by MoLice** [comment]
你的意思是点击第4个 `tabBarItem`，`tabBar` 就被隐藏了？还是说点击 `SettingViewController` 列表里的某个 cell 进入到下一级界面时，`tabBar` 隐藏了？

**Comment by TracyYanghandsome** [comment]
@MoLice 点击首页或者咨询、客户都会出现tabbar被隐藏掉

**Comment by TracyYanghandsome** [comment]
@MoLice 我搞了一个GIF动态图 你看下

![1](https://cloud.githubusercontent.com/assets/19200800/22816917/982393f2-ef9f-11e6-809d-d972e9484f8b.gif)

**Comment by MoLice** [comment]
这是 `hidesBottomBarWhenPushed` 属性错误设置导致的。你原本是设置在 `UINavigationController` 上，应该设置在 `UIViewController` 上。例如：
```Objective-C
SettingViewController *myVC = [SettingViewController new];
myVC.hidesBottomBarWhenPushed = NO;
QDNavigationController *myNavController = [[QDNavigationController alloc] initWithRootViewController:myVC];
```

**Comment by TracyYanghandsome** [comment]
是我复制的时候复制错了。。没看出来。。不好意思
