### ISSUE TITLE
QMUITextField  是否可以控制输入类型 比如 字符 ，数字， 中文？？

### ISSUE THREAD

**Issue by datafu** [QMUI/QMUI_iOS#430]
### 请填写运行环境

- [x] 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统：`iOS 11.x`
- [x] Xcode 版本：`9.x`
- [x] QMUI iOS 版本：`2.x.x`

**Comment by MoLice** [comment]
系统提供的 `[UITextFieldDelegate textField:shouldChangeCharactersInRange:replacementString]` 已足够方便，QMUITextField 暂时没有必要再次封装。
