### ISSUE TITLE
iPad presentViewController 之后点击空白dismiss或者主动dismiss崩溃

### ISSUE THREAD

**Issue by Jonas-o** [QMUI/QMUI_iOS#433]
### 请填写运行环境

- [x] 设备：`iPad` 
- [x] 系统：`iOS 10.2.1`
- [x] Xcode 版本：`10.0`
- [x] QMUI iOS 版本：`2.9.0` `2.9.1`

### 请描述具体问题
UIViewController以UIModalPresentationPopover的方式弹出时，不管是手动dismiss还是点击空白dismiss都会直接崩溃，已测试过2.8.1版本前不会出现，另外这个只在10.2.1，12.0测试过，12.0没问题

**Comment by Jonas-o** [comment]
相关截图：
![2018-11-15 4 47 46-01](https://user-images.githubusercontent.com/31504742/48542070-2cbec280-e8f9-11e8-9112-4c065f2f0bb8.jpg)
![2018-11-15 4 30 04](https://user-images.githubusercontent.com/31504742/48542089-37795780-e8f9-11e8-8c96-ce0092c7fdf3.jpg)
![screen shot 2018-11-15 at 4 30 15-01](https://user-images.githubusercontent.com/31504742/48541969-e8332700-e8f8-11e8-94df-5cb3b72bb5ec.jpg)

**Comment by zhoon** [comment]
会尽快发新版本修复。临时可以在 CALayer+QMUI 里面的 QMUICornerRadius_layoutSublayersOfLayer: 方法里面注释 if (self.layer.qmui_maskedCorners) {} 里面的代码。

**Comment by MoLice** [comment]
已发布 [2.9.2](https://github.com/QMUI/QMUI_iOS/releases/tag/2.9.2) 修复该问题。
