### ISSUE TITLE
输入框长按无法弹出操作菜单，再次长按或者点击崩溃

### ISSUE THREAD

**Issue by jhchenchong** [QMUI/QMUI_iOS#434]
### 请填写运行环境

- [x] 设备：`iPhone 6s`
- [x] 系统：`iOS 10.3.3`
- [x] Xcode 版本：`10`
- [x] QMUI iOS 版本：`2.9.0`

### 请描述具体问题
官方提供的Demo, 在任何有输入框的位置，长按输入框，无法显示操作菜单，再次点击或者长按输入框，崩溃。

**Comment by zhoon** [comment]
下个版本会修复，请留意

**Comment by MoLice** [comment]
已发布 [2.9.2](https://github.com/QMUI/QMUI_iOS/releases/tag/2.9.2) 修复该问题。
