### ISSUE TITLE
适配问题

### ISSUE THREAD

**Issue by nobut** [QMUI/QMUI_iOS#437]
### 请填写运行环境

- [x] 设备：`模拟器`
- [x] 系统：`iOS 12.1`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`2.9.0`

### 请描述具体问题
请问QMUI_iOS屏幕适配或者比例怎么做的呢？
我们的做法是设计师以iPhone 8为基准做的UI效果图，用宏定义
#define SCREEN_WIDTH ([[UIScreen mainScreen] bounds].size.width)
#define Fitsize(X) (SCREEN_WIDTH/375.0) * X  乘iPhone 8的比例，进行缩放。
请问QMUI_iOS有这样的方法吗？或者有更好的解决方案？

**Comment by MoLice** [comment]
1. 同一个界面在不同屏幕大小下布局要如何调整，取决于设计意图。
2. 一般不会采用比例换算的方式去适配，而是以自适应的方式适配，例如同一行里有左右两个元素，其中一个的 size 包裹自身大小，剩余空间留给另一个元素，这种设计意图，与屏幕大小是无关的，无需牵扯到比例换算。
3. 如果要区分不同设备，QMUI 在 `QMUICommonDefines.h` 内提供 `PreferredValueXxx` 系列宏，以及在 `QMUIHelper (Device)` 内提供系列方法，按需选择。

**Comment by nobut** [comment]
好的，谢谢
