### ISSUE TITLE
QMUITabBarViewController提供动态隐藏底部tabbar接口

### ISSUE THREAD

**Issue by 276523923** [QMUI/QMUI_iOS#440]
列表滑动的时候，动态控制tabbar的隐藏跟显示，能不能提供下接口！

**Comment by MoLice** [comment]
这属于业务需求，QMUI 层面不会对这种需求做支持的，因为不具备通用性。

但用目前提供的组件已经能实现你的这种需求，具体请参考 QMUI Demo 里的 Components -> QMUIScrollAnimator，有两种交互方式可供选择，其中第二种刚好以隐藏 navigationBar 作为示例，你可以参考写法，去隐藏 tabBar。
