### ISSUE TITLE
建议:为何不给QMUIButton添加badge属性，很多时候需要这个功能~

### ISSUE THREAD

**Issue by Karthus1110** [QMUI/QMUI_iOS#443]

**Comment by MoLice** [comment]
这种问题不同场景需求相差较大，而且增加 subview/sublayer 也可能影响原有 view 对自身 subview 的管理，因此这个功能暂不考虑，业务自行处理即可。

我们为 UIBarItem 支持是因为涉及到系统的控件，业务要处理太麻烦，而如果是一个普通的 UIView，业务自行处理，成本不高，自己抽取一个也是没问题的，所以才会有这样的组件划分。

**Comment by Karthus1110** [comment]
got it
