### ISSUE TITLE
能否新增这种图片裁剪模式

### ISSUE THREAD

**Issue by loveuqian** [QMUI/QMUI_iOS#447]
一张本来 100*50 的图片
使用 qmui_imageResizedInLimitedSize:CGSizeMake(10, 10) 默认模式进行裁剪
会出来一张 10*5 的图片
但是我想要一张 10*10 的图片，裁剪出的图片上下左右居中，剩余不够的部分，补上白色或者自定义颜色

**Comment by MoLice** [comment]
已有现成方法，请自行阅读头文件。

**Comment by loveuqian** [comment]
@MoLice ，是哪个方法，我现在的做法是生成一个白底图片，然后用 qmui_imageWithImageAbove

**Comment by MoLice** [comment]
`UIImage (QMUI) - qmui_imageResizedInLimitedSize:resizingMode:` 可以满足你的需求，生成的图片的 opaque 取决于你原 UIImage 对象的 opaque 属性的值。如果原图 opaque 为 YES，则“剩余不够的部分”会变成黑色（系统默认如此，QMUI 没有提供方法自定义这一部分的颜色），如果原图 opaque 为 NO，则“剩余不够的部分”是透明。

按你的描述，猜测你的原图应该是 opaque = YES 才需要处理空余位置的颜色，而你目前生成一个白色底图再用 qmui_imageWithImageAbove 的方式是合理的。

**Comment by loveuqian** [comment]
@MoLice ，明白
