### ISSUE TITLE
宏定义命名冲突

### ISSUE THREAD

**Issue by SilenceLove** [QMUI/QMUI_iOS#448]
### 请填写运行环境

- [x] 设备：`All`
- [x] 系统：`iOS 12.0`
- [x] Xcode 版本：`10.0`
- [x] QMUI iOS 版本：`2.9.2`

### 请描述具体问题
宏定义和其他库冲突....

**Comment by MoLice** [comment]
如无详细信息补充，该 issue 将被视为无效 issue 而关闭。
