### ISSUE TITLE
请问如何去掉返回的文字 只显示返回的箭头？

### ISSUE THREAD

**Issue by mesoar** [QMUI/QMUI_iOS#449]
请问如何去掉返回的文字 只显示返回的箭头？

#### 相关截图
![1544010432534](https://user-images.githubusercontent.com/12460906/49511625-9c0b4f00-f8c6-11e8-8d5d-7569db003ced.jpg)

![1544010517947](https://user-images.githubusercontent.com/12460906/49511684-c78e3980-f8c6-11e8-860b-0dc687095d46.jpg)
如何才能跟demo中只出现一个返回的箭头呢？ 我看了demo里面没有相关的代码啊
我尝试更改QMUIConfigurationTemplate配置文件，但是不行呢？

**Comment by fanyuecheng** [comment]
QMUINavigationController

**Comment by fanyuecheng** [comment]
QMUICMI.needsBackBarButtonItemTitle + QMUINavigationController
