### ISSUE TITLE
这个打包审核的时候会不会被拒？动态库能过审核吗？

### ISSUE THREAD

**Issue by LDXu** [QMUI/QMUI_iOS#45]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by zhoon** [comment]
不会的，动态库是苹果自己开放出来的，不太可能会拒自己开放的特性。

**Comment by MoLice** [comment]
我们已经在微信读书、企业微信上使用了很长一段时间，请放心打包。

**Comment by LDXu** [comment]
嗯，可以，审核过了。谢谢

**Comment by AgoniNemo** [comment]
@LDXu 你好  请问下 用的是动态库吗？
