### ISSUE TITLE
2.9.3 版本，自定义tabBar frame 变成 (0, 0, 0, 0)

### ISSUE THREAD

**Issue by Oniityann** [QMUI/QMUI_iOS#467]
### 请填写运行环境

- [x] 设备：`All` 
- [x] 系统：`iOS 12.1.2`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`2.9.3`

### 请描述具体问题

自定义 tabBar 在非 notch 机型上，frame 会变成 (0, 0, 0, 0)
切换到 2.9.2 之前的版本都是好的

出错代码`[self setValue:baseTabBar forKeyPath:@"tabBar"];`

#### 相关截图（断点的堆栈、控制台的 log）

<img width="392" alt="wechatimg1" src="https://user-images.githubusercontent.com/13940150/50425608-b4fb9480-08b5-11e9-9b8e-47985f3e50df.png">

**Comment by MoLice** [comment]
请贴出完整代码，这句代码看不出什么。

**Comment by Oniityann** [comment]
> 请贴出完整代码，这句代码看不出什么。

需要的是这种效果， 中间和微博那种自定义的按钮

<img width="371" alt="screen shot 2018-12-26 at 3 04 55 pm" src="https://user-images.githubusercontent.com/13940150/50436200-a6e25e00-091f-11e9-89fc-94cb347b53e0.png">

`[self setValue:baseTabBar forKeyPath:@"tabBar"];`

这句代码是我替换系统tabBar写的代码，如果把这句话注释掉，那么 tabBar 是正常显示的， 也就是不替换系统的 tabBar。

如果加上这句代码，替换系统 tabBar ，那就会出现第一张图那样，tabBar 的 frame 为 (0, 0, 0, 0) 的情况。在 2.9.2 版本中，上面那段代码能正常工作。

完整的代码就是自己继承了一个系统的 tabBar，在自定义的 tabBar controller 里面调用了一下而已。

tabBar.m
```
@implementation XLBaseTabBar

- (instancetype)initWithFrame:(CGRect)frame {
    self = [super initWithFrame:frame];
    if (self) {
        
        XLButton *publishButton = [XLButton buttonWithType:UIButtonTypeCustom];
        [publishButton setBackgroundImage:ImageNamed(@"tab_publish") forState:UIControlStateNormal];
        [self addSubview:publishButton];
        self.publishButton = publishButton;
        
    }
    return self;
}

- (void)layoutSubviews {
    [super layoutSubviews];
    
    // 其他 button 的 frame
    CGFloat normalButtonY = 0.f;
    CGFloat normalButtonW = self.width / 5;
    CGFloat normalButtonH = self.height;
    if (NotchPhone) {
        normalButtonH = self.height - iPhoneXBotSafeAreaHeight;
    }
    
    // 发布按钮的 frame
    self.publishButton.size = PublishButtonSize;
    self.publishButton.center = CGPointMake(self.width * 0.5, normalButtonH * 0.5);
    
    NSInteger buttonIndex = 0;
    
    for (UIView *button in self.subviews) {
        
        CGFloat normalButtonX = 0.f;
        
        if (buttonIndex > 1) {
            normalButtonX = normalButtonW * (buttonIndex + 1);
        } else {
            normalButtonX = normalButtonW * buttonIndex;
        }
        
        if (![button isKindOfClass:NSClassFromString(@"UITabBarButton")]) {
            continue;
        }
        
        button.frame = CGRectMake(normalButtonX, normalButtonY, normalButtonW, normalButtonH);
        button.tag = 10000 + buttonIndex;
        
        buttonIndex++;
    }
}
```

这样定义的 tabBar，在 controller 中调用了一下：

tabBarController.m
```
@implementation XLBaseTabBarController

- (void)viewDidLoad {
    [super viewDidLoad];
    
    XLBaseTabBar *baseTabBar = [[XLBaseTabBar alloc] init];

    self.publishButton = baseTabBar.publishButton;

    [self setValue:baseTabBar forKeyPath:@"tabBar"];
}

@end
```

2.9.2 中正常，2.9.3 中 frame 出现问题。

**Comment by MoLice** [comment]
参照你的代码在 2.9.3 QMUI Demo，iPhone 8 Plus 12.1.2 真机上并没有重现你的问题。

需要的话可以打包一个 Demo 发送到 contact@qmuiteam.com。

![image](https://user-images.githubusercontent.com/1190261/50437656-a64cc600-0925-11e9-93b8-2cdc25e11e36.png)

![image](https://user-images.githubusercontent.com/1190261/50437673-b95f9600-0925-11e9-8709-a0c10d6eb433.png)

**Comment by MoLice** [comment]
原因同 #463，这两天会发个小版本修复，在此之前建议参考该 issue 里的修复方式临时改一下。

**Comment by Oniityann** [comment]
> 原因同 #463，这两天会发个小版本修复，在此之前建议参考该 issue 里的修复方式临时改一下。

谢谢大佬！

**Comment by pcjbird** [comment]
好像3.0.0并没有修复，已回退到2.9.2～～～
