### ISSUE TITLE
QMUIConfigurationTemplate 不起作用

### ISSUE THREAD

**Issue by zhangchioulin** [QMUI/QMUI_iOS#48]
### 运行环境 ###

- [x] iOS 设备：`模拟器`
- [x] 系统版本：`iOS 10.2`
- [x] Xcode 版本：`8.2.1`
- [x] QMUI iOS 版本：`1.2.0`

### 具体问题描述 ###
我继承`QMUIConfigurationTemplate`更改了`Button`的`buttonTintColor`,但是不起作用.
于是我直接在`QMUIConfigurationTemplate`更改`buttonTintColor`也不起作用.一直是默认的蓝色

**Comment by zhangchioulin** [comment]
感谢回复, 我在`application:didFinishLaunchingWithOptions:`调用了, 感觉继承的方式更好,为什么不这样做呢

**Comment by MoLice** [comment]
继承你需要先去找到配置表里有哪些值可以修改，然后再把要改的值写到你的子类里。
如果是目前的做法，你直接到配置表里找到你要改的值改了就行了，不用两边切来切去。
最终结果都是一致的。

**Comment by zhangchioulin** [comment]
但是继承我就需要把这个类拷贝过去了,从结构来说继承好点,不是吗

**Comment by MoLice** [comment]
用继承的话，不也是要新建一个文件？

**Comment by zhangchioulin** [comment]
但是这样的话就不用去管理升级QMUI所带来的影响了吧

**Comment by MoLice** [comment]
对，这是继承比模板好的地方。

**Comment by zhoon** [comment]
@zhangchioulin 

QMUIConfigurationTemplate只是提供了一个工具方法，这个工具方法里面是通过去修改QMUIConfigurationManager这个**单例**里面的值的，所以理论上也是相当于一个继承的作用。即使是要继承，也是要去继承QMUIConfigurationManager这个类，但是继承一个单例的类是没啥意义的。

至于你说的不用去管理升级QMUI所带来的影响，使用模板也是不会有什么影响的，我们只会去增加模板的配置属性，而不会删除，所以你只要往你的项目里面的QMUIConfigurationTemplate增加QMUI增加的配置属性就好了。

所以我个人觉得两种方式是一样的，没有说谁好谁坏：
1、通过QMUIConfigurationTemplate修改单例的属性值；
2、通过继承QMUIConfigurationManager来修改实例的属性值；

**Comment by MoLice** [comment]
@zhangchioulin 刚刚更新了 [1.5.0](https://github.com/QMUI/QMUI_iOS/releases/tag/1.5.0) 版本，对 3 种使用 QMUI iOS 的方式重新整理，其中对配置表 `QMUIConfigurationTemplate` 的使用也有更明确的使用说明，有空可以查看哈。
