### ISSUE TITLE
图片预览视图, 快速滑动会闪退

### ISSUE THREAD

**Issue by c344081** [QMUI/QMUI_iOS#49]
### 运行环境 ###

- [x] iOS 设备：`iPhone`  4s
- [x] 系统版本：`iOS 9.3.5`
- [x] Xcode 版本：`8.2`
- [x] QMUI iOS 版本：`1.2.0`

### 具体问题描述 ###
图片预览视图, 快速滑动, 会因为内存问题闪退

**Comment by c344081** [comment]
`QMUIAsset`中不缓存`previewImage`,145张图片,滑动不会闪退..建议做下处理😳

**Comment by MoLice** [comment]
这个问题我们看一下，会优化缓存策略。

**Comment by MoLice** [comment]
@c344081 这个问题在上周[这个 commit ](https://github.com/QMUI/QMUI_iOS/commit/f5821d8855e2fbbeb2eed97837016532730d1958)里已经优化，去掉了对 `UIImage` 的缓存。
