### ISSUE TITLE
如何拿到 GIF 图片？

### ISSUE THREAD

**Issue by wanhmr** [QMUI/QMUI_iOS#51]
### 关于ImagePicker ###
- 如果是 GIF 图片，目前好像没有办法拿到

**Comment by wanhmr** [comment]
如果能提供拿 NSDada 的对象更好，UIImage 好像对内存暴涨有影响。

**Comment by zhoon** [comment]
没办法拿到Gif图片是指相册控件里面没有显示出来吗？我试了一下好像是可以获取到图片的，只不过我们目前在预览的时候只能展示静止的状态。

**Comment by zhoon** [comment]
嗯，内存暴涨问题我们目前正在着手解决，感谢提醒

**Comment by wanhmr** [comment]
因为我要做图片上传功能，包括上传 GIF 图片，但是目前的接口只能拿到 UIMage 对象。

**Comment by zhoon** [comment]
嗯，这确实是一个问题，我们会尽快支持。

**Comment by wanhmr** [comment]
目前是使用 KVC 拿到 PHAseet 对象，然后再去拿的资源。

**Comment by wanhmr** [comment]
有一些建议，由于是使用的 Cocopads，不好更改代码，也不必要更改代码。有些组件我觉得是可以拆分出来的。比如 tableView cell 高度自动计算，图片表情面板。前者已经有 FD 框架，后者又不是必须。

**Comment by zhoon** [comment]
拆分的问题也有很多人提过了，由于QMUI是个整体的框架，很多组件都会相互依赖，例如一些全局用的UI配置或者工具方法和宏；还有不同的类之间也有可能互相依赖；所以就比较难拆分出来，你觉得有什么比较好的方案可以来拆分吗？@wanhmr

**Comment by wanhmr** [comment]
@zhoon 我目前的想法是，有依赖是没有关系的。比如 QMUIKit 提供一个基础的框架，如 UIKit 一样。高度计算是一个组件，表情面板是一个组件，他们是可以强依赖 QMUIKit 的。因为 QMUIKit 足够基础，可以说这些组件是 QMUIKit 的扩展而已。这样子，别人也能在 QMUIKit 的基础上生成组件，就像围绕在 QMUIKit 的一个生态一样。

**Comment by wanhmr** [comment]
[TZImagePickerController](https://github.com/banchichen/TZImagePickerController)，像这样的框架，我们可以容易的在 QMUIKit 上扩展出来这样子的一个组件，特别方便。我目前就是使用 QMUIKit 把他干掉了。

**Comment by zhoon** [comment]
嗯嗯，你说的这种思路我们尝试一下可不可行

**Comment by LimingZou** [comment]
ImagePickerController 后期能播放视频么

**Comment by MoLice** [comment]
@LimingZou 正在支持视频功能。

**Comment by MoLice** [comment]
@wanhmr 内存暴涨的问题在上周[这个 commit ](https://github.com/QMUI/QMUI_iOS/commit/f5821d8855e2fbbeb2eed97837016532730d1958)里已优化，去掉了对 `UIImage` 的缓存。

**Comment by wanhmr** [comment]
@MoLice 收到，thx,  如果没有问题，cocoapods 希望也同步一下。

**Comment by MoLice** [comment]
@wanhmr 已更新 CocoaPod 到 1.3.1 版本。

**Comment by zdiovo** [comment]
@MoLice 关于拆分,可以参考一下[PromiseKit](https://github.com/mxcl/PromiseKit.git) 采用subspec的方式. @wanhmr

**Comment by kayo5994** [comment]
@wanhmr 刚刚发布了 [1.7.1](https://github.com/QMUI/QMUI_iOS/releases/tag/1.7.1) ，`QMUIAsset` 中新增了 `requestImageData:` 方法可以获取图片的 `NSDada` 对象，以及判断图片是否为 GIF 图片。

**Comment by wanhmr** [comment]
@kayo5994 直接返回 isGif，是否扩展不好？如果我需要知道图片的更详细的信息呢？如图片格式：png or jpg? 不过目前已经解决了拿到图片数据的问题，其实也可以根据数据自己去解析图片格式。thx

**Comment by kayo5994** [comment]
@wanhmr 在刚刚提交的修改中，优化了 [`requestImageData:`](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIComponents/AssetLibrary/QMUIAsset.h#L132)，可以获取图片的详细信息，感谢你的建议。
