### ISSUE TITLE
可否拆分为多个组件？这样可以更普及一些

### ISSUE THREAD

**Issue by hydyy** [QMUI/QMUI_iOS#54]
如题，可能楼主的项目适合于较新的项目使用，面对沉重的历史包袱，想用难度有点大！

可否根据特色，拆分出一些组件，这样使用起来更好一些吧。

比如，QMAlert 类似这样

**Comment by MoLice** [comment]
请参考[这个 issue](https://github.com/QMUI/QMUI_iOS/issues/32)，类似问题。
对于只想使用其中某些组件的，可以考虑自行拆分，其实像父类继承、通用宏这种，拆分成本不高。如果遇到一些拆分成本高的，或许是我们设计的问题，可以给我们提一下意见，谢谢。

**Comment by hydyy** [comment]
okokok
