### ISSUE TITLE
 - (BOOL)textViewShouldReturn:(QMUITextView *)textView; 这个代理方法，pod 版本没有，请尽快更新pod 版本

### ISSUE THREAD

**Issue by boai** [QMUI/QMUI_iOS#55]
### 运行环境 ###

- [x] iOS 设备：`iPhone` 
- [x] 系统版本：`iOS 10.3`
- [x] Xcode 版本：`8.0`
- [x] QMUI iOS 版本：`1.2.0`

### 具体问题描述 ###
 - (BOOL)textViewShouldReturn:(QMUITextView *)textView; 这个代理方法，pod 版本没有，请尽快更新pod 版本

**Comment by zhoon** [comment]
你好，pod上面的版本刚刚已经更新至1.3.0
