### ISSUE TITLE
QMUIQQEmotionManager 中的表情显示的文字，怎么在label上显示表情

### ISSUE THREAD

**Issue by boai** [QMUI/QMUI_iOS#57]
### 运行环境 ###

- [x] iOS 设备：`iPhone`
- [x] 系统版本：`iOS 10.3`
- [x] Xcode 版本：`8.0`
- [x] QMUI iOS 版本：`1.2`

### 具体问题描述 ###
1、QMUIQQEmotionManager 中的表情显示的文字，怎么在label上显示表情？
2、输入的表情怎么都在文字前面了，
3、表情键盘右下角的return 按钮的点击事件没有！demo有，pod 没更新！
#### 问题截图 ####

**Comment by MoLice** [comment]
对于第1点，`QMUIQQEmotionManager` 目前仅支持在控件内显示“文字”，而不支持在控件内显示“表情”，因为每个项目里对于如何处理图文混排都没有标准做法。
以 `UILabel` 为例，要在其中显示表情图片，一般做法是以 `NSTextAttachment` 的方式插入到 `NSAttributedString` 中再赋值给 `UILabel.attributedText` 属性。
但如果你用的是 `TTTAttributedLabel`，它不支持 `NSTextAttachment`，所以你又要以其他方式（例如  `CoreText`）去实现。
鉴于这种场景一般只需要做字符串匹配即可，实现成本不高，所以 `QMUIQQEmotionManager` 不处理这方面的问题。

**Comment by MoLice** [comment]
对于第 2 点，请参照 `QMUIQQEmotionManager.h` 的注释，检查是否有调用相关方法？

**Comment by MoLice** [comment]
对于第 3 点，下午就会更新，请关注。

**Comment by boai** [comment]
第一点我自己再看，第二点希望demo 完善下，第三点希望pod 尽快更新！还有其他小bug，不过目前影响不大，不过有一点，里面的布局框架希望能够尽快适配 autolayout ，要不然局限太多，多谢大神框架！很方便！

**Comment by MoLice** [comment]
@boai 

第 2 点，QMUI Demo 已更新，请查看更新 log。

QMUI CocoaPod 已更新到 1.3.0。
