### ISSUE TITLE
IOS7 闪退

### ISSUE THREAD

**Issue by wenyhooo** [QMUI/QMUI_iOS#6]
![18e038c0-f7e2-48f9-88ec-6ca07bf9fa74](https://cloud.githubusercontent.com/assets/5977236/21512550/b3bad1a8-cce9-11e6-93be-b910b3b41f18.png)
![a1f756f7-8826-4287-bc86-898ec8b0baad](https://cloud.githubusercontent.com/assets/5977236/21512552/c1b56f84-cce9-11e6-8e47-e5f4ed3af9ba.png)

**Comment by MoLice** [comment]
抱歉，QMUI 本身支持 iOS 7，但作为 Sample Code，QMUI Demo 只支持到 iOS 8。

**Comment by LiweiDong** [comment]
看 [http://qmuiteam.com/ios/page/start.html](http://qmuiteam.com/ios/page/start.html) 注意事项

**Comment by wenyhooo** [comment]
我这么搞依然不行
![image](https://cloud.githubusercontent.com/assets/5977236/21516358/6b8064b0-cd12-11e6-9ccf-43f287cc829d.png)

**Comment by MoLice** [comment]
抱歉，这个问题是由于 iOS 7 下对 BOOL 类型的 property 不支持 UIAppearance 声明，所以导致 crash。
已经修复，请更新代码重试。
关键在 `QMUIToastBackgroundView.m:93`。
