### ISSUE TITLE
在使用 QMUIEmotion 的时候，能不能只通过displayName 获取到QMUIEmotion 的image？

### ISSUE THREAD

**Issue by boai** [QMUI/QMUI_iOS#60]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
@interface QMUIEmotion : NSObject

/// 当前表情的标识符，可用于区分不同表情
@property(nonatomic, copy) NSString *identifier;

/// 当前表情展示出来的名字，可用于输入框里的占位文字，例如“[委屈]”
@property(nonatomic, copy) NSString *displayName;

/// 表情对应的图片。若表情图片存放于项目内，则建议用当前表情的`identifier`作为图片名
@property(nonatomic, strong) UIImage *image;

/**
 *  快速生成一个`QMUIEmotion`对象，并且以`identifier`为图片名在当前项目里查找，作为表情的图片
 *  @param  identifier  表情的标识符，也会被当成图片的名字
 *  @param  displayName 表情展示出来的名字
 */
+ (instancetype)emotionWithIdentifier:(NSString *)identifier displayName:(NSString *)displayName;

在textView 获取到的时QMUIEmotion 的 displayName，怎么能够根据 displayName 获取到image 呢？

@end

**Comment by MoLice** [comment]
在我们的项目中，我们通过这种方式获取 image：
```Objective-C
+ (UIImage *)imageForEmotionWithDisplayName:(NSString *)displayName {
    for (QMUIEmotion *emotion in [QMUIQQEmotionManager emotionsForQQ]) {
        if ([displayName isEqualToString:emotion.displayName]) {
            return emotion.image;
        }
    }
    return nil;
}
```

**Comment by boai** [comment]
恩，我试试看！多谢！

**Comment by boai** [comment]
OK ，果然是内部方法，厉害！

**Comment by boai** [comment]
忘了有一点，MLeaksFinder 检测 QMUITabBarViewController 这个类有内存泄露！不知道准确不，你们可以看看！

**Comment by MoLice** [comment]
好的多谢，稍后检查一下。
