### ISSUE TITLE
更新1.3.0之后运行出错

### ISSUE THREAD

**Issue by RanYeee** [QMUI/QMUI_iOS#61]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.2.1`
- [x] Xcode 版本：`8.2.1`
- [x] QMUI iOS 版本：`1.3.0`

### 具体问题描述 ###
在AppDelegate 里面设置    [QMUIConfigurationManager renderGlobalAppearances];后应用打开直接崩溃在QMUIConfigurationManager.m 第230行！！！
#### 问题截图 ####
![E3A04D69-9221-45A2-A4FB-6F101A5A7B74.png](http://upload-images.jianshu.io/upload_images/1528347-3ca6ebbe4f1a0573.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by MoLice** [comment]
麻烦截图看看崩溃时 Xcode 控制台给出的信息是什么？

**Comment by RanYeee** [comment]
![image](https://cloud.githubusercontent.com/assets/11763180/23242073/e6020a4c-f9b1-11e6-8e46-03dcabf4eda7.png)

**Comment by LimingZou** [comment]
pod 'QMUIKit', '~>1.3.0'  控制台输出没有找到

**Comment by MoLice** [comment]
@RanYeee 请检查你的配置表里，`QMUICMI.navBarTitleColor` 的值是否为 `nil`？
![image](https://cloud.githubusercontent.com/assets/1190261/23242674/1e42ec34-f9b5-11e6-873f-11d2a7846814.png)

**Comment by MoLice** [comment]
@LimingZou 请参考[这个 issue](https://github.com/QMUI/QMUI_iOS/issues/21)。

**Comment by RanYeee** [comment]
@MoLice 哦哦,可以了，原来这个要手动打开的，thanks！！😊

**Comment by MoLice** [comment]
不客气

**Comment by MoLice** [comment]
@RanYeee 刚刚更新了 [1.5.0](https://github.com/QMUI/QMUI_iOS/releases/tag/1.5.0) 版本，对 3 种使用 QMUI iOS 的方式重新整理，其中对配置表 `QMUIConfigurationTemplate` 的使用也有明确的说明，建议重新查看哈。
