### ISSUE TITLE
子类怎么才能修改父类tableView的frame

### ISSUE THREAD

**Issue by RabbitDream** [QMUI/QMUI_iOS#63]
### 运行环境 ###

- [x] iOS 设备：`iPhone` 
- [x] 系统版本：`iOS 10.2`
- [x] Xcode 版本：`8.2`
- [x] QMUI iOS 版本：`1.3.0`

### 具体问题描述 ###
父类继承`QMUICommonTableViewController`，子类怎么才能修改tableView的frame

**Comment by zhoon** [comment]
请在子类的 `viewDidLayoutSubviews` 里面修改

**Comment by RabbitDream** [comment]
好的，感谢答复
