### ISSUE TITLE
全局颜色无效问题

### ISSUE THREAD

**Issue by didez** [QMUI/QMUI_iOS#66]
### 运行环境 ###

- [x] iOS 设备：`iPhone 6`
- [x] 系统版本：`iOS 10.12`
- [x] Xcode 版本：`8.2.1`
- [x] QMUI iOS 版本：`1.3.1`

### 具体问题描述 ###

pod导入qmui，设置modal的背景时，发现uicolorxx宏无效，打印为null，使用[uicolor xx]后正常，但遮罩同样无效(除非自定义)

手机打字，细节望谅解

#### 问题截图 ####

待补充

**Comment by didez** [comment]
看错，iOS版本 是 10.2.1

**Comment by MoLice** [comment]
请参照 QMUI Demo 的使用方式，在你的项目里为 QMUI 进行初始化配置，具体请查看[这里](https://github.com/QMUI/QMUIDemo_iOS/blob/master/qmuidemo/AppDelegate.m#L27-L31)。

**Comment by didez** [comment]
谢答复, 已解决: AppDelegate 中加入初始化代码: [QMUICMI initDefaultConfiguration];

(依照 Demo 自定义配置失败: 重复导入问题)
