### ISSUE TITLE
 pod  search qmui 找不到你们的库,然后 update  pod 'QMUIKit'  无效

### ISSUE THREAD

**Issue by stevendinggang** [QMUI/QMUI_iOS#67]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by zhoon** [comment]
请在命令行做以下操作，再 `pod search QMUIKit` 试一试

rm ~/Library/Caches/CocoaPods/search_index.json

或者

rm -rf ~/.cocoapods
pod setup （这个步骤比较费时，请耐心等一等）
