### ISSUE TITLE
DEMO的标题菜单一直存在

### ISSUE THREAD

**Issue by dwanghello** [QMUI/QMUI_iOS#69]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

#### 问题截图 ####
![snip20170308_1](https://cloud.githubusercontent.com/assets/15830996/23686771/80c18772-03e6-11e7-95be-2f61378c14a8.png)

**Comment by MoLice** [comment]
感谢反馈，已在[这次 commit](https://github.com/QMUI/QMUIDemo_iOS/commit/4873044ca039f1f2a8990e1564114794e1a0e2ab) 里修复。
