### ISSUE TITLE
在ARC和MRC环境下需要做其他处理吗

### ISSUE THREAD

**Issue by ChinaJackSion** [QMUI/QMUI_iOS#70]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by MoLice** [comment]
与任何代码的处理一样，没任何特殊。
