### ISSUE TITLE
XIB 中 QMUITextField 的 qmui_borderWidth 属性无效

### ISSUE THREAD

**Issue by didez** [QMUI/QMUI_iOS#71]
### 运行环境 ###

- [x] iOS 设备：`模拟器`
- [x] 系统版本：`iOS 10.2.1`
- [x] Xcode 版本：`8.2.1`
- [x] QMUI iOS 版本：`1.3.1`

### 具体问题描述 ###
拖入 UIView, Class 改为 QMUITextField, 修改边框属性和颜色, Runtime 中出现相关 KeyPath

Debug View 中打印为 QMUITextField: 0x7fa8b0f09170; baseClass = UITextField;

**Comment by MoLice** [comment]
请检查是否有在代码里为 `QMUITextField` 设置 `qmui_borderPosition` 属性？单纯只改 `qmui_borderWidth` 是不生效的。

另外为了与使用系统的 `view.layer` 为一个 `UIView` 显示 4 条边框线的做法区分开，我们在刚刚的 [commit](https://github.com/QMUI/QMUI_iOS/commit/587dc334fc62c1cb5abccdc650924d0a3c4420d4) 里修改了注释说明，尽量只将 `UIView (QMUI_Border)` 用于需要为某几条边加边框的场景。

**Comment by didez** [comment]
谢谢, 已解决
