### ISSUE TITLE
QMUIDialogViewController 初始化crash

### ISSUE THREAD

**Issue by ihomelp07** [QMUI/QMUI_iOS#72]
### 运行环境 ###

- [x] iOS 设备：`iPhone`
- [x] 系统版本：`iOS 10.2.1`
- [x] Xcode 版本：`8.2.1`
- [x] QMUI iOS 版本：`1.3.2`

### 具体问题描述 ###
[QMUIDialogViewController appearance] 初始化buttonTitleAttributes时候报错，代码如下：
- 报错代码：
``` Objective-c
dialogViewControllerAppearance.buttonTitleAttributes = @{NSForegroundColorAttributeName: UIColorBlue, NSKernAttributeName: @2};
```
- 报错原因：
``` Objective-c
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
``` 
- 修改建议：
``` Objective-c
dialogViewControllerAppearance.buttonTitleAttributes = [[NSDictionary alloc] initWithObjectsAndKeys:UIColorBlue,@"NSForegroundColorAttributeName",@2,@"NSKernAttributeName",nil];
```

**Comment by MoLice** [comment]
请检查是否有在项目的 `application:didFinishLaunchingWithOptions:` 里调用 `[QMUIConfigurationTemplate setupConfigurationTemplate]`，具体请查看[使用文档](http://qmuiteam.com/ios/page/start.html)。

**Comment by ihomelp07** [comment]
哦，这样啊，好的，谢谢！
