### ISSUE TITLE
StatusbarStyleLightInitially状态栏不能变白

### ISSUE THREAD

**Issue by RabbitDream** [QMUI/QMUI_iOS#73]
### 运行环境 ###

- [x] iOS 设备：`iPhone`
- [x] 系统版本：`iOS 102`
- [x] Xcode 版本：`8.2`
- [x] QMUI iOS 版本：`1.3.2`

### 具体问题描述 ###
`    QMUICMI.statusbarStyleLightInitially = YES;          // StatusbarStyleLightInitially : 默认的状态栏内容是否使用白色，默认为NO，也即黑色` 调用这个方法后，状态栏也不能变白；

**Comment by MoLice** [comment]
![image](https://cloud.githubusercontent.com/assets/1190261/23885319/28914fd0-08ad-11e7-97ae-2e3303da7027.png)

请检查是否有按照注释来设置 `Info.plist` 文件。

**Comment by RabbitDream** [comment]
设置过了，还是不行

**Comment by RabbitDream** [comment]
解决了。感谢
