### ISSUE TITLE
navigationItem无法单独修改颜色

### ISSUE THREAD

**Issue by dwanghello** [QMUI/QMUI_iOS#74]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
试过多种方式，都无法只修改一个item的颜色，通过图片创建item也会被渲染成设置的统一颜色
#### 问题截图 ####
![snip20170314_18](https://cloud.githubusercontent.com/assets/15830996/23889175/a53bb7f0-08c6-11e7-9ecd-5053fee115c9.png)

![snip20170314_19](https://cloud.githubusercontent.com/assets/15830996/23889361/b078c3c8-08c7-11e7-8fad-4e98a9ae503f.png)

**Comment by MoLice** [comment]
请尝试：
```Objective-C
UIImage *image = xxx;
image = [image imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];// UIBarButtonItem 里的 image 默认都是以 UIImageRenderingModeAlwaysTemplate 的方式渲染，会被 tintColor 强制修改颜色，所以需要手动修改 renderingMode
self.navigationItem.rightBarButtonItem = [QMUINavigationButton barButtonItemWithImage:image xxx];
```

**Comment by dwanghello** [comment]
已解决 谢啦
