### ISSUE TITLE
【提问】关于对模拟器的特殊处理

### ISSUE THREAD

**Issue by wanhmr** [QMUI/QMUI_iOS#77]
`- (BOOL)qmui_becomeFirstResponder {
    if (IS_SIMULATOR && ![self isKindOfClass:[UIWindow class]]) {
        NSAssert(self.window.keyWindow, @"尝试让一个处于非 keyWindow 上的 %@ becomeFirstResponder", NSStringFromClass(self.class));
    }
    return [self qmui_becomeFirstResponder];
}`
QMUIAlertViewController 的 window 也没有成为 keyWindow 呀？

**Comment by MoLice** [comment]
可能是旧代码，请更新后再尝试。

`QMUIAlertController` 使用 `QMUIModalPresentationViewController` 来显示，而在[这行代码](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIComponents/QMUIModalPresentationViewController.m#L394)里，`QMUIModalPresentationViewController` 是有变成 `keyWindow` 的。

另外 `UIView (QMUI)` 这个错误检测已从 `NSAssert` 改为 `NSLog`，避免太过暴力的提醒。

**Comment by wanhmr** [comment]
@MoLice QAQ，那我的是旧代码= =，谢谢。
