### ISSUE TITLE
报错：isViewControllerTransiting = YES, -[QMUINavigationController pushViewController:animated:], self.viewControllers =

### ISSUE THREAD

**Issue by xztl** [QMUI/QMUI_iOS#80]
### 运行环境 ###

- [x] iOS 设备：`iPhone`
- [x] 系统版本：`iOS 10.2.1`
- [x] Xcode 版本：`8.2.1`
- [x] QMUI iOS 版本：`1.3.3`

### 具体问题描述 ###
push经常遇到：NSAssert(NO, @"isViewControllerTransiting = YES, %s, self.viewControllers = %@", __func__, self.viewControllers);  崩溃于此！正确姿势是什么？如何解决！？
#### 问题截图 ####
![](https://ww1.sinaimg.cn/large/006tKfTcly1fdoqghx8fkj30o204ggmm.jpg)

**Comment by MoLice** [comment]
这个情况说明你在上一次界面切换（push or pop）动画尚未结束时就又发起了一次 push 操作，容易导致很多奇怪 bug。
请检查你的 push 操作发起的时机，猜测可能你在 `viewWillAppear:`、`viewWillDisappear:` 里进行 push 了？又或者是类似下面这种写法：
```Objective-C
[self.navigationController pushViewController:A animated:YES];
...
[self.navigationController pushViewController:B animated:YES];// 两次 push 都是 animated:YES，所以会中 assert，只要把上面那次 push 的 animated 改为 NO 即可
```

**Comment by xztl** [comment]
谢谢

—
一封简信 (http://jianx.in/m|3)

**Comment by xztl** [comment]
但是遇到过，并不是连续push的情况，只是用户操作连续而已，也会那样

—
一封简信 (http://jianx.in/m|3)

**Comment by xztl** [comment]
这个问题经常出现呀！并没有写多个push！不可能限制用户手速吧

—
一封简信 (http://jianx.in/m|3)

**Comment by MoLice** [comment]
如果用户真的快速点击的话，Release 下没问题的，后续的点击会被忽略，只是 Debug 下会中 assert

**Comment by xztl** [comment]
谢谢

—
一封简信 (http://jianx.in/m|3)
