### ISSUE TITLE
测试切换横竖屏的时候，没有显示切换动画

### ISSUE THREAD

**Issue by leonardo-hammer** [QMUI/QMUI_iOS#83]
### 运行环境 ###

- [x] iOS 设备：`iPhone`
- [x] 系统版本：`iOS 10.1.2`
- [x] Xcode 版本：`8.2.1`
- [x] QMUI iOS 版本：`1.2`

### 具体问题描述 ###

测试切换横竖屏的时候，没有显示切换动画。界面一瞬间直接变成横屏。

使用QMUINavigationController, 设置rootViewController = QMUICommonTableViewController的子类。

Template配置支持All
```objc
#pragma mark - Others
    
QMUICMI.supportedOrientationMask = UIInterfaceOrientationMaskAll;
```

**Comment by MoLice** [comment]
@leonardo-hammer 单纯从你提供的信息里尚无法判断问题所在。

QMUI Demo 里是正常的，应该是你的某些业务代码影响到了，可以特别关注那些与 layout 相关的代码。

**Comment by leonardo-hammer** [comment]
找到解决的方法了！

删除项目中的 `info.plist` 的 `Main storyboard file base name` key, 删除 `Main.storyboard` 后，横竖屏切换的动画就恢复正常了。

**Comment by MoLice** [comment]
竟然跟这种有关系，不过平时没用到 storyboard 的话都会删掉，也就不会遇到。

**Comment by MoLice** [comment]
vv
