### ISSUE TITLE
Demo中QMUIImagePreviewView栏目中会导致崩溃

### ISSUE THREAD

**Issue by dwanghello** [QMUI/QMUI_iOS#84]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

#### 问题截图 ####
![snip20170321_23](https://cloud.githubusercontent.com/assets/15830996/24129914/a60ffeca-0e20-11e7-877b-c2e088974c35.png)
![snip20170321_22](https://cloud.githubusercontent.com/assets/15830996/24129916/a8da0e16-0e20-11e7-8c6e-04502f545890.png)

**Comment by MoLice** [comment]
这通常是因为配置表 `QMUIConfigurationTemplate` 没有正确生效导致在某些 `NSDictionary` 里插入 `nil` 导致的。
QMUI Demo 本身是没问题的，请检查你本地是否有做过修改。
关于 `QMUIConfigurationTemplate` 请参考 [开始使用](http://qmuiteam.com/ios/page/start.html#qw_downloadForUse)。

**Comment by MoLice** [comment]
@dwanghello 刚刚更新了 README.md，重新对 `QMUIConfigurationTemplate` 配置表的使用进行了说明，请对照文档。

**Comment by MoLice** [comment]
@dwanghello 刚发布了 [1.5.0](https://github.com/QMUI/QMUI_iOS/releases/tag/1.5.0) 版本，针对 `QMUIConfigurationTemplate` 配置表的使用进行了完整的说明，建议查看。

**Comment by dwanghello** [comment]
OK
