### ISSUE TITLE
遇到了很多问题，有冲突有直接导致异常，有时间会逐步将问题描述列上来。遇到的麻烦很多，打算移除了

### ISSUE THREAD

**Issue by hllGitHub** [QMUI/QMUI_iOS#85]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by MoLice** [comment]
可以把冲突和异常的问题贴一下我们看看

**Comment by hllGitHub** [comment]
有点多，在修改个东西，弄好之后我贴一下

**Comment by MoLice** [comment]
好的，到时看看。

**Comment by MoLice** [comment]
@hllGitHub 请问这个有补充吗？没有的话我 close 了

**Comment by hllGitHub** [comment]
那你先close吧。更新之后有的问题没有了。

**Comment by MoLice** [comment]
好的
