### ISSUE TITLE
使用QMUIImagePickerPreviewViewController返回按钮的高度有问题

### ISSUE THREAD

**Issue by dwanghello** [QMUI/QMUI_iOS#86]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
感觉好像是没有加状态栏的高度，这个应该需要考虑在内吧？
我是直接使用的预览控制器
#### 问题截图 ####
![snip20170321_25](https://cloud.githubusercontent.com/assets/15830996/24136913/4056a4fe-0e4c-11e7-9977-75bb3d1025ce.png)

**Comment by MoLice** [comment]
`QMUIImagePickerPreviewViewController` 默认是隐藏状态栏的（参照微信），所以在布局时也没有考虑状态栏显示时的情况，因为实际使用中如果要让这个界面的状态栏显示出来，是需要继承子类实现的，而此时你就可以在子类的 `viewDidLayoutSubviews` 里调整顶部 bar 的按钮布局。

不过在刚刚的提交里，对状态栏显示时的布局做了兼容，你可以更新代码试试看。
