### ISSUE TITLE
PopupContentView

### ISSUE THREAD

**Issue by dengxingwen** [QMUI/QMUI_iOS#89]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
显示自定义浮层 打开状态如果不关闭浮层就关闭当前controller，则浮层不会自动关闭；

**Comment by MoLice** [comment]
对于使用 `UIWindow` 的方式来显示的浮层，一般会配合属性 `automaticallyHidesWhenUserTap` 来使用，这样就能避免浮层正在显示时还能退出当前 viewController。

而对于使用 `UIWindow` 的方式来显示，并且 `automaticallyHidesWhenUserTap` 属性为 `NO` 的情况，是需要自己在 viewController 的 `viewWillDisappear:` 里手动隐藏浮层的，这个之前注释和 Demo 里都没有提示，所以在这个 [commit](https://github.com/QMUI/QMUI_iOS/commit/559365554948938542a6d80176e85c23dfa37118) 里补上注释了。
