### ISSUE TITLE
开始使用文章有疏漏...

### ISSUE THREAD

**Issue by coderAs7** [QMUI/QMUI_iOS#9]
### 具体问题描述 ###
在 安装及使用：http://qmuiteam.com/ios/page/start.html   中,使用步骤描述有疏漏
具体位置:
点击项目 project 进入 Xcode 配置界面，在 General -> Linked Frameworks and Libraried 点击加号搜索并添加QMUIKit.framework到列表里面，然后在使用的地方 #import <QMUIKit/QMUIKit.h> 即可（如果有pch文件，只要在pch文件中import一次就够了）。
#### 修正 ####
应该是:
点击项目 project 进入 Xcode 配置界面，在 General -> Linked Frameworks and Libraried 点击加号搜索并添加QMUIKit.framework到列表里面，_**并且在General -> Embedded Binaries中点击加号搜索并添加QMUIKit.framework到列表里面(否则真机运行会报错:dyld: Library not loaded:...)**_,然后在使用的地方 #import <QMUIKit/QMUIKit.h> 即可（如果有pch文件，只要在pch文件中import一次就够了）。

**Comment by kayo5994** [comment]
感谢你的建议，文档已修正。
