### ISSUE TITLE
可以再QMUIPopupMenuItem 中点击的时候携带参数吗？

### ISSUE THREAD

**Issue by RabbitDream** [QMUI/QMUI_iOS#93]
### 运行环境 ###

- [x] iOS 设备：`iPhone` 
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
比如说我在弹出的视图里，点击某个item，需要携带一些参数然后再跳转到其他页面，这个功能可以实现吗？

**Comment by MoLice** [comment]
不太明白你的意思，能否用伪代码写出你希望的语法？
因为 `QMUIPopupMenuItem` 的点击事件是在 init 时就要定义一个 block 作为参数传进去的，在定义 block 的地方你可以很方便地定义其他变量，在 block 里使用，不一定非要利用参数。

**Comment by RabbitDream** [comment]
懂了。谢谢。
