### ISSUE TITLE
不兼容Swift吗？

### ISSUE THREAD

**Issue by zdiovo** [QMUI/QMUI_iOS#95]
### 运行环境 ###

- [x] iOS 设备：`iPhone 6` / `模拟器`
- [x] 系统版本：`iOS 10.3`
- [x] CocoaPods版本：`1.2.0`
- [x] Xcode 版本：`8.3 beta4`
- [x] QMUI iOS 版本：`1.3.6`
- [x] 项目语言：`Swift 3.0.1`

### 具体问题描述 ###
编译通过，run-->模拟器，启动的时候：
objc[4426]: Class PLBuildVersion is implemented in both /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x11081ccc0) and /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x1106336f0). One of the two will be used. Which one is undefined.
2017-03-29 23:52:38.696 CocoaThirdLibs[4426:86017] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001044b5b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000101d3f141 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001043d0ac2 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 354
	3   CoreFoundation                      0x00000001043d092b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	4   QMUIKit                             0x000000010163088d +[QMUIConfigurationManager(UIAppearance) renderGlobalAppearances] + 653
	5   CocoaThirdLibs                      0x0000000101353f96 _TFC14CocoaThirdLibs11AppDelegate11applicationfTCSo13UIApplication29didFinishLaunchingWithOptionsGSqGVs10DictionaryVSC29UIApplicationLaunchOptionsKeyP____Sb + 150
	6   CocoaThirdLibs                      0x0000000101354114 _TToFC14CocoaThirdLibs11AppDelegate11applicationfTCSo13UIApplication29didFinishLaunchingWithOptionsGSqGVs10DictionaryVSC29UIApplicationLaunchOptionsKeyP____Sb + 180
	7   UIKit                               0x0000000102206e37 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 299
	8   UIKit                               0x000000010220871c -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4119
	9   UIKit                               0x000000010220ea64 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1709
	10  UIKit                               0x000000010220bc73 -[UIApplication workspaceDidEndTransaction:] + 182
	11  FrontBoardServices                  0x00000001068eb5f6 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	12  FrontBoardServices                  0x00000001068eb46d -[FBSSerialQueue _performNext] + 186
	13  FrontBoardServices                  0x00000001068eb7f6 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	14  CoreFoundation                      0x000000010445bc01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	15  CoreFoundation                      0x00000001044410cf __CFRunLoopDoSources0 + 527
	16  CoreFoundation                      0x00000001044405ff __CFRunLoopRun + 911
	17  CoreFoundation                      0x0000000104440016 CFRunLoopRunSpecific + 406
	18  UIKit                               0x000000010220a50f -[UIApplication _run] + 468
	19  UIKit                               0x00000001022105b4 UIApplicationMain + 159
	20  CocoaThirdLibs                      0x00000001013549d7 main + 55
	21  libdyld.dylib                       0x000000010617c65d start + 1
	22  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

#### 问题截图 ####
![snip20170329_2](https://cloud.githubusercontent.com/assets/10203021/24464144/90d862ba-14db-11e7-92ca-f900c6899991.png)

**Comment by MoLice** [comment]
这个问题是因为尝试将一个 `nil` 作为 `NSDictionary` 的 value 导致的 crash，请参考这个 #72 。另外近期我们也会优化使用 QMUI 的初始配置流程，减少这种情况的出现。

**Comment by zdiovo** [comment]
之前没仔细看,现在才发现: exception 'NSInvalidArgumentException', 
reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'
不过我很疑惑啊,才didfinishedLaunch,执行到按照Demo写的两个全局配置,还没做啥具体操作就报  insert nil object to dictionary,好尴尬😓.

**Comment by MoLice** [comment]
@zdiovo 因为配置表里的值会在 `[QMUIConfigurationManager renderGlobalAppearances]` 里就被使用，所以执行到这里如果某些值为 `nil` 就会出问题。

**Comment by MoLice** [comment]
@zdiovo 刚刚发了 1.3.7，对可能因 nil 导致的 crash 都做了保护，现在应该不会了。

**Comment by MoLice** [comment]
@zdiovo 刚刚更新了 [1.5.0](https://github.com/QMUI/QMUI_iOS/releases/tag/1.5.0) 版本，对 3 种使用 QMUI iOS 的方式重新整理，其中对配置表 `QMUIConfigurationTemplate` 的使用也有明确的说明，建议重新查看哈。

**Comment by zdiovo** [comment]
期待出Swift版本,使用OC总感觉水土不服😂
如果出Swift版本,命名方式建议采用SnapKit里那种命名方式:
someObject.qmui_someFunction ==> someObject.qmui.someFunction()
