### ISSUE TITLE
以后会出邮箱写邮件的界面UI吗？

### ISSUE THREAD

**Issue by Ryan0520** [QMUI/QMUI_iOS#96]
以后会出邮箱写邮件的界面UI吗？最近在做邮箱相关的东西，发邮件的界面效果始终不是很理想，到时候能出一个这个界面实例demo吗？能带选择人的textfiled~

**Comment by MoLice** [comment]
短期内没有，这种太业务，如果出也可能是一个单独的控件。

**Comment by Ryan0520** [comment]
@MoLice 恩~
