### ISSUE TITLE
crash if use QMUITextField and BlocksKit in the same project

### ISSUE THREAD

**Issue by zenghaojim33** [QMUI/QMUI_iOS#98]
### 运行环境 ###

- [x] iOS 设备：iPhone6
- [x] 系统版本：`iOS 10.0.2`
- [x] Xcode 版本：`8.2`
- [x] QMUI iOS 版本：`1.3.7`

### 具体问题描述 ###
在storyboard中使用QMUITextField时，点击textfield时出现了崩溃
#### 问题截图 ####

<img width="907" alt="qq20170406-0 2x" src="https://cloud.githubusercontent.com/assets/8848084/24737455/6bff893c-1ac1-11e7-8924-c066cc2421e7.png">

**Comment by MoLice** [comment]
稍等，下午看看

**Comment by MoLice** [comment]
@zenghaojim33 你是必现吗？我这里使用 storyboard 无法重现你说的问题

**Comment by zenghaojim33** [comment]
是的，但是用QMUITextView就没这个问题

**Comment by zenghaojim33** [comment]
找到问题了，貌似是跟BlockKit不兼容的缘故

**Comment by MoLice** [comment]
那句代码里没什么实例对象，按理不应该出现 EXC_BAD_ACCESS 错误才对

**Comment by zenghaojim33** [comment]
@MoLice 出现了死循环
<img width="1175" alt="qq20170407-1 2x" src="https://cloud.githubusercontent.com/assets/8848084/24788723/9bd9374e-1ba1-11e7-9bcc-3d7198dac07c.png">

**Comment by MoLice** [comment]
看起来 BlocksKit 在一些场景下是会出现这个问题，在 BlocksKit 这个 [issue](https://github.com/zwaldowski/BlocksKit/issues/257) 里很多人都提到这一点，等 BlocksKit 作者答复吧。

**Comment by yuejieee** [comment]
我目前也遇到了这个问题

**Comment by MoLice** [comment]
2.5.0 版本已兼容 BlocksKit。
