### ISSUE TITLE
使用QMUISearchController时点击搜索时tableView会向下偏移

### ISSUE THREAD

**Issue by TracyYanghandsome** [QMUI/QMUI_iOS#99]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
使用QMUISearchController时点击搜索时tableView会向下偏移，每次点击就向下偏移。默认进来是正常的

#### 问题截图 ####
![Uploading 1.gif…]()
![Uploading 4B75F97B-530F-4DD1-AE96-474814E8C215.png…]()
![Uploading 5AB0D3F6-0386-4790-9EB6-FB919EFFD176.png…]()
![Uploading BA063F9F-15DC-4CC3-879E-D190FD0BED62.png…]()
![Uploading E7BED811-6601-4B5C-A558-9D89B5CBF350.png…]()

**Comment by TracyYanghandsome** [comment]
![1](https://cloud.githubusercontent.com/assets/19200800/24782645/11f312e2-1b7a-11e7-96c3-c323d158d8c6.gif)
![4b75f97b-530f-4dd1-ae96-474814e8c215](https://cloud.githubusercontent.com/assets/19200800/24782654/2adb3438-1b7a-11e7-8b69-5ae1c247e73a.png)
![5ab0d3f6-0386-4790-9eb6-fb919effd176](https://cloud.githubusercontent.com/assets/19200800/24782656/2b16a39c-1b7a-11e7-82fc-9217b3a6e321.png)
![ba063f9f-15dc-4cc3-879e-d190fd0bed62](https://cloud.githubusercontent.com/assets/19200800/24782655/2b1372bc-1b7a-11e7-84ea-38341044e9d4.png)
![e7bed811-6601-4b5c-a558-9d89b5cbf350](https://cloud.githubusercontent.com/assets/19200800/24782658/2b6a4754-1b7a-11e7-86bb-f485179e9c68.png)

**Comment by MoLice** [comment]
猜测你的 viewController.view.frame.origin.y 是否为 64？
这是系统的 `UISearchController` 在配合 `edgesForExtendedLayout` 为 `UIRectEdgeNone` 时的问题。
如果你的 navigationBar 背景图为不透明图片，那么请检查你的 `UIViewController.extendedLayoutIncludesOpaqueBars` 是否为 `NO`？如果为 `NO`，请改为 `YES` 试试看。

**Comment by TracyYanghandsome** [comment]
@MoLice UIViewController.extendedLayoutIncludesOpaqueBars设置为yes就可以了，我的状态栏不是透明的，请问下你们demo里面的viewController.view.frame.origin.y  64是怎么解决的啊

**Comment by MoLice** [comment]
@TracyYanghandsome QMUI 里的所有 viewController 都是继承自 `QMUICommonViewController`，而在[这行代码](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIMainFrame/QMUICommonViewController.m#L46)里我们默认就把 `extendedLayoutIncludesOpaqueBars` 设为 `YES`，所以编码时无需担心区别。
所以我们也是建议把业务项目的 viewController 基类改为 `QMUICommonViewController`、`QMUICommonTableViewController`，这样能保证与各个控件的配合。

**Comment by TracyYanghandsome** [comment]
@MoLice  奇怪了，我的父类都是继承于QDTableViewController，而QDTableViewController继承与QMUICommonTableViewController，之前一直都是这样，现在在schemeListViewController这个控制前加了一个extendedLayoutIncludesOpaqueBars=YES就没问题了，后来你说默认就把 extendedLayoutIncludesOpaqueBars 设为 YES时候我看了下我的父类是不是继承QMUICommonTableViewController，然后我把schemeListViewController 这个控制器的extendedLayoutIncludesOpaqueBars属性删了也没问题了。。 还有请问下 基类为QMUICommonViewController的时候 控件的y坐标需要偏64吗

**Comment by MoLice** [comment]
@TracyYanghandsome 如果在 `UIScrollView` 里布局（包括 `UITableView`、`UICollectionView`），由于 `UIViewController.automaticallyAdjustsScrollViewInsets` 默认为 YES，所以布局时从 0 开始即可。如果在 `UIView` 里布局，则控件的 y 坐标是要偏移 64 的，一般我们都这么写：
```Objective-C
- (void)viewDidLayoutSubviews {
    [super viewDidLayoutSubviews];
    // 从 navigationBar 下方开始布局
    xx.frame = CGRectSetY(xx.frame, CGRectGetMaxY(self.navigationController.navigationBar.frame));
    // 或者用宏
    xx.frame = CGRectSetY(xx.frame, NavigationContentStaticTop);
}
```

另外，不建议使用 QDXxxx，因为 QD 项目只是个 Demo，展示如何使用 QMUI iOS。我们一般都是建立自己业务的基类，例如：
```Objective-C
@interface WRCommonViewController : QMUICommonViewController
@end

@interface WRCommonTableViewController : QMUICommonTableViewController
@end
```

**Comment by TracyYanghandsome** [comment]
@MoLice 好的。多谢哈
